feat: SVG Icon support for theme and addon.
brainstormforce/astra pull request #1722
Opened 2020-04-29 05:38 UTC by premanshup

2021-01-20 07:12 UTC, imnavanath commented
@premanshup I'm facing this issue - https://a.cl.ly/GGu2Dexb can you once check. 
Checked by resetting astra-settings as well, see here - https://a.cl.ly/geuonKZE

2021-01-20 10:32 UTC, premanshup commented
> @premanshup I'm facing this issue - https://a.cl.ly/GGu2Dexb can you once check.
> Checked by resetting astra-settings as well, see here - https://a.cl.ly/geuonKZE

@imnavanath This may come when the batch process is running, once it is done, it should load properly. Can you please check this after resetting the customizer, after that as well this issue should not come. Let me know here how it goes.

2021-03-09 09:23 UTC, vrundakansara requested changes

2021-03-09 09:23 UTC, vrundakansara commented on searchform.php
> +		<span class="screen-reader-text">Search for:</span>
Need to make this string translatable.

2021-03-09 09:23 UTC, vrundakansara commented on searchform.php
> +		<input type="search" class="search-field" placeholder="Search …" value="" name="s">
Need to make the placeholder string translatable.

2021-03-09 09:27 UTC, vrundakansara requested changes

2021-03-09 09:27 UTC, vrundakansara commented on searchform.php
> +<?php
Can you point me to where is this file called from @premanshup ?
I am having difficulty understanding this logic.

2021-03-12 12:43 UTC, premanshup commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +			}
@vrundakansara Done!

2021-03-12 12:46 UTC, premanshup commented on searchform.php
> +		<span class="screen-reader-text">Search for:</span>
@vrundakansara Done!

2021-03-12 12:46 UTC, premanshup commented on searchform.php
> +		<input type="search" class="search-field" placeholder="Search …" value="" name="s">
@vrundakansara Done!

2021-03-12 13:26 UTC, vrundakansara approved these changes

2021-03-15 05:13 UTC, rohitp-bsf requested changes

2021-03-15 05:13 UTC, rohitp-bsf commented on inc/core/class-astra-icons.php
> +				case 'menu-bars':
Can we add this in the svg.json file?  @premanshup

2021-03-15 14:11 UTC, premanshup commented on inc/core/class-astra-icons.php
> +				case 'menu-bars':
@rohitp-bsf As discussed in the previous discussion regarding JSON file size. I think it would be better to keep this in PHP only.

2021-03-16 04:52 UTC, rohitp-bsf commented on inc/core/class-astra-icons.php
> +				case 'menu-bars':
OK!

2021-03-16 06:21 UTC, rohitp-bsf approved these changes

2021-03-19 11:56 UTC, rohitp-bsf approved these changes

2021-03-19 12:04 UTC, vrundakansara approved these changes

2021-03-19 12:04 UTC, merged