improvement: GB Column, Group, Media-Text block compatibility
brainstormforce/astra pull request #1856
Opened 2020-08-15 07:59 UTC by imnavanath

### Description
- Added compatibility CSS for GB Column, Group, Media-Text block
- https://gist.github.com/imnavanath/76fa266f293748e8516269b7ca59f560

### Types of changes
- Run batch function for maintaining design of existing users
- Added filter support as well

### How has this been tested?
- With new WP version 5.5 & below

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards
- [ ] My code has proper inline documentation
- [ ] I've included any necessary tests
- [ ] I've included developer documentation
- [ ] I've added proper labels to this pull request

2020-09-30 11:24 UTC, premanshup requested changes

2020-09-30 11:24 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +					'.ast-theme-transparent-header #primary, .ast-theme-transparent-header #secondary' => array(
@imnavanath Why haven't we used these similar conditions here? - https://github.com/brainstormforce/astra/commit/eedd4f32f045639485f30d845c457c5e175df6dc

2020-09-30 11:24 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +					'figure.size-full'                   => array(
@imnavanath Can we add any prefix class here? Maybe related to `wp-block`. figure.size-full seems like very common CSS class.

2020-10-05 11:03 UTC, imnavanath commented on inc/class-astra-dynamic-css.php
> +					'.ast-theme-transparent-header #primary, .ast-theme-transparent-header #secondary' => array(
Correct 👍 Doing it WIP...

2020-10-05 11:22 UTC, imnavanath commented on inc/class-astra-dynamic-css.php
> +					'figure.size-full'                   => array(
Unfortunately, the image directly applies `figure` block, no wrapper here used by GB (like `wp-block` etc). Here we can improve CSS from `figure.size-full` to `.wp-block-image.size-full`. I've done this.

2020-10-05 11:23 UTC, imnavanath commented on inc/class-astra-dynamic-css.php
> +					'.ast-theme-transparent-header #primary, .ast-theme-transparent-header #secondary' => array(
Done

2020-10-06 09:46 UTC, premanshup approved these changes

2020-10-06 10:47 UTC, shubhw12 approved these changes

2020-10-06 10:49 UTC, merged