fix: console error with settings group in case of RTL languages.
brainstormforce/astra pull request #1863
Opened 2020-08-25 11:50 UTC by shubhw12

### Description
In the case of RTL languages, we had an issue for the UI tab key being passed the same as the language. fixed this by setting a counter and based on that counter the key will be decided.

### Screenshots

### Types of changes

### How has this been tested?

Checked with 3 color options and in RTL languages and LTR languages as well.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2020-08-27 06:08 UTC, premanshup requested changes

2020-08-27 06:08 UTC, premanshup commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
> +                    else if( 1 == counter ){
@shubhw12 Please use Yoda conditions here.

2020-08-27 06:08 UTC, premanshup commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
> +                    if( 0 == tabs_counter ) {
@shubhw12 Please use Yoda conditions here.

2020-08-27 06:08 UTC, premanshup commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
> +                _.each( fields.tabs, function ( value , key ) {
@shubhw12 Please remove extra space before comma between value and key.

2020-08-27 06:08 UTC, premanshup commented on inc/customizer/custom-controls/settings-group/settings-group.js
> +                _.each( fields.tabs, function ( value , key ) {
@shubhw12 Please remove extra space before comma between value and key.

2020-08-27 06:30 UTC, premanshup approved these changes

2020-08-27 07:59 UTC, shubhw12 commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
> +                _.each( fields.tabs, function ( value , key ) {
Donw

2020-08-27 07:59 UTC, shubhw12 commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
> +                    if( 0 == tabs_counter ) {
Done

2020-08-27 12:19 UTC, imnavanath commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
> +                    if( 0 === tabs_counter ) {
We can replace if-else-if logic with switch case.

2020-08-31 13:24 UTC, shubhw12 commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
> +                    if( 0 === tabs_counter ) {
Yes I have replaced it with switch case.

2020-09-03 04:16 UTC, imnavanath approved these changes

2020-09-03 04:18 UTC, premanshup approved these changes

2020-10-01 13:59 UTC, merged