chore: Remove error_log() and rename the class with Astra prefix.
brainstormforce/astra pull request #1876
Opened 2020-09-08 12:08 UTC by shubhw12

### Description
Theme review changes removed the error_log() and renamed a file with Astra class prefix.

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2020-09-08 12:16 UTC, imnavanath approved these changes

2020-09-08 12:21 UTC, premanshup requested changes

2020-09-08 12:21 UTC, premanshup commented on inc/theme-update/class-astra-theme-wp-background-process.php
> +	class Astra_Theme_WP_Background_Process extends WP_Background_Process {
@shubhw12 Please verify if this class is used in Astra Pro or not?

2020-09-08 12:23 UTC, shubhw12 commented on inc/theme-update/class-astra-theme-wp-background-process.php
> +	class Astra_Theme_WP_Background_Process extends WP_Background_Process {
@premanshup Sir, Yes I have already verified it this class is not used in Astra PRO.

2020-09-08 12:24 UTC, premanshup approved these changes

2020-09-10 07:20 UTC, imnavanath approved these changes

2020-09-10 07:21 UTC, merged