fix: Header partial refresh issues and general.
brainstormforce/astra pull request #1920
Opened 2020-09-18 14:42 UTC by rohitp-bsf

### Description
- fix: Header partial refresh issues and general.

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2020-09-18 16:45 UTC, vrundakansara approved these changes

2020-09-21 05:34 UTC, premanshup requested changes

2020-09-21 05:34 UTC, premanshup commented on inc/class-astra-constants.php
> +		public static function is_header_footer_builder() {
@rohitp-bsf Instead of creating two functions with same name and definition, we can use the existing `Astra_Builder_Helper::is_header_footer_builder();`. Please check!

2020-09-21 05:34 UTC, premanshup commented on inc/customizer/class-astra-builder-customizer.php
> +					'contexts'                 => self::ast_get_contexts(),
@rohitp-bsf Please rename this function to `get_contexts` as we have already added Astra prefix in the class name.

2020-09-21 05:34 UTC, premanshup commented on inc/customizer/class-astra-builder-customizer.php
> +					'choices'                  => self::ast_get_choices(),
@rohitp-bsf Please rename this function to `get_choices` as we have already added Astra prefix in the class name.

2020-09-21 06:01 UTC, rohitp-bsf commented on inc/class-astra-constants.php
> +		public static function is_header_footer_builder() {
I have cut pasted that functions inside the constants file. Can not be called Astra_Builder_Helper inside constants as `Astra_Builder_Helper` is not yet loaded.

2020-09-21 06:39 UTC, premanshup approved these changes

2020-09-21 06:40 UTC, merged