fix: Page Header & Mega Menu scripts not loading as dependent script is missing from theme
brainstormforce/astra pull request #1931
Opened 2020-09-22 06:51 UTC by imnavanath

### Description
- Page Header & Mega menu stopped working
- https://i.imgur.com/J56G3Ey.png
- https://i.imgur.com/thdESpu.png

### Screenshots
- https://a.cl.ly/8LuPvzvO
- https://a.cl.ly/7KuLY97g

### Types of changes
- Registered again the `astra-color-alpha` script in theme

### How has this been tested?
- With Page Header edit page
- With Mega menu popup

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation
- [ ] I've added proper labels to this pull request

2020-09-22 07:35 UTC, premanshup requested changes

2020-09-22 07:35 UTC, premanshup commented on inc/core/class-astra-admin-settings.php
> +			wp_register_script( 'astra-color-alpha', ASTRA_THEME_URI . 'assets/js/' . $dir . '/wp-color-picker-alpha' . $js_prefix, $js_handle, ASTRA_THEME_VERSION, true );
@imnavanath I think this whole register should be moved to Addon as we are not using this anymore in the theme, we are using https://developer.wordpress.org/block-editor/components/color-picker/. Please check!

2020-09-22 07:38 UTC, imnavanath commented on inc/core/class-astra-admin-settings.php
> +			wp_register_script( 'astra-color-alpha', ASTRA_THEME_URI . 'assets/js/' . $dir . '/wp-color-picker-alpha' . $js_prefix, $js_handle, ASTRA_THEME_VERSION, true );
Yes, valid one 👍 
On it...

2020-09-22 08:25 UTC, imnavanath commented on inc/core/class-astra-admin-settings.php
> +			wp_register_script( 'astra-color-alpha', ASTRA_THEME_URI . 'assets/js/' . $dir . '/wp-color-picker-alpha' . $js_prefix, $js_handle, ASTRA_THEME_VERSION, true );
PR for the addon - https://git.brainstormforce.com/astra/astra-addon/-/merge_requests/1775

2020-09-23 10:45 UTC, premanshup approved these changes

2020-09-23 10:49 UTC, merged