fix: Width of Gradient angle input number field restricts number selection in WP-5.6
brainstormforce/astra pull request #2017
Opened 2020-11-25 10:15 UTC by imnavanath

### Description
- Number field is not proper in WP5.6 for gradient angle control
- PS: up-down arrow for number field is left aligned completely

### Screenshots
- https://a.cl.ly/nOunbNkg

### Types of changes
- Updated its CSS as compatible with any WP Version

### How has this been tested?
- With WP version 5.6 >
- With WP version 5.6 <
- With responsive devices

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2020-12-01 03:36 UTC, premanshup requested changes

2020-12-01 03:36 UTC, premanshup commented on inc/customizer/custom-controls/assets/css/unminified/color.css
> +    max-width: 65px;
@imnavanath The Type and angle fields are not aligned - https://d.pr/i/8tzczv - Please check.

2020-12-02 04:10 UTC, imnavanath commented on inc/customizer/custom-controls/assets/css/unminified/color.css
> +    max-width: 65px;
Updated CSS, can you please verify it once on your end @premanshup ?

2020-12-04 13:54 UTC, imnavanath commented
Moved PR here - https://github.com/brainstormforce/astra/pull/2078 to dev branch in case of immediate update.

2020-12-04 13:54 UTC, closed without merging