refactor: Removed ast-hide customizer CSS as we managed this from customizer JS
brainstormforce/astra pull request #2044
Opened 2020-12-01 09:57 UTC by imnavanath

### Description
- Removed ast-hide customizer CSS as we managed this from customizer JS

### Types of changes
- Removed `ast-hide` CSS from customizer-controls.css

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've added proper labels to this pull request

2020-12-01 11:39 UTC, premanshup approved these changes

2021-03-10 03:48 UTC, rohitp-bsf requested changes
@imnavanath Is this tested? And also make sure this call has not been used anywhere. Also, Please update this PR.

2021-03-10 05:48 UTC, imnavanath commented
> @imnavanath Is this tested? And also make sure this call has not been used anywhere. Also, Please update this PR.

Verified @rohitp-bsf as this is not used anywhere for customizer-section. Also branch is upto-date now.

Also new card is created for testing purpose, after tested we can merge this. Task - https://trello.com/c/sm9X48zB/620-ast-hide-css-removed-which-required-previously-for-php-based-customizer-sections

2021-03-10 13:23 UTC, vrundakansara approved these changes

2021-03-11 12:05 UTC, rohitp-bsf approved these changes

2021-03-11 12:06 UTC, merged