wip:New global color palette
brainstormforce/astra pull request #2088
Opened 2020-12-08 13:32 UTC by amithire1201

### Description
https://trello.com/c/CktyyqGt/835-global-color-palette

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-01-11 10:29 UTC, premanshup requested changes

2021-01-11 10:29 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +			{	pattern1html }
@amithire1201 Please add proper indentation.

2021-01-11 10:29 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		</p> */}
@amithire1201 Please remove the commented code.

2021-01-11 10:29 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		<div className={'astra-palette-import-wrap'}>
@amithire1201 Is there a need to add dynamic JSX syntax for a class name? it looks like this is static and not dynamic. Please check other attributes too from the rest of the JSX.

2021-01-11 10:29 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +																} }
@amithire1201 Please avoid using inline Style until it is really required.

2021-01-11 10:29 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +																			transition: '100ms transform ease',
@amithire1201 Please avoid using inline Style until it is really required.

2021-01-11 10:29 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color/color-component.js
> +		props.control.container[0].setAttribute('paleteused', value);
@amithire1201 Please check the spelling for the `palette`.

2021-01-11 10:29 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/responsive-background/responsive-background.js
> +					current_color = e.detail.palette[e.detail.palette.patterntype][4]
@amithire1201 Instead of labels can we check key maybe? We very frequently change the Label but key is very rare. Let's try to switch this to key instead of label.

2021-01-11 10:29 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/responsive-background/responsive-background.js
> +
@amithire1201 Please remove blank spaces from here and everywhere else.

2021-01-11 10:29 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/responsive-color/responsive-color-component.js
> +	var temp_dbval = Object.assign({},dbvalue);
@amithire1201 Please use camel casing.

2021-01-11 10:29 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/responsive-color/responsive-color-component.js
> +		if(key == "desktop"){
@amithire1201 Please use strict type checking.

2021-01-12 08:19 UTC, amithire1201 commented on inc/customizer/class-astra-customizer.php
> +			if ( isset( get_option( ASTRA_THEME_SETTINGS )['global-color-palette'] ) ) {
Done.

2021-01-12 08:19 UTC, amithire1201 commented on inc/customizer/class-astra-customizer.php
> +					'sanitize_callback' => '',
Done.

2021-01-12 08:19 UTC, amithire1201 commented on inc/customizer/class-astra-customizer.php
> +					'sanitize_callback' => '',
Done.

2021-01-12 08:19 UTC, amithire1201 commented on inc/customizer/custom-controls/color-palette/class-astra-control-color-palette.php
> + * @since       1.0.0
Done.

2021-01-12 08:19 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/background/background.js
> +	var dbvalue= props.control.setting.get();
Done.

2021-01-12 08:19 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/background/background.js
> +	const updatepaletteuse = (value,index,defaultset) =>{
Done.

2021-01-12 08:20 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		<Fragment>
Done.

2021-01-12 08:20 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +import { SelectControl,Dashicon,RadioControl,Button,Popover,TabPanel,TextareaControl } from '@wordpress/components';
Done.

2021-01-12 08:20 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +
Done.

2021-01-12 08:20 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		}
Done.

2021-01-12 08:20 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		var passglobalpalette = new CustomEvent( "colorpaletteglobal",
Done.

2021-01-12 08:20 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		</Fragment>
Done.

2021-01-12 08:20 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +				<div className="ast-color-picker-palette-1 ast-color-palette-inline" title="Text Color">
Done.

2021-01-12 08:20 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		function testJSON(text) {
Done.

2021-01-12 08:20 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +	return <Fragment>
Done.

2021-01-12 08:20 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +			{	pattern1html }
Done.

2021-01-12 08:20 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		</p> */}
Done.

2021-01-12 08:20 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		<div className={'astra-palette-import-wrap'}>
Done.

2021-01-12 08:21 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +																} }
Done.

2021-01-12 08:21 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +																			transition: '100ms transform ease',
Done.

2021-01-12 08:21 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color/color-component.js
> +		props.control.container[0].setAttribute('paleteused', value);
Done.

2021-01-12 08:21 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/responsive-background/responsive-background.js
> +
Done.

2021-01-12 08:21 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/responsive-color/responsive-color-component.js
> +	var temp_dbval = Object.assign({},dbvalue);
Done.

2021-01-12 08:21 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/responsive-color/responsive-color-component.js
> +		if(key == "desktop"){
Done.

2021-01-14 09:22 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/responsive-background/responsive-background.js
> +					current_color = e.detail.palette[e.detail.palette.patterntype][4]
Here labels are used as they are in common and we can handle them globally. Alternatively, we can change to some other custom key which will require some rework in all controls config files. Let me know if  I should go with custom keys.

2021-01-14 09:23 UTC, amithire1201 commented on inc/customizer/configurations/colors-background/class-astra-body-colors-configs.php
> +					'default'  => '#0274b2',
We are changing as we need to keep in sync with our color palette.

2021-02-01 12:45 UTC, premanshup commented on inc/addons/heading-colors/customizer/class-astra-heading-colors-configs.php
> +					'default'           => '#3a3a3b',
@amithire1201 Is this same as the color defined in Static  CSS?

2021-02-01 12:45 UTC, premanshup commented on inc/customizer/custom-controls/color-palette/color-palette.scss
> +    }
@amithire1201 It looks like we are not using this CSS class anywhere in the HTML markup. Please remove this if this is not loaded. Verify any other old CSS as well.

2021-02-01 12:49 UTC, premanshup commented on inc/customizer/configurations/colors-background/class-astra-body-colors-configs.php
> +					'default'  => '#0274b2',
@amithire1201 So, right now, aren't we keeping the same old colors in Global Palette by default except for the last color ( heading color )?

2021-02-01 12:52 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/responsive-background/responsive-background.js
> +					current_color = e.detail.palette[e.detail.palette.patterntype][4]
@amithire1201 Instead of keeping the custom event, can we add default value as var(palette1), var(palette2), var(palette3), var(palette4) which will be in sync with the global palette color. And add default values to the Global Palette color same as text, hover, link, and theme color? I think we can then directly remove this custom event and the common key logic that we have added. Let me know your thoughts.

2021-02-02 03:38 UTC, amithire1201 commented on inc/customizer/custom-controls/color-palette/color-palette.scss
> +    }
Done.

2021-02-05 14:03 UTC, premanshup requested changes

2021-02-05 14:03 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/control-customizer.js
> +				document.dispatchEvent(event);
@amithire1201 Instead of custom even can we use `updateValues` function to finally update the CSS without dispatching Custom Event?

2021-02-05 14:03 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/responsive-background/responsive-background.js
> +			props.control.setting.set(obj);
@amithire1201 Please add proper indentation and spacing.

2021-02-05 14:03 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/responsive-color/responsive-color-component.js
> +						fontSize: 14
@amithire1201 Please try to avoid using inline CSS. Add CSS in respective SCSS for the control instead of adding it inline.

2021-02-05 16:35 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/responsive-background/responsive-background.js
> +			props.control.setting.set(obj);
Done.

2021-02-05 16:35 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color/color-component.js
> +
Done.

2021-02-05 16:35 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +	const myFunction = (e) =>{
Done.

2021-02-05 16:36 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		setState(obj)
Done.

2021-02-05 16:40 UTC, amithire1201 commented on inc/class-astra-dynamic-css.php
> +			$array = $global_palette[ $global_palette['patterntype'] ];
Updated.

2021-02-05 16:40 UTC, amithire1201 commented on inc/core/builder/class-astra-builder-options.php
> +			array( '#3a3a3a', 'Text Color' ),
Done.

2021-02-05 16:40 UTC, amithire1201 commented on functions.php
> +
Done

2021-02-05 16:40 UTC, amithire1201 commented on inc/customizer/custom-controls/responsive-background/responsive-background.scss
> +*/
Done.

2021-02-05 16:40 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/background/background.js
> +import {Dashicon,Popover,Button} from '@wordpress/components';
Done

2021-02-05 16:40 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +
Done.

2021-02-05 16:40 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		if (typeof color === 'string' || color instanceof String) {
Done.

2021-02-05 17:02 UTC, Nikschavan commented on inc/class-astra-dynamic-css.php
> +					$palette_variables                  = '--ast-global-palette' . $key;
```suggestion
					$palette_variables                  = '--ast-global-palette-' . $key;
```

Let's add an extra `-` before the dynamic part of the string, You will need to update it everywhere else as well.

2021-02-05 18:13 UTC, Nikschavan requested changes
Some general feedback - 

- There are lot of empty lines in between which are not required.
- Lot of incorrect spacings/indentations, I have flagged a few places and not flagged others.
- Improper variable names like `string`, `obj` etc. Name all variables appripriately
- use `camelCase` for all variables.

Do check whole PR and then re-assign for review.

2021-02-05 18:13 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +			props.control.setting.set( obj );
What is difference between both these statements?

2021-02-05 18:13 UTC, Nikschavan commented on inc/customizer/class-astra-customizer.php
> +				add_filter( 'language_attributes', array( $this, 'add_style_tag_to_html_element' ) );
Is this required? I see at the bottom that we are also adding CSS with CSS Variables to `:root` using JS.

2021-02-05 18:13 UTC, Nikschavan commented on inc/customizer/class-astra-customizer.php
> +		public function check_filters_for( $hook = '' ) {
Name the function appropriately, I believe this function is checking if old palette is used? maybe the function can be names something similar?

2021-02-06 12:50 UTC, premanshup commented on inc/core/builder/class-astra-builder-options.php
> +			array( '#3a3a3b', __( 'Heading Color ( H1 - H6 )', 'astra' ) ),
@Nikschavan Agree! For strings, there is no need to add space after/before brackets.

2021-03-22 06:38 UTC, closed without merging

2021-03-22 06:40 UTC, Nikschavan commented
This is being worked in #2520