imprv: Shifted cart icon static css from js file to php file.
brainstormforce/astra pull request #2090
Opened 2020-12-09 06:29 UTC by sagarb90

### Description
- Shifted cart icon static css from js file to php file.

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards <!-- Guidelines: https://make.wordpress.org/core/handbook/best-practices/coding-

2020-12-09 14:59 UTC, premanshup commented on sass/site/builder/_header.scss
> -.ast-header-break-point{
@sagarb90 I think we provide Shortcode for the Cart, In case of shortcode, this may not work. Let's have a call to discuss this case.

2020-12-09 15:00 UTC, premanshup requested changes

2020-12-09 15:00 UTC, premanshup commented on sass/site/builder/_header.scss
> -.ast-header-break-point{
@sagarb90  I think we provide Shortcode for the Cart, In case of shortcode, this may not work. Let's have a call to discuss this case.

2020-12-09 15:03 UTC, imnavanath commented on inc/class-astra-dynamic-css.php
> +			if ( Astra_Builder_Helper::is_component_loaded( 'header', 'woo-cart' ) || Astra_Builder_Helper::is_component_loaded( 'header', 'edd-cart' ) ) {
Agreed with the comment, we should make sure shortcodes will work as earlier. This condition will restrict the usage of shortcode

2020-12-10 04:44 UTC, sagarb90 commented on sass/site/builder/_header.scss
> -.ast-header-break-point{
Okay!

2020-12-10 05:56 UTC, premanshup commented on sass/site/builder/_header.scss
> -.ast-header-break-point{
@sagarb90 As per the discussion with @RajkiranBagal , this will not cause any issue because the Shortcode CSS is present in the Addon. I'm merging this.

2020-12-10 05:56 UTC, premanshup approved these changes

2020-12-10 05:57 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +			if ( Astra_Builder_Helper::is_component_loaded( 'header', 'woo-cart' ) || Astra_Builder_Helper::is_component_loaded( 'header', 'edd-cart' ) ) {
@imnavanath As per the discussion with @RajkiranBagal , this will not cause any issue because the Shortcode CSS is present in the Addon. I'm merging this.

2020-12-10 06:03 UTC, imnavanath commented on inc/class-astra-dynamic-css.php
> +				display: inline-block;
Can we get these selectors in combined way, so we will reduce this repetitive CSS on page load. https://a.cl.ly/jkuYed1y

2020-12-10 06:03 UTC, shubhw12 approved these changes

2020-12-10 06:26 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> +				display: inline-block;
Done Changes.

2020-12-10 06:40 UTC, imnavanath approved these changes

2020-12-10 06:41 UTC, merged