new: Mobile Header Cart Flyout.
brainstormforce/astra pull request #2107
Opened 2020-12-11 08:51 UTC by RajkiranBagal

### Description
 - Trello task - https://trello.com/c/jjOlTZuE/704-cart-for-mobile-header

### Types of changes
New feature (non-breaking change which adds functionality)

### How has this been tested?
 - In the mobile Header click on Cart to see the items in the cart.

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-02-08 07:03 UTC, premanshup requested changes

2021-02-08 07:03 UTC, premanshup commented on assets/js/unminified/frontend.js
> +	cartFlyoutOpen = function ( event ) {
@RajkiranBagal This can be more optimized, If we create a separate JS file instead of adding this in the frontend.js which will load this JS even if WooCommerce is not installed.

I will recommend adding a different JS file for this and loading it conditionally.

Also, I'm not sure if there is any option or not to disable/enable this feature, it would be recommended to keep this option based so the JS will load only when this option is enabled.

2021-02-08 07:03 UTC, premanshup commented on assets/css/unminified/frontend.css
> +/** Mobile Header Cart Flyout */
@RajkiranBagal Same here as for JS, this CSS should be loaded from Dynamic CSS that too option based. Only when WooCommerce and the option for Flyout Cart is enabled.

2021-02-12 12:31 UTC, sagarb90 commented on assets/js/unminified/frontend.js
> +	cartFlyoutOpen = function ( event ) {
@premanshup Yes we have make separate JS file and load conditionally  i.e. when component is loaded

2021-02-12 12:35 UTC, sagarb90 commented on assets/css/unminified/frontend.css
> +/** Mobile Header Cart Flyout */
@premanshup Yes we have moved all static CSS related to Woo/EDD in dynamic CSS and load it conditionally.

2021-02-12 15:44 UTC, premanshup requested changes

2021-02-12 15:44 UTC, premanshup commented on assets/js/unminified/mobile-cart.js
> + *
@sagarb90 Since tag is missing from the function doc comment.

2021-02-12 15:44 UTC, premanshup commented on assets/js/unminified/mobile-cart.js
> +
```suggestion

```

2021-02-12 15:44 UTC, premanshup commented on assets/js/unminified/mobile-cart.js
> +
```suggestion

```

2021-02-12 15:44 UTC, premanshup commented on assets/js/unminified/mobile-cart.js
> +	 */
```suggestion
  /**
	 * Opens the Cart Flyout.
	 */
```

2021-02-12 15:44 UTC, premanshup commented on assets/js/unminified/mobile-cart.js
> +
```suggestion

```

2021-02-12 15:44 UTC, premanshup commented on assets/js/unminified/mobile-cart.js
> +
```suggestion
			
```

2021-02-12 15:44 UTC, premanshup commented on inc/builder/markup/class-astra-builder-header.php
> +
```suggestion

```

2021-02-12 15:44 UTC, premanshup commented on inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php
> +
```suggestion

```

2021-02-12 15:44 UTC, premanshup commented on inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php
> +
```suggestion

```

2021-02-12 15:44 UTC, premanshup commented on inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php
> +
```suggestion

```

2021-02-12 15:44 UTC, premanshup commented on inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php
> +
```suggestion

```

2021-02-12 15:44 UTC, premanshup commented on inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php
> +
```suggestion

```

2021-02-12 15:44 UTC, premanshup commented on inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php
> +
```suggestion

```

2021-02-12 15:44 UTC, premanshup commented on inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php
> +
```suggestion

```

2021-02-12 15:44 UTC, premanshup commented on inc/builder/type/header/woo-cart/assets/js/customizer-preview.js
> +	// astra_css( 'astra-settings[header-woo-cart-link-color]', 'color', '' );
```suggestion

```

2021-02-12 15:44 UTC, premanshup commented on inc/builder/type/header/woo-cart/assets/js/customizer-preview.js
> +	// astra_css( 'astra-settings[header-woo-cart-btn-bg-hover-color]', 'background-color', '.ast-site-header-cart .ast-site-header-cart-data .widget_shopping_cart_content a.button.wc-forward:not(.check
@RajkiranBagal @sagarb90 Why do we have commented code here? Is it required or not?

2021-02-12 15:44 UTC, premanshup commented on inc/builder/type/header/woo-cart/assets/js/customizer-preview.js
> +	// astra_css( 'astra-settings[header-woo-cart-link-color]', 'color', '' );
Is this commented code required or not?

2021-02-12 15:44 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +				text-align: center;
@RajkiranBagal @sagarb90 Can we reduce the CSS weightage here and all the CSS added in this file?

2021-02-12 15:44 UTC, premanshup commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +				$woo_cart_link = '#';
@RajkiranBagal Why are we replacing link with # in Customizer Preview?

2021-02-12 15:44 UTC, premanshup commented on inc/core/class-astra-enqueue-scripts.php
> +
```suggestion

```

2021-02-12 15:44 UTC, premanshup commented on sass/site/builder/_header.scss
>  .ast-mobile-popup-content .ast-builder-menu-mobile .main-header-menu {
Do we need backward compatibility for this?

2021-02-15 04:14 UTC, RajkiranBagal commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +				$woo_cart_link = '#';
This is needed because as it is an anchor tag, if we click on it in customizer preview, it causes customizer refresh & event.preventDefault() is not working there.

2021-02-15 04:15 UTC, RajkiranBagal commented on assets/js/unminified/frontend.js
> -	}
Yes this is needed.

2021-02-15 04:39 UTC, sagarb90 commented on sass/site/builder/_header.scss
>  .ast-mobile-popup-content .ast-builder-menu-mobile .main-header-menu {
@premanshup No we have just shift this static CSS to dynamic CSS and load conditionally as we have done before.

2021-02-15 05:16 UTC, sagarb90 commented on inc/builder/type/header/woo-cart/assets/js/customizer-preview.js
> +	// astra_css( 'astra-settings[header-woo-cart-btn-bg-hover-color]', 'background-color', '.ast-site-header-cart .ast-site-header-cart-data .widget_shopping_cart_content a.button.wc-forward:not(.check
@premanshup Done removed all commented code.

2021-02-15 05:17 UTC, sagarb90 commented on assets/js/unminified/mobile-cart.js
> + *
@premanshup Added since tag in doc comment.

2021-02-15 06:18 UTC, RajkiranBagal commented on inc/class-astra-dynamic-css.php
> +				text-align: center;
Reduced the CSS weightage where it is possible.

2021-02-15 06:30 UTC, RajkiranBagal commented on inc/builder/controllers/class-astra-builder-ui-controller.php
> +					<div class="astra-cart-drawer-header">
Done. Removed unwanted div.

2021-02-15 06:32 UTC, sagarb90 commented on assets/js/unminified/frontend.js
> -	}
Yes reverted this code.

2021-02-16 13:10 UTC, premanshup approved these changes

2021-02-17 09:49 UTC, vrundakansara commented on inc/builder/controllers/class-astra-builder-ui-controller.php
> +		public static function render_mobile_cart_flyout_markup() {
Should we add `is_component_loaded` check here in order to avoid unnecessary markup?

2021-02-17 09:49 UTC, vrundakansara commented on inc/builder/markup/class-astra-builder-header.php
> +		public function define_constants() {
Can we get rid of blank function?

2021-02-17 09:49 UTC, vrundakansara commented on inc/class-astra-dynamic-css.php
> +				.ast-header-break-point.ast-woocommerce-cart-menu.astra-hfb-header .ast-cart-menu-wrap, .ast-header-break-point.astra-hfb-header .ast-cart-menu-wrap {
Can we combine these two?
```css
.ast-header-break-point.ast-woocommerce-cart-menu.astra-hfb-header .ast-cart-menu-wrap, .ast-header-break-point.astra-hfb-header .ast-cart-menu-wrap,
.ast-header-break-point .ast-edd-site-header-cart-wrap .ast-edd-cart-menu-wrap {
					width: 2em;
					height: 2em;
					font-size: 1.4em;
					line-height: 2;
					vertical-align: middle;
					text-align: right;
				}
```

2021-02-17 09:49 UTC, vrundakansara commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> -			'color' => esc_attr( $cart_link_color ),
What will happen to old values?

2021-02-17 10:19 UTC, sagarb90 commented on inc/builder/markup/class-astra-builder-header.php
> +		public function define_constants() {
@vrundakansara Yes this is removed.

2021-02-17 10:20 UTC, sagarb90 commented on inc/builder/controllers/class-astra-builder-ui-controller.php
> +		public static function render_mobile_cart_flyout_markup() {
Yes loaded  conditionally markup on is_component_loaded();

2021-02-17 10:20 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> +				.ast-header-break-point.ast-woocommerce-cart-menu.astra-hfb-header .ast-cart-menu-wrap, .ast-header-break-point.astra-hfb-header .ast-cart-menu-wrap {
Yes combined

2021-02-17 10:21 UTC, sagarb90 commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> -			'color' => esc_attr( $cart_link_color ),
As these are totally new controls so their  is no need to maintained old values.

2021-02-17 10:48 UTC, vrundakansara approved these changes

2021-02-17 10:50 UTC, merged