fix: Issues from Beta 2 zip
brainstormforce/astra pull request #2120
Opened 2020-12-15 10:55 UTC by imnavanath

### Description
- Issues of priority and customizer context issues in HFB
- https://trello.com/c/C76RYcpO/853-beta-zip

### Types of changes
- CSS, JS improvements as per listed issues

### How has this been tested?
- WIth old header-footer & new HFB

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2020-12-15 15:30 UTC, vrundakansara approved these changes

2020-12-16 06:58 UTC, rohitp-bsf approved these changes
LGTM

2020-12-16 07:34 UTC, premanshup approved these changes

2020-12-16 07:36 UTC, premanshup requested changes

2020-12-16 07:36 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/divider/divider-component.js
> +		separatorHtml = null
@imnavanath let separatorHtml = null; is already defined above. Can you please check if this is required or not?

2020-12-16 07:38 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/divider/divider-component.js
> +		separatorHtml = null
Yes already defined but after that we add `<hr/>` to it, which creates this issue after assigning label/title to it. https://i.imgur.com/lIE3xhr.png
That's why I've again set this null if title/label is assigned.

2020-12-16 07:51 UTC, premanshup approved these changes

2020-12-16 08:10 UTC, merged