improvement: Removed extra white spaces and blank lines.
brainstormforce/astra pull request #2124
Opened 2020-12-15 13:36 UTC by sagarb90

### Description
- Removed extra white spaces and blank lines.
- Removed extra PHP tags.

### Screenshots

### Types of changes
- Improvements.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards

2020-12-22 15:34 UTC, premanshup requested changes

2020-12-22 15:34 UTC, premanshup commented on inc/assets/css/customizer-preview.css
> +.elementor-page .customize-partial-edit-shortcut button {
@sagarb90 PLease verify why we are adding this CSS?

2020-12-22 15:34 UTC, premanshup commented on inc/builder/type/footer/copyright/class-astra-footer-copyright-component-loader.php
> -		// Localize variables for Astra Breakpoints JS.
@sagarb90 PLease verify why we are removing this JS?

2020-12-23 06:00 UTC, sagarb90 commented on inc/assets/css/customizer-preview.css
> +.elementor-page .customize-partial-edit-shortcut button {
@premanshup this is other developer commit changes here we have just worked on HTML blank spaces. Now I have updated with latest branch.

2020-12-23 06:01 UTC, sagarb90 commented on inc/builder/type/footer/copyright/class-astra-footer-copyright-component-loader.php
> -		// Localize variables for Astra Breakpoints JS.
@premanshup Same as above comment.

2020-12-24 11:32 UTC, premanshup commented on inc/assets/css/customizer-preview.css
> +.elementor-page .customize-partial-edit-shortcut button {
@sagarb90 Got it 👍🏼

2020-12-24 11:32 UTC, premanshup commented on inc/builder/type/footer/copyright/class-astra-footer-copyright-component-loader.php
> -		// Localize variables for Astra Breakpoints JS.
@sagarb90 👍🏼

2020-12-24 11:32 UTC, shubhw12 approved these changes

2020-12-24 11:33 UTC, premanshup approved these changes

2020-12-28 13:00 UTC, vrundakansara approved these changes

2020-12-28 13:14 UTC, merged