fix: added condition for pagination markup to avoid blank print.
brainstormforce/astra pull request #2129
Opened 2020-12-16 07:38 UTC by sagarb90

### Description
- Added condition for pagination markup to avoid blank print.

### Types of changes
- Improvement.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards

2020-12-17 05:26 UTC, premanshup requested changes

2020-12-17 05:26 UTC, premanshup commented on inc/markup-extras.php
> +		if ( ( $wp_query->max_num_pages < 2 && ( is_home() || is_archive() || is_search() ) ) || ! $enabled ) {
@sagarb90 Any specific reason for adding this condition?

`( is_home() || is_archive() || is_search() ) )`

2020-12-17 06:06 UTC, sagarb90 commented on inc/markup-extras.php
> +		if ( ( $wp_query->max_num_pages < 2 && ( is_home() || is_archive() || is_search() ) ) || ! $enabled ) {
@premanshup Yes pagination markup is added in these 3 pages so added conditions for the same.

2020-12-18 05:56 UTC, premanshup requested changes

2020-12-18 05:56 UTC, premanshup commented on inc/markup-extras.php
> +		if ( ( isset( $numpages ) && $wp_query->max_num_pages < 2 ) || ! $enabled ) {
@sagarb90 Can we use $numpages instead of `$wp_query->max_num_pages` here? This way maybe we can remove `$wp_query;`?

2020-12-18 06:20 UTC, sagarb90 commented on inc/markup-extras.php
> +		if ( ( isset( $numpages ) && $wp_query->max_num_pages < 2 ) || ! $enabled ) {
@premanshup No we cannot use $numpages as it always return 1 for single page with multiple posts, if no. of post more than 3 and page limit is 2 then we are getting $numpages value =1 so we get the exact count in $wp_query->max_num_pages only, so I have used this I have also refer other themes pagination condition they have use same for that.

2020-12-22 14:55 UTC, premanshup approved these changes

2020-12-23 04:48 UTC, merged