fix: Zero values are not accepting in Icon size, Icon spacing, Icon BG space & Icon radius
brainstormforce/astra pull request #2136
Opened 2020-12-16 11:48 UTC by imnavanath

### Description
- In Social Component Zero values are not accepting in Icon size, Icon spacing, Icon BG space & Icon radius

### Screenshots
- Back end Screenshot - https://i.imgur.com/lmRdqed.png
- Front End screenshot - https://i.imgur.com/O1YnVTk.png

### Types of changes
- Updated conditions in validation of these values

### How has this been tested?
- Header/Footer social component

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2020-12-17 14:31 UTC, vrundakansara approved these changes

2020-12-24 06:21 UTC, premanshup requested changes

2020-12-24 06:21 UTC, premanshup commented on inc/builder/type/base/dynamic-css/social/class-astra-social-component-dynamic-css.php
> +			$icon_spacing_mobile  = ( isset( $icon_spacing['mobile'] ) && '' !== $icon_spacing['mobile'] ) ? (int) $icon_spacing['mobile'] / 2 : 6;
@imnavanath Please check if we can replace this with our function `function astra_get_css_value`

Also, if we already have default then why are we again adding default `6` for the value?

Please verify them.

2020-12-24 08:50 UTC, imnavanath commented on inc/builder/type/base/dynamic-css/social/class-astra-social-component-dynamic-css.php
> +			$icon_spacing_mobile  = ( isset( $icon_spacing['mobile'] ) && '' !== $icon_spacing['mobile'] ) ? (int) $icon_spacing['mobile'] / 2 : 6;
We already used this function below on line 94, https://github.com/brainstormforce/astra/pull/2136/files#diff-621cca59f6764c7449de8c15ea039392bc6ae09d35054c1de51bd37b9d03d941R94

Reverted this 6 to '' as this is managed from static style itself.

2020-12-28 10:36 UTC, premanshup approved these changes

2020-12-28 10:41 UTC, merged