feat: Astra compatibility with Gutenberg block patterns
brainstormforce/astra pull request #2142
Opened 2020-12-17 09:02 UTC by imnavanath

### Description
- https://trello.com/c/8HMa6B4q/233-gutenberg-block-pattern-compatibility
- Compatibility with Buttons to buttons used in GB block patterns

### Types of changes
- Added backward compatibility for old users
- For new it start directly

### How has this been tested?
- For old setup
- Filter to use - `add_filter( 'astra_gutenberg_patterns_compatibility', '__return_true' );`

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards
- [x] My code has proper inline documentation
- [x] I've included any necessary tests 
- [x] I've included developer documentation
- [x] I've added proper labels to this pull request

2021-01-06 06:04 UTC, premanshup requested changes

2021-01-06 06:04 UTC, premanshup commented on functions.php
> +define( 'ASTRA_THEME_VERSION', '2.6.3' );
@imnavanath Please pull latest `next-release` in this and change the backward comp version to 3.0.0 as well.

2021-01-06 06:04 UTC, premanshup commented on inc/core/class-gutenberg-editor-css.php
> +						'color' => esc_attr( $btn_text_hover_color ) . ' !important',
@imnavanath Can we remove `!important` if possible here?

2021-01-06 07:26 UTC, shubhw12 approved these changes

2021-01-11 06:58 UTC, imnavanath commented on functions.php
> +define( 'ASTRA_THEME_VERSION', '2.6.3' );
Updated to version `3.1.0` for both theme constant & backward function.

2021-01-11 06:58 UTC, imnavanath commented on inc/core/class-gutenberg-editor-css.php
> +						'color' => esc_attr( $btn_text_hover_color ) . ' !important',
I tried this, but the CSS applies inline through GB block. That's why I've added important here.

2021-03-02 09:56 UTC, premanshup approved these changes

2021-03-02 13:19 UTC, vrundakansara approved these changes

2021-03-08 05:06 UTC, merged