improvements: separate pagination css file and load conditionally
brainstormforce/astra pull request #2144
Opened 2020-12-17 10:29 UTC by sagarb90

### Description
- Separate pagination CSS file and load conditionally  to optimize the fronetend.css file.

### Types of changes
- Improvements.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards

2020-12-18 10:31 UTC, premanshup requested changes

2020-12-18 10:31 UTC, premanshup commented on sass/grid/mixins/_grid-framework.scss
> -      @each $modifier in (pull, push, offset) {
@sagarb90 Let's move this CSS to backward compatibility as we did for normalize.scss file.

2020-12-18 10:41 UTC, sagarb90 commented on sass/grid/mixins/_grid-framework.scss
> -      @each $modifier in (pull, push, offset) {
@premanshup Okay!

2020-12-18 11:09 UTC, sagarb90 commented on sass/grid/mixins/_grid-framework.scss
> -      @each $modifier in (pull, push, offset) {
@premanshup Done in this PR - https://github.com/brainstormforce/astra/pull/2116/files

2020-12-22 15:04 UTC, premanshup requested changes

2020-12-22 15:04 UTC, premanshup commented on Gruntfile.js
> +                        'assets/css/unminified/blog-pagination.css': 'sass/site/blog/blog-pagination.scss',
@sagarb90 For blog-pagination CSS - min-rtl.css is missing, please check.

2020-12-22 15:04 UTC, premanshup commented on assets/css/unminified/blog-pagination-rtl.css
> +  display: inline-block;
@sagarb90 Maybe can we replace blog-pagination CSS with flex CSS? Can you please check if this can be optimized further?

2020-12-24 11:20 UTC, sagarb90 reviewed
I have check their is no need for change.

2020-12-24 11:20 UTC, sagarb90 commented on Gruntfile.js
> +                        'assets/css/unminified/blog-pagination.css': 'sass/site/blog/blog-pagination.scss',
@premanshup This is done. added blog-pagination.min-rtl.css.

2020-12-24 11:21 UTC, sagarb90 commented on inc/core/class-astra-enqueue-scripts.php
> +			}
@premanshup Yes this is resolved now.

2020-12-28 12:59 UTC, vrundakansara approved these changes

2020-12-28 13:12 UTC, premanshup approved these changes

2020-12-28 13:14 UTC, merged