feat: fronend.js optimization
brainstormforce/astra pull request #2150
Opened 2020-12-18 10:07 UTC by sagarb90

### Description
- Optimization of fronend.js

### Types of changes
Improvements.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests

2020-12-22 15:10 UTC, premanshup requested changes

2020-12-22 15:10 UTC, premanshup commented on assets/js/unminified/frontend.js
> +	    bodyElement = body;
@sagarb90 If body is a global variable then we can remove  `bodyElement = body;` this assignment and use `body` directly.

2020-12-22 15:10 UTC, premanshup commented on assets/js/unminified/frontend.js
> +		var body = body;
@sagarb90 If body is a global variable then we can remove  `var body = body;` this assignment and use `body` directly.

2020-12-23 06:09 UTC, sagarb90 commented on assets/js/unminified/frontend.js
> +		var body = body;
@premanshup Done mentioned changes.

2020-12-23 06:10 UTC, sagarb90 commented on assets/js/unminified/frontend.js
> +	    bodyElement = body;
@premanshup Done mentioned changes.

2020-12-24 11:21 UTC, premanshup approved these changes

2020-12-24 11:22 UTC, shubhw12 approved these changes

2020-12-29 06:26 UTC, vrundakansara approved these changes

2020-12-29 06:26 UTC, merged