imprv: revamp main header section div structure
brainstormforce/astra pull request #2152
Opened 2020-12-21 10:18 UTC by sagarb90

### Description
- Revamp main Header div srtructure. 
- Reduce no. of divs.
 
### Types of changes
- Improvements.
 
### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests

2020-12-22 15:36 UTC, premanshup requested changes

2020-12-22 15:36 UTC, premanshup commented on template-parts/header/builder/header-row.php
> +									do_action( 'astra_render_header_column', $row, 'left_center' );
@sagarb90 Please verify this in theme and addon if we are changing the action it should be changed from everywhere else too.

2020-12-23 05:29 UTC, sagarb90 commented on template-parts/header/builder/header-row.php
> +									do_action( 'astra_render_header_column', $row, 'left_center' );
@premanshup We have not changing any action here we have just work on Div structure I think  due to line number change it showing that changes I have also compare this with main branch file so none of action is missing or changed.

2020-12-30 05:32 UTC, premanshup approved these changes

2020-12-30 05:37 UTC, vrundakansara approved these changes

2020-12-30 05:37 UTC, imnavanath approved these changes

2020-12-30 05:38 UTC, merged