Improvements: Removed site container div and modify  it's depended CSS.
brainstormforce/astra pull request #2157
Opened 2020-12-22 09:05 UTC by sagarb90

### Description
- Removed site container div and modify  it's depended CSS.
- Removed from Desktop header, mobile header and footer layout.

### Screenshots

### Types of changes
- Improvements.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards

2020-12-22 15:39 UTC, premanshup requested changes

2020-12-22 15:39 UTC, premanshup commented on template-parts/header/builder/mobile-header-row.php
> -				<div class="site-container">
@sagarb90 Please check if there is any CSS related to in Addon as well? We should remove it as well.

2020-12-23 04:55 UTC, sagarb90 commented on template-parts/header/builder/mobile-header-row.php
> -				<div class="site-container">
@premanshup I have checked their is no any CSS or class related to  `site-container` in add-on.

2020-12-29 15:49 UTC, vrundakansara approved these changes

2020-12-29 15:51 UTC, merged