fix: Overflowing content not wrapping as per grid layout on responsive device
brainstormforce/astra pull request #2175
Opened 2020-12-30 06:28 UTC by imnavanath

### Description
- Grid builder layout overflowing content

### Screenshots
- https://a.cl.ly/YEuQ4zAB

### Types of changes
- CSS updated for wrap

### How has this been tested?
- With multiple (header line breaking) changes

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've included developer documentation
- [x] I've added proper labels to this pull request

2021-01-12 12:16 UTC, vrundakansara approved these changes

2021-01-18 14:49 UTC, premanshup requested changes

2021-01-18 14:49 UTC, premanshup commented on .github/workflows/label_approved_pr.yml
> +        REMOVE_LABEL: "needs-review"
@imnavanath This is already merged in the next-release. Please pull next-release to `hf-milestones` once.

2021-01-19 03:33 UTC, imnavanath commented on .github/workflows/label_approved_pr.yml
> +        REMOVE_LABEL: "needs-review"
Updated @premanshup 👍 You can review now.

2021-01-19 19:46 UTC, premanshup approved these changes

2021-01-21 09:14 UTC, merged