feat: Social Icons element multiple improvements.
brainstormforce/astra pull request #2206
Opened 2021-01-06 12:28 UTC by RajkiranBagal

### Description
 - Trello task - https://trello.com/c/hPl8NAcl/278-social-icons
 
### Types of changes
New feature (non-breaking change which adds functionality)

### How has this been tested?
 - Multiple new improvements to test as per task provided.
 
### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-01-15 05:26 UTC, rohitp-bsf requested changes

2021-01-15 05:26 UTC, rohitp-bsf commented on inc/assets/js/ast-render-svg.js
> +export default renderSVG
Can we memorize this with React.memo() as we are just passing a param and fetching it?

2021-01-15 05:26 UTC, rohitp-bsf commented on inc/customizer/extend-custom-controls/src/social-icons/item-component.js
> +import astIcons from "../../../../../assets/svg/ast-social-icons"
Is it possible to use an absolute path?

2021-01-15 05:26 UTC, rohitp-bsf commented on inc/customizer/extend-custom-controls/src/social-icons/social-component.js
> +			let icon = ( 'email_2' === itemControl ) ? 'email' : ( 'phone_2' === itemControl ) ? 'phone' : itemControl;
can we just replace with regex  _ with digit with empty? `_/[0-9]+/g`

2021-01-15 10:46 UTC, RajkiranBagal commented on inc/customizer/extend-custom-controls/src/social-icons/social-component.js
> +			let icon = ( 'email_2' === itemControl ) ? 'email' : ( 'phone_2' === itemControl ) ? 'phone' : itemControl;
Done

2021-01-15 11:03 UTC, RajkiranBagal commented on inc/assets/js/ast-render-svg.js
> +export default renderSVG
Done

2021-01-21 15:03 UTC, rohitp-bsf approved these changes

2021-01-22 07:13 UTC, vrundakansara approved these changes

2021-01-22 07:13 UTC, merged