improvements: mobile and desktop Header revamp
brainstormforce/astra pull request #2221
Opened 2021-01-11 07:52 UTC by sagarb90

### Description
mobile and desktop Header revamp

### Types of changes
improvements

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards

2021-01-21 07:20 UTC, imnavanath approved these changes

2021-01-25 07:16 UTC, premanshup requested changes

2021-01-25 07:16 UTC, premanshup commented on inc/markup-extras.php
> +					%2$s',
@sagarb90 Please verify once this with the old header as well.

2021-01-25 07:16 UTC, premanshup commented on sass/site/header/_header-layouts.scss
> +		.site-logo-img + .site-title{
@sagarb90 Verify with old Header and Addon options.

2021-01-25 07:16 UTC, premanshup commented on inc/builder/type/header/above-header/assets/js/customizer-preview.js
> +	astra_builder_visibility_css( 'section-above-header-builder', '.ast-above-header-bar', 'grid' );
@sagarb90 Why are we changing the default value from Block to Grid? and does this require backward compatibility?

2021-01-27 08:45 UTC, sagarb90 commented on inc/builder/markup/class-astra-builder-footer.php
> +				echo '<div class="ast-footer-copyright ast-footer-html-inner">';
@premanshup Removed class ast-footer-html-inner from both theme and from add-on

2021-01-27 08:54 UTC, sagarb90 commented on inc/builder/type/header/above-header/assets/js/customizer-preview.js
> +	astra_builder_visibility_css( 'section-above-header-builder', '.ast-above-header-bar', 'grid' );
@premanshup Yes Reverted this change as we have already handle this CSS

2021-01-27 09:10 UTC, sagarb90 commented on sass/site/header/_header-layouts.scss
> +		.site-logo-img + .site-title{
@premanshup Yes verified and working fine.

2021-01-27 09:12 UTC, sagarb90 commented on inc/markup-extras.php
> +					%2$s',
@premanshup Yes verified and working fine as it replace the div with %1$s & %2$s

2021-01-28 01:42 UTC, premanshup approved these changes

2021-02-05 10:57 UTC, merged