SonarLint Issue Fixes
brainstormforce/astra pull request #2222
Opened 2021-01-11 14:29 UTC by abhishek-bsf

### Description

Fixed issues found in SonarLint - [task](https://trello.com/c/Enk9f395/946-blackfire-and-sonarlint-fixes)

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

Checked whether customizer is working properly after changes.

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests

2021-01-12 14:35 UTC, premanshup requested changes

2021-01-12 14:35 UTC, premanshup commented on inc/builder/type/footer/above-footer/class-astra-above-footer-component-loader.php
>  		wp_enqueue_script( 'astra-footer-above-customizer-preview-js', ASTRA_BUILDER_FOOTER_ABOVE_FOOTER_URI . '/assets/js/customizer-preview.js', array( 'customize-preview', 'astra-customizer-preview-js'
@abhishek-bsf  Instead of removing this, create min file and use it there. Please check this code:

```/* Directory and Extension */
		$dir_name    = ( SCRIPT_DEBUG ) ? 'unminified' : 'minified';
		$file_prefix = ( SCRIPT_DEBUG ) ? '' : '.min';
		wp_enqueue_script( 'astra-heading-colors-customizer-preview-js', ASTRA_THEME_HEADING_COLORS_URI . 'assets/js/' . $dir_name . '/customizer-preview' . $file_prefix . '.js', array( 'customize-preview', 'astra-customizer-preview-js' ), ASTRA_THEME_VERSION, true );```

2021-01-12 14:35 UTC, premanshup commented on inc/builder/type/footer/above-footer/dynamic-css/dynamic.css.php
> +function astra_fb_above_footer_dynamic_css( $dynamic_css ) {
@abhishek-bsf Let's not remove this, this can be used in the future. If we pass anything from the filter `astra_dynamic_theme_css`, we will not receive the value from there.

2021-01-12 14:35 UTC, premanshup commented on inc/builder/type/footer/below-footer/class-astra-below-footer-component-loader.php
>  		wp_enqueue_script( 'astra-footer-below-footer-customizer-preview-js', ASTRA_BUILDER_FOOTER_BELOW_FOOTER_URI . '/assets/js/customizer-preview.js', array( 'customize-preview', 'astra-customizer-previ
@abhishek-bsf Same here, please do not remove this and add min & dir compatibility.

2021-01-12 14:35 UTC, premanshup commented on inc/builder/type/footer/below-footer/dynamic-css/dynamic.css.php
> +function astra_fb_below_footer_dynamic_css( $dynamic_css ) {
@abhishek-bsf Please check the previous comment for the same.

2021-01-12 14:35 UTC, premanshup commented on inc/builder/type/footer/button/dynamic-css/dynamic.css.php
> +function astra_fb_button_dynamic_css( $dynamic_css ) {
@abhishek-bsf Same comment.

2021-01-12 14:35 UTC, premanshup commented on inc/builder/type/footer/menu/class-astra-footer-menu-component-loader.php
> -		$file_prefix = ( SCRIPT_DEBUG ) ? '' : '.min';
@abhishek-bsf Please do the same change here and everywhere else as well.

2021-01-12 14:35 UTC, premanshup commented on inc/builder/type/header/mobile-menu/dynamic-css/dynamic.css.php
> -
@abhishek-bsf Please verify if we need to remove this or we need to fix this and include this?

2021-01-12 14:35 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +			if ( ! astra_get_option( 'submenu-below-header', true ) &&
@abhishek-bsf Please get such options verified from your end and @Swapnildhanrale Sir as well.

2021-01-12 14:35 UTC, premanshup commented on inc/class-astra-loop.php
> +						if ( $is_page ) {
@abhishek-bsf If the value of $is_page is string and not true this will still pass and can cause issue. Please make sure the values coming in $is_page is always in boolean and there is no filter to update the values.

2021-01-12 14:35 UTC, premanshup commented on inc/compatibility/class-astra-visual-composer.php
> +			if ( ! astra_enable_page_builder_compatibility() || 'post' == get_post_type() ) {
@abhishek-bsf Please make sure to check if the function is returning false always and not any strings. Please check this in all the condition where we have modified.

2021-01-12 14:35 UTC, premanshup commented on inc/core/class-astra-admin-settings.php
> +				<img class="ast-starter-sites-img" alt="" src="<?php echo esc_url( ASTRA_THEME_URI . 'assets/images/astra-starter-sites.jpg' ); ?>">
@abhishek-bsf alt tag should not be blank, make sure add some descriptive text/string in it.

2021-01-12 14:35 UTC, premanshup commented on inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
> -			$class_obj     = Astra_Builder_Header::get_instance();
@abhishek-bsf This variable is not used but could be used to initialize the class `Astra_Builder_Header::get_instance();`

Make sure to verify that.

2021-01-12 14:35 UTC, premanshup commented on inc/markup-extras.php
> +			if ( ( $above_header_on_mobile && $above_header_merge ) || ( $below_header_on_mobile && $below_header_merge ) ) {
@abhishek-bsf Make sure the value is not other than true otherwise this will pass condition which is not expected.

2021-01-12 14:35 UTC, premanshup commented on template-parts/footer/builder/components.php
> +		<aside class="footer-widget-area widget-area site-footer-focus-item" data-section="sidebar-widgets-footer-widget-1" aria-label="">
@abhishek-bsf Please add something inside `aria-label`,. This should not be blank. Please do the same changes everywhere else as well.

2021-01-19 09:26 UTC, abhishek-bsf commented on inc/builder/type/footer/above-footer/class-astra-above-footer-component-loader.php
>  		wp_enqueue_script( 'astra-footer-above-customizer-preview-js', ASTRA_BUILDER_FOOTER_ABOVE_FOOTER_URI . '/assets/js/customizer-preview.js', array( 'customize-preview', 'astra-customizer-preview-js'
Resolved!

2021-01-19 09:26 UTC, abhishek-bsf commented on inc/builder/type/footer/above-footer/dynamic-css/dynamic.css.php
> +function astra_fb_above_footer_dynamic_css( $dynamic_css ) {
Resolved!

2021-01-19 09:27 UTC, abhishek-bsf commented on inc/builder/type/header/mobile-menu/dynamic-css/dynamic.css.php
> -
Resolved!

2021-01-19 09:27 UTC, abhishek-bsf commented on inc/class-astra-dynamic-css.php
> +			if ( ! astra_get_option( 'submenu-below-header', true ) &&
Resolved!

2021-01-19 09:27 UTC, abhishek-bsf commented on inc/core/class-astra-admin-settings.php
> +				<img class="ast-starter-sites-img" alt="" src="<?php echo esc_url( ASTRA_THEME_URI . 'assets/images/astra-starter-sites.jpg' ); ?>">
Resolved!

2021-01-19 09:27 UTC, abhishek-bsf commented on inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
> -			$class_obj     = Astra_Builder_Header::get_instance();
Resolved!

2021-01-19 09:27 UTC, abhishek-bsf commented on template-parts/footer/builder/components.php
> +		<aside class="footer-widget-area widget-area site-footer-focus-item" data-section="sidebar-widgets-footer-widget-1" aria-label="">
Resolved!

2021-01-20 10:11 UTC, Nikschavan commented on inc/class-astra-dynamic-css.php
> +			if ( ! astra_get_option( 'submenu-below-header', true ) &&
IMO `false ===` is much better than the `!` check, What is the rule that was flagged here?

2021-01-22 13:32 UTC, vrundakansara approved these changes

2021-01-22 13:49 UTC, rohitp-bsf commented
LGTM

2021-01-27 05:54 UTC, abhishek-bsf commented on inc/class-astra-dynamic-css.php
> +			if ( ! astra_get_option( 'submenu-below-header', true ) &&
Resolved!

2021-02-03 11:52 UTC, abhishek-bsf commented on inc/builder/type/footer/below-footer/class-astra-below-footer-component-loader.php
>  		wp_enqueue_script( 'astra-footer-below-footer-customizer-preview-js', ASTRA_BUILDER_FOOTER_BELOW_FOOTER_URI . '/assets/js/customizer-preview.js', array( 'customize-preview', 'astra-customizer-previ
Resolved!

2021-02-03 11:53 UTC, abhishek-bsf commented on inc/builder/type/footer/below-footer/dynamic-css/dynamic.css.php
> +function astra_fb_below_footer_dynamic_css( $dynamic_css ) {
Resolved!

2021-02-03 11:53 UTC, abhishek-bsf commented on inc/builder/type/footer/button/dynamic-css/dynamic.css.php
> +function astra_fb_button_dynamic_css( $dynamic_css ) {
Resolved!

2021-02-03 11:53 UTC, abhishek-bsf commented on inc/builder/type/footer/menu/class-astra-footer-menu-component-loader.php
> -		$file_prefix = ( SCRIPT_DEBUG ) ? '' : '.min';
Resolved!

2021-02-03 11:53 UTC, abhishek-bsf commented on inc/class-astra-loop.php
> +						if ( $is_page ) {
Resolved!

2021-02-03 11:53 UTC, abhishek-bsf commented on inc/compatibility/class-astra-visual-composer.php
> +			if ( ! astra_enable_page_builder_compatibility() || 'post' == get_post_type() ) {
Resolved!

2021-02-03 11:54 UTC, abhishek-bsf commented on inc/markup-extras.php
> +			if ( ( $above_header_on_mobile && $above_header_merge ) || ( $below_header_on_mobile && $below_header_merge ) ) {
Resolved!

2021-02-04 04:49 UTC, premanshup approved these changes

2021-02-04 05:07 UTC, abhishek-bsf commented on inc/class-astra-loop.php
> +						if ( $is_page ) {
I have confirmed this case $is_page a boolean value.

2021-02-04 05:11 UTC, abhishek-bsf commented on inc/compatibility/class-astra-visual-composer.php
> +			if ( ! astra_enable_page_builder_compatibility() || 'post' == get_post_type() ) {
I have checked such cases every where and made these changes only where there are boolean values.

2021-02-04 05:11 UTC, abhishek-bsf commented on inc/markup-extras.php
> +			if ( ( $above_header_on_mobile && $above_header_merge ) || ( $below_header_on_mobile && $below_header_merge ) ) {
https://github.com/brainstormforce/astra/pull/2222#discussion_r569951028

2021-02-04 05:48 UTC, abhishek-bsf commented on inc/builder/type/header/mobile-menu/dynamic-css/dynamic.css.php
> -
Those variables were for future use, added those back.

2021-02-04 06:46 UTC, Nikschavan requested changes
While the code is all good, I am not happy with all the commit messages in this PR - 

![image](https://user-images.githubusercontent.com/2931091/106854842-035cfd80-66e2-11eb-9751-d49abf592588.png)

This PR could also be divided into multiple PRs based on the individual sonarlint errors, Like one PR can only fix the indentation errors, another can fix condition changes etc.

I am going to close this PR for this reason, Please create a new PRs based on above suggestions. do assign me as a reviewer as well.

cc @vrundakansara, @premanshup, @rohitp-bsf

2021-02-04 06:46 UTC, closed without merging