imprv: Mobile header revamp
brainstormforce/astra pull request #2224
Opened 2021-01-12 04:49 UTC by sagarb90

### Description
- Removed `ast-builder-grid-row-container-inner` from mobile header.
-  combined `ast-site-title-wrap` & `site-title` classes

### Types of changes
- Improvements.

### How has this been tested?
Test mobile header components and logo alignments are working correctly or not.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards

2021-01-21 07:21 UTC, imnavanath commented on inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
> +	// We have removed ast-builder-grid-row-container-inner div so to manage display property for mobile and table we have added this CSS.
@sagarb90  `table` should be `tablet` here.

2021-01-21 07:22 UTC, imnavanath commented on inc/builder/type/header/below-header/dynamic-css/dynamic.css.php
> +	// We have removed ast-builder-grid-row-container-inner div so to manage display property for mobile and table we have added this CSS.
Same with the above comment.

2021-01-21 12:15 UTC, sagarb90 commented on inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
> +	// We have removed ast-builder-grid-row-container-inner div so to manage display property for mobile and table we have added this CSS.
@imnavanath This is done!

2021-01-21 12:15 UTC, sagarb90 commented on inc/builder/type/header/below-header/dynamic-css/dynamic.css.php
> +	// We have removed ast-builder-grid-row-container-inner div so to manage display property for mobile and table we have added this CSS.
@imnavanath This is done!

2021-01-21 15:23 UTC, vrundakansara approved these changes

2021-01-25 09:00 UTC, premanshup requested changes

2021-01-25 09:00 UTC, premanshup commented on inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
> +			'display' => 'grid',
@sagarb90 Have we removed the grid CSS where it was earlier added since we are now adding new CSS.

2021-01-25 09:00 UTC, premanshup commented on template-parts/header/builder/mobile-header-row.php
> +		<div class="<?php echo esc_attr( 'ast-' . $row . '-header-bar ast-' . $row . '-header ' ); ?><?php echo 'primary' === $row ? 'main-header-bar ' : ''; ?>site-<?php echo esc_attr( $row ); ?>-header-w
@sagarb90 Can we merge CSS from this class - `ast-builder-grid-row-container-inner` to any other class and remove this class from the div if possible?

2021-01-27 08:19 UTC, sagarb90 reviewed
@premanshup Removed `ast-builder-grid-row-container` class and manage CSS in other classes

2021-01-27 09:59 UTC, sagarb90 commented on inc/builder/controllers/class-astra-builder-ui-controller.php
> +							'class' => 'site-branding ast-site-identity',
@premanshup No as their is more dependency in add-on and theme as well so keep as it is.

2021-01-28 01:43 UTC, premanshup commented on inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
> +	// We have removed ast-builder-grid-row-container-inner div so to manage display property for mobile and table we have added this CSS.
@imnavanath Please verify this once.

2021-01-28 01:43 UTC, premanshup commented on inc/builder/type/header/below-header/dynamic-css/dynamic.css.php
> +	// We have removed ast-builder-grid-row-container-inner div so to manage display property for mobile and table we have added this CSS.
@imnavanath Please verify.

2021-01-28 01:49 UTC, premanshup commented on inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
> +			'display' => 'grid',
@sagarb90 Yes we need this CSS but was this same CSS added before for `.ast-builder-grid-row-container-inner` div? If yes, then have we removed it or is it still there? :slightly_smiling_face:

2021-01-28 01:50 UTC, premanshup commented on inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
> +			'display' => 'grid',
Just make sure that there are no duplicate CSS for grid, the new one and the old one ( if any ).

2021-01-28 05:12 UTC, sagarb90 commented on inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
> +			'display' => 'grid',
@pre Yes this CSS was for `.ast-builder-grid-row-container-inner`  and we have removed this class/div from every where.

2021-01-28 12:15 UTC, premanshup commented on inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
> +			'display' => 'grid',
@sagarb90 Great 👍🏼

2021-01-28 12:55 UTC, imnavanath commented on inc/builder/type/header/below-header/dynamic-css/dynamic.css.php
> +	// We have removed ast-builder-grid-row-container-inner div so to manage display property for mobile and table we have added this CSS.
Really sorry I missed, looks perfect. 👍  Resolving comment.

2021-01-28 12:55 UTC, imnavanath commented on inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
> +	// We have removed ast-builder-grid-row-container-inner div so to manage display property for mobile and table we have added this CSS.
Really sorry I missed, looks perfect. 👍  Resolving comment.

2021-01-28 12:56 UTC, imnavanath approved these changes

2021-01-29 12:26 UTC, premanshup approved these changes

2021-01-29 12:26 UTC, merged