improvements: Dynamic CSS optimization: added conditions for respective css to avoided  unnecessarily loading
brainstormforce/astra pull request #2226
Opened 2021-01-13 14:05 UTC by sagarb90

### Description
- Dynamic CSS optimization changes mentioned in from below sheet .
https://docs.google.com/spreadsheets/d/1xfejGG9kC4qhi9zUaQUp7eWagqIItColBa0XnBolPhQ/edit#gid=147196791

### Types of changes
- Improvements

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards

2021-01-21 07:09 UTC, imnavanath commented on inc/builder/type/header/primary-header/dynamic-css/dynamic.css.php
>  		$genral_global_responsive = array(
@sagarb90 can you please correct spell here - `genral` -> `general`

2021-01-21 07:09 UTC, premanshup requested changes

2021-01-21 07:09 UTC, premanshup commented on inc/builder/type/header/mobile-trigger/dynamic-css/dynamic.css.php
> +		$selector . ' .ast-button-wrap .ast-mobile-menu-trigger-minimal' => array(
@sagarb90 Can this also go inside condition when `minimal` is selected, like we did for `fill`?

2021-01-21 07:09 UTC, premanshup commented on inc/builder/type/header/mobile-trigger/dynamic-css/dynamic.css.php
> +	if ( 'outline' == $style ) {
@sagarb90 Instead of using `if` multiple times, we can use switch case I guess which will be more optimized. Please check.

2021-01-21 07:09 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +				'.entry-meta a:hover, .entry-meta a:hover *, .entry-meta a:focus, .entry-meta a:focus *, .ast-pagination a:hover, .ast-pagination a:focus, .ast-pagination > span:hover:not(.dots), .ast-pagination
@sagarb90 Why are we adding pagination related CSS here and it is not under any condition.

2021-01-21 13:47 UTC, sagarb90 commented on inc/builder/type/header/mobile-trigger/dynamic-css/dynamic.css.php
> +		$selector . ' .ast-button-wrap .ast-mobile-menu-trigger-minimal' => array(
@premanshup Yes this is Done.

2021-01-21 13:47 UTC, sagarb90 commented on inc/builder/type/header/mobile-trigger/dynamic-css/dynamic.css.php
> +	if ( 'outline' == $style ) {
@premanshup Yes added into switch case statement

2021-01-28 01:39 UTC, premanshup commented on inc/builder/type/header/mobile-trigger/dynamic-css/dynamic.css.php
> +		$selector . ' .ast-button-wrap .ast-mobile-menu-trigger-minimal' => array(
@sagarb90 Thank you, looking good 👍🏼

2021-01-28 01:40 UTC, premanshup commented on inc/builder/type/header/primary-header/dynamic-css/dynamic.css.php
>  		$genral_global_responsive = array(
@sagarb90 Please check this as well.

2021-01-28 01:41 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +				'.entry-meta a:hover, .entry-meta a:hover *, .entry-meta a:focus, .entry-meta a:focus *, .ast-pagination a:hover, .ast-pagination a:focus, .ast-pagination > span:hover:not(.dots), .ast-pagination
@sagarb90 Any update on this?

2021-01-28 04:05 UTC, sagarb90 commented on inc/builder/type/header/primary-header/dynamic-css/dynamic.css.php
>  		$genral_global_responsive = array(
@premanshup Yes this change is already Done.

2021-01-28 04:15 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> +				'.entry-meta a:hover, .entry-meta a:hover *, .entry-meta a:focus, .entry-meta a:focus *, .ast-pagination a:hover, .ast-pagination a:focus, .ast-pagination > span:hover:not(.dots), .ast-pagination
@premanshup Yes actually this pagination related css  `.ast-pagination a:hover, .ast-pagination a:focus, .ast-pagination > span:hover:not(.dots), .ast-pagination > span.current` move to condition in this branch `dynamic-css-optmz-1`

2021-01-28 12:13 UTC, premanshup approved these changes

2021-01-28 12:44 UTC, imnavanath commented on inc/theme-update/astra-update-functions.php
> + * @since 3.1.0
Please use `x.x.x` @since versions, because it automatically updates whenever we run  our update process. Because sometimes changes may delay to deliver so in that case x.x.x versions are safe.

2021-01-28 12:52 UTC, imnavanath commented
Code looks good to me, but let this go by testing phase once. Because I doubt, as we have switch case for cart styles so maybe in customizer preview instant reflections break somewhere.

2021-01-28 12:55 UTC, sagarb90 commented on inc/theme-update/astra-update-functions.php
> + * @since 3.1.0
@imnavanath Yes thanks I have updated @since version to x.x.x

2021-01-28 12:56 UTC, sagarb90 commented on inc/core/builder/class-astra-builder-helper.php
> +		return apply_filters( 'astra_is_updated_dynamic_css_apply', $astra_settings['is-updated-dynamic-css'] );
@imnavanath Yes I have update this function name to `apply_older_dynamic_css` As we are not apply dynamic CSS changes to older/existing user .

2021-02-05 10:59 UTC, premanshup commented
@sagarb90 Please pull the base branch.

2021-02-05 12:30 UTC, Nikschavan requested changes

2021-02-05 12:30 UTC, Nikschavan commented on inc/class-astra-dynamic-css.php
> +			// Remove this condition after 2-3 updates of add-on.
Do add a task for this in the backlog

2021-02-05 12:30 UTC, Nikschavan commented on inc/class-astra-dynamic-css.php
> +				$css_output['.ast-pagination a:hover, .ast-pagination a:focus, .ast-pagination > span:hover:not(.dots), .ast-pagination > span.current'] = array(
`span:hover:not(.dots)`

Instead of this, is it possible for us to add a class to this span and target this with only the classname? that way we can avoid this complex selector and it's parent as well (`.ast-pagination >`)

2021-02-05 12:30 UTC, Nikschavan commented on inc/class-astra-dynamic-css.php
> +				$css_output['.ast-pagination a:hover, .ast-pagination a:focus, .ast-pagination > span:hover:not(.dots), .ast-pagination > span.current'] = array(
`span.current` => `.current` This will reduce the selector weight. target the tag as well if only required.

2021-02-05 12:30 UTC, Nikschavan commented on inc/class-astra-dynamic-css.php
> +
```suggestion
```

2021-02-05 12:30 UTC, Nikschavan commented on inc/class-astra-dynamic-css.php
> +				);
```suggestion
				);

```

2021-02-05 12:30 UTC, Nikschavan commented on inc/class-astra-dynamic-css.php
> +
```suggestion
```

2021-02-05 12:30 UTC, Nikschavan commented on inc/class-astra-dynamic-css.php
> +				if ( 'content-boxed-container' == $container_layout || 'boxed-container' == $container_layout ) {
Can we do strict checks here?

2021-02-05 12:30 UTC, Nikschavan commented on inc/class-astra-dynamic-css.php
> +
```suggestion
```

2021-02-05 12:30 UTC, Nikschavan commented on inc/class-astra-dynamic-css.php
> +					$parse_css               .= astra_parse_css( $static_pagination_tablet, '', astra_get_tablet_breakpoint() );
```suggestion

					$parse_css .= astra_parse_css( $static_pagination_tablet, '', astra_get_tablet_breakpoint() );
```

2021-02-05 12:30 UTC, Nikschavan commented on inc/class-astra-dynamic-css.php
> +				$static_layout_css_min = array_merge( $static_layout_css_min, $autho_table_css );
```suggestion

				$static_layout_css_min = array_merge( $static_layout_css_min, $autho_table_css );
```

2021-02-05 12:30 UTC, Nikschavan commented on inc/class-astra-dynamic-css.php
> +
```suggestion
```

2021-02-05 12:30 UTC, Nikschavan commented on inc/class-astra-dynamic-css.php
> +				/* Parse CSS from array() -> min-width: (tablet-breakpoint + 1)px CSS */
```suggestion

				/* Parse CSS from array() -> min-width: (tablet-breakpoint + 1)px CSS */
```

2021-02-05 12:30 UTC, Nikschavan commented on inc/core/common-functions.php
> +
```suggestion
```

2021-02-05 12:30 UTC, Nikschavan commented on inc/core/common-functions.php
> +
```suggestion
```

2021-02-05 13:26 UTC, sagarb90 commented on inc/builder/type/header/mobile-trigger/dynamic-css/dynamic.css.php
> +			if ( ! $is_customizer ) {
Yes, Done and Updated to `false === $is_customizer`  in all code blocks.

2021-02-05 13:27 UTC, sagarb90 commented on inc/builder/type/header/mobile-trigger/dynamic-css/dynamic.css.php
> +
Done removed blank space.

2021-02-05 13:27 UTC, sagarb90 commented on inc/builder/type/header/mobile-trigger/dynamic-css/dynamic.css.php
> +					// Background.
Yes removed

2021-02-05 13:30 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> +				$static_layout_css_min = array_merge( $static_layout_css_min, $autho_table_css );
Corrected spell  to `author_table_css `

2021-02-05 13:31 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> +				/* Parse CSS from array() -> min-width: (tablet-breakpoint + 1)px CSS */
Removed commented code.

2021-02-05 14:02 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> +				'.entry-meta a:hover, .entry-meta a:hover *, .entry-meta a:focus, .entry-meta a:focus *, .page-links > .page-link, .page-links .page-link:hover, .post-navigation a:hover' => array(
Yes this is required, I think this is required to select only child selector `.page-link` for  parent `.page-links` class. May be someone added this for css priority. I have just move this selector in common CSS property.

2021-02-05 15:04 UTC, premanshup commented
> Code looks good to me, but let this go by testing phase once. Because I have doubt, as we have used switch case for cart styles for dynamic CSS so maybe in customizer preview (instant reflections) may break for different styles.

@sagarb90 Please make sure to provide this test case to the @Swapnildhanrale

2021-02-05 15:05 UTC, Nikschavan commented on inc/class-astra-dynamic-css.php
> +				$static_layout_css_min = array_merge( $static_layout_css_min, $autho_table_css );
I meant there can be a new line here, before the variable declaration.

2021-02-06 06:46 UTC, vrundakansara approved these changes

2021-02-06 07:27 UTC, merged