refactor: Removed unused PHP controls.
brainstormforce/astra pull request #2233
Opened 2021-01-14 13:12 UTC by rohitp-bsf

### Description
- refactor: Removed unused PHP controls.

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-01-14 13:31 UTC, vrundakansara commented on inc/customizer/extend-custom-controls/src/settings-group/control.js
> +			if( jQuery( '#tmpl-' + template_id ).length ) {
Instead of a DOM selection, we can just check if `( undefined === template )`

2021-01-14 16:43 UTC, rohitp-bsf commented on inc/customizer/extend-custom-controls/src/settings-group/control.js
> +			if( jQuery( '#tmpl-' + template_id ).length ) {
@vrundakansara template will never be undefined here as it is a function passed as a reference which just accepts the control config and internally checks the template as we checked here.

2021-01-15 04:26 UTC, RajkiranBagal approved these changes

2021-01-18 07:25 UTC, vrundakansara approved these changes

2021-01-18 14:43 UTC, premanshup requested changes

2021-01-18 14:43 UTC, premanshup commented on inc/addons/heading-colors/customizer/class-astra-heading-colors-configs.php
> -					'transport'         => 'postMessage',
@rohitp-bsf I think we should keep 

`'transport'         => 'postMessage',`

Or else live preview maynot work.

2021-01-18 14:43 UTC, premanshup commented on inc/customizer/configurations/typography/class-astra-body-typo-configs.php
> -					'transport'         => 'postMessage',
@rohitp-bsf Why are we removing, section and transport from here? Please verify.

2021-01-18 14:43 UTC, premanshup commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-configs.php
> +					'sanitize_callback' => array( 'Astra_Customizer_Sanitizes', 'sanitize_responsive_spacing' ),
@rohitp-bsf Should we remove sanitization from `prepare_javascript_control_configs` function and an other functions if we are adding it from the control array itself. Can you please verify this once?

2021-01-21 04:59 UTC, rohitp-bsf commented on inc/addons/heading-colors/customizer/class-astra-heading-colors-configs.php
> -					'transport'         => 'postMessage',
@premanshup I haven't removed that property, it is just moved. Please verify here: https://github.com/brainstormforce/astra/blob/8bdb089ddd0723a32ad9bd7fb3bdc385a5212fc1/inc/addons/heading-colors/customizer/class-astra-heading-colors-configs.php#L270

2021-01-21 07:37 UTC, rohitp-bsf commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-configs.php
> +					'sanitize_callback' => array( 'Astra_Customizer_Sanitizes', 'sanitize_responsive_spacing' ),
Done!

2021-01-21 07:37 UTC, rohitp-bsf commented on inc/customizer/configurations/typography/class-astra-body-typo-configs.php
> -					'transport'         => 'postMessage',
Removed duplicate property!

2021-01-25 10:36 UTC, premanshup approved these changes

2021-01-25 10:37 UTC, merged