feat: Toggle on Desktop.
brainstormforce/astra pull request #2235
Opened 2021-01-15 08:37 UTC by RajkiranBagal

### Description
 - Trello task - https://trello.com/c/kcWKZN7H/871-toggle-for-desktop

### Types of changes
New feature (non-breaking change which adds functionality)

### How has this been tested?
 - Check Backward compatibility.
 - Check by adding/removing Toggle the Button element in Desktop Header.

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-02-02 11:23 UTC, RajkiranBagal commented on inc/builder/type/header/off-canvas/assets/js/customizer-preview.js
> +	var tablet_break_point    = astraBuilderPreview.tablet_break_point || 768,
Done

2021-02-02 11:23 UTC, RajkiranBagal commented on sass/site/builder/_header.scss
> +	// .ast-mobile-header-content {
Done

2021-03-02 10:39 UTC, premanshup requested changes

2021-03-02 10:39 UTC, premanshup commented on assets/css/unminified/frontend.css
> +.astra-hfb-header .menu-toggle.toggled .ast-close-svg {
@RajkiranBagal For HTML attributes, please use `ast-` as prefix instead of `astra-`.

Also, can we reduce the CSS weightage here and from everywhere else in the frontend CSS?

2021-03-02 10:39 UTC, premanshup commented on assets/css/unminified/frontend.css
> +}
@RajkiranBagal I think we should move all this CSS dynamic CSS and load this only when Toggle on Desktop is enabled on the website. All this CSS will reduce the performance if the Toggle on Desktop element is not used on the users' website. Please check.

2021-03-02 10:39 UTC, premanshup commented on assets/js/unminified/frontend.js
> +
@RajkiranBagal Same for JS, can weload this only conditionally, this will increase the size of JS file.

2021-03-02 10:39 UTC, premanshup commented on inc/builder/markup/class-astra-builder-header.php
> +
```suggestion
				
```

2021-03-02 10:39 UTC, premanshup commented on inc/builder/markup/class-astra-builder-header.php
> +
```suggestion
				
```

2021-03-02 10:39 UTC, premanshup commented on inc/builder/markup/class-astra-builder-header.php
> +		 */
@RajkiranBagal Since doc comment missing.

2021-03-02 10:39 UTC, premanshup commented on inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
> +	$padding                     = astra_get_option( 'popup-padding' );
@RajkiranBagal Instead of `popup-padding` / `popup-width` can we provide some more detailing name like `desktop-canvas-padding` or something? I personally feel popup is very generic and can be a little confusing.

2021-03-02 10:39 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/builder-layout/builder-component.js
> +
```suggestion

```

2021-03-02 10:39 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/builder-layout/builder-component.js
> +
```suggestion

```

2021-03-02 10:39 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/builder-layout/builder-component.js
> +
```suggestion

```

2021-03-02 10:39 UTC, premanshup commented on sass/site/builder/_header.scss
> +.ast-desktop-header-content .ast-builder-layout-element:not(.ast-builder-menu):not(.ast-header-divider-element) {
@RajkiranBagal Check if we reduce the CSS class weightage.

2021-03-03 08:35 UTC, RajkiranBagal commented on assets/css/unminified/frontend.css
> +.astra-hfb-header .menu-toggle.toggled .ast-close-svg {
@premanshup This class is added in the body from the starting phase & used in almost 75 places in the theme. Shall I replace this in this same PR or shall we have a different task for it?

2021-03-03 10:13 UTC, RajkiranBagal commented on assets/js/unminified/frontend.js
> +
It is a change in the current Mobile off-canvas functionality, I do not think it will be ideal to create the same file for Desktop, as most of the code in this file will be needed there. Please let me know your thoughts.

2021-03-03 10:16 UTC, RajkiranBagal commented on inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
> +	$padding                     = astra_get_option( 'popup-padding' );
Naming it as `off-canvas-padding` & `off-canvas-width` as it is not just for desktop.

2021-03-03 10:20 UTC, RajkiranBagal commented on sass/site/builder/_header.scss
> +.ast-desktop-header-content .ast-builder-layout-element:not(.ast-builder-menu):not(.ast-header-divider-element) {
It's the lesser we can keep achieving the result.

2021-03-03 10:20 UTC, RajkiranBagal commented on inc/customizer/extend-custom-controls/src/builder-layout/builder-component.js
> +
Done.

2021-03-03 10:20 UTC, RajkiranBagal commented on inc/customizer/extend-custom-controls/src/builder-layout/builder-component.js
> +
Done.

2021-03-03 10:20 UTC, RajkiranBagal commented on inc/customizer/extend-custom-controls/src/builder-layout/builder-component.js
> +
Done.

2021-03-03 10:20 UTC, RajkiranBagal commented on inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
> +	$padding                     = astra_get_option( 'popup-padding' );
Done.

2021-03-03 10:20 UTC, RajkiranBagal commented on inc/builder/markup/class-astra-builder-header.php
> +		 */
Added.

2021-03-03 10:21 UTC, RajkiranBagal commented on inc/builder/markup/class-astra-builder-header.php
> +
Done.

2021-03-03 10:21 UTC, RajkiranBagal commented on inc/builder/markup/class-astra-builder-header.php
> +
Done.

2021-03-03 10:21 UTC, RajkiranBagal commented on assets/css/unminified/frontend.css
> +}
Done.

2021-03-03 13:06 UTC, premanshup commented on assets/css/unminified/frontend.css
> +.astra-hfb-header .menu-toggle.toggled .ast-close-svg {
@RajkiranBagal By starting phase you mean since v3.0.0? If yes then I think we can replace it with search-replace. Do check this in Addon as well whether we have used it there as well or not? Let me know if there is any need for additional testing for this. If not, then you can push the changes in this branch only.

2021-03-03 13:09 UTC, premanshup commented on assets/js/unminified/frontend.js
> +
@RajkiranBagal Okay, let's keep this as it is.

2021-03-03 13:18 UTC, RajkiranBagal commented on assets/css/unminified/frontend.css
> +.astra-hfb-header .menu-toggle.toggled .ast-close-svg {
Okay! No extra testing needed for that. I Pushed the Theme folder changes in the same Branch & created a new PR for Addon changes, Please review & merge this too. - https://git.brainstormforce.com/bsf-store-products/astra/astra-addon/-/merge_requests/2138

2021-03-03 14:10 UTC, premanshup commented on assets/css/unminified/frontend.css
> +.astra-hfb-header .menu-toggle.toggled .ast-close-svg {
@RajkiranBagal Thank you! Just one more thing. We should add backward compatibility for the CSS class. Please consider the below two cases.

1. If only Theme is updated and addon is not update to `v3.2.0`

If the Addon version is less than `v3.2.0` CSS class in the body should be both `astra-` and `ast-`. This will make sure that if the addon is not updated both the CSS will still apply.

2. If only Addon is updated and theme is not updated to `v3.2.0`

In this case we will load old CSS `astra-` and if the theme version is updated then we will load the `ast-`. 

It's okay if you want to create a new task for backward compatibility for now we can merge this. Do add task link here if you plan on doing so.

2021-03-04 04:02 UTC, Nikschavan commented
![](https://github.trello.services/images/mini-trello-icon.png) [Toggle for Desktop](https://trello.com/c/kcWKZN7H/258-toggle-for-desktop)

2021-03-04 09:41 UTC, RajkiranBagal commented on assets/css/unminified/frontend.css
> +.astra-hfb-header .menu-toggle.toggled .ast-close-svg {
@premanshup Handled Case 1 in current PR. Handling Case 2 & also changing the classes in Addon i this task - https://trello.com/c/W0BiehsW/610-backward-compatibility-for-body-class-changed-from-astra-hfb-header-to-ast-hfb-header.

Please do not merge the PR I mentioned in the above comment. I am adding the Backward compatibility in the same PR.

2021-03-04 09:42 UTC, premanshup commented on assets/css/unminified/frontend.css
> +.astra-hfb-header .menu-toggle.toggled .ast-close-svg {
@RajkiranBagal Yes sure, Can I merge this PR though?

2021-03-04 09:43 UTC, RajkiranBagal commented on assets/css/unminified/frontend.css
> +.astra-hfb-header .menu-toggle.toggled .ast-close-svg {
Yes, This PR is Done from my end. If your review is done, you can add your review & pass it to QA.

2021-03-04 09:44 UTC, premanshup submitted a review, later dismissed

2021-03-04 10:01 UTC, vrundakansara requested changes

2021-03-04 10:18 UTC, RajkiranBagal commented on inc/class-astra-dynamic-css.php
> +			$header_desktop_items = astra_get_option( 'header-desktop-items' );
Done.

2021-03-05 08:22 UTC, vrundakansara submitted a review, later dismissed

2021-03-18 07:35 UTC, vrundakansara submitted a review, later dismissed

2021-03-18 07:37 UTC, vrundakansara submitted a review, later dismissed

2021-03-18 08:17 UTC, rohitp-bsf requested changes

2021-03-18 08:17 UTC, rohitp-bsf commented on inc/customizer/configurations/builder/header/class-astra-customizer-off-canvas-configs.php
> +					'name'     => ASTRA_THEME_SETTINGS . '[off-canvas-inner-element-spacing-divider]',
Do not use `ast-divider` control, try using divider attr like,

`'divider'  => array( 'ast_class' => 'ast-bottom-divider ast-top-divider' ),`

2021-03-18 08:17 UTC, rohitp-bsf commented on inc/customizer/configurations/builder/header/class-astra-customizer-off-canvas-configs.php
> +					'name'     => ASTRA_THEME_SETTINGS . '[off-canvas-canvas-close-color-divider]',
Do not use ast-divider control, try using divider attr like,

`'divider' => array( 'ast_class' => 'ast-bottom-divider ast-top-divider' ),`

2021-03-18 08:17 UTC, rohitp-bsf commented on inc/customizer/configurations/builder/header/class-astra-customizer-off-canvas-configs.php
> +					'name'     => ASTRA_THEME_SETTINGS . '[header-builder-menu-toggle-target-divider]',
Do not use ast-divider control, try using divider attr like,

`'divider' => array( 'ast_class' => 'ast-bottom-divider ast-top-divider' ),`

2021-03-18 08:17 UTC, rohitp-bsf commented on inc/customizer/configurations/builder/header/class-astra-customizer-off-canvas-configs.php
> +					'name'     => ASTRA_THEME_SETTINGS . '[off-canvas-slide-divider]',
Do not use ast-divider control, try using divider attr like,

`'divider' => array( 'ast_class' => 'ast-bottom-divider ast-top-divider' ),`

2021-03-18 08:17 UTC, rohitp-bsf commented on inc/customizer/configurations/builder/header/class-astra-customizer-mobile-trigger-configs.php
> +				'name'     => ASTRA_THEME_SETTINGS . '[mobile-header-menu-label-divider]',
Do not use ast-divider control, try using divider attr like,

`'divider' => array( 'ast_class' => 'ast-bottom-divider ast-top-divider' ),`

2021-03-18 08:17 UTC, rohitp-bsf commented on inc/customizer/configurations/builder/header/class-astra-customizer-mobile-trigger-configs.php
> +				'name'     => ASTRA_THEME_SETTINGS . '[mobile-header-toggle-icon-size-divider]',
Do not use ast-divider control, try using divider attr like,

`'divider' => array( 'ast_class' => 'ast-bottom-divider ast-top-divider' ),`

2021-03-18 08:35 UTC, RajkiranBagal commented on inc/customizer/configurations/builder/header/class-astra-customizer-off-canvas-configs.php
> +					'name'     => ASTRA_THEME_SETTINGS . '[off-canvas-inner-element-spacing-divider]',
Done

2021-03-18 08:35 UTC, RajkiranBagal commented on inc/customizer/configurations/builder/header/class-astra-customizer-off-canvas-configs.php
> +					'name'     => ASTRA_THEME_SETTINGS . '[off-canvas-canvas-close-color-divider]',
Done

2021-03-18 08:36 UTC, RajkiranBagal commented on inc/customizer/configurations/builder/header/class-astra-customizer-off-canvas-configs.php
> +					'name'     => ASTRA_THEME_SETTINGS . '[header-builder-menu-toggle-target-divider]',
Done

2021-03-18 08:36 UTC, RajkiranBagal commented on inc/customizer/configurations/builder/header/class-astra-customizer-off-canvas-configs.php
> +					'name'     => ASTRA_THEME_SETTINGS . '[off-canvas-slide-divider]',
Done

2021-03-18 08:36 UTC, RajkiranBagal commented on inc/customizer/configurations/builder/header/class-astra-customizer-mobile-trigger-configs.php
> +				'name'     => ASTRA_THEME_SETTINGS . '[mobile-header-toggle-icon-size-divider]',
Done

2021-03-18 08:36 UTC, RajkiranBagal commented on inc/customizer/configurations/builder/header/class-astra-customizer-mobile-trigger-configs.php
> +				'name'     => ASTRA_THEME_SETTINGS . '[mobile-header-menu-label-divider]',
Done

2021-03-18 09:06 UTC, rohitp-bsf approved these changes

2021-03-18 09:43 UTC, vrundakansara approved these changes

2021-03-18 09:43 UTC, merged