Fix: Megamenu default border not working
brainstormforce/astra pull request #2240
Opened 2021-01-18 05:26 UTC by sushmak02

### Description

Problem Statement - Default border set from here - https://share.getcloudapp.com/GGu2GDr7 is not working if the mega menu is set as a submenu. This issue occurs only in the customizer.

### Screenshots
https://share.getcloudapp.com/GGu2GDr7

### Types of changes

Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-02-05 10:17 UTC, Nikschavan approved these changes

2021-02-08 07:17 UTC, premanshup requested changes

2021-02-08 07:17 UTC, premanshup commented on inc/builder/type/header/menu/dynamic-css/dynamic.css.php
> +			$selector . ' .sub-menu, ' . $selector . ' .inline-on-mobile .sub-menu, ' . $selector . ' .main-header-menu.submenu-with-border .astra-megamenu, ' . $selector . ' .main-header-menu.submenu-with-bo
@sushmak02 Why are we adding Addon related CSS in the theme? Megamenu is loaded from the addon, why this CSS is added here? Can you explain?

2021-03-12 10:33 UTC, rohitp-bsf approved these changes

2021-05-17 02:38 UTC, closed without merging