fix: Submenu Divider option conflict with menu layout & breaks design on responsive devices
brainstormforce/astra pull request #2243
Opened 2021-01-19 08:44 UTC by imnavanath

### Description
- On the mobile view when enabled item divider, we can't adjust the thickness of the divider the same with the new divider widget
- When we used the chrome developer inspection tool it looks like it 5px border from all around,

### Screenshots
- https://a.cl.ly/o0uqnRKG
- Screencast - https://a.cl.ly/o0uq2OA0

### Types of changes
- Corrected CSS as per requirement
- Removed extra unwanted CSS
- Updated dynamic CSS, customizer preview JS conditions

### How has this been tested?
- Enable Item Divider option for primary menu
- Then we face this issue
- Screencast - https://a.cl.ly/o0uq2OA0

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-01-19 11:44 UTC, vrundakansara approved these changes

2021-01-19 19:59 UTC, premanshup requested changes

2021-01-19 19:59 UTC, premanshup commented on inc/builder/type/header/menu/dynamic-css/dynamic.css.php
> +				'border-bottom-width' => ( $sub_menu_divider_toggle ) ? '1px' : '0px',
@imnavanath I think we have already added static CSS for this? `border: 0`, do we still need it?

2021-01-20 03:20 UTC, imnavanath commented on inc/builder/type/header/menu/dynamic-css/dynamic.css.php
> +				'border-bottom-width' => ( $sub_menu_divider_toggle ) ? '1px' : '0px',
1px border is required here, buy just realized this CSS is already in condition `if ( true === $sub_menu_divider_toggle ) {` so no need to check `'border-bottom-width' => ( $sub_menu_divider_toggle ) ? '1px'` this condition again. I'll directly add 1px here (like as set before on this line).

2021-01-20 03:30 UTC, imnavanath commented on inc/builder/type/header/menu/dynamic-css/dynamic.css.php
> +				'border-bottom-width' => ( $sub_menu_divider_toggle ) ? '1px' : '0px',
Removed extra condition 👍  please review now.

2021-01-20 06:22 UTC, premanshup approved these changes

2021-01-27 13:40 UTC, vrundakansara approved these changes

2021-01-28 04:07 UTC, vrundakansara commented on changelog.txt
> +<<<<<<< HEAD
Please resolve these conflicts @imnavanath

2021-01-28 04:23 UTC, imnavanath commented on changelog.txt
> +<<<<<<< HEAD
Done, resolved

2021-01-28 07:13 UTC, premanshup requested changes

2021-01-28 07:13 UTC, premanshup commented on inc/customizer/configurations/builder/header/class-astra-mobile-menu-component-configs.php
> +					'default'           => '',
@imnavanath Please add defaults and use `astra_get_option` here instead of the blank string.

2021-01-28 08:34 UTC, premanshup approved these changes

2021-01-28 08:37 UTC, merged