improvements: Dynamic CSS optimmization
brainstormforce/astra pull request #2249
Opened 2021-01-20 12:29 UTC by sagarb90

### Description
- Added conditions to optimize and avoid loading unwanted CSS code. 
- Tasks - https://trello.com/c/Ek4bft5N/966-dynamic-inline-css-optimization-comparison-with-gp-kandence-and-blocksy

### Types of changes
- Improvements.

### How has this been tested?
Check in above task if the CSS is loading related to that element or not.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation

2021-01-21 15:20 UTC, vrundakansara commented on inc/class-astra-dynamic-css.php
> -			global $wp_query;
Any reason why have we removed this? Where have we again defined this?

2021-01-22 04:37 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> -			global $wp_query;
@vrundakansara Yes this variable is already defined at the starting of the function so I have removed from here.

2021-01-25 09:55 UTC, premanshup requested changes

2021-01-25 09:55 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> -				'header .site-logo-img .custom-logo-link img' => array(
@sagarb90 Please verify this with the old header and footer as well.

2021-01-25 09:55 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> -				'.entry-meta a:hover, .entry-meta a:hover *, .entry-meta a:focus, .entry-meta a:focus *, .ast-pagination a:hover, .ast-pagination a:focus, .ast-pagination > span:hover:not(.dots), .ast-pagination
@sagarb90 Why have we not moved this CSS under the Pagination condition? - 
`page-links > .page-link, .page-links .page-link:hover, .post-navigation a:hover`

2021-01-25 09:55 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +					if ( 'content-boxed-container' == $container_layout || 'boxed-container' == $container_layout ) {
@sagarb90 Can we convert all the `if/else` conditions to `switch` cases? This will be more optimized.

2021-01-25 09:55 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +				if ( $wp_query->max_num_pages > 1 && apply_filters( 'astra_pagination_enabled', true ) ) {
@sagarb90 Instead of adding multiple `apply_filters` for a common filter, let's create a common function and use it everywhere. This will make sure in the future we change the filter name or deprecate it, it is removed or deprecated from everywhere.

2021-01-25 09:55 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> -				'.single .nav-links .nav-previous, .single .nav-links .nav-next, .single .ast-author-details .author-title, .ast-comment-meta' => array(
@sagarb90 We need to add backward compatibility for this. If the user only updates the theme and not addon then this will be removed. Need check this condition as well. 
`.single .ast-author-details .author-title`

2021-01-25 09:55 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +			if ( is_singular() && comments_open() ) {
@sagarb90 Can we create a common funtion for checking `comments_open` and `is_singular`?  Replace this common function with the conditions?

2021-01-27 05:01 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> -				'header .site-logo-img .custom-logo-link img' => array(
@premanshup Verified, It's working fine.

2021-01-27 05:10 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> -				'.entry-meta a:hover, .entry-meta a:hover *, .entry-meta a:focus, .entry-meta a:focus *, .ast-pagination a:hover, .ast-pagination a:focus, .ast-pagination > span:hover:not(.dots), .ast-pagination
@premanshup As these CSS is not part of ast-pagination/post pagination  these are related to Prev and Next post link and we don't have condition to check these links so I have keep as it is.

2021-01-27 06:03 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> +			if ( is_singular() && comments_open() ) {
@premanshup Yes this is done create common function.

2021-01-27 06:04 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> +					if ( 'content-boxed-container' == $container_layout || 'boxed-container' == $container_layout ) {
@premanshup Yes Added switch cases.

2021-01-27 09:20 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> +				if ( $wp_query->max_num_pages > 1 && apply_filters( 'astra_pagination_enabled', true ) ) {
@premanshup Yes added common function for the same

2021-01-27 10:02 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> -				'.single .nav-links .nav-previous, .single .nav-links .nav-next, .single .ast-author-details .author-title, .ast-comment-meta' => array(
@premanshup As per discussion for now we will add the add-on version check condition and after 2-3 updated we will remove this condition.

2021-01-28 01:55 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> -			global $wp_query;
@vrundakansara Please verify this.

2021-01-28 02:01 UTC, premanshup requested changes

2021-01-28 02:01 UTC, premanshup commented on inc/core/common-functions.php
> +	return false;
@sagarb90 Can we directly return this condition? - `return $wp_query->max_num_pages > 1 && apply_filters( 'astra_pagination_enabled', true );`

2021-01-28 04:18 UTC, sagarb90 commented on inc/core/common-functions.php
> +	return false;
@premanshup Yes This is Done, directly return condition

2021-01-28 04:40 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> -			global $wp_query;
@vrundakansara AS we had added this variable `global $wp_query;`  for  pagination condition  and now we have manage that condition in common function so this is completely removed from this file.

2021-01-29 04:13 UTC, vrundakansara commented on inc/class-astra-dynamic-css.php
> -			global $wp_query;
Thanks @sagarb90 and @premanshup 👍🏼

2021-01-29 04:14 UTC, vrundakansara approved these changes

2021-01-29 04:16 UTC, premanshup approved these changes

2021-01-29 12:25 UTC, merged