WIP:Global palette design 2
brainstormforce/astra pull request #2251
Opened 2021-01-21 09:34 UTC by amithire1201

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-01-28 02:31 UTC, premanshup requested changes

2021-01-28 02:31 UTC, premanshup commented on functions.php
> +});
@amithire1201 Just curious why we are adding this?

2021-01-28 02:31 UTC, premanshup commented on inc/customizer/custom-controls/assets/css/unminified/color.css
> +.astra-global-color-sticker.selected:before {
@amithire1201 We use `ast` instead of `astra` in CSS classes, please make sure to replace all the `astra` with `ast` from CSS Classes.

2021-01-28 02:31 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/background/background.js
> +	var globalpalette = props.customizer.control('astra-settings[global-color-palette]').setting.get()
@amithire1201 Please make sure to use camel casing for JS variables.

2021-01-28 02:31 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +import PropTypes, { array } from 'prop-types';
@amithire1201 Please remove `array` if it is not used.

2021-01-28 02:31 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +			</Button> */}
@amithire1201 Please remove the commented code.

2021-01-28 02:31 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		<div className='astra-palette-import-wrap'>
@amithire1201 Use `ast-palette-import-wrap` instead of `astra-palette-import-wrap`

2021-01-28 14:21 UTC, amithire1201 commented on functions.php
> +});
Removed. Added by mistake

2021-01-28 14:21 UTC, amithire1201 commented on inc/customizer/custom-controls/assets/css/unminified/color.css
> +.astra-global-color-sticker.selected:before {
Done.

2021-01-28 14:21 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/background/background.js
> +	var globalpalette = props.customizer.control('astra-settings[global-color-palette]').setting.get()
Done.

2021-01-28 14:21 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +import PropTypes, { array } from 'prop-types';
Done.

2021-01-28 14:21 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		<div className='astra-palette-import-wrap'>
Done.

2021-01-28 14:22 UTC, amithire1201 commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +			</Button> */}
Done.

2021-02-01 05:35 UTC, premanshup approved these changes

2021-02-01 05:39 UTC, premanshup approved these changes

2021-02-01 05:42 UTC, merged