fix: Menu top offset distance hide its submenu when hover in between offset spacing
brainstormforce/astra pull request #2253
Opened 2021-01-21 11:17 UTC by imnavanath

### Description
- Submenu get hides when we assign any top offset
- In this margin (top offset) distance submenu closes immediately, this should not be happen

### Screenshots
- https://a.cl.ly/JruqKRoJ

### Types of changes
- Needed CSS changes which fixed this issue

### How has this been tested?
- Assign some random top offset value
- Basically just create distance between menu-item & it's submenu by using top-offset
- Then this issue comes, whenever we hover in between that space it hides the submenu

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-01-21 12:59 UTC, vrundakansara approved these changes

2021-01-25 07:05 UTC, premanshup requested changes

2021-01-25 07:05 UTC, premanshup commented on sass/site/header/_header-builder-main.scss
> +}
@imnavanath Please check this issue with depth submenus. The position is not appearing properly. - [https://d.pr/i/gCQDEe](https://d.pr/i/gCQDEe)

2021-01-25 11:22 UTC, imnavanath commented on sass/site/header/_header-builder-main.scss
> +}
Valid one @premanshup 👍 

Thanks, updated CSS code with `>` before menu-item. Now it fixed.

2021-01-28 01:31 UTC, premanshup commented on sass/site/header/_header-builder-main.scss
> +}
@imnavanath Thank you, looking good :+1:

2021-01-28 01:31 UTC, premanshup approved these changes

2021-02-16 06:14 UTC, merged