improvement: Revamp CSS and DIV structure of Comment module
brainstormforce/astra pull request #2258
Opened 2021-01-22 07:13 UTC by sagarb90

### Description
- Revamp CSS and DIV structure of Comment module.
- Replace float property with flex.
- Removed Extra divs and manage it's CSS.
- Also removed `clear: both` property CSS as we using flex property so no need this.

### Types of changes
- Improvements

### How has this been tested?
- Test all type of comments design and check if it is breaking layout.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards

2021-01-28 02:34 UTC, premanshup commented
@sagarb90 Just wondering why there are no changes in the Static files? Can you please once verify if any changes in the SCSS files for comment required?

2021-01-28 04:31 UTC, sagarb90 commented
@premanshup As we have move all the static CSS to dynamic CSS  for the comment module so their is no change in SCSS file.

2021-02-01 13:00 UTC, premanshup commented
> @premanshup As we have move all the static CSS to dynamic CSS for the comment module so their is no change in SCSS file.

@sagarb90 Ah right! The PR is looking good 👍🏼

2021-02-16 14:59 UTC, premanshup requested changes

2021-02-16 14:59 UTC, premanshup commented on comments.php
> -		<div class="comments-count-wrapper">
@sagarb90 Need to manage backward compatibility for HTML markup with old structure.

2021-02-19 06:55 UTC, sagarb90 commented on comments.php
> -		<div class="comments-count-wrapper">
Added  backward compatibility using common markup function.

2021-02-24 02:03 UTC, premanshup requested changes
@sagarb90 Instead of overriding the CSS, can we have just one CSS selector? Maybe we can add layout specific CSS Classes and add them conditionally.

For eg. - [https://d.pr/i/FdDAWj](https://d.pr/i/FdDAWj)

2021-02-24 13:49 UTC, sagarb90 reviewed
`Instead of overriding the CSS, can we have just one CSS selector? Maybe we can add layout specific CSS Classes and add them conditionally` - This is Done, Added layout condition for border-bottom CSS.

2021-02-24 15:27 UTC, premanshup approved these changes

2021-03-08 06:59 UTC, merged