wip: Page refresh on click of Colorpicker reset icon
brainstormforce/astra pull request #2280
Opened 2021-01-29 11:49 UTC by abhishek-bsf

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-01-29 14:23 UTC, rohitp-bsf requested changes

2021-01-29 14:23 UTC, rohitp-bsf commented on inc/customizer/extend-custom-controls/src/background/background.js
> +								value['background-image'] = AstraBuilderCustomizerData.defaults[props.control.id]['background-image'];
Add checks for hasOwnProperty to avoid future failure.

2021-02-05 08:30 UTC, abhishek-bsf commented on inc/customizer/extend-custom-controls/src/background/background.js
> +								value['background-image'] = AstraBuilderCustomizerData.defaults[props.control.id]['background-image'];
Resolved

2021-02-05 08:55 UTC, vrundakansara approved these changes

2021-02-05 08:57 UTC, merged