new: Added Responsive Alignment control & set it to all Alignment options in customizer settings.
brainstormforce/astra pull request #2285
Opened 2021-02-01 09:27 UTC by RajkiranBagal

### Description
 - Trello task - https://trello.com/c/WlfUb5FA/1021-need-new-control-for-alignment

### Types of changes
New feature (non-breaking change which adds functionality)

### How has this been tested?
 - Check all settings if working or not listed in the checklist in the Trello task.
 - Check Backward compatibility for the same controls.

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-02-04 12:50 UTC, premanshup requested changes

2021-02-04 12:50 UTC, premanshup commented on assets/css/unminified/frontend.css
> -}
@RajkiranBagal Once update your npm and run grunt minify and push the changes.

2021-02-04 12:50 UTC, premanshup commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-configs.php
> +					'partial'    => array(
@RajkiranBagal The alignment options are not appearing properly at my end - https://d.pr/i/0txXth

Theme - `align-control`
Addon - `align-control`

2021-02-04 12:50 UTC, premanshup commented on inc/customizer/configurations/builder/base/class-astra-social-icon-component-configs.php
> +					'control'    => 'ast-alignment',
@RajkiranBagal Instead of `ast-alignment` can we rename it to something more generic? Like here it is used for Color Type. Maybe `ast-select` or `ast-selector`?

2021-02-04 12:50 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/alignment/alignment-component.js
> +import {__} from '@wordpress/i18n';
@RajkiranBagal Please remove unused imports.

2021-02-04 12:50 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/alignment/alignment-component.js
> +	const [props_value, setPropsValue] = useState(props.control.setting.get());
@RajkiranBagal Use `camelCasing` for JS variables.

2021-02-04 12:50 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/alignment/control.js
> +import { astraGetAlignmentJs } from '../common/responsive-helper';
@RajkiranBagal `astraGetAlignmentJs` - `astraGetAlignmentJS` - JS should be always capital.

2021-02-04 13:12 UTC, RajkiranBagal commented on assets/css/unminified/frontend.css
> -}
Done

2021-02-04 13:14 UTC, RajkiranBagal commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-configs.php
> +					'partial'    => array(
Yes, @imnavanath has created Pr for those 5 settings which do not look correct. He will share now

2021-02-04 13:18 UTC, RajkiranBagal commented on inc/customizer/extend-custom-controls/src/alignment/alignment-component.js
> +import {__} from '@wordpress/i18n';
Done

2021-02-04 13:22 UTC, RajkiranBagal commented on inc/customizer/extend-custom-controls/src/alignment/alignment-component.js
> +	const [props_value, setPropsValue] = useState(props.control.setting.get());
Done

2021-02-04 13:24 UTC, RajkiranBagal commented on inc/customizer/extend-custom-controls/src/alignment/control.js
> +import { astraGetAlignmentJs } from '../common/responsive-helper';
Done

2021-02-04 13:29 UTC, premanshup commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-configs.php
> +					'partial'    => array(
@RajkiranBagal Can you please mention the PR here in which this is fixed for future references?

2021-02-04 13:35 UTC, RajkiranBagal commented on inc/customizer/configurations/builder/base/class-astra-social-icon-component-configs.php
> +					'control'    => 'ast-alignment',
Done

2021-02-04 13:43 UTC, premanshup approved these changes

2021-02-05 14:09 UTC, premanshup commented
@RajkiranBagal Please pull latest code here.

2021-02-05 14:12 UTC, RajkiranBagal commented
> @RajkiranBagal Please pull latest code here.

Done

2021-02-05 14:18 UTC, merged