chore: Widgets  HTML and CSS revamp
brainstormforce/astra pull request #2288
Opened 2021-02-02 10:00 UTC by sagarb90

### Description
- Remove `<div class="footer-widget-area-inner site-info-inner site-info-inner">`  Div and add `footer-widget-area-inner` class in parent Div and mange respective CSS.

### Types of changes
- Improvemens

### How has this been tested?
Test All controls of widgets.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards

2021-03-09 13:14 UTC, vrundakansara requested changes

2021-03-09 13:14 UTC, vrundakansara commented on inc/builder/type/footer/widget/dynamic-css/dynamic.css.php
> +		if ( Astra_Builder_Helper::apply_flex_based_css() ) {
Add the selectors conditionally -
```js
$modified_selector = ( Astra_Builder_Helper::apply_flex_based_css() ) ? $selector . '.footer-widget-area-inner' : $selector . ' .footer-widget-area-inner';
```

2021-03-09 13:14 UTC, vrundakansara commented on inc/class-astra-dynamic-css.php
> +				if ( Astra_Builder_Helper::apply_flex_based_css() ) {
Add selector conditionally as shown above.

2021-03-10 11:12 UTC, vrundakansara approved these changes

2021-03-12 06:43 UTC, premanshup approved these changes

2021-03-12 12:00 UTC, merged