feat: Off-Canvas - Added an option to manage spacing between inner elements of the Off-Canvas.
brainstormforce/astra pull request #2290
Opened 2021-02-02 14:50 UTC by vrundakansara

### Description
Off-Canvas - Added an option to manage spacing between inner elements of the Off-Canvas.
Task - [Link](https://trello.com/c/iZaI8fKR/1018-issue-flyout-menu-primary-secondary-mobile-space-between-them)

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests

2021-02-05 10:25 UTC, Nikschavan requested changes

2021-02-05 10:25 UTC, Nikschavan commented on inc/builder/type/header/off-canvas/assets/js/customizer-preview.js
> +
```suggestion
```

Space here can be removed.

2021-02-05 10:25 UTC, Nikschavan commented on inc/builder/type/header/off-canvas/assets/js/customizer-preview.js
> +
```suggestion
```

2021-02-05 10:25 UTC, Nikschavan commented on inc/builder/type/header/off-canvas/assets/js/customizer-preview.js
> +			var dynamicStyle = '';
```suggestion
			let dynamicStyle = '';
```

2021-02-05 10:25 UTC, Nikschavan commented on inc/builder/type/header/off-canvas/assets/js/customizer-preview.js
> +			var dynamicStyle = '';
Unless `var` is required specifically.

2021-02-05 10:25 UTC, Nikschavan commented on inc/builder/type/header/off-canvas/assets/js/customizer-preview.js
> +
```suggestion
```

2021-02-05 10:25 UTC, Nikschavan commented on inc/builder/type/header/off-canvas/assets/js/customizer-preview.js
> +
```suggestion
```

2021-02-08 09:57 UTC, premanshup commented on inc/builder/type/header/off-canvas/assets/js/customizer-preview.js
> +
@Nikschavan Done.

2021-02-08 09:58 UTC, premanshup commented on inc/builder/type/header/off-canvas/assets/js/customizer-preview.js
> +			var dynamicStyle = '';
@Nikschavan Since in Customizer Preview babel or webpack is not setup hence var is required here.

2021-02-08 10:01 UTC, premanshup approved these changes

2021-02-08 10:10 UTC, merged