feat:No refresh in global palette
brainstormforce/astra pull request #2291
Opened 2021-02-03 03:59 UTC by amithire1201

### Description
https://trello.com/c/pyGM8IEp/948-global-color-palette-no-refresh-in-customizer

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-02-03 04:46 UTC, premanshup approved these changes

2021-02-03 15:40 UTC, premanshup requested changes

2021-02-03 15:40 UTC, premanshup commented on .vscode/launch.json
> +}
@amithire1201 Please check if we need this in Theme repo.

2021-02-03 15:40 UTC, premanshup commented on functions.php
> +});
@amithire1201 I don't think this is required, please confirm.

2021-02-03 16:48 UTC, premanshup commented
@amithire1201 On changing the Preset, I'm getting these JS console errors, do check them - https://d.pr/i/OkHea5

2021-02-04 08:04 UTC, Nikschavan commented on functions.php
> +});
Also - let's not _yet_ write anonymous PHP functions, I am not sure we have declared Astra to be PHP 5.6+ yet.

2021-02-04 10:13 UTC, amithire1201 commented on .vscode/launch.json
> +}
Removed.

2021-02-04 10:13 UTC, amithire1201 commented on functions.php
> +});
Removed. Added by mistake

2021-02-04 10:15 UTC, amithire1201 commented
> @amithire1201 On changing the Preset, I'm getting these JS console errors, do check them - https://d.pr/i/OkHea5

Did not reproduced at my end. Could you please mention the steps to reproduce?

2021-02-05 05:52 UTC, premanshup commented
> > @amithire1201 On changing the Preset, I'm getting these JS console errors, do check them - https://d.pr/i/OkHea5
> 
> Did not reproduced at my end. Could you please mention the steps to reproduce?

I will share the steps on task. Merging this PR for now, because we need to implement Backward Comp for old palette color.

2021-02-05 05:52 UTC, premanshup approved these changes

2021-02-05 05:54 UTC, merged