feat: Introducing new Color Group control
brainstormforce/astra pull request #2292
Opened 2021-02-03 04:59 UTC by imnavanath

### Description
- If we have only two color options, right now we are loading those into setting group which leads 2-3 extra clicks for user
- So we decided that we will introduce new color group control, where if 2 or 3 colors are used in combination then it will show directly in customizer section

### Screenshots
- Old - https://a.cl.ly/ApuRnmLG
- New - https://a.cl.ly/mXu1EXmj

### Types of changes
- Introduced new color group control
- Removed setting group wherever possible

### How has this been tested?
- With color groups used
- With backward set color is rendering or not

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-02-04 07:12 UTC, premanshup commented
@imnavanath Right now, the code is distributed for Color Group Control between branches - `customizer-redesign` and `color-group-control`. Please create a single branch where we can check all the changes related to Color Group Control.

2021-02-04 07:30 UTC, Nikschavan requested changes

2021-02-04 07:30 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +	const linked_sub_colors = AstraBuilderCustomizerData.js_configs.sub_controls[name];
The JS variable names should be following `camleCase`
Please do this for all the "new" variables that are created in this PR.

2021-02-04 07:30 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +
```suggestion
```

The empty line here can be removed.

2021-02-04 07:30 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +			value = 'rgba(' + color.rgb.r + ',' + color.rgb.g + ',' + color.rgb.b + ',' + color.rgb.a + ')';
```suggestion
			value = `rgba(${color.rgb.r},${color.rgb.g},${color.rgb.b},${color.rgb.a})`;
```

Tip - [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) can be used to build strings.

@vrundakansara - Do confirm if we should add this only in one place now or we should do one commit in all the places?

2021-02-04 07:30 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +		if (typeof color === 'string' || color instanceof String) {
Are both the conditions same? is there any case where only one of these will be true?

2021-02-04 07:30 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +
```suggestion
```

2021-02-04 07:30 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +
```suggestion
```

2021-02-04 07:30 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +		var tooltip = tooltips[key] || __('Color', 'astra');
Are we using `var` or `let`?

2021-02-04 07:30 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-group/control.js
> +			var resetBtnWrap = container.find('.ast-color-btn-reset-wrap');
`let` or `var`?

2021-02-04 07:30 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-group/control.js
> +		jQuery(document).mouseup(function(e) {
Can we use plain Js for this instead of jQuery?

2021-02-04 12:09 UTC, premanshup requested changes

2021-02-04 12:09 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-group/control.js
> +			var resetBtnWrap = container.find('.ast-color-btn-reset-wrap');
The Reset button is missing as we have in other color options - 
Other controls - [https://d.pr/i/oKDaAi](https://d.pr/i/oKDaAi)
Color Group Controls - [https://d.pr/i/0yG87w](https://d.pr/i/0yG87w)

2021-02-04 13:26 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/color-group/control.js
> +			var resetBtnWrap = container.find('.ast-color-btn-reset-wrap');
let is correct, updated here - https://github.com/brainstormforce/astra/pull/2292/commits/a059ca8b27747381ca81846668ab273c3818877b

2021-02-04 13:26 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +		var tooltip = tooltips[key] || __('Color', 'astra');
let is correct, updated here - https://github.com/brainstormforce/astra/pull/2292/commits/a059ca8b27747381ca81846668ab273c3818877b

2021-02-04 13:27 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +
Removed space here - https://github.com/brainstormforce/astra/pull/2292/commits/a059ca8b27747381ca81846668ab273c3818877b

2021-02-04 13:29 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +
Done here - https://github.com/brainstormforce/astra/pull/2292/commits/35a5527d24daa93c1239751686d540d9ee0a9d1f

2021-02-04 13:29 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +
Done here - https://github.com/brainstormforce/astra/pull/2292/commits/a059ca8b27747381ca81846668ab273c3818877b

2021-02-04 13:30 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +	const linked_sub_colors = AstraBuilderCustomizerData.js_configs.sub_controls[name];
Done sir here with commit - https://github.com/brainstormforce/astra/pull/2292/commits/a059ca8b27747381ca81846668ab273c3818877b

2021-02-04 13:47 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +		if (typeof color === 'string' || color instanceof String) {
Second one can be removed here , corrected - https://github.com/brainstormforce/astra/pull/2292/commits/0808e36b314e1bca71e2d2701c8934b9ca6b47b6

2021-02-04 13:54 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +			value = 'rgba(' + color.rgb.r + ',' + color.rgb.g + ',' + color.rgb.b + ',' + color.rgb.a + ')';
Done here @Nikschavan sir in all cases - https://github.com/brainstormforce/astra/pull/2292/commits/5c9fd9bd64bb769ac4c4a2b2385921841c84fdbc

Please review. 

cc: @vrundakansara

2021-02-05 02:46 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/color-group/control.js
> +			var resetBtnWrap = container.find('.ast-color-btn-reset-wrap');
let is correct here, updated accordingly.

2021-02-05 07:04 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/color-group/control.js
> +			var resetBtnWrap = container.find('.ast-color-btn-reset-wrap');
Done @premanshup, like this - https://a.cl.ly/WnuBNR4Y

2021-02-05 07:09 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/color-group/control.js
> +		jQuery(document).mouseup(function(e) {
Sir in the customizer we can use jQuery, in most of cases we used. 
It can be okay, isn't it? Please correct me if I wrong.

2021-02-05 09:59 UTC, Nikschavan requested changes

2021-02-05 09:59 UTC, Nikschavan commented on inc/customizer/custom-controls/color-group/color-group.scss
> +.customize-control.customize-control-ast-color-group {
```suggestion
.customize-control
	+.customize-control-ast-color-group {
```

I believe in SCSS we should be writing it this way?

2021-02-05 09:59 UTC, Nikschavan commented on inc/customizer/custom-controls/color-group/color-group.scss
> +}
```suggestion
}

```

Can you confirm you have editor-config extension installed for your IDE and that is using the `.editorconfig` file?

2021-02-05 09:59 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +		let html = (
```suggestion
		return (
```

Since this is a one-off variable, this can be removed and returned right away, right?

2021-02-05 09:59 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +		let html = (
If this is done you will have remove return from below

2021-02-05 09:59 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +	const[ state , setState ] = useState(colorGroup);
The const `state` can be named what this is storing in this.

2021-02-05 09:59 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-group/control.js
> +		jQuery(document).mouseup(function(e) {
This does work for now, Although we should start to remove using jQuery from backend as well.

2021-02-05 09:59 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +import {Dashicon} from '@wordpress/components';
```suggestion
import {Dashicon, Tooltip} from '@wordpress/components';
```

This both packages should be correct, right? Can you confirm this?

2021-02-05 09:59 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +const {__} = wp.i18n;
```suggestion
import { __ } from '@wordpress/i18n';
```

Maybe `@wordpress/i18n` will also need to be added to npm dependencies.

2021-02-05 09:59 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-group/control.js
> +			var container = jQuery(control.container);
use `let` unless `var` is required

2021-02-05 10:07 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +	const[ state , setState ] = useState(colorGroup);
do remember to change this variable in this file as well once this is changed

2021-02-05 10:08 UTC, premanshup approved these changes

2021-02-06 03:50 UTC, imnavanath commented on inc/customizer/custom-controls/color-group/color-group.scss
> +.customize-control.customize-control-ast-color-group {
Done

2021-02-06 04:00 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +		let html = (
Done

2021-02-06 04:00 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +	const[ state , setState ] = useState(colorGroup);
Done

2021-02-06 04:04 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +import {Dashicon} from '@wordpress/components';
Right ✔️ Corrected as per suggestion.

2021-02-06 04:11 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/color-group/control.js
> +			var container = jQuery(control.container);
Corrected.

2021-02-06 04:15 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +const {__} = wp.i18n;
Corrected ✔️

2021-02-06 05:51 UTC, imnavanath commented on inc/customizer/custom-controls/color-group/color-group.scss
> +}
It was not installed previously, just installed now & corrected this one.

2021-02-06 09:06 UTC, merged