feat: Reasponsive Spacing control - Added default Linked support only if connected flag is set to true from setting configs.
brainstormforce/astra pull request #2294
Opened 2021-02-03 05:59 UTC by RajkiranBagal

### Description
 - Trello task - https://trello.com/c/or2ndfp5/1029-by-default-link-icon-should-be-disconnected

### Types of changes
 New feature (non-breaking change which adds functionality)

### How has this been tested?
 - Check all ast-responsive-spacing settings if they are linked by default.

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-02-03 06:28 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/responsive-spacing/responsive-spacing-component.js
> +		let disconnected_class = ( connected ) ? 'disconnected' : '';
@RajkiranBagal Can we combine these two?

Something like this?

`let is_connected_class = ( connected ) ? 'connected' : 'disconnected';`

2021-02-03 06:36 UTC, RajkiranBagal commented on inc/customizer/extend-custom-controls/src/responsive-spacing/responsive-spacing-component.js
> +		let disconnected_class = ( connected ) ? 'disconnected' : '';
No these variables need to be used in two different places.

2021-02-03 06:54 UTC, vrundakansara approved these changes

2021-02-03 07:11 UTC, premanshup approved these changes

2021-02-04 09:54 UTC, Nikschavan requested changes
@RajkiranBagal - Can you also check the conflicts in the PR?

2021-02-04 09:54 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/responsive-spacing/responsive-spacing-component.js
> +		let connected_class = ( false === connected ) ? '' : 'connected';
use `camelCase` for variable names for the new variables defined in the PR.

2021-02-04 10:01 UTC, RajkiranBagal commented on inc/customizer/extend-custom-controls/src/responsive-spacing/responsive-spacing-component.js
> +		let connected_class = ( false === connected ) ? '' : 'connected';
Done

2021-02-04 10:02 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/responsive-spacing/responsive-spacing-component.js
> +			linkHtml = <li key={'connect-disconnect' + device} className={ `ast-spacing-input-item-link ${disconnected_class}` }>
The variable will need to be updated here and below as well

2021-02-04 10:03 UTC, RajkiranBagal commented on inc/customizer/extend-custom-controls/src/responsive-spacing/responsive-spacing-component.js
> +			linkHtml = <li key={'connect-disconnect' + device} className={ `ast-spacing-input-item-link ${disconnected_class}` }>
Yes, Sorry missed it.

2021-02-04 10:06 UTC, RajkiranBagal commented on inc/customizer/extend-custom-controls/src/responsive-spacing/responsive-spacing-component.js
> +			linkHtml = <li key={'connect-disconnect' + device} className={ `ast-spacing-input-item-link ${disconnected_class}` }>
Done

2021-02-04 10:16 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/responsive-spacing/responsive-spacing-component.js
> +
```suggestion
```

No need of empty line here as next line is variable declaration.

2021-02-04 10:17 UTC, Nikschavan commented on inc/customizer/extend-custom-controls/src/responsive-spacing/responsive-spacing-component.js
```suggestion
```

This line can also be removed.

2021-02-04 10:30 UTC, RajkiranBagal commented on inc/customizer/extend-custom-controls/src/responsive-spacing/responsive-spacing-component.js
> +
Done

2021-02-04 10:30 UTC, RajkiranBagal commented on inc/customizer/extend-custom-controls/src/responsive-spacing/responsive-spacing-component.js
Done

2021-02-04 11:01 UTC, Nikschavan approved these changes

2021-02-04 11:01 UTC, merged