feat: Old Color Palette backward compatibility with Global Color Palette.
brainstormforce/astra pull request #2303
Opened 2021-02-04 06:33 UTC by premanshup

### Description

This PR provides backward compatibility with the Old Color Palette. If users have added a filter for Color Palette, load the Color Palette, if not, do not load the old palette.
https://trello.com/c/QfuXhne4/949-global-palette-old-palette-backward-compatibility

### Screenshots

https://d.pr/i/zd9IKk

### Types of changes

Non breaking, backward compatibility change.

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-02-04 07:02 UTC, Nikschavan commented on inc/customizer/class-astra-customizer.php
> +			if ( empty( $hook ) || ! isset( $wp_filter[ $hook ] ) ) {
Instead of accessing `global $wp_filter` can something like `has_filter()` be used here?

2021-02-04 07:04 UTC, Nikschavan requested changes

2021-02-04 07:04 UTC, Nikschavan commented on inc/customizer/class-astra-customizer.php
> +			self::$localize_arr['customizer']['is_old_palette_used'] = true;
The name of the method is `get_filters_for`, the `get_` indicates something is to be returned but we are not returning anything here. Can you check the name of this method?

2021-02-05 07:55 UTC, premanshup commented on inc/customizer/class-astra-customizer.php
> +			if ( empty( $hook ) || ! isset( $wp_filter[ $hook ] ) ) {
@Nikschavan Sir, replaced `global $wp_filter` with `has_filter()`

2021-02-05 07:56 UTC, premanshup commented on inc/customizer/class-astra-customizer.php
> +			self::$localize_arr['customizer']['is_old_palette_used'] = true;
@Nikschavan Sir, right, renamed function name from `get_filters_for()` to `check_filters_for()`.

2021-02-05 10:42 UTC, merged