fix: Tab color issue on hover for responsive BG control & extra spacing for gradient picker in Background control
brainstormforce/astra pull request #2307
Opened 2021-02-04 09:37 UTC by imnavanath

### Description
- Tab color issue on hover for responsive BG control & extra spacing for gradient picker in Background control
- CSS tweaks

2021-02-04 13:35 UTC, premanshup requested changes

2021-02-04 13:35 UTC, premanshup commented on inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
> +  padding: 0px 15px 15px
@imnavanath Ideally all 4 or 2 or just 1 padding values should be added.

2021-02-05 02:52 UTC, imnavanath commented on inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
> +  padding: 0px 15px 15px
Updated here @premanshup https://github.com/brainstormforce/astra/pull/2307/commits/8a605147b9f8ce9d95dd055762d83e8494296448

2021-02-05 04:44 UTC, premanshup approved these changes

2021-02-05 04:45 UTC, merged