Refactor: Replace float based CSS with flex based CSS for primary content, also added backward compatibility for the same.
brainstormforce/astra pull request #2308
Opened 2021-02-04 09:42 UTC by sagarb90

### Description
- Replace float based CSS with flex based CSS for primary content, also added backward compatibility for the same.
- https://trello.com/c/eCydK421/1051-5-content-primary-secondary-flex-based

### Types of changes
- Improvements

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-03-03 15:08 UTC, premanshup commented
@sagarb90 In HTML Markup, the CSS Class is not appearing properly, it is breaking the markup attribute. 

Screenshot: [https://d.pr/i/IU3Vfz](https://d.pr/i/IU3Vfz)

Please verify all the markup once and make sure that we do not leave such breaking markup in the HTML.

2021-03-03 15:31 UTC, premanshup commented on assets/css/unminified/frontend.css
>  .ast-col-xs-1, .ast-col-xs-2, .ast-col-xs-3, .ast-col-xs-4, .ast-col-xs-5, .ast-col-xs-6, .ast-col-xs-7, .ast-col-xs-8, .ast-col-xs-9, .ast-col-xs-10, .ast-col-xs-11, .ast-col-xs-12, .ast-col-sm-1, .
@sagarb90 Can we reduce the classes here and add only those which are used?

2021-03-03 15:45 UTC, premanshup commented
@sagarb90 Can we remove before CSS [https://d.pr/i/dpgUlS](https://d.pr/i/dpgUlS)

2021-03-03 15:55 UTC, premanshup commented
@sagarb90 It looks like we have multiple breakpoints like 922 and 921. I think we should combine such CSS and add it on only a single breakpoint.

Screenshot - [https://d.pr/i/Y3Sq6E](https://d.pr/i/Y3Sq6E)

cc: @Nikschavan

2021-03-03 15:58 UTC, premanshup commented
@sagarb90 If we are adding `max-width: 1240px` then I think we can remove the `max-width: 100%` CSS. 

Screenshot - [https://d.pr/i/eqacwS](https://d.pr/i/eqacwS)

Please let me know your thoughts.

2021-03-03 16:00 UTC, premanshup commented
@sagarb90 Can we remove this CSS as well? Let's go through individual HTML for all the layouts and discuss which CSS we can remove.

Screenshot: [https://d.pr/i/BABCzO](https://d.pr/i/BABCzO)

2021-03-03 16:17 UTC, premanshup requested changes

2021-03-03 16:17 UTC, premanshup commented on inc/dynamic-css/container-layouts.php
> + * @package astra-builder
```suggestion
 * @package astra
```

2021-03-03 16:17 UTC, premanshup commented on inc/dynamic-css/container-layouts.php
> +	if ( 'page-builder' == $container_layout ) {
@sagarb90 Use ternary operator here.

2021-03-04 11:47 UTC, sagarb90 reviewed
> @sagarb90 If we are adding `max-width: 1240px` then I think we can remove the `max-width: 100%` CSS.
> 
> Screenshot - https://d.pr/i/eqacwS
> 
> Please let me know your thoughts.

@premanshup We can remove but 1240px; added from dynamic CSS i.e customizer Container layout width If this value will be black then by default it will be apply 100% from static CSS. Please let me know you thought on this scenario.

2021-03-04 11:47 UTC, sagarb90 commented on assets/css/unminified/frontend.css
> -  }
@premanshup Yes these CSS are already added in dynamic CSS Which is added by Navanath and I have also confirm same from him so Removing duplicated CSS - https://share.getcloudapp.com/rRukDBXd.

2021-03-04 11:47 UTC, sagarb90 commented on assets/css/unminified/frontend.css
>  .ast-col-xs-1, .ast-col-xs-2, .ast-col-xs-3, .ast-col-xs-4, .ast-col-xs-5, .ast-col-xs-6, .ast-col-xs-7, .ast-col-xs-8, .ast-col-xs-9, .ast-col-xs-10, .ast-col-xs-11, .ast-col-xs-12, .ast-col-sm-1, .
@premanshup As you already know these CSS are added from scss using for loop and we already discuss this, so we can not remove and we have already removed these CSS from main.css file (i.e flex based changes).

2021-03-04 12:16 UTC, sagarb90 commented
> @sagarb90 Can we remove before CSS https://d.pr/i/dpgUlS

@premanshup Yes we have already removed from main.css i.e.flex base changes - https://share.getcloudapp.com/qGuXbbzr
Looks like you are checking frontend.css i.e existing user css.

2021-03-04 13:39 UTC, sagarb90 commented
> @sagarb90 Can we remove this CSS as well? Let's go through individual HTML for all the layouts and discuss which CSS we can remove.
> 
> Screenshot: https://d.pr/i/BABCzO

@premanshup Yes I have check and removed css you mentioned in the screenshot and also check rest of layout CSS their is no such CSS for  any HTML markup.

2021-03-04 14:01 UTC, sagarb90 commented
> @sagarb90 It looks like we have multiple breakpoints like 922 and 921. I think we should combine such CSS and add it on only a single breakpoint.
> 
> Screenshot - https://d.pr/i/Y3Sq6E
> 
> cc: @Nikschavan

@premanshup Yes As these are tablet breakpoints so I have added condition for  921 i.e. 100% ,if site container width is empty/ null then apply 100% width CSS. Please let me know your thought on this.

2021-03-04 14:02 UTC, sagarb90 commented
> @sagarb90 In HTML Markup, the CSS Class is not appearing properly, it is breaking the markup attribute.
> 
> Screenshot: https://d.pr/i/IU3Vfz
> 
> Please verify all the markup once and make sure that we do not leave such breaking markup in the HTML.

@premanshup Yes thank you for checking this I have resolved this now.

2021-03-09 13:19 UTC, vrundakansara requested changes

2021-03-09 13:19 UTC, vrundakansara commented on inc/dynamic-css/container-layouts.php
> +<?php
Instead of a new file, can we add this function to `inc/extras.php` file @premanshup 
And call the same function above.

2021-03-09 15:07 UTC, premanshup commented on assets/css/unminified/frontend.css
>  .ast-col-xs-1, .ast-col-xs-2, .ast-col-xs-3, .ast-col-xs-4, .ast-col-xs-5, .ast-col-xs-6, .ast-col-xs-7, .ast-col-xs-8, .ast-col-xs-9, .ast-col-xs-10, .ast-col-xs-11, .ast-col-xs-12, .ast-col-sm-1, .
@sagarb90 Okay!

2021-03-09 15:08 UTC, premanshup commented
> > @sagarb90 Can we remove before CSS https://d.pr/i/dpgUlS
> 
> @premanshup Yes we have already removed from main.css i.e.flex base changes - https://share.getcloudapp.com/qGuXbbzr
> Looks like you are checking frontend.css i.e existing user css.

Yep! I missed the file name, my bad. Looking good 👍🏼

2021-03-09 15:15 UTC, premanshup commented
> > @sagarb90 If we are adding `max-width: 1240px` then I think we can remove the `max-width: 100%` CSS.
> > Screenshot - https://d.pr/i/eqacwS
> > Please let me know your thoughts.
> 
> @premanshup We can remove but 1240px; added from dynamic CSS i.e customizer Container layout width If this value will be black then by default it will be apply 100% from static CSS. Please let me know you thought on this scenario.

@sagarb90 SO can we load this conditionally? If the value is null or empty from option only then add 100% CSS. Let me know your thoughts?

2021-03-10 06:40 UTC, sagarb90 commented
> > > @sagarb90 If we are adding `max-width: 1240px` then I think we can remove the `max-width: 100%` CSS.
> > > Screenshot - https://d.pr/i/eqacwS
> > > Please let me know your thoughts.
> > 
> > 
> > @premanshup We can remove but 1240px; added from dynamic CSS i.e from customizer Container layout width, If this value will be blank then by default it will be apply 100% from static CSS. Please let me know you thought on this scenario.
> 
> @sagarb90 SO can we load this conditionally? If the value is null or empty from option only then add 100% CSS. Let me know your thoughts?



> > > @sagarb90 If we are adding `max-width: 1240px` then I think we can remove the `max-width: 100%` CSS.
> > > Screenshot - https://d.pr/i/eqacwS
> > > Please let me know your thoughts.
> > 
> > 
> > @premanshup We can remove but 1240px; added from dynamic CSS i.e from customizer Container layout width, If this value will be blank then by default it will be apply 100% from static CSS. Please let me know you thought on this scenario.
> 
> @sagarb90 SO can we load this conditionally? If the value is null or empty from option only then add 100% CSS. Let me know your thoughts?

@premanshup Yes I have added condition as you mentioned - https://share.getcloudapp.com/E0u9v1jd

2021-03-10 11:14 UTC, vrundakansara commented on inc/dynamic-css/container-layouts.php
> +<?php
Alright. 👍🏼

2021-03-10 11:16 UTC, vrundakansara commented on inc/class-astra-dynamic-css.php
> +			$parse_css .= require_once ASTRA_THEME_DIR . 'inc/dynamic-css/container-layouts.php'; // PHPCS:ignore WPThemeReview.CoreFunctionality.FileInclude.FileIncludeFound
@premanshup - Please confirm if this is the correct way to get dynamic CSS?
May be calling a function would be fine here instead of requiring an entire file.

2021-03-11 05:18 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> +			$parse_css .= require_once ASTRA_THEME_DIR . 'inc/dynamic-css/container-layouts.php'; // PHPCS:ignore WPThemeReview.CoreFunctionality.FileInclude.FileIncludeFound
@vrundakansara Yes you are correct that is better approach and I have changed that to calling function instead require file.

2021-03-12 07:04 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +			$parse_css .= require_once ASTRA_THEME_DIR . 'inc/dynamic-css/container-layouts.php'; // PHPCS:ignore WPThemeReview.CoreFunctionality.FileInclude.FileIncludeFound
@vrundakansara Agree!

2021-03-12 07:10 UTC, premanshup commented
> SO can we load this conditionally? If the value is null or empty from option only then add 100% CSS. Let me know your thoughts?

@sagarb90  Thank you!

2021-03-12 07:10 UTC, premanshup approved these changes

2021-03-12 07:12 UTC, vrundakansara approved these changes

2021-03-15 13:38 UTC, merged