feat: Above & Below header meta settings compatibility.
brainstormforce/astra pull request #2320
Opened 2021-02-06 14:53 UTC by premanshup

### Description

This PRs introduces the following checkboxes for the meta settings to provide compatibility with Header Footer builder:
1. Disable Above Header
2. Disable Below Header

https://trello.com/c/5vmuEIIM/976-add-option-to-hide-the-above-below-header-in-page-meta-settings-it-was-there-previously

### Screenshots

https://d.pr/i/crPsZf

### Types of changes

New feature (non-breaking change which adds functionality)

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-02-08 13:42 UTC, imnavanath approved these changes

2021-02-09 04:22 UTC, Nikschavan requested changes

2021-02-09 04:22 UTC, Nikschavan commented on inc/builder/markup/class-astra-builder-header.php
> +				if ( astra_wp_version_compare( '5.4.99', '>=' ) ) {
Why are we checking for version 5.4.99? I believe we want to check for v5.5 and above since that is where the last parameter for `get_template_part()` was added? Doing a check if version number is  v5.5 and above will be much straight forward, right?

2021-02-09 04:22 UTC, Nikschavan commented on inc/metabox/class-astra-meta-boxes.php
> +					<?php if ( $show_meta_field && Astra_Builder_Helper::is_row_empty( 'above', 'header', 'desktop' ) ) { ?>
```suggestion
					<?php if ( $show_meta_field && Astra_Builder_Helper::is_row_empty( 'above', 'header', 'desktop' ) ) : ?>
```

I believe this is a preferred way of writing the conditions inside of markup?

2021-02-09 04:22 UTC, Nikschavan commented on inc/metabox/class-astra-meta-boxes.php
> +					<?php } ?>
```suggestion
					<?php endif: ?>
```

2021-02-09 14:49 UTC, premanshup commented on inc/builder/markup/class-astra-builder-header.php
> +				if ( astra_wp_version_compare( '5.4.99', '>=' ) ) {
@Nikschavan This is something we checked in other reference PRs, this includes all beta versions too due to which we have added this.

2021-02-09 14:53 UTC, Nikschavan commented on inc/builder/markup/class-astra-builder-header.php
> +				if ( astra_wp_version_compare( '5.4.99', '>=' ) ) {
Any reference PR that you can refer to? will checking for v5.5 and above work as well?

2021-02-09 15:13 UTC, premanshup commented on inc/builder/markup/class-astra-builder-header.php
> +				if ( astra_wp_version_compare( '5.4.99', '>=' ) ) {
@Nikschavan I couldn't find the original PR where I looked at this. But in this reference PR - https://github.com/brainstormforce/astra/pull/1831/files#r466861402 we decided to go with similar conditions. Please Let me know if your thoughts.

2021-02-10 07:16 UTC, premanshup commented on inc/metabox/class-astra-meta-boxes.php
> +					<?php if ( $show_meta_field && Astra_Builder_Helper::is_row_empty( 'above', 'header', 'desktop' ) ) { ?>
@Nikschavan Yes, replaced `if {}` conditions with `if :`

2021-02-10 07:16 UTC, premanshup commented on inc/metabox/class-astra-meta-boxes.php
> +					<?php } ?>
@Nikschavan Yes, replaced all `if {}` conditions with `if :`

2021-02-10 07:18 UTC, merged