Fix: Fixed footer sections vertical alignment issue
brainstormforce/astra pull request #2324
Opened 2021-02-08 08:39 UTC by sushmak02

### Description
Footer above/below and primary header vertical alignment was not working due to some Divider CSS. I have added a fix for the Alignment issue.

### Screenshots

### Types of changes

Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-02-08 13:13 UTC, premanshup requested changes

2021-02-08 13:13 UTC, premanshup commented on inc/builder/type/footer/below-footer/assets/js/customizer-preview.js
> +        selector + ' .ast-builder-grid-row, ' + selector + ' .ast-builder-grid-row .site-footer-section'
@sushmak02 Do we really need  `.ast-builder-grid-row .site-footer-section`
Or can it managed by just once class -  `.site-footer-section`

2021-02-08 13:13 UTC, premanshup commented on inc/builder/type/footer/above-footer/dynamic-css/dynamic.css.php
> +		$selector . ' .ast-builder-grid-row, ' . $selector . ' .ast-builder-grid-row .site-footer-section' => array(
@sushmak02 Do we really need `.ast-builder-grid-row .site-footer-section`
Or can it managed by just once class - `.site-footer-section`

2021-02-08 13:13 UTC, premanshup commented on inc/builder/type/footer/primary-footer/dynamic-css/dynamic.css.php
> +		$selector . ' .ast-builder-grid-row, ' . $selector . ' .ast-builder-grid-row .site-footer-section' => array(
@sushmak02 Do we really need `.ast-builder-grid-row .site-footer-section`
Or can it managed by just once class - `.site-footer-section`

2021-02-08 13:29 UTC, sushmak02 commented on inc/builder/type/footer/below-footer/assets/js/customizer-preview.js
> +        selector + ' .ast-builder-grid-row, ' + selector + ' .ast-builder-grid-row .site-footer-section'
Done!

2021-02-08 13:29 UTC, sushmak02 commented on inc/builder/type/footer/above-footer/dynamic-css/dynamic.css.php
> +		$selector . ' .ast-builder-grid-row, ' . $selector . ' .ast-builder-grid-row .site-footer-section' => array(
Done!

2021-02-08 13:29 UTC, sushmak02 commented on inc/builder/type/footer/primary-footer/dynamic-css/dynamic.css.php
> +		$selector . ' .ast-builder-grid-row, ' . $selector . ' .ast-builder-grid-row .site-footer-section' => array(
Done!

2021-02-08 13:32 UTC, premanshup approved these changes

2021-02-11 07:35 UTC, vrundakansara approved these changes

2021-02-11 07:41 UTC, merged