refactor: Updated partial edit icons with new SVG icon
brainstormforce/astra pull request #2326
Opened 2021-02-08 10:29 UTC by imnavanath

### Description
- Updated with new SVG icon for previous edit icon

### Screenshots
- https://a.cl.ly/o0uEgPL5

### Types of changes
- Non breaking change

### How has this been tested?
- With customizer refresh

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-02-08 11:02 UTC, premanshup commented
@imnavanath Please resolve merge conflicts and check semantic pull request status.

2021-02-08 11:08 UTC, imnavanath commented
> @imnavanath Please resolve merge conflicts and check semantic pull request status.

Done @premanshup

2021-02-08 11:19 UTC, premanshup requested changes

2021-02-08 11:19 UTC, premanshup commented on inc/assets/css/customizer-preview-rtl.css
> +	border-width: 1px;
@imnavanath Check the indentation.

2021-02-08 11:19 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/customizer.js
> +
```suggestion

```

2021-02-08 11:19 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/customizer.js
> +
```suggestion

```

2021-02-08 11:19 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/customizer.js
> +
```suggestion

```

2021-02-08 11:19 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/customizer.js
> +
```suggestion

```

2021-02-10 11:49 UTC, imnavanath commented on inc/assets/css/customizer-preview-rtl.css
> +	border-width: 1px;
Corrected 👍

2021-02-10 12:45 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/customizer.js
> +
Reverted these changes as previous edit button was finalized.

2021-02-10 12:45 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/customizer.js
> +
Reverted these changes as previous edit button was finalized.

2021-02-10 12:45 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/customizer.js
> +
Reverted these changes as previous edit button was finalized.

2021-02-10 12:46 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/customizer.js
> +
Reverted these changes as previous edit button was finalized.

2021-02-10 12:47 UTC, premanshup approved these changes

2021-02-10 12:47 UTC, merged