refactor: Design changes for reset icon in Ast-customizer
brainstormforce/astra pull request #2330
Opened 2021-02-08 12:58 UTC by imnavanath

### Description
- Reset icon design changes

### Screenshots
- https://share.getcloudapp.com/12uo1Xe4

### Types of changes
- Non breaking changes

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-02-10 14:58 UTC, premanshup requested changes

2021-02-10 14:58 UTC, premanshup commented on inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
> +	background: transparent;
@imnavanath Check the alignment.

2021-02-10 14:58 UTC, premanshup commented on inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
> +	background: transparent;
@imnavanath Check the alignment.

2021-02-11 06:11 UTC, imnavanath commented on inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
> +	background: transparent;
Fixed, and it's aligned now - https://a.cl.ly/v1uNxPkx

2021-02-11 06:12 UTC, imnavanath commented on inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
> +	background: transparent;
Fixed, it's aligned now - https://a.cl.ly/rRukogR5

2021-02-11 06:18 UTC, premanshup approved these changes

2021-02-11 06:19 UTC, merged