Feat: Customizer redesign responsive color group
brainstormforce/astra pull request #2334
Opened 2021-02-09 06:54 UTC by amithire1201

### Description
https://trello.com/c/vLaZFE2m/1072-responsive-color-group-needed

### Types of changes

New feature (non-breaking change which adds functionality)

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-02-11 01:56 UTC, Nikschavan commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
> +							Astra_Builder_Helper::$design_tab_config : Astra_Builder_Helper::$general_tab_config,
Instead of repeating this tertiary condition everywhere, why not simply create a method in the same class to return the relevant config?

This can be created in a separate task, can you create an issue for this?

2021-02-11 06:00 UTC, premanshup requested changes

2021-02-11 06:00 UTC, premanshup commented on functions.php
> +define( 'ASTRA_THEME_VERSION', '3.2.0' );
@amithire1201 Make sure to pull the latest next-release, the version number should be v3.1.0 here.

2021-02-11 06:39 UTC, amithire1201 commented on functions.php
> +define( 'ASTRA_THEME_VERSION', '3.2.0' );
Done.

2021-02-12 10:18 UTC, vrundakansara approved these changes

2021-02-12 10:19 UTC, vrundakansara commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
> +							Astra_Builder_Helper::$design_tab_config : Astra_Builder_Helper::$general_tab_config,
I will add a task about it.

2021-02-12 11:46 UTC, merged