fix: Updated the Icons Markup & CSS as per the UI/UX perspective.
brainstormforce/astra pull request #2337
Opened 2021-02-09 10:45 UTC by RajkiranBagal

### Description
 - Trello task - https://trello.com/c/idwR1QsN/1107-change-reset-icon-design

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
 - Styling Changes in CSS.

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-02-10 14:53 UTC, premanshup requested changes

2021-02-10 14:53 UTC, premanshup commented on inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
> +}
@imnavanath Please check if we can combine the above CSS with this?

`.customize-control-ast-responsive-background .ast-color-btn-reset-wrap {`

Both have same CSS properties.

2021-02-10 14:53 UTC, premanshup commented on inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
> +}
@imnavanath This looks like a duplicate CSS - 

https://github.com/brainstormforce/astra/pull/2337/files#diff-168566eaa47d45cb74bf319565059c0a924f9c87e66451821f796d041fda9377R2280

Please make sure there are no other duplicate CSS.

2021-02-10 14:53 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color/color-component.js
> +		console.log(defaultValue);
@imnavanath Remove all `console.log()`

2021-02-10 14:53 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color/color-component.js
> +		let tempVal = state.value.replace( 'unset', '' );
@imnavanath This can be `const` instead of `let`

2021-02-11 04:15 UTC, RajkiranBagal commented on inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
> +}
Done.

2021-02-11 04:16 UTC, RajkiranBagal commented on inc/customizer/custom-controls/assets/css/unminified/custom-controls-rtl.css
> +}
Removed Duplicate CSS, & checked for no other.

2021-02-11 04:16 UTC, RajkiranBagal commented on inc/customizer/extend-custom-controls/src/color/color-component.js
> +		console.log(defaultValue);
Removed.

2021-02-11 04:16 UTC, RajkiranBagal commented on inc/customizer/extend-custom-controls/src/color/color-component.js
> +		let tempVal = state.value.replace( 'unset', '' );
Done.

2021-02-11 05:43 UTC, premanshup approved these changes

2021-02-11 13:02 UTC, vrundakansara approved these changes

2021-02-11 13:02 UTC, merged