fix: white label not working in copyright component
brainstormforce/astra pull request #2338
Opened 2021-02-09 12:29 UTC by shubhw12

### Description
Instead of using static values for theme author and URL, I have used the variables just like what was done previously previous header footer markup.

### Types of changes

Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
Checked this with the white label enabled.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-02-09 14:44 UTC, premanshup requested changes

2021-02-09 14:44 UTC, premanshup commented on inc/builder/markup/class-astra-builder-footer.php
> +			);
@shubhw12 Instead of adding two apply filter for same filter, it will be recommended to create a single function with single apply_filter and call that function here.

2021-02-10 04:31 UTC, Nikschavan approved these changes

2021-02-10 09:42 UTC, shubhw12 commented on inc/builder/markup/class-astra-builder-footer.php
> +			);
@premanshup Sir I have made the changes accordingly

2021-02-12 08:20 UTC, vrundakansara approved these changes

2021-02-12 09:49 UTC, premanshup approved these changes

2021-02-12 12:07 UTC, merged