feta: Customizer redesign for Astra v3.1.0
brainstormforce/astra pull request #2353
Opened 2021-02-12 13:04 UTC by imnavanath

### Description
- Customizer redesign includes following parameters
- Major improvements
1. Slider input control revamped with WordPress's core range control.
2. Color-group implemented for better UX.
3. Select group converted into multi-button group which leads better UX.
4. Checkbox control revamped with WordPress's toggle control.
5. Align selection field also revamped with mutli-button control for better UX.
- Design improvements -
1. Color picker UI changes
2. Spacing control design updated.
3. Implemented divider in between all controls so controls are separated properly.
4. Drag-drop meta structure control design's also revamped.
- Checkbox control converted into Toggle control

### Types of changes
- Customizer control revamped
- CSS changed as per design perspective for customizer

### How has this been tested?
- With normal controls & controls inside group control
- Test customizer-redesign with Old header footer
- Check with addon/theme only updated
- Verify if previous values comes as it is in new controls after update (majorly in following controls)
1. Checkbox -> Toggle control
2. Slider -> Rangecontrol
3. Setting (color) group -> Color-group
- Cross-browser testing
- RTL language testing

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-02-17 05:26 UTC, Nikschavan reviewed
Some minor comments, I am Ok if this will be addressed in the next update. Make sure to add issues for these suggestions though.

2021-02-17 05:26 UTC, Nikschavan commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
> +			} else {
This else can be avoided, Just set `$content_colors_control_title` before the if condition as a default value and change it in the if condition if the condition is met.

2021-02-17 05:26 UTC, Nikschavan commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
> +			if ( Astra_Builder_Helper::$is_header_footer_builder_active ) {
```suggestion
			if ( true === Astra_Builder_Helper::$is_header_footer_builder_active ) {
```

Please perform explicit checks everywhere possible.

2021-02-17 05:26 UTC, Nikschavan commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
> +							Astra_Builder_Helper::$design_tab_config : Astra_Builder_Helper::$general_tab_config,
Have we created a task for this to be improved? - A simple method can be created which will return the required value instead of performing this condition everywhere.

Can you link to the task so that I can follow it up?

2021-02-17 12:33 UTC, imnavanath commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
> +							Astra_Builder_Helper::$design_tab_config : Astra_Builder_Helper::$general_tab_config,
Here is the task for this - https://trello.com/c/hgrhPsLW/1192-create-common-function-which-returns-context-based-on-condition

2021-02-17 12:36 UTC, imnavanath commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
> +			} else {
I've checked this conditions, it's widely used. So I've moved this to in new card (where I'll be work on it for next update)
Task for this - https://trello.com/c/8NHUTOuS/1191-customizer-redesign-pr-review-changes
@vrundakansara if sounds okay, can you please resolve this comment

2021-02-17 12:37 UTC, imnavanath commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
> +			if ( Astra_Builder_Helper::$is_header_footer_builder_active ) {
Added improvement in the same task - Task for this - https://trello.com/c/8NHUTOuS/1191-customizer-redesign-pr-review-changes

2021-02-17 13:06 UTC, vrundakansara approved these changes

2021-02-17 13:14 UTC, RajkiranBagal requested changes

2021-02-17 13:14 UTC, RajkiranBagal commented on inc/customizer/configurations/builder/header/class-astra-customizer-edd-cart-configs.php
> +					'name'       => ASTRA_THEME_SETTINGS . '[header-edd-cart-text-color]',
Why `ASTRA_THEME_SETTINGS` appended to a sub-control config?

2021-02-17 13:14 UTC, RajkiranBagal commented on inc/customizer/configurations/builder/header/class-astra-customizer-edd-cart-configs.php
> +					'name'       => ASTRA_THEME_SETTINGS . '[header-edd-cart-link-color]',
Why `ASTRA_THEME_SETTINGS` appended to a sub-control config?

2021-02-17 13:19 UTC, imnavanath commented on inc/customizer/configurations/builder/header/class-astra-customizer-edd-cart-configs.php
> +					'name'       => ASTRA_THEME_SETTINGS . '[header-edd-cart-link-color]',
Done here - https://github.com/brainstormforce/astra/pull/2353/commits/033b23e2c4481469a09ce1bcf2bd3b56d4d151e6

2021-02-17 13:19 UTC, imnavanath commented on inc/customizer/configurations/builder/header/class-astra-customizer-edd-cart-configs.php
> +					'name'       => ASTRA_THEME_SETTINGS . '[header-edd-cart-text-color]',
Done here - https://github.com/brainstormforce/astra/pull/2353/commits/033b23e2c4481469a09ce1bcf2bd3b56d4d151e6

2021-02-17 13:29 UTC, RajkiranBagal approved these changes

2021-02-18 04:20 UTC, rohitp-bsf approved these changes

2021-02-18 04:30 UTC, premanshup approved these changes

2021-02-18 06:38 UTC, RajkiranBagal commented on inc/assets/css/ast-builder-customizer.css
> +    top: -26px;
Done

2021-02-18 06:38 UTC, RajkiranBagal commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
> +
Done

2021-02-18 06:38 UTC, RajkiranBagal commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
> +
Done

2021-02-18 06:40 UTC, merged