fix: Page header settings issue with header footer builder
brainstormforce/astra pull request #2401
Opened 2021-02-23 14:02 UTC by abhishek-bsf

### Description

Fixed issue regarding Display above header and Display below header options from page header settings not working for new Header Footer builder

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
Tested options by comparing with Old Header Footer Builder

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests

2021-02-24 14:23 UTC, premanshup requested changes

2021-02-24 14:23 UTC, premanshup commented on inc/builder/markup/class-astra-builder-header.php
> +			}
@abhishek-bsf We can use the existing filter - `astra_above_header_display` instead of adding new filters, please check.

2021-02-24 14:23 UTC, premanshup commented on inc/builder/markup/class-astra-builder-header.php
> +			}
@abhishek-bsf We can use the existing filter - astra_above_header_display instead of adding new filters, please check.

2021-02-25 11:51 UTC, abhishek-bsf commented on inc/builder/markup/class-astra-builder-header.php
> +			}
Used existing filter instead of adding new filter.

2021-02-25 11:51 UTC, abhishek-bsf commented on inc/builder/markup/class-astra-builder-header.php
> +			}
Used existing filter instead of adding new filter.

2021-02-25 11:52 UTC, abhishek-bsf commented
@premanshup We can close this PR now as we are not changing any files.

2021-02-26 03:53 UTC, premanshup commented
> @premanshup We can close this PR now as we are not changing any files.

@abhishek-bsf Yes please, you can go ahead and close this PR.

2021-02-26 05:01 UTC, closed without merging