Add web stories embed support with default customizer settings
brainstormforce/astra pull request #2407
Opened 2021-02-24 13:05 UTC by pradeep910

### Description
Adds web stories circles list above the header if web stories are enabled via customizer settings. This uses web stories added to the site using [Web Stories Plugin](https://wordpress.org/plugins/web-stories/). 

In order to make it work please use this [web-stories-v7.zip](https://github.com/brainstormforce/astra/files/6035970/web-stories-v7.zip) as this feature is not yet released. Here is the [github branch link](https://github.com/rtCamp/web-stories-wp/tree/feature/embed-stories).

### Screenshots
![Screenshot 2021-02-24 at 5 31 06 PM](https://user-images.githubusercontent.com/1139853/108997924-3897b280-76c6-11eb-877d-4920014c73c1.png)
![Screenshot 2021-02-24 at 5 31 38 PM](https://user-images.githubusercontent.com/1139853/108997938-3df4fd00-76c6-11eb-9614-341a22ab8dc1.png)

### Types of changes
- Adds theme customizer settings support using `add_theme_support( 'web-stories' );`
- Changes `header.php` to add web stories embed code. (This displays web stories above the header on all pages.)

### How has this been tested?

Tested with a few astra starter templates (Photographer, Custom Printing, Italian Restaurant) with customizer enabled stories in desktop, tablet and mobile devices.
(Please use this [web-stories-v7.zip](https://github.com/brainstormforce/astra/files/6035970/web-stories-v7.zip) as this feature is not yet released. Also, this will require "Show stories" to be enabled from customizer.)

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests

2021-02-24 13:09 UTC, pradeep910 commented
@Nikschavan How would you like this PHP 5.2 issue resolved? Looks like astra requires PHP 5.3, so we may not need to resolve this. https://github.com/brainstormforce/astra/blob/master/style.css#L10

```
FILE: /home/runner/work/astra/astra/header.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 1 LINE
----------------------------------------------------------------------
 35 | ERROR | the \ operator (for namespaces) is not present in PHP
    |       | version 5.2 or earlier
    |       | (PHPCompatibility.LanguageConstructs.NewLanguageConstructs.t_ns_separatorFound)
 35 | ERROR | the \ operator (for namespaces) is not present in PHP
    |       | version 5.2 or earlier
    |       | (PHPCompatibility.LanguageConstructs.NewLanguageConstructs.t_ns_separatorFound)
 35 | ERROR | the \ operator (for namespaces) is not present in PHP
    |       | version 5.2 or earlier
    |       | (PHPCompatibility.LanguageConstructs.NewLanguageConstructs.t_ns_separatorFound)
----------------------------------------------------------------------
```

2021-02-24 15:19 UTC, pradeep910 commented
@Nikschavan I see there are some namespace related issues coming from PHP 5.2. WordPress needs minimum 5.6, so may I suggest to update php version compatibility check?

Also please note WP also needs minimum 5.6 version to run. https://wordpress.org/about/requirements/

2021-02-24 15:26 UTC, Nikschavan requested changes
Adding some feedback on the overall structure we are following to add compatibility to third-party plugins.

2021-02-24 15:26 UTC, Nikschavan commented on inc/class-astra-after-setup-theme.php
> +			add_theme_support( 'web-stories' );
This can be moved in the above-mentioned file as well, the idea is - everything related to Web stories will be initiated from this file.

2021-02-24 15:26 UTC, Nikschavan commented on sass/site/_site.scss
> +@import "web-stories/web-stories-circles";
Ideally, we would want to load the CSS in the frontend only if the web-stories plugin is active and a dtory it is being displayed in the page.

If the CSS is going to be small like it is right now this can be added in the dynamic CSS (CSS generated using PHP, where we can use conditionals) and an example for this is for [elementor comparibility](https://github.com/brainstormforce/astra/blob/master/inc/compatibility/class-astra-elementor.php#L57), we CSS in the form of an array to the filter `astra_dynamic_theme_css`.

Since we don't have public documentation for this filter, feel free to ignore this change, I can get this done later on.

2021-02-24 15:26 UTC, Nikschavan commented on sass/site/web-stories/_web-stories-circles.scss
> +	padding: 15px 0;
Is there going to be more CSS than this to add compatibility? 
Is this padding going to be required by all the themes? If this is the case I was wondering if this can be moved into the plugin? That would reduce the effort required from the theme authors to add compatibility for their themes.

2021-02-24 15:46 UTC, Nikschavan commented
@pradeep910 Re: PHP 5.2, You can ignore this rule in the new file that will be created, This is done for the elementor compatibility file I mentioned above. We are planning to raise the minimum PHP version but we will have to do it with an announcement to the users and that has just been pending to be done. 

While WP raised the minimum version, themes have to support the last three versions of WordPress so we could raise the minimum version since WP 5.5. Although, we appreciate that there might be sites among 1M active installs that might be updating theme but not WordPress so we feel it is necessary to announce it before upping the requirements.

---

btw - I tried web stories on a few starter templates - I noticed that if the user has not used "Global background color" (Global -> Colors -> Base Colors) then the stories container does not have any background color - 

<img width="2558" alt="Markup 2021-02-24 at 21 10 31" src="https://user-images.githubusercontent.com/2931091/109025657-edd96300-76e4-11eb-8767-03fac5ae8b7c.png">

Do you think it makes sense for the web-stories plugin to add some basic styling options?

The global background color will not really work for this case as this color is added everywhere on the site where the background color is not added to any div. For eg try removing this color from the site that you are using in the screenshot.

I believe a theme would need to provide separate options anyway to style and make this section look nicer and integrated in the overall UI. Let me know your thoughts on this.

2021-02-24 15:57 UTC, Nikschavan commented on sass/site/_site.scss
> +@import "web-stories/web-stories-circles";
Also - This can be decided after the whole compatibility CSS will be ready.

2021-02-24 15:58 UTC, pradeep910 commented on header.php
> +}
Creating separate file as you mentioned makes sense, however we wanted to keep changes minimum to demonstrate how stories can be shown above header.

There is another hook on top of `wp_body_open`, which is Astra's own hook - `astra_body_top`. As that can take precedence over `wp_body_open` we can try that maybe?

2021-02-24 16:07 UTC, pradeep910 commented on sass/site/_site.scss
> +@import "web-stories/web-stories-circles";
I liked the idea of adding css dynamically. It totally depends on theme author how much they would like to support and how they would like to style stories on a particular template. 

In general, for a simple template or design it may not make sense to add css but for complex design where you can have sticky elements and absolute positioned elements it may need extra css to override. 

We will have to determine how much css changes are needed in the existing free starter templates https://wordpress.org/plugins/astra-sites/ and the premium starter templates https://wpastra.com/docs/install-premium-starter-templates/

2021-02-24 16:10 UTC, pradeep910 commented
Thanks for the feedback about global color @Nikschavan. 

@divyarajmasani do you have any suggestion on this?

2021-02-24 16:14 UTC, Nikschavan commented on sass/site/_site.scss
> +@import "web-stories/web-stories-circles";
Agreed - The CSS might be bit more depending on all the options that are possible.

2021-02-24 16:32 UTC, pradeep910 commented on sass/site/web-stories/_web-stories-circles.scss
> +	padding: 15px 0;
As I mentioned in my [previous comment](https://github.com/brainstormforce/astra/pull/2407#discussion_r582089646), it might need more css depending upon the starter template used. Some templates might need extra CSS, but adding them dynamically will be a good idea. We can create array of templates used if Astra stores currently used template somewhere and then add CSS based on that. 
Not sure if it is too much to check just to add one line of css.

2021-02-25 09:53 UTC, divyarajmasani commented
@Nikschavan 

That would be a really nice addition to the web-stories plugin, users being able to tweak some basic styles. We would keep this in our future roadmap and definitely try to address it as quickly as possible. 

Thank you for your feedback.

2021-03-03 14:24 UTC, premanshup commented on inc/compatibility/class-astra-web-stories.php
> +		}
Just a suggestion, instead of the singleton class can we keep it as a regular class?
```suggestion

```

2021-03-03 14:25 UTC, premanshup commented on inc/compatibility/class-astra-web-stories.php
> +Astra_Web_Stories::get_instance();
```suggestion
new Astra_Web_Stories();
```

2021-03-03 15:06 UTC, pradeep910 commented on inc/compatibility/class-astra-web-stories.php
> +				<style type="text/css">
@premanshup @Nikschavan I think this CSS can be added through `astra_dynamic_theme_css` filter available in theme. You can take over and change it to as per your structure or standards.

2021-03-11 13:03 UTC, Nikschavan commented
@pradeep910 Can you check if in this PR "Allow edits by maintainers" setting is enabled?

<img width="591" alt="Markup 2021-03-11 at 18 31 01" src="https://user-images.githubusercontent.com/2931091/110791352-1b530e80-8298-11eb-94a1-9267e5e70304.png">

With this we can add final changes to this PR and get this merged, Right now I don;t have permission to add any commits to this PR.

2021-03-12 11:43 UTC, Nikschavan commented
> @pradeep910 Can you check if in this PR "Allow edits by maintainers" setting is enabled?
> 
> <img alt="Markup 2021-03-11 at 18 31 01" width="591" src="https://user-images.githubusercontent.com/2931091/110791352-1b530e80-8298-11eb-94a1-9267e5e70304.png">
> 
> With this we can add final changes to this PR and get this merged, Right now I don;t have permission to add any commits to this PR.

@pradeep910, @divyarajmasani - Can you check this setting? We are good to merge this after fixing the phpcs waning and moving the CSS to use `astra_dynamic_theme_css` filter. I can get this done and get the PR merged.

2021-03-12 12:18 UTC, pradeep910 commented
I don't see this option somehow. @Divyaraj Masani
***@***.***> please check.

Regards,
Pradeep

On Fri, 12 Mar, 2021, 5:13 pm Nikhil, ***@***.***> wrote:

> @pradeep910 <https://github.com/pradeep910> Can you check if in this PR
> "Allow edits by maintainers" setting is enabled?
> [image: Markup 2021-03-11 at 18 31 01]
> <https://user-images.githubusercontent.com/2931091/110791352-1b530e80-8298-11eb-94a1-9267e5e70304.png>
>
> With this we can add final changes to this PR and get this merged, Right
> now I don;t have permission to add any commits to this PR.
>
> @pradeep910 <https://github.com/pradeep910>, @divyarajmasani
> <https://github.com/divyarajmasani> - Can you check this setting? We are
> good to merge this after fixing the phpcs waning and moving the CSS to use
> astra_dynamic_theme_css filter. I can get this done and get the PR merged.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/brainstormforce/astra/pull/2407#issuecomment-797438323>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIWJDPQ6CQO62MAGHPJPYDTDH45TANCNFSM4YEPKDJQ>
> .
>

2021-03-15 05:54 UTC, Nikschavan commented
That is weird, I am not able to push to this PR as I don't have that permission (this option allows maintainers of the repo to push commits to the PRs)

I have created a separate PR from this one #2488 and will be getting that one merged soon, You can add any feedback if you have there.

2021-03-15 05:54 UTC, closed without merging