refactor: Removing divider controls and updating it with help of css
brainstormforce/astra pull request #2411
Opened 2021-02-25 04:56 UTC by rohitp-bsf

### Description
- Removing divider controls and updating it with help of css

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-02-25 07:34 UTC, vrundakansara commented
Test comment @rohitp-bsf

2021-02-25 07:39 UTC, vrundakansara commented
@rohitp-bsf - Test comment. 👋🏼

2021-02-25 07:40 UTC, vrundakansara commented
@rohitp-bsf - Hello Rohit! 🎉

2021-02-25 07:47 UTC, vrundakansara requested changes

2021-02-25 07:47 UTC, vrundakansara commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
> +					'input_attrs' => array( 'ast_class' => 'ast-bottom-divider' ),
Can we have the following parameters?
```php
'input_attrs' => array(
    'divider-below' => true, // Default true if not passed.
    'divider-above' => false, // Default false if not passed.
    'class' => 'ast-my-exta-class' // This is add a class in the wrapper div, optional.
),
```

I would like to hear your inputs too @premanshup / @imnavanath / @Nikschavan

2021-02-25 07:50 UTC, rohitp-bsf commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
> +					'input_attrs' => array( 'ast_class' => 'ast-bottom-divider' ),
instead of that, we can introduce two classes 'ast-above-divider' & 'ast-below-divder'? 

input_attr is used to pass other values as well so we might need to use like this,

```
'input_attrs' => array(
array(
'divider-below' => true, // Default true if not passed.
    'divider-above' => false, // Default false if not passed.
    'class' => 'ast-my-exta-class' // This is add a class in the wrapper div, optional.
),
// other properties
    
),
```

2021-02-25 07:59 UTC, vrundakansara commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
> +					'input_attrs' => array( 'ast_class' => 'ast-bottom-divider' ),
Right, will this work? I just want to avoid the multi-dimensional array here. Everything at a single level would be easy to access.
```php
'input_attrs' => array(
    'divider' => array( 'below', 'above' ) | array( 'below' ) | array( 'above' ), // To avoid multiple parameters.
    'class' => 'ast-my-exta-class' // This is add a class in the wrapper div, optional.
    'some-more-options' => 'value'
),
```

2021-02-25 08:00 UTC, rohitp-bsf commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
> +					'input_attrs' => array( 'ast_class' => 'ast-bottom-divider' ),
Great! We are on track then just need to update classes. Thanks @vrundakansara

2021-02-25 14:15 UTC, premanshup commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
> +					'input_attrs' => array( 'ast_class' => 'ast-bottom-divider' ),
@vrundakansara Agree!

2021-03-03 09:12 UTC, vrundakansara requested changes
@rohitp-bsf - Let's get rid of these extra prefixes, change
```php
'ast_divider' => array(
    'ast_class' => 'ast-top-divider',
    'ast_title' => __( 'Checkout', 'astra' ),
),
```

to

```php
'divider' => array(
    'classes' => array( 'ast-top-divider' ), // Array of classes.
    'title' => __( 'Checkout', 'astra' ),
),
```

2021-03-03 09:12 UTC, vrundakansara commented on inc/customizer/class-astra-customizer.php
> +				// add_action( 'customize_save_after', array( $this, 'refresh_astra_settings' ) );
If we don't need this action, shall we remove it entirely?

2021-03-03 09:12 UTC, vrundakansara commented on inc/customizer/class-astra-customizer.php
> +		/**
If we don't need this function, shall we remove it entirely?

2021-03-03 09:12 UTC, vrundakansara commented on inc/customizer/class-astra-customizer.php
> -					$default_responsive_spacing = array(
Removing this might cause warnings and notices in the Dynamic CSS files.

2021-03-03 09:15 UTC, vrundakansara commented on inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
> +					'input_attrs' => array( 'ast_class' => 'ast-bottom-divider' ),
Raised one more point [here](https://github.com/brainstormforce/astra/pull/2411#pullrequestreview-602659119).

2021-03-03 13:50 UTC, rohitp-bsf commented on inc/customizer/class-astra-customizer.php
> +				// add_action( 'customize_save_after', array( $this, 'refresh_astra_settings' ) );
Yes! Need to discuss this. WIll remove it from this PR and will add in another. Thank you @vrundakansara

2021-03-03 13:50 UTC, rohitp-bsf commented on inc/customizer/class-astra-customizer.php
> +		/**
Yes! Need to discuss this. WIll remove it from this PR and will add in another. Thank you @vrundakansara

2021-03-03 14:32 UTC, rohitp-bsf commented on inc/customizer/class-astra-customizer.php
> +				// add_action( 'customize_save_after', array( $this, 'refresh_astra_settings' ) );
Removed!

2021-03-03 14:32 UTC, rohitp-bsf commented on inc/customizer/class-astra-customizer.php
> +		/**
Removed!

2021-03-03 14:34 UTC, rohitp-bsf commented on inc/customizer/class-astra-customizer.php
> -					$default_responsive_spacing = array(
This is creating database options as the default value. Maybe @RajkiranBagal is working on this in another task by setting defaults for margin and paddings. So shall we keep this here? or in another PR by @RajkiranBagal ?

2021-03-05 08:47 UTC, vrundakansara commented on inc/customizer/class-astra-customizer.php
> -					$default_responsive_spacing = array(
@rohitp-bsf / @RajkiranBagal  - I think another PR is okay. Let's remove this and add it via other PR so that testing and review becomes easy.

2021-03-12 14:21 UTC, rohitp-bsf commented
> @rohitp-bsf - Let's get rid of these extra prefixes, change
> 
> ```
> 'ast_divider' => array(
>     'ast_class' => 'ast-top-divider',
>     'ast_title' => __( 'Checkout', 'astra' ),
> ),
> ```
> 
> to
> 
> ```
> 'divider' => array(
>     'classes' => array( 'ast-top-divider' ), // Array of classes.
>     'title' => __( 'Checkout', 'astra' ),
> ),
> ```

Resolved! @vrundakansara

2021-03-12 15:26 UTC, vrundakansara requested changes

2021-03-12 15:26 UTC, vrundakansara commented on inc/customizer/extend-custom-controls/src/core/control.js
> +			ast_class = args.params.ast_divider.ast_class;
@rohitp-bsf - Should this be `args.params.divider.ast_class;`?

2021-03-15 04:40 UTC, vrundakansara requested changes

2021-03-15 04:40 UTC, vrundakansara commented on inc/customizer/configurations/builder/footer/class-astra-customizer-copyright-configs.php
> +					'ast_class' => 'ast-bottom-divider',
Will this work in the param? Since we have fetched it like this in the param - 
`ast_class = args.params.ast_divider.ast_class;`

2021-03-15 04:40 UTC, vrundakansara commented on inc/customizer/configurations/builder/header/class-astra-customizer-mobile-trigger-configs.php
> +					'ast_class' => 'ast-bottom-divider',
`ast_class = args.params.ast_divider.ast_class;`
Will this work in the param?

2021-03-15 04:40 UTC, vrundakansara commented on inc/customizer/configurations/builder/header/class-astra-header-account-component-configs.php
> +					'ast_class' => 'ast-bottom-divider',
Have we added this twice? I already see it on the line number 374.

2021-03-15 04:40 UTC, vrundakansara commented on inc/customizer/configurations/builder/header/class-astra-header-menu-component-configs.php
> +							'ast_class' => 'ast-bottom-divider',
`ast_class = args.params.ast_divider.ast_class;`
Will this work in the param?

2021-03-15 04:40 UTC, vrundakansara commented on inc/customizer/configurations/layout/class-astra-site-identity-configs.php
> -					'priority'  => $retina_logo_togglecontrol,
Any reason why we have removed this?

2021-03-15 04:56 UTC, rohitp-bsf commented on inc/customizer/configurations/builder/footer/class-astra-customizer-copyright-configs.php
> +					'ast_class' => 'ast-bottom-divider',
@vrundakansara Thank you for noticing this case. Have removed all possible `ast_class` attr from all input_attrs.

2021-03-15 04:56 UTC, rohitp-bsf commented on inc/customizer/configurations/builder/header/class-astra-header-account-component-configs.php
> +					'ast_class' => 'ast-bottom-divider',
@vrundakansara Thank you for noticing this case. Have removed all possible `ast_class` attr from all input_attrs.

2021-03-15 04:56 UTC, rohitp-bsf commented on inc/customizer/configurations/builder/header/class-astra-customizer-mobile-trigger-configs.php
> +					'ast_class' => 'ast-bottom-divider',
@vrundakansara Thank you for noticing this case. Have removed all possible `ast_class` attr from all input_attrs.

2021-03-15 04:56 UTC, rohitp-bsf commented on inc/customizer/configurations/builder/header/class-astra-header-menu-component-configs.php
> +							'ast_class' => 'ast-bottom-divider',
@vrundakansara Thank you for noticing this case. Have removed all possible `ast_class` attr from all input_attrs.

2021-03-15 04:57 UTC, rohitp-bsf commented on inc/customizer/configurations/layout/class-astra-site-identity-configs.php
> -					'priority'  => $retina_logo_togglecontrol,
Priority has been updated to 4, in merge conflict so kept the updated one.  @vrundakansara

2021-03-15 06:36 UTC, vrundakansara requested changes

2021-03-15 06:36 UTC, vrundakansara commented on inc/customizer/configurations/builder/header/class-astra-header-menu-component-configs.php
> +						'title'    => __( 'SUBMENU', 'astra-addon' ),
Please remove the text domain for the addon.
Also, keep the string as `Submenu`.

2021-03-15 06:40 UTC, rohitp-bsf commented on inc/customizer/configurations/builder/header/class-astra-header-menu-component-configs.php
> +						'title'    => __( 'SUBMENU', 'astra-addon' ),
Resolved! Thanks @vrundakansara

2021-03-15 06:41 UTC, vrundakansara submitted a review, later dismissed

2021-03-16 04:07 UTC, premanshup requested changes

2021-03-16 04:07 UTC, premanshup commented on inc/customizer/configurations/layout/class-astra-header-layout-configs.php
> +							'value'    => array( 'button', 'text-html' ),
@rohitp-bsf Please make sure to add a test case to get this tested.

2021-03-16 04:07 UTC, premanshup commented on inc/customizer/configurations/layout/class-astra-site-identity-configs.php
>  					'control'  => 'ast-divider',
@rohitp-bsf Why are we still keeping `ast-divider` controls?

2021-03-16 04:10 UTC, rohitp-bsf commented on inc/customizer/configurations/layout/class-astra-site-identity-configs.php
>  					'control'  => 'ast-divider',
We can currently add CSS divider for only Astra controls, in the case of WP controls as of now we need to use the divider control. There are only 3 controls left. @premanshup

2021-03-16 04:10 UTC, rohitp-bsf commented on inc/customizer/configurations/layout/class-astra-header-layout-configs.php
> +							'value'    => array( 'button', 'text-html' ),
Yes!

2021-03-16 04:36 UTC, rohitp-bsf commented on inc/customizer/configurations/builder/footer/class-astra-customizer-copyright-configs.php
> +	// No direct access, please.
Done!

2021-03-16 04:36 UTC, rohitp-bsf commented on inc/customizer/configurations/builder/footer/class-astra-customizer-copyright-configs.php
> +	 */
Done!

2021-03-16 04:36 UTC, rohitp-bsf commented on inc/customizer/configurations/builder/footer/class-astra-customizer-copyright-configs.php
> +	 */
Done!

2021-03-16 04:36 UTC, rohitp-bsf commented on inc/customizer/configurations/builder/footer/class-astra-customizer-copyright-configs.php
> +	new Astra_Customizer_Copyright_Configs();
Done!

2021-03-16 04:36 UTC, rohitp-bsf commented on inc/customizer/configurations/builder/header/class-astra-customizer-below-header-configs.php
> +
Done!

2021-03-16 04:45 UTC, premanshup commented on inc/customizer/configurations/layout/class-astra-header-layout-configs.php
> +							'value'    => array( 'button', 'text-html' ),
@rohitp-bsf Thank you!

2021-03-16 04:45 UTC, premanshup commented on inc/customizer/configurations/layout/class-astra-site-identity-configs.php
>  					'control'  => 'ast-divider',
@rohitp-bsf Okay!

2021-03-16 04:46 UTC, premanshup submitted a review, later dismissed

2021-03-16 05:22 UTC, vrundakansara approved these changes

2021-03-17 06:32 UTC, imnavanath commented
@rohitp-bsf getting PHP errors into it - Only free is active in my case.

`[17-Mar-2021 06:29:08 UTC] PHP Notice:  Undefined variable: button_config in C:\laragon\www\wordpress\wp-content\themes\astra\inc\customizer\configurations\builder\base\class-astra-button-component-configs.php on line 423
[17-Mar-2021 06:29:08 UTC] PHP Fatal error:  Uncaught Error: Unsupported operand types in C:\laragon\www\wordpress\wp-content\themes\astra\inc\customizer\configurations\builder\base\class-astra-button-component-configs.php:423
Stack trace:
#0 C:\laragon\www\wordpress\wp-content\themes\astra\inc\customizer\configurations\builder\footer\class-astra-footer-button-component-configs.php(38): Astra_Button_Component_Configs::register_configuration(Array, 'footer', 'section-fb-butt...')
#1 C:\laragon\www\wordpress\wp-includes\class-wp-hook.php(287): Astra_Footer_Button_Component_Configs->register_configuration(Array, Object(WP_Customize_Manager))
#2 C:\laragon\www\wordpress\wp-includes\plugin.php(212): WP_Hook->apply_filters(Array, Array)
#3 C:\laragon\www\wordpress\wp-content\themes\astra\inc\customizer\class-astra-customizer.php(1001): apply_filters('astra_customize...', Array, Object(WP_Customize_Manager))
#4 C:\laragon\www\wordpress\wp-content\themes\astra\inc\customizer\class-astra-customizer.php(821): Astra_Customizer->get_customizer_configurations(Object in C:\laragon\www\wordpress\wp-content\themes\astra\inc\customizer\configurations\builder\base\class-astra-button-component-configs.php on line 423
`

2021-03-17 06:47 UTC, rohitp-bsf commented
> @rohitp-bsf getting PHP errors into it - Only free is active in my case.
> 
> `[17-Mar-2021 06:29:08 UTC] PHP Notice: Undefined variable: button_config in C:\laragon\www\wordpress\wp-content\themes\astra\inc\customizer\configurations\builder\base\class-astra-button-component-configs.php on line 423 [17-Mar-2021 06:29:08 UTC] PHP Fatal error: Uncaught Error: Unsupported operand types in C:\laragon\www\wordpress\wp-content\themes\astra\inc\customizer\configurations\builder\base\class-astra-button-component-configs.php:423 Stack trace: #0 C:\laragon\www\wordpress\wp-content\themes\astra\inc\customizer\configurations\builder\footer\class-astra-footer-button-component-configs.php(38): Astra_Button_Component_Configs::register_configuration(Array, 'footer', 'section-fb-butt...') #1 C:\laragon\www\wordpress\wp-includes\class-wp-hook.php(287): Astra_Footer_Button_Component_Configs->register_configuration(Array, Object(WP_Customize_Manager)) #2 C:\laragon\www\wordpress\wp-includes\plugin.php(212): WP_Hook->apply_filters(Array, Array) #3 C:\laragon\www\wordpress\wp-content\themes\astra\inc\customizer\class-astra-customizer.php(1001): apply_filters('astra_customize...', Array, Object(WP_Customize_Manager)) #4 C:\laragon\www\wordpress\wp-content\themes\astra\inc\customizer\class-astra-customizer.php(821): Astra_Customizer->get_customizer_configurations(Object in C:\laragon\www\wordpress\wp-content\themes\astra\inc\customizer\configurations\builder\base\class-astra-button-component-configs.php on line 423 `

Thanks @imnavanath On it!

2021-03-17 06:55 UTC, vrundakansara approved these changes

2021-03-17 06:56 UTC, rohitp-bsf commented
> button_config

Fixed!

2021-03-17 06:57 UTC, vrundakansara approved these changes

2021-03-17 07:12 UTC, imnavanath commented
> > button_config
> 
> Fixed!

Done @rohitp-bsf Fixed! 👍

2021-03-17 09:42 UTC, vrundakansara approved these changes

2021-03-17 09:47 UTC, premanshup approved these changes

2021-03-17 09:58 UTC, merged