fix: Heading divider added extra top space after builder tabs
brainstormforce/astra pull request #2416
Opened 2021-02-25 13:42 UTC by imnavanath

### Description
- Added input_attrs support to heading config to add custom class
- For now, added this to remove extra top spacing in Account element > Heading comes after builder tabs

### Screenshots
- https://share.getcloudapp.com/P8uk7dWX

### Types of changes
- Non-breaking change

### How has this been tested?
- For now this case (where Heading is available after builder tabs is only) In Account element

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-01 06:38 UTC, vrundakansara requested changes

2021-03-01 06:38 UTC, vrundakansara commented on inc/customizer/configurations/builder/header/class-astra-header-account-component-configs.php
> +					'ast_class' => 'ast-control-reduce-top-space',
@imnavanath - Shall we address this as just `class` instead of `ast_class` since this is our own input attribute for our own control.

2021-03-01 06:45 UTC, imnavanath commented on inc/customizer/configurations/builder/header/class-astra-header-account-component-configs.php
> +					'ast_class' => 'ast-control-reduce-top-space',
Done @vrundakansara 👍

2021-03-01 06:49 UTC, vrundakansara approved these changes

2021-03-02 07:07 UTC, premanshup requested changes

2021-03-02 07:07 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/heading/heading-component.js
> +	astClass = props.control.params.input_attrs.class;
```suggestion
	  astClass = props.control.params.input_attrs.class;
```

2021-03-02 10:41 UTC, merged