refactor: Removed double dividers in customizer & updated priorities wherever necessary in controls
brainstormforce/astra pull request #2420
Opened 2021-02-26 11:39 UTC by imnavanath

### Description
- Avoided double dividers appear consecutively

### Screenshots
- https://a.cl.ly/GGu6JRpx
- https://a.cl.ly/xQunxd5k

### Types of changes
- Non-breaking changes as only dividers are updated

### How has this been tested?
- Test cases as mentioned here - https://trello.com/c/g68tfRK9/1229-remove-double-border-improvement

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-01 06:42 UTC, vrundakansara requested changes

2021-03-01 06:42 UTC, vrundakansara commented on inc/customizer/configurations/layout/class-astra-site-identity-configs.php
> +				$retina_log_divider        = 4;
Should this be `$retina_logo_divider`?

2021-03-01 06:52 UTC, imnavanath commented on inc/customizer/configurations/layout/class-astra-site-identity-configs.php
> +				$retina_log_divider        = 4;
Done @vrundakansara Thanks 👍

2021-03-01 07:17 UTC, vrundakansara approved these changes

2021-03-02 06:52 UTC, premanshup requested changes

2021-03-02 06:52 UTC, premanshup commented on inc/customizer/configurations/layout/class-astra-site-identity-configs.php
> +				$display_title_priority    = 6.5;
@imnavanath Instead of adding priority in decimal can we use single digits? It will get more complicated in the future to check points.

2021-03-02 10:46 UTC, imnavanath commented on inc/customizer/configurations/layout/class-astra-site-identity-configs.php
> +				$display_title_priority    = 6.5;
@premanshup this task is ready and also after updating priorities it will need some testing with old header/new header, addon option dependencies. So I've added another task for this in P1 board - https://trello.com/c/gR75lKoL/604-site-identitys-customizer-controls-priorities-should-not-be-in-decimal

Is it okay??

2021-03-02 10:49 UTC, premanshup commented on inc/customizer/configurations/layout/class-astra-site-identity-configs.php
> +				$display_title_priority    = 6.5;
@imnavanath Yes, sounds good.

2021-03-02 10:49 UTC, premanshup approved these changes

2021-03-02 10:51 UTC, merged