fix: Sonarlint attribute missing in element issue
brainstormforce/astra pull request #2428
Opened 2021-02-26 13:23 UTC by abhishek-bsf

### Description

Fixed SonarLint issues related to missing attribute in HTML elements

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-02-26 15:00 UTC, Nikschavan approved these changes

2021-03-01 07:01 UTC, vrundakansara requested changes

2021-03-01 07:01 UTC, vrundakansara commented on inc/core/class-astra-admin-settings.php
> +				<img class="ast-starter-sites-img" alt="Astra Starter Sites" src="<?php echo esc_url( ASTRA_THEME_URI . 'assets/images/astra-starter-sites.jpg' ); ?>">
Let's rename this to "Starter Templates".

2021-03-02 07:26 UTC, abhishek-bsf commented on inc/core/class-astra-admin-settings.php
> +				<img class="ast-starter-sites-img" alt="Astra Starter Sites" src="<?php echo esc_url( ASTRA_THEME_URI . 'assets/images/astra-starter-sites.jpg' ); ?>">
Renamed it to 'Starter Templates'.

2021-03-02 10:59 UTC, vrundakansara approved these changes

2021-03-03 14:42 UTC, merged