fix: SonarLint strict operator condition check fix
brainstormforce/astra pull request #2430
Opened 2021-02-26 13:29 UTC by abhishek-bsf

### Description

Fixed SonarLint issues related to strict operator checking in conditional statements

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-02-26 15:03 UTC, Nikschavan approved these changes

2021-02-26 15:11 UTC, Nikschavan commented
@abhishek-bsf For all the functions in the if conditions like `anchors_in_css_selectors_heading()` or `astra_get_option()` etc make sure for each and every case in detail that the values returned for that particular cases are indeed boolean.

2021-03-01 07:04 UTC, vrundakansara requested changes

2021-03-01 07:04 UTC, vrundakansara commented on inc/compatibility/class-astra-beaver-builder.php
> +			if ( false === astra_enable_page_builder_compatibility() || 'post' == get_post_type() ) {
@abhishek-bsf - Do you think we need to strict-check here too?
`'post' === get_post_type()`

2021-03-01 07:04 UTC, vrundakansara commented on inc/compatibility/class-astra-elementor.php
> +			if ( false === astra_enable_page_builder_compatibility() || 'post' == get_post_type() ) {
@abhishek-bsf - Do you think we need to strict-check here too?
'post' === get_post_type()

2021-03-01 07:04 UTC, vrundakansara commented on inc/compatibility/class-astra-visual-composer.php
> +			if ( false === astra_enable_page_builder_compatibility() || 'post' == get_post_type() ) {
@abhishek-bsf - Do you think we need to strict-check here too?
'post' === get_post_type()

2021-03-01 08:26 UTC, abhishek-bsf commented on inc/compatibility/class-astra-beaver-builder.php
> +			if ( false === astra_enable_page_builder_compatibility() || 'post' == get_post_type() ) {
We can add strict-check here also, but in this PR we are fixing error that are reported in SonarLint only. And SonarLint returns error only for `Boolean` checks.

2021-03-01 08:26 UTC, abhishek-bsf commented on inc/compatibility/class-astra-elementor.php
> +			if ( false === astra_enable_page_builder_compatibility() || 'post' == get_post_type() ) {
We can add strict-check here also, but in this PR we are fixing error that are reported in SonarLint only. And SonarLint returns error only for `Boolean` checks.

2021-03-01 08:26 UTC, abhishek-bsf commented on inc/compatibility/class-astra-visual-composer.php
> +			if ( false === astra_enable_page_builder_compatibility() || 'post' == get_post_type() ) {
We can add strict-check here also, but in this PR we are fixing error that are reported in SonarLint only. And SonarLint returns error only for `Boolean` checks.

2021-03-01 08:33 UTC, vrundakansara commented on inc/compatibility/class-astra-elementor.php
> +			if ( false === astra_enable_page_builder_compatibility() || 'post' == get_post_type() ) {
Alright, let's keep it as it is then.

2021-03-01 08:33 UTC, vrundakansara approved these changes

2021-03-03 14:43 UTC, merged