fix: Sonarlint unused function parameter issue
brainstormforce/astra pull request #2431
Opened 2021-02-26 13:32 UTC by abhishek-bsf

### Description

Fixed SonarLint issue related to unused parameters passed to function

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-02-26 15:25 UTC, Nikschavan requested changes
Can you check loading the customizer as well as test the theme with Astra Pro once? I am seeing a few fatal errors.

2021-02-26 15:25 UTC, Nikschavan commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> -		public function customize_register( $wp_customize ) {
I believe this will be required in all the customize_register methods, For eg try loading the customizer and you will see a fatal error.

2021-03-01 07:09 UTC, vrundakansara requested changes

2021-03-01 07:09 UTC, vrundakansara commented on inc/compatibility/class-astra-beaver-themer.php
> +		public function builder_before_render_content() {
Do you think we will need to check the backward compatibility here?
Please check once with Custom Layouts from Astra Addon.
I think this action hook is used and might cause a problem if we remove the `$post_id`.

2021-03-01 07:09 UTC, vrundakansara commented on inc/compatibility/class-astra-beaver-themer.php
> +		public function builder_after_render_content() {
Do you think we will need to check the backward compatibility here?
Please check once with Custom Layouts from Astra Addon.
I think this action hook is used and might cause a problem if we remove the `$post_id`.

2021-03-01 07:09 UTC, vrundakansara commented on inc/builder/type/header/search/class-astra-header-search-component-loader.php
> -	public static function get_search_markup( $search_markup, $option = '', $device = '' ) {
I think the later 2 parameters to this function are required.
Can you please verify with adding the Search element in the Mobile layout once?
@RajkiranBagal - Can you confirm once, please?

2021-03-01 08:12 UTC, abhishek-bsf commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> -		public function customize_register( $wp_customize ) {
I have added back `$wp_customize` parameter to the functions.

2021-03-01 08:14 UTC, abhishek-bsf commented on inc/compatibility/class-astra-beaver-themer.php
> +		public function builder_before_render_content() {
This function is called on the hook of Beaver Builder. I check that hook in Beaver Builder docs and added back `$post_id` parameter to the function.

2021-03-01 08:15 UTC, abhishek-bsf commented on inc/compatibility/class-astra-beaver-themer.php
> +		public function builder_after_render_content() {
This function is called on the hook of Beaver Builder. I check that hook in Beaver Builder docs and added back `$post_id` parameter to the function.

2021-03-02 05:12 UTC, RajkiranBagal commented on inc/builder/type/header/search/class-astra-header-search-component-loader.php
> -	public static function get_search_markup( $search_markup, $option = '', $device = '' ) {
@abhishek-bsf  Yes we need them.

2021-03-02 05:37 UTC, abhishek-bsf commented on inc/builder/type/header/search/class-astra-header-search-component-loader.php
> -	public static function get_search_markup( $search_markup, $option = '', $device = '' ) {
Added back parameters to the function.

2021-03-02 13:38 UTC, Nikschavan requested changes

2021-03-02 13:38 UTC, Nikschavan commented on inc/class-astra-after-setup-theme.php
> +		public function responsive_oembed_wrapper( $html, $url ) {
Let's also remove the number of parameters we are expecting to match the updated parameters - 

https://github.com/brainstormforce/astra/blob/208f3d833ec85be774f9ec737d0479c2c45e8bf2/inc/class-astra-after-setup-theme.php#L159

2021-03-02 13:38 UTC, Nikschavan commented on inc/customizer/class-astra-customizer.php
> +		public static function logo_image_sizes( $sizes ) {
Let's change the number of parameters we are expecting from here - 

https://github.com/brainstormforce/astra/blob/208f3d833ec85be774f9ec737d0479c2c45e8bf2/inc/customizer/class-astra-customizer.php#L1355

Also, do test if this functionality is working (The `add_filter` and `remove_filter` functionality)

2021-03-02 13:38 UTC, Nikschavan commented on inc/markup-extras.php
> +	function astra_replace_header_attr( $attr, $attachment ) {
Let's remove the expected number of attributes from the filter - 

https://github.com/brainstormforce/astra/blob/208f3d833ec85be774f9ec737d0479c2c45e8bf2/inc/markup-extras.php#L1522

2021-03-02 14:13 UTC, vrundakansara commented
@abhishek-bsf - In my opinion, most of the removed parameters will cause an issue for backward compatibility. Especially, when the function is a callback for filter or so.
Let me know what you think here @Nikschavan / @premanshup / @rohitp-bsf.

2021-03-02 14:13 UTC, vrundakansara requested changes

2021-03-02 14:13 UTC, vrundakansara commented on inc/class-astra-mobile-header.php
> +		public function astra_mobile_header_custom_logo( $html ) {
This will create issues for backward compatibility. Ex: If any user has used this filter.

2021-05-08 02:25 UTC, closed without merging