refactor: Improving Code level as per PR comments for condition checks, var declarations, regex comments
brainstormforce/astra pull request #2434
Opened 2021-02-27 10:15 UTC by imnavanath

### Description
- Direct `Astra_Builder_Helper::$is_header_footer_builder_active` conditions avoided and used with strict bool checks `true === Astra_Builder_Helper::$is_header_footer_builder_active`
- Removed possible else part of conditions where variables are declared
- Set those variables before `if` condition and if condition met then only updated in conditional part
- Updated valid variable names & removed all `temp` variable strings from vars
- Added regex comments in overall JS scripts

### Types of changes
- Code level changes
- Non-breaking

### How has this been tested?
- With builder customizer (for JS errors if trigger any)
- With all components used in Builder layout

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-01 07:40 UTC, vrundakansara approved these changes

2021-03-04 07:16 UTC, premanshup requested changes

2021-03-04 07:16 UTC, premanshup commented on inc/core/class-astra-enqueue-scripts.php
> +
```suggestion

```

2021-03-04 07:16 UTC, premanshup commented on inc/core/class-astra-enqueue-scripts.php
> +
```suggestion

```

2021-03-04 07:16 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/builder-layout/builder-component.js
> +		let customizerBuilderchoices = (AstraBuilderCustomizerData && AstraBuilderCustomizerData.choices && AstraBuilderCustomizerData.choices[controlParams.group] ? AstraBuilderCustomizerData.choices[cont
Can be `const`

2021-03-04 07:16 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/builder-layout/drop-component.js
> +		let sortList = [...currentList];
Can be `const`

2021-03-04 07:16 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/builder-layout/item-component.js
>  				component_track[ forceRemoveSection.builder + '-' + forceRemoveSection.type ] = existing_component_count;
should be `camelCase`

2021-03-04 07:16 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/customizer.js
> +				clone_from_id = clone_from_id.replace(/[0-9]+/g, is_cloning_index); // Replace random numeric with valid clone index.
should be `camelCase`

2021-03-05 04:50 UTC, imnavanath commented on inc/core/class-astra-enqueue-scripts.php
> +
Done 👍

2021-03-05 04:50 UTC, imnavanath commented on inc/core/class-astra-enqueue-scripts.php
> +
Done 👍

2021-03-05 04:51 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/builder-layout/builder-component.js
> +		let customizerBuilderchoices = (AstraBuilderCustomizerData && AstraBuilderCustomizerData.choices && AstraBuilderCustomizerData.choices[controlParams.group] ? AstraBuilderCustomizerData.choices[cont
Done 👍

2021-03-05 04:51 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/builder-layout/drop-component.js
> +		let sortList = [...currentList];
Done 👍

2021-03-05 04:51 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/builder-layout/item-component.js
>  				component_track[ forceRemoveSection.builder + '-' + forceRemoveSection.type ] = existing_component_count;
Done 👍

2021-03-05 04:51 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/customizer.js
> +				clone_from_id = clone_from_id.replace(/[0-9]+/g, is_cloning_index); // Replace random numeric with valid clone index.
Done 👍

2021-03-05 07:28 UTC, rohitp-bsf requested changes

2021-03-05 07:28 UTC, rohitp-bsf commented on inc/customizer/configurations/layout/class-astra-site-identity-configs.php
> +				array(
This config needs to be removed! if merged later on.

2021-03-05 09:10 UTC, imnavanath commented on inc/customizer/configurations/layout/class-astra-site-identity-configs.php
> +				array(
@rohitp-bsf I think this position is valid one for divider - https://a.cl.ly/xQunJEkA
Why this should be removed?

2021-03-08 05:31 UTC, rohitp-bsf commented on inc/customizer/configurations/layout/class-astra-site-identity-configs.php
> +				array(
In another task, we have moved dividers into CSS-based configs. Nevermind will merge and update it in final PR.

2021-03-08 05:32 UTC, rohitp-bsf approved these changes

2021-03-08 05:46 UTC, premanshup approved these changes

2021-03-11 11:58 UTC, merged