refactor: Added components are unused saying message in builder panel when builder layout is empty
brainstormforce/astra pull request #2436
Opened 2021-03-01 05:38 UTC by imnavanath

### Description
- Added message when none of the component not used in builder layout

### Screenshots
- https://a.cl.ly/9Zu8yx4Q

### Types of changes
- Non-breaking changes
- Removed extra unwanted code
- Then conditionally loaded span for this message

### How has this been tested?
- With blank builder ;layout as per above screenshot

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-01 07:27 UTC, vrundakansara requested changes

2021-03-01 07:27 UTC, vrundakansara commented on inc/assets/css/ast-builder-customizer.css
> +.ahfb-available-items-pool- .ahfb-all-coponents-unused  {
I think we must rename this class `ahfb-available-items-pool-`.

2021-03-01 07:27 UTC, vrundakansara commented on inc/customizer/extend-custom-controls/src/draggable/draggable-component.js
> +				<span className="ahfb-all-coponents-unused"> {__('Components Being Used in Builder will Visible Here.', 'astra')} </span>
`Elements used in the builder will be visible here.`
Let's reframe the message too.

2021-03-01 07:27 UTC, vrundakansara commented on inc/customizer/extend-custom-controls/src/draggable/draggable-component.js
> +				<span className="ahfb-all-coponents-unused"> {__('Components Being Used in Builder will Visible Here.', 'astra')} </span>
Do you think we must remove the `ahfb` prefix altogether?

2021-03-01 10:38 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/draggable/draggable-component.js
> +				<span className="ahfb-all-coponents-unused"> {__('Components Being Used in Builder will Visible Here.', 'astra')} </span>
Replaced with - `ast-builder-elements-notice`

2021-03-01 10:39 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/draggable/draggable-component.js
> +				<span className="ahfb-all-coponents-unused"> {__('Components Being Used in Builder will Visible Here.', 'astra')} </span>
Done 👍

2021-03-01 10:43 UTC, imnavanath commented on inc/assets/css/ast-builder-customizer.css
> +.ahfb-available-items-pool- .ahfb-all-coponents-unused  {
Updated with - `ast-builder-elements-section`

2021-03-01 11:05 UTC, vrundakansara commented on inc/customizer/extend-custom-controls/src/draggable/draggable-component.js
> +				<span className="ahfb-all-coponents-unused"> {__('Components Being Used in Builder will Visible Here.', 'astra')} </span>
@imnavanath - Let's not capitalize all the words. Keep it `Elements used in the builder will be visible here.`.

2021-03-01 11:20 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/draggable/draggable-component.js
> +				<span className="ahfb-all-coponents-unused"> {__('Components Being Used in Builder will Visible Here.', 'astra')} </span>
Corrected 👍

2021-03-01 11:25 UTC, vrundakansara approved these changes

2021-03-03 05:46 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/draggable/draggable-component.js
> -			</ReactSortable>}
@imnavanath Can you please explain why are we removing this? I think using `droppedCount` only we can check the number of dropped elements and add the message?

2021-03-03 09:18 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/draggable/draggable-component.js
> -			</ReactSortable>}
This code is not required, this one is extra piece of code.
You can see here - https://github.com/brainstormforce/astra/pull/2436/files/a7200d3a2be92a4e73e602865a26ad90350a0fcc#diff-d7139873fc188a4eea4038ebfe85db88b5d95f8b8fa4857cf49d5ec5c41fc533R88 we just called 'links' builder components,  for 'available' we don't need. Previously it was for to showcase remaining components in builder panel. But now, it's not required.

2021-03-04 07:26 UTC, premanshup approved these changes

2021-03-05 05:00 UTC, merged