feat: Added new Woo+EDD cart icon colors for Transparent header
brainstormforce/astra pull request #2437
Opened 2021-03-01 10:21 UTC by imnavanath

### Description
- https://trello.com/c/R37EmJtK/262-transparent-header-cart-creating-issue
- Added new color options for Woo & EDD cart icons (in Transparent Header)

### Screenshots
- https://a.cl.ly/BluYzoLG

### Types of changes
- New option introducing
- Dynamic CSS, JS preview changes

### How has this been tested?
- With Woo/EDD cart components + Transparent Header

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-01 11:35 UTC, vrundakansara requested changes
@imnavanath - Please have a look at these feedback.

2021-03-01 11:35 UTC, vrundakansara commented on inc/builder/type/header/edd-cart/assets/js/customizer-preview.js
> +			wp.customize.preview.send( 'refresh' );
Since we have already added customizer preview JS [here](https://github.com/brainstormforce/astra/pull/2437/files#diff-876b67d453e01e27819be659b96ca4cc0957886e1a0a99183189fc720abbbe05R32-R43) for this option, do we still need this refresh call?

2021-03-01 11:35 UTC, vrundakansara commented on inc/builder/type/header/woo-cart/assets/js/customizer-preview.js
> +		'border-color',
Should this be a background color?

2021-03-01 11:35 UTC, vrundakansara commented on inc/builder/type/header/woo-cart/assets/js/customizer-preview.js
> +	wp.customize( 'astra-settings[transparent-header-woo-cart-icon-color]', function( setting ) {
Do we still need this code if we have [this](https://github.com/brainstormforce/astra/pull/2437/files#diff-be4e3ea9bd09cb9db15922bc0ebb1c4920a31f29102c03074610970bd49e1fdbR46-R57) code?

2021-03-01 11:35 UTC, vrundakansara commented on inc/core/builder/class-astra-builder-options.php
> +	$defaults['transparent-header-woo-cart-icon-color'] = '';
Should we add a similar default one for EDD too?

2021-03-01 11:35 UTC, vrundakansara commented on inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
> +			array(
Let's add these options from Transparent Header files, instead of Woo/EDD files. This is because these settings will be unnecessarily visible when the transparent header is off.

2021-03-01 11:35 UTC, vrundakansara commented on inc/customizer/configurations/builder/header/class-astra-customizer-edd-cart-configs.php
> +			array(
Let's add these options from Transparent Header files, instead of Woo/EDD files. This is because these settings will be unnecessarily visible when the transparent header is off.

2021-03-01 11:49 UTC, imnavanath commented on inc/builder/type/header/edd-cart/assets/js/customizer-preview.js
> +			wp.customize.preview.send( 'refresh' );
Yes it's necessary because on the basis of this color option, we calculate it's foreground color (through PHP) which required for count as well as for text (if its Fill type) for ex - https://a.cl.ly/mXu1Gx0z

2021-03-01 11:51 UTC, imnavanath commented on inc/builder/type/header/woo-cart/assets/js/customizer-preview.js
> +		'border-color',
Border color is correct one, as this required here - https://a.cl.ly/wbu9LQjb

2021-03-01 11:58 UTC, imnavanath commented on inc/builder/type/header/woo-cart/assets/js/customizer-preview.js
> +	wp.customize( 'astra-settings[transparent-header-woo-cart-icon-color]', function( setting ) {
`background-color:` CSS is valid here, but yes border-color one is repetitive. So removed now.

2021-03-01 12:00 UTC, imnavanath commented on inc/core/builder/class-astra-builder-options.php
> +	$defaults['transparent-header-woo-cart-icon-color'] = '';
Thanks, I missed that one. Added 👍

2021-03-01 12:21 UTC, imnavanath commented on inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
> +			array(
Done 👍

2021-03-01 12:21 UTC, imnavanath commented on inc/customizer/configurations/builder/header/class-astra-customizer-edd-cart-configs.php
> +			array(
Done 👍

2021-03-01 13:42 UTC, vrundakansara requested changes

2021-03-01 13:42 UTC, vrundakansara commented on inc/builder/type/header/edd-cart/assets/js/customizer-preview.js
> +	wp.customize( 'astra-settings[transparent-header-edd-cart-icon-color]', function( setting ) {
Let's move this customizer preview CSS to transparent header files and not in individual Woo/EDD files.

2021-03-01 13:42 UTC, vrundakansara commented on inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php
> +	$selector                   = '.ast-edd-site-header-cart';
Let's move this customizer preview CSS to transparent header files and not in individual Woo/EDD files.

2021-03-01 13:42 UTC, vrundakansara commented on inc/builder/type/header/woo-cart/assets/js/customizer-preview.js
> +	// Transparent Header - Icon Color.
Let's move this customizer preview CSS to transparent header files and not in individual Woo/EDD files.

2021-03-02 06:15 UTC, imnavanath commented on inc/builder/type/header/woo-cart/assets/js/customizer-preview.js
> +	// Transparent Header - Icon Color.
Moved this JS code in transparent header preview JS.

2021-03-02 06:15 UTC, imnavanath commented on inc/builder/type/header/edd-cart/assets/js/customizer-preview.js
> +	wp.customize( 'astra-settings[transparent-header-edd-cart-icon-color]', function( setting ) {
Moved this JS code in transparent header preview JS.

2021-03-02 07:28 UTC, premanshup commented on inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php
> +	$selector                   = '.ast-edd-site-header-cart';
@vrundakansara I think it will be better to keep EDD or Woo related customizer preview in their respective files because I think we do not load these files unless EDD or Woo are installed on users' sites. If we keep these in a transparent header then this will run despite of these plugins active or not on users website. Please let me know your thoughts on this.

2021-03-02 07:36 UTC, imnavanath commented on inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php
> +	$selector                   = '.ast-edd-site-header-cart';
Customizer preview JS code is moved into transparent header JS file.  Shall I revert or okay for now?

2021-03-02 13:01 UTC, premanshup requested changes

2021-03-02 13:01 UTC, premanshup commented on inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php
> +	$selector                   = '.ast-edd-site-header-cart';
@vrundakansara Can you please confirm?

2021-03-02 13:17 UTC, vrundakansara commented on inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php
> +	$selector                   = '.ast-edd-site-header-cart';
I think @premanshup has a valid point here. The call is yours @imnavanath 
Either of the changes is okay with me.

2021-03-03 10:04 UTC, imnavanath commented on inc/addons/transparent-header/assets/js/unminified/customizer-preview.js
> +	});
Done for both Woo & EDD customizer preview JS @premanshup 👍

2021-03-03 10:11 UTC, imnavanath commented
> @imnavanath - Please have a look at these feedback.

Everything is done @vrundakansara

2021-03-03 10:17 UTC, vrundakansara approved these changes

2021-03-03 13:02 UTC, premanshup approved these changes

2021-03-08 05:08 UTC, vrundakansara requested changes

2021-03-08 05:08 UTC, vrundakansara commented on changelog.txt
> +- New: Builder - WooCommerce Cart & EDD Cart - Transparent header icon color options.
I think this would be -
`- New: Transparent Header - WooCommerce Cart & EDD Cart icon color options.`

2021-03-08 05:10 UTC, imnavanath commented on changelog.txt
> +- New: Builder - WooCommerce Cart & EDD Cart - Transparent header icon color options.
Done 👍

2021-03-08 05:13 UTC, vrundakansara approved these changes

2021-03-08 05:13 UTC, merged