feat: Single header layout across the site.
brainstormforce/astra pull request #2442
Opened 2021-03-03 12:20 UTC by RajkiranBagal

### Description
- Trello task - https://trello.com/c/M6Hkd2wG/259-single-header-layout-across-the-site

### Types of changes
New feature (non-breaking change which adds functionality)

### How has this been tested?
 - Test cases mentioned in the task.

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-03-15 13:32 UTC, rohitp-bsf requested changes

2021-03-15 13:32 UTC, rohitp-bsf commented on inc/builder/markup/class-astra-builder-header.php
> +			foreach ( $default_header_mobile_items as $row_name => $row_contents ) {
Can't we compare the array identical with `===` operator? instead array loop?

2021-03-15 13:32 UTC, rohitp-bsf commented on inc/builder/markup/class-astra-builder-header.php
> +			$is_mobile_header_layout_default = true;
Add a static variable to check default instead of always calculating it?

2021-03-15 13:35 UTC, RajkiranBagal commented on inc/builder/markup/class-astra-builder-header.php
> +			foreach ( $default_header_mobile_items as $row_name => $row_contents ) {
No, we can't compare directly because we only need to compare those keys with Row names, There are also other keys that do not compare.

2021-03-16 05:29 UTC, RajkiranBagal commented on inc/builder/markup/class-astra-builder-header.php
> +			$is_mobile_header_layout_default = true;
Done.

2021-03-16 07:56 UTC, rohitp-bsf requested changes

2021-03-16 07:56 UTC, rohitp-bsf commented on inc/builder/markup/class-astra-builder-header.php
> +			foreach ( $default_header_mobile_items as $row_name => $row_contents ) {
Ok, Can you try this once?

`public static function is_mobile_header_layout_default() {

			$mobile_header_type = astra_get_option( 'mobile-header-type' );

			if ( 'off-canvas' === $mobile_header_type || 'full-width' === $mobile_header_type ) {
				return false;
			}

			$header_mobile_items = astra_get_option( 'header-mobile-items' );
			$default_header_mobile_items = array(
				'popup'   => array( 'popup_content' => array() ),
				'above'   =>
					array(
						'above_left'   => array(),
						'above_center' => array(),
						'above_right'  => array(),
					),
				'primary' =>
					array(
						'primary_left'   => array( 'logo' ),
						'primary_center' => array(),
						'primary_right'  => array( 'mobile-trigger' ),
					),
				'below'   =>
					array(
						'below_left'   => array(),
						'below_center' => array(),
						'below_right'  => array(),
					),
			);

			return ( 0 === strcmp( wp_json_encode( $default_header_mobile_items + $header_mobile_items ),
				wp_json_encode( $header_mobile_items ) ) );

		}`

2021-03-16 08:29 UTC, RajkiranBagal commented on inc/builder/markup/class-astra-builder-header.php
> +			$is_mobile_header_layout_default = true;
@rohitp-bsf  Needed to remove this change, because it was not updating when partial refresh occur.

2021-03-16 09:09 UTC, RajkiranBagal commented on inc/builder/markup/class-astra-builder-header.php
> +			foreach ( $default_header_mobile_items as $row_name => $row_contents ) {
Done. Thankyou!

2021-03-16 13:11 UTC, rohitp-bsf approved these changes

2021-03-16 13:12 UTC, vrundakansara submitted a review, later dismissed

2021-05-23 02:44 UTC, closed without merging