fix: Page load bloacking for the customizer load
brainstormforce/astra pull request #2453
Opened 2021-03-05 12:23 UTC by rohitp-bsf

### Description
fix: Page load bloacking for the customizer load

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-03-08 07:28 UTC, vrundakansara approved these changes

2021-03-09 16:01 UTC, premanshup requested changes

2021-03-09 16:01 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/customizer.js
> +					}inc/customizer/override-defaults.php
@rohitp-bsf `}inc/customizer/override-defaults.php` please check if the comment is mixed with the comment?

2021-03-11 08:25 UTC, rohitp-bsf commented
Advanced PR: https://github.com/brainstormforce/astra/pull/2474/files

2021-03-11 08:25 UTC, closed without merging