refactor: Added 2px border support for outline GB buttons in all cases
brainstormforce/astra pull request #2454
Opened 2021-03-06 05:28 UTC by imnavanath

### Description
- As per requirement 2px border will apply to all outline GB buttons

### Types of changes
- Dynamic CSS changes for outline buttons adjusting border size

### How has this been tested?
- Test this with Customizer > Global > Buttons - Border width
- Check with empty border size (in this case border should be 2px for outline GB buttons)
- Check with '0' border size (in this case border should be 2px for outline GB buttons)
- Check with 'x' number border size (in this case border should be 'x' px for outline GB buttons)

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-08 04:45 UTC, vrundakansara requested changes

2021-03-08 04:45 UTC, vrundakansara commented on assets/js/unminified/customizer-preview.js
> +					wp.customize.preview.send( 'refresh' );
Do you think we should add some notes to the customizer? This is because the user will get confused about why his borders won't apply?
@premanshup - Your thoughts here?

2021-03-08 09:24 UTC, imnavanath commented on assets/js/unminified/customizer-preview.js
> +					wp.customize.preview.send( 'refresh' );
Borders will apply here, but in this pattern compatibility update we managed border & padding by some calculations, these will be bit tricky in preview JS that's why added here by refreshing preview.
@premanshup ☝️

2021-03-08 10:07 UTC, premanshup commented on assets/js/unminified/customizer-preview.js
> +					wp.customize.preview.send( 'refresh' );
@vrundakansara as @imnavanath has mentioned that the borders will apply then we can skip the notice I think.

2021-03-08 12:00 UTC, vrundakansara approved these changes

2021-03-09 12:13 UTC, rohitp-bsf approved these changes

2021-03-09 15:47 UTC, premanshup approved these changes

2021-03-10 05:15 UTC, merged