fix: Fatal error due to undeclared static color_group_configs var
brainstormforce/astra pull request #2455
Opened 2021-03-06 06:03 UTC by imnavanath

### Description
- Fatal error caused due to undeclared static color_group_configs var
- Removed this code as it's not needed
- Control / sub-control relationship managed via customizer.js only

### Screenshots
- https://a.cl.ly/wbu9Ob5l

### Types of changes
- Non breaking change
- Removed extra unwanted code

### How has this been tested?
- With color group control in customizer
- Check whether all color-group controls are working properly

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-06 06:35 UTC, rohitp-bsf approved these changes

2021-03-06 06:35 UTC, rohitp-bsf commented on inc/customizer/class-astra-customizer.php
> -				case 'ast-color-group':
Do we need this control? `class-astra-control-color-group.php` same static property is used inside that? Please check @imnavanath

2021-03-06 06:49 UTC, imnavanath commented on inc/customizer/class-astra-customizer.php
> -				case 'ast-color-group':
Right, the file is also not needed. So removed this class control file.

2021-03-08 07:29 UTC, vrundakansara requested changes

2021-03-08 07:29 UTC, vrundakansara commented on changelog.txt
> +- Fix: Fatal error due to undeclated static property Astra_Customizer::$color_group_configs.
`- Fix: Fatal error due to undeclared static property Astra_Customizer::$color_group_configs.`

2021-03-08 07:38 UTC, imnavanath commented on changelog.txt
> +- Fix: Fatal error due to undeclated static property Astra_Customizer::$color_group_configs.
Done thanks 👍

2021-03-08 07:39 UTC, vrundakansara approved these changes

2021-03-08 10:46 UTC, merged