refactor: Removed default database options and added as plain default.
brainstormforce/astra pull request #2456
Opened 2021-03-06 12:27 UTC by rohitp-bsf

### Description
refactor: Removed default database options and added as plain default.

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-03-11 12:58 UTC, vrundakansara approved these changes

2021-03-12 06:41 UTC, premanshup requested changes

2021-03-12 06:41 UTC, premanshup commented on inc/core/builder/class-astra-builder-options.php
> +		'header-mobile-menu-submenu-spacing',
@rohitp-bsf This setting is defined in the addon. Can you please check all the defaults which have settings added in addon should be moved to the addon?

2021-03-12 09:52 UTC, rohitp-bsf commented on inc/core/builder/class-astra-builder-options.php
> +		'header-mobile-menu-submenu-spacing',
Resolved: Added a PR for addon: https://git.brainstormforce.com/bsf-store-products/astra/astra-addon/-/merge_requests/2147

2021-03-12 10:01 UTC, premanshup commented on inc/core/builder/class-astra-builder-options.php
> +		'header-mobile-menu-submenu-spacing',
@rohitp-bsf Thank you!

2021-03-12 10:02 UTC, premanshup requested changes

2021-03-12 10:02 UTC, premanshup commented on inc/core/builder/class-astra-builder-options.php
> +		'header-menu2-megamenu-heading-space',
@rohitp-bsf Can you please remove them from here since they are already added in the addon?

2021-03-12 10:04 UTC, rohitp-bsf commented on inc/core/builder/class-astra-builder-options.php
> +		'header-menu2-megamenu-heading-space',
Yes, @premanshup removed!

2021-03-12 10:06 UTC, premanshup approved these changes

2021-03-15 12:54 UTC, merged