fix: code editor block sticks left align without spacings
brainstormforce/astra pull request #2459
Opened 2021-03-08 07:30 UTC by imnavanath

### Description
- Code editor block sticks to left align in editor 

### Screenshots
- Editor - https://share.getcloudapp.com/4gu1RXxY
- Frontend - https://share.getcloudapp.com/Jru1meb7

### Types of changes
- Non-breaking changes
- Editor code bloc change

### How has this been tested?
- By taking code block in editor
- Check screenshot for reference

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-08 07:38 UTC, vrundakansara requested changes

2021-03-08 07:38 UTC, vrundakansara commented on changelog.txt
> +- Fix: Gutenberg Editor - Code Block sticks to left align without spacing.
`- Fix: Block Editor - Code Block spacing CSS tweaks when it is left aligned .`

2021-03-08 07:41 UTC, imnavanath commented on changelog.txt
> +- Fix: Gutenberg Editor - Code Block sticks to left align without spacing.
Done thanks 👍

2021-03-08 07:42 UTC, vrundakansara approved these changes

2021-03-08 13:54 UTC, rohitp-bsf approved these changes

2021-03-09 12:11 UTC, rohitp-bsf approved these changes

2021-03-09 15:26 UTC, premanshup approved these changes

2021-03-10 05:15 UTC, merged