feat: Introduced new filter for updating Shopping Cart text in mobile flyout for Woo & EDD cart
brainstormforce/astra pull request #2467
Opened 2021-03-09 04:04 UTC by imnavanath

### Description
- As per user's support request we are introducing new filter which will help to update static "Shopping Cart" text in flyout 

### Screenshots
- https://a.cl.ly/jkue0OWm
- With using filter - https://a.cl.ly/qGuX8Gjm

### Types of changes
- Non-breaking change

### How has this been tested?
- Steps to replicate - https://a.cl.ly/jkue0O87
- `add_filter( 'ast_header_cart_flyout_shopping_cart_text', function() {
	return 'My Shop Flyout Cart';
} );`

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-09 15:29 UTC, premanshup requested changes

2021-03-09 15:29 UTC, premanshup commented on inc/builder/controllers/class-astra-builder-ui-controller.php
> +						echo apply_filters( 'ast_header_cart_flyout_shopping_cart_text', __( 'Shopping Cart', 'astra' ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
`ast_header_cart_flyout_shopping_cart_text` - @imnavanath This should be `astra_`

2021-03-10 04:14 UTC, imnavanath commented on inc/builder/controllers/class-astra-builder-ui-controller.php
> +						echo apply_filters( 'ast_header_cart_flyout_shopping_cart_text', __( 'Shopping Cart', 'astra' ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
Updated with prefix - `astra`

2021-03-10 05:01 UTC, premanshup approved these changes

2021-03-10 13:06 UTC, vrundakansara approved these changes

2021-03-31 05:56 UTC, rohitp-bsf approved these changes

2021-05-24 12:33 UTC, premanshup commented on changelog.txt
> +- Improvement: Builder - WooCommerce Cart & EDD Cart - Filter to change "Shopping Cart" text in responsive flyout.
```suggestion
- Improvement: Builder - WooCommerce Cart & EDD Cart - Filter to change "Shopping Cart" text in responsive flyout. ( Need Doc )
```

2021-05-24 12:34 UTC, premanshup commented on changelog.txt
> +- Improvement: Added site title & tagline color options from Astra Pro to free theme.
```suggestion
- Improvement: Added Site Title & Tagline color options from Astra Pro to free theme.
```

2021-05-24 12:39 UTC, merged