Refactor: Use matchMedia to detect mobile device to resolve SiteOrigin Page Builder mobile issue
brainstormforce/astra pull request #2475
Opened 2021-03-09 13:32 UTC by AlexGStapleton

### Description
This PR changes how the mobile/desktop menu is displayed. It uses [matchMedia](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) instead of the documents windows innerWidth which can be briefly much larger than expected if a plugin implements a container breaker.

This change was done to resolve an issue with the [SiteOrigin Page Builder container breaker code](https://github.com/siteorigin/siteorigin-panels/blob/2.11.8/js/styling.js) that resulted n the mobile menu not appearing in a row that had a non-standard Row Layout.

This issue was reported here.

### How has this been tested?
This PR has been tested on a client site and a local test site. Both Android and iOS (native devices, not emulated) were tested to ensure functionality remained the same and the highlighted issue was resolved.

### Checklist:
- [*] My code is tested
- [*] My code passes the PHPCS tests
- [*] My code follows accessibility standards 
- [*] My code has proper inline documentation

2021-05-09 02:27 UTC, AlexGStapleton commented
This is still a useful change.

2021-05-10 04:55 UTC, premanshup commented
Hello @AlexGStapleton, apologies for the delay. We are looking into it and will soon give you an update.

2021-07-26 09:00 UTC, AlexGStapleton commented
Still useful.

2021-07-26 09:16 UTC, Nikschavan approved these changes

2021-11-30 15:36 UTC, premanshup requested changes

2021-11-30 15:36 UTC, premanshup commented on assets/js/unminified/navigation.js
> +					if (window.matchMedia('(max-width: ' + break_point + 'px)').matches) {
```suggestion
					if ( ! window.matchMedia( '( max-width: ' + break_point + 'px )' ).matches ) {
```
Howdy @AlexGStapleton

This original change updates the appearance of the menu. It loads Mobile Menu on the Desktop view ( for devices greater 921 px ). This is not the expected behavior.

I have added this change so that Desktop Menu loads on Desktop devices and Mobile Menu loads on Mobile devices ( devices less than 921 px ).

How it should appear for Desktop devices:
![Image 2021-11-30 at 8 58 40 PM](https://user-images.githubusercontent.com/36841355/144076829-0e7aa883-132b-43b1-8159-b851746dd29c.jpeg)

How it appears with the originally suggested changes:
![Image 2021-11-30 at 9 00 42 PM](https://user-images.githubusercontent.com/36841355/144077136-c0b0788b-9784-4976-a64d-8a550bfbbccf.jpeg)

[Not Expected]

How it appears with the current change suggested by me:
![Image 2021-11-30 at 9 02 20 PM](https://user-images.githubusercontent.com/36841355/144077380-f13633d7-96b8-4b55-8d56-6ca346b20c27.jpeg)

[Expected]

Can you please check if this can be added and this fixes the original issue?

The same change is applicable to file - `assets/js/unminified/style.js`

2021-12-06 01:49 UTC, closed without merging