imprv: replace float based CSS to Grid based CSS of third party plugins
brainstormforce/astra pull request #2476
Opened 2021-03-10 04:39 UTC by sagarb90

### Description
**WooCommerce**
-  Replace float CSS to Grid layout CSS for Shop page, Single product page, Category and reviews. 
- Replace float based CSS to flex CSS of Shop page pagination. 

**EDD**
- Replace float CSS to Grid layout CSS for Shop/products page,Products Downloads (archive) page products listing and pagination markup  on all devices.

**LearnDash**
- We are conditionally loading Legacy related CSS from dynamic CSS.

### Types of changes
 - Improvements
 
### How has this been tested?
Verify third party plugins on all devices i.e  WooCommerce, EDD and Learndahs for all page design layouts

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-03-13 08:45 UTC, premanshup commented
@sagarb90 The bottom spacing on page Shop of WooCommerce is not appearing properly.

Steps to reproduce:

1. Set the following settings in Customizer - [https://d.pr/i/qSICvU](https://d.pr/i/qSICvU) for both the previous version and this branch.

2. Check the shop page for both:

Previous version - [https://d.pr/i/hkWNHT](https://d.pr/i/hkWNHT)

Current branch - [https://d.pr/i/gMzSc8](https://d.pr/i/gMzSc8)

2021-03-13 10:55 UTC, premanshup commented
@sagarb90  Please check the spacing of `Next Course` link in the current branch and older versions for `Lifter LMS`.

Previous versions: [https://d.pr/i/CyfYKY](https://d.pr/i/CyfYKY)
Current branch: [https://d.pr/i/nYth0M](https://d.pr/i/nYth0M)

Please check the alignment as well.

Also, check this for both the logged-in and logged-out users.

2021-03-13 11:10 UTC, premanshup commented
@sagarb90 Lifter LMS - Sign up page border issue:

Previous versions: [https://d.pr/i/Fqhf52](https://d.pr/i/Fqhf52)
Current version: [https://d.pr/i/VQY0wj](https://d.pr/i/VQY0wj)

Please check!

2021-03-13 11:50 UTC, premanshup requested changes

2021-03-13 11:50 UTC, premanshup commented on sass/site/compatibility/lifterlms-flex.scss
> + * Governs the general look and feel of WooCommerce sections of stores using themes that do not
@sagarb90 Please check the comment.

2021-03-13 11:50 UTC, premanshup commented on sass/site/compatibility/lifterlms-flex.scss
> +}
@sagarb90 Why is WooCommerce CSS added in the lifter LMS file?

2021-03-13 11:50 UTC, premanshup commented on inc/compatibility/edd/class-astra-edd.php
> -			}
@sagarb90 I think this is required, please confirm this with @RajkiranBagal

2021-03-13 11:50 UTC, premanshup commented on inc/compatibility/edd/class-astra-edd.php
> +			$assets['css']['astra-edd'] = 'compatibility/edd-grid';
@sagarb90 Have we not added backward compatibility for `compatibility/edd`?

2021-03-13 11:50 UTC, premanshup commented on sass/site/compatibility/learndash.scss
> -}
@sagarb90 Just confirming if we have checked this with LearnDash old version Legacy as well?

2021-03-15 04:56 UTC, sagarb90 commented on sass/site/compatibility/lifterlms-flex.scss
> +}
@premanshup This is not newly added by me It's already their for lifter LMS dependent woo cart related CSS, please refer this - https://share.getcloudapp.com/yAu65xDg

2021-03-15 12:17 UTC, sagarb90 commented
> @sagarb90 The bottom spacing on page Shop of WooCommerce is not appearing properly.
> 
> Steps to reproduce:
> 
> 1. Set the following settings in Customizer - https://d.pr/i/qSICvU for both the previous version and this branch.
> 2. Check the shop page for both:
> 
> Previous version - https://d.pr/i/hkWNHT
> 
> Current branch - https://d.pr/i/gMzSc8
> 
> Below CSS is missing in this branch:
> 
> `.woocommerce ul.products li.product, .woocommerce-page ul.products li.product { float: left; margin: 0 20px 2.992em 0; padding: 0; position: relative; width: 22.05%; margin-left: 0; }`

@premanshup Yes I have resolved this. and also confirm with Previous version.

2021-03-15 12:18 UTC, sagarb90 commented on sass/site/compatibility/learndash.scss
> -}
@premanshup This code was not removing It just change line number so it is showing change/code removed.

2021-03-15 12:19 UTC, sagarb90 commented on inc/compatibility/edd/class-astra-edd.php
> +			$assets['css']['astra-edd'] = 'compatibility/edd-grid';
@premanshup Yes I had missed it , have added backward compatibility.

2021-03-15 12:21 UTC, sagarb90 commented on inc/compatibility/edd/class-astra-edd.php
> -			}
Yes their was  code conflicts so unexpectedly it was removed now updated with latest code.

2021-03-15 12:26 UTC, sagarb90 commented on sass/site/compatibility/lifterlms-flex.scss
> + * Governs the general look and feel of WooCommerce sections of stores using themes that do not
@premanshup Yes corrected the same.

2021-03-15 12:27 UTC, sagarb90 commented
> @sagarb90 Lifter LMS - Sign up page border issue:
> 
> Previous versions: https://d.pr/i/Fqhf52
> Current version: https://d.pr/i/VQY0wj
> 
> Please check!

@premanshup Yes resolved border issue It was because of we have changed float based to flex based CSS.

2021-03-15 13:13 UTC, sagarb90 commented
> @sagarb90 Please check the spacing of `Next Course` link in the current branch and older versions for `Lifter LMS`.
> 
> Previous versions: https://d.pr/i/CyfYKY
> Current branch: https://d.pr/i/nYth0M
> 
> Please check the alignment as well.
> 
> Also, check this for both the logged-in and logged-out users.

@premanshup Yes It is because of a. post-navigation  CSS missing  in earlier/previous 3.0.0 version while optimize ast-pagination CSS, So I have added back, now in current branch It 's correct and in Previous version it was missing .https://share.getcloudapp.com/RBu4Qdrm

2021-03-16 05:53 UTC, premanshup commented on sass/site/compatibility/lifterlms-flex.scss
> +}
@sagarb90 I see! Thank you for sharing the screenshot.

2021-03-16 05:53 UTC, premanshup commented on inc/compatibility/edd/class-astra-edd.php
> -			}
@sagarb90 Thank you!

2021-03-16 05:53 UTC, premanshup commented on inc/compatibility/edd/class-astra-edd.php
> +			$assets['css']['astra-edd'] = 'compatibility/edd-grid';
@sagarb90 Thank you!

2021-03-16 05:54 UTC, premanshup commented on sass/site/compatibility/learndash.scss
> -}
@sagarb90 Got it!

2021-03-16 05:56 UTC, premanshup commented
> > @sagarb90 Please check the spacing of `Next Course` link in the current branch and older versions for `Lifter LMS`.
> > Previous versions: https://d.pr/i/CyfYKY
> > Current branch: https://d.pr/i/nYth0M
> > Please check the alignment as well.
> > Also, check this for both the logged-in and logged-out users.
> 
> @premanshup Yes It is because of a. post-navigation CSS missing in earlier/previous 3.0.0 version while optimize ast-pagination CSS, So I have added back, now in current branch It 's correct and in Previous version it was missing .https://share.getcloudapp.com/RBu4Qdrm

So is this issue since v3.0.0? When we optimized the pagination CSS? Can you please confirm?

2021-03-16 06:15 UTC, premanshup approved these changes

2021-03-16 07:56 UTC, vrundakansara approved these changes

2021-03-16 13:14 UTC, rohitp-bsf approved these changes

2021-03-18 06:43 UTC, merged