refactor: Partial refresh calls to the backend.
brainstormforce/astra pull request #2486
Opened 2021-03-11 11:21 UTC by rohitp-bsf

### Description
- While doing partial refresh it was recalculation static array which is the same always. 

### Screenshots
- NA

### Types of changes
- Created a database option with autoloading false.
- While doing the partial refresh, fetching the database and reset the existing array instead of recalculating.
- Delete cached data on publishing.

### How has this been tested?
- Check the possibility of breaking the application.
- Check partial /. page refresh.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-03-11 12:55 UTC, vrundakansara requested changes

2021-03-11 12:55 UTC, vrundakansara commented on inc/customizer/class-astra-customizer.php
> +		private function get_customizer_configurations() {
Any reason why we have removed the function parameter and added a global variable?

2021-03-11 12:55 UTC, vrundakansara commented on inc/customizer/class-astra-customizer.php
> +		public function prepare_customizer_javascript_configs() {
Any reason why we have removed the function parameter and added a global variable?

2021-03-11 12:55 UTC, vrundakansara commented on inc/customizer/class-astra-customizer.php
> +				self::$dynamic_options = $cached_data;
Where have we assigned the `self::$dynamic_options` when it doesn't go in this `if`.
First-time user, a first-time refresh of the customizer, who has no cache saved?

2021-03-11 13:10 UTC, rohitp-bsf commented on inc/customizer/class-astra-customizer.php
> +		private function get_customizer_configurations() {
`$wp_customize` variable is defined by WP and can be used as global anywhere. Passing it as the function will unnecessarily create extra injection to the function which may increase a `Cyclomatic complexity` in the future. @vrundakansara

2021-03-11 13:10 UTC, rohitp-bsf commented on inc/customizer/class-astra-customizer.php
> +		public function prepare_customizer_javascript_configs() {
`$wp_customize` variable is defined by WP and can be used as global anywhere. Passing it as the function will unnecessarily create extra injection to the function which may increase a `Cyclomatic complexity` in the future. @vrundakansara

2021-03-11 13:15 UTC, rohitp-bsf commented on inc/customizer/class-astra-customizer.php
> +				self::$dynamic_options = $cached_data;
As we have added settings and partials dynamically, we are having filters for that where we are identifying these settings and partials at the server end which is initially stored in `self::$dynamic_options` variable, and on each refresh, it is unnecessarily calculating again and again.
so,

1. initially we calculate everything as it was and store in the database only settings and partials.
2. on each request, check if is partial rendering? and have cached data already then return cached or again recalculate as a fallback.
3. delete the cached data on the customizer save. and repeat at step 2 as a fallback. @vrundakansara

2021-03-11 14:17 UTC, vrundakansara commented on inc/customizer/class-astra-customizer.php
> +				self::$dynamic_options = $cached_data;
Okay.

2021-03-11 14:18 UTC, vrundakansara submitted a review, later dismissed

2021-03-12 06:38 UTC, premanshup requested changes

2021-03-12 06:38 UTC, premanshup commented on inc/customizer/class-astra-customizer.php
> +			$cached_data = get_option( 'astra_partials_config_cache', false );
@rohitp-bsf The PR is looking good but I'm skeptical about one thing. I see that we are reducing the iterations of the loop but we are also increasing a DB call on every load. Just confirming if this will not affect the performance? Can you please share stats of by how much this is increasing the performance? Thank you!

2021-03-12 10:15 UTC, rohitp-bsf commented on inc/customizer/class-astra-customizer.php
> +			$cached_data = get_option( 'astra_partials_config_cache', false );
How it was working?

- While preparing the configs for each control config default we were using the `astra_get_option` which is implicitly calling the database around `no of configs` times.
- On each partial refresh again the same thing where we do not need this as we have migrated settings to the JS.
- We just need the partial array for the WP dynamic filters ex `customize_dynamic_partial_args`

How it is working now?
- We are preparing the partial array at once on the first customizer load.
- On each partial refresh we are hitting the database just for once.


Taking about the performance: I am trying to major the partial performance time though but I can see sufficient speed improvement in the partial refresh.

@premanshup

2021-03-12 10:22 UTC, premanshup commented on inc/customizer/class-astra-customizer.php
> +			$cached_data = get_option( 'astra_partials_config_cache', false );
@rohitp-bsf Got it! Thank you for the explanation 👍🏼

2021-03-12 10:22 UTC, premanshup approved these changes

2021-03-15 13:57 UTC, premanshup submitted a review, later dismissed

2021-03-15 16:22 UTC, vrundakansara submitted a review, later dismissed

2021-03-16 04:08 UTC, premanshup approved these changes

2021-03-16 05:19 UTC, vrundakansara approved these changes

2021-03-16 05:20 UTC, merged