feat: Added filter to update breakpoint of min CSS which making  Transparent Header in both devices case
brainstormforce/astra pull request #2489
Opened 2021-03-15 07:59 UTC by imnavanath

### Description
- Transparent header position CSS is at `min-width: 922px`
- This should be `min-width: 921px`
- Case is for `both` devices enable mode - https://a.cl.ly/kpu7jQL2
- For Desktop case as well it set for 921 but with this (both) case it's loading at 922px

### Screenshots
- Screencast - https://a.cl.ly/5zuAzmGe

### Types of changes
- Introducing new filter `astra_trasparent_header_both_devices_min_css_breakpoint` for updating min value breakpoint of Transparent Header making CSS

### How has this been tested?
- This should be test in following options
- Enable transparent header for Desktop / Mobile & for Both devices

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-16 08:24 UTC, vrundakansara requested changes
Please add a changelog for this.

2021-03-16 09:24 UTC, imnavanath commented
> Please add a changelog for this.

Done please take a look @vrundakansara - `- Fix: Transparent Header - Header is not visible at exact tablet breakpoint device.`

2021-03-17 06:46 UTC, vrundakansara approved these changes

2021-03-18 06:15 UTC, vrundakansara approved these changes

2021-03-18 07:17 UTC, imnavanath commented
Closing this PR because by mistaken pulled next-release code into it. And managed new PR here - https://github.com/brainstormforce/astra/pull/2508

2021-03-18 07:17 UTC, closed without merging