AST-2686 - fix: Different reset buttons UI in Background control made identical now
brainstormforce/astra pull request #2491
Opened 2021-03-15 11:13 UTC by imnavanath

### Description
- Updated CSS to make reset buttons from color-picker & from gradient control identical
- Added CSS with !important because to override wp-includes higher weightage CSS

### Screenshots
- https://share.getcloudapp.com/E0u9Z67p

### Types of changes
- Non-breaking change

### How has this been tested?
- With any Background / Responsive-Background control
- EX: Global > Colors ? Base Colors - Background Color

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-15 11:14 UTC, Nikschavan commented
Task linked: [AST-2686 Different reset buttons UI in the Background popup](https://app.clickup.com/t/3387275/AST-2686)

2021-03-18 11:51 UTC, vrundakansara approved these changes

2021-03-19 07:03 UTC, rohitp-bsf requested changes

2021-03-19 07:03 UTC, rohitp-bsf commented on inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
> +    box-shadow: none !important;
Can we avoid the use of `!important` ?

2021-03-19 07:05 UTC, imnavanath commented on inc/customizer/custom-controls/assets/css/unminified/color-rtl.css
> +    box-shadow: none !important;
Unfortunately this CSS from WordPress is higher weightage that's why I've added here !important have a look - https://a.cl.ly/yAu6wwYj

2021-03-19 07:38 UTC, rohitp-bsf submitted a review, later dismissed

2021-03-19 08:11 UTC, vrundakansara approved these changes

2021-03-30 12:29 UTC, vrundakansara approved these changes

2021-03-30 12:29 UTC, merged