AST-3326 - refactor: Default line-height for HTML element set to body's line-height in main-header-bar
brainstormforce/astra pull request #2509
Opened 2021-03-18 09:37 UTC by imnavanath

### Description
- Currently if HTML element is used in Primary header then line-height for HTML applied as 3
- Whereas if element used in Above / Below header then it applied as 1.8 (inheriting from body)
- So decided to have line-height common not 3.

### Screenshots
- Line height applied as 3 in Primary Header - https://a.cl.ly/KouZpO7o

### Types of changes
- Non-breaking change

### How has this been tested?
- Take HTML element in primary header (Notice line-height here as 3)
- Take HTML element in Above / Below header (notice here for line-height as 1.8 - inherited from body)

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-18 09:37 UTC, Nikschavan commented
Task linked: [AST-3326 HTML Widget - Default line-height Issue](https://app.clickup.com/t/3387275/AST-3326)

2021-03-18 10:43 UTC, vrundakansara requested changes

2021-03-18 10:43 UTC, vrundakansara commented on sass/site/header/_header-builder-main.scss
> +			line-height: 1.85714285714286;
How exactly have we calculated this complex number @imnavanath ?

2021-03-18 10:46 UTC, imnavanath commented on sass/site/header/_header-builder-main.scss
> +			line-height: 1.85714285714286;
This is used in our theme for basic style widely - https://a.cl.ly/OAugkw1r That's why I've used it here as well. Example - https://a.cl.ly/7KupYJ91

2021-03-20 13:11 UTC, vrundakansara submitted a review, later dismissed

2021-03-22 06:33 UTC, rohitp-bsf approved these changes

2021-03-30 16:03 UTC, vrundakansara approved these changes

2021-03-30 16:03 UTC, merged