Global color palette
brainstormforce/astra pull request #2520
Opened 2021-03-22 06:40 UTC by patilvikasj

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-04-05 12:05 UTC, vrundakansara requested changes

2021-04-05 12:05 UTC, vrundakansara commented on inc/customizer/configurations/colors-background/class-astra-body-colors-configs.php
> +								'palette-1' => array(
Can we fetch the common repeated color codes from a static variable? 
Here and also in defaults file?

2021-04-05 13:00 UTC, rohitp-bsf requested changes

2021-04-05 13:06 UTC, patilvikasj commented on inc/customizer/configurations/colors-background/class-astra-body-colors-configs.php
> +					'default'   => get_option(
This is intentional. We have kept this option outside the Astra settings array as this will not be needed on front end.

2021-04-05 13:08 UTC, patilvikasj commented on inc/customizer/configurations/colors-background/class-astra-body-colors-configs.php
> +								'palette-1' => array(
These color codes are not finalized yet. If there are repeated colors in the final color codes, I will add them to the static variable.

2021-04-05 13:47 UTC, premanshup requested changes

2021-04-05 13:47 UTC, premanshup commented on inc/core/builder/class-astra-builder-options.php
> +
```suggestion

```

2021-04-05 13:47 UTC, premanshup commented on inc/core/builder/class-astra-builder-options.php
> +
```suggestion

```

2021-04-05 13:47 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +import { Dashicon, Button, TextControl } from "@wordpress/components";
@patilvikasj Please remove unused imports.

2021-04-05 13:47 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +	let value = props.control.setting.get();
```suggestion
	const value = props.control.setting.get();
```

2021-04-05 13:47 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +	let defaultValue = props.control.params.default;
```suggestion
	const defaultValue = props.control.params.default;
```

2021-04-05 13:47 UTC, premanshup commented on inc/customizer/configurations/colors-background/class-astra-body-colors-configs.php
> +							'current_palette' => 'palette-1',
```suggestion
							'currentPalette' => 'palette-1',
```

2021-04-05 13:47 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +			const sel_palettes = props.customizer.control( 'astra-settings[selected-color-palette]' ).setting.get();
```suggestion
			const selectedPalette = props.customizer.control( 'astra-settings[selected-color-palette]' ).setting.get();
```

2021-04-05 13:47 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +				([palette_key, palette_color_obj]) => {
```suggestion
				([paletteKey, paletteColorObj]) => {
```

2021-04-05 13:47 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +					let palette_label = (
```suggestion
					const paletteLabel = (
```

2021-04-05 13:47 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		props.control.setting.set({ ...updateState, flag: !updateState.flag });
@patilvikasj Can we remove `flag: !updateState.flag` ?

2021-04-05 13:47 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		props.control.setting.set({ ...updateState, flag: !updateState.flag });
@patilvikasj Can we remove `flag: !updateState.flag`

2021-04-05 13:55 UTC, Nikschavan commented
@patilvikasj - Can you merge the PR to the `development` branch?

2021-04-06 08:03 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +import { Dashicon, Button, TextControl } from "@wordpress/components";
Done.

2021-04-06 08:03 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +	let value = props.control.setting.get();
Done.

2021-04-06 08:04 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		? useState(props.control.setting.get())
Done.

2021-04-06 08:04 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +			const sel_palettes = props.customizer.control( 'astra-settings[selected-color-palette]' ).setting.get();
Done

2021-04-06 08:04 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +				([palette_key, palette_color_obj]) => {
Done

2021-04-06 08:04 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +					let palette_label = (
Done.

2021-04-06 09:56 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +export default ColorPaletteComponent;
Done.

2021-04-08 07:34 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		props.control.setting.set({ ...updateState, flag: !updateState.flag });
@premanshup  The flag is used to trigger change events. Without it, a change event does not trigger.

2021-04-08 10:06 UTC, vrundakansara approved these changes

2021-04-08 11:03 UTC, premanshup approved these changes

2021-04-08 11:04 UTC, merged