refactor: Updated Astra Options page with Starter Templates screenshot & Important Links postbox
brainstormforce/astra pull request #2525
Opened 2021-03-22 12:03 UTC by imnavanath

### Description
- Reduced other postboxes on Astra options page & managed with single "Important Links" postbox
- Starter Templates plugin screenshot updation [WIP]

### Screenshots
- https://a.cl.ly/L1udn7g8

### Types of changes
- Non-breaking changes

### How has this been tested?
- Check with Astra options page
- Test with other browser can be a test case as well.

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-22 12:03 UTC, Nikschavan commented
Task linked: [AST-3347 Update Astra Options Page with new starter templates screenshot & optimizing postboxes](https://app.clickup.com/t/3387275/AST-3347)

2021-03-24 06:18 UTC, rohitp-bsf approved these changes

2021-03-24 15:53 UTC, vrundakansara requested changes

2021-03-24 15:53 UTC, vrundakansara commented on inc/core/class-astra-admin-settings.php
> +		public static function astra_external_links_scetion() {
Let's remove the `astra` prefix from the function name. Also, rectify the `external_links_section` typo.

2021-03-25 03:45 UTC, imnavanath commented on inc/core/class-astra-admin-settings.php
> +		public static function astra_external_links_scetion() {
Done 👍 Also updated func name with - `external_important_links_section`

2021-03-25 09:19 UTC, vrundakansara approved these changes

2021-03-25 09:29 UTC, rohitp-bsf requested changes

2021-03-25 09:29 UTC, rohitp-bsf commented on inc/core/class-astra-admin-settings.php
> +			if ( is_callable( 'Astra_Ext_White_Label_Markup::get_whitelabel_string' ) ) {
Sure to use `is_callable`, I think it works with access specifiers only. 
ex: https://www.php.net/manual/en/function.is-callable.php

Good to use `method_exists`, just cross-verify it once!

2021-03-25 11:16 UTC, imnavanath commented on inc/core/class-astra-admin-settings.php
> +			if ( is_callable( 'Astra_Ext_White_Label_Markup::get_whitelabel_string' ) ) {
Updated with `method_exists` & verified with after whitelable, with free theme like these cases.

2021-03-28 04:44 UTC, Nikschavan approved these changes

2021-03-30 08:02 UTC, vrundakansara approved these changes

2021-03-30 08:52 UTC, merged