CU-2f93hm - Retina Logo not set
brainstormforce/astra pull request #2529
Opened 2021-03-23 08:38 UTC by rohitp-bsf

### Description
fix: Default for ratina and other options was not working

### Screenshots
- NA

### Types of changes
- Added a default as an updated value.

### How has this been tested?
- Set the new value to the option, reload the customizer and check if updated values appear.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-03-23 08:38 UTC, Nikschavan commented
Task linked: [CU-2f93hm Retina Logo not set](https://app.clickup.com/t/2f93hm)

2021-03-23 09:02 UTC, Nikschavan commented
Task linked: [CU-2f82qd Fix: LearnDash (3.0 template) - Overwrite LearnDash color option is not being saved in master](https://app.clickup.com/t/2f82qd)

2021-03-24 07:55 UTC, vrundakansara requested changes

2021-03-24 07:55 UTC, vrundakansara commented on inc/compatibility/lifterlms/customizer/sections/layout/class-astra-lifter-general-configs.php
> -					'name'              => ASTRA_THEME_SETTINGS . '[llms-course-grid]',
Why have we removed the name?

2021-03-24 08:43 UTC, rohitp-bsf commented on inc/compatibility/lifterlms/customizer/sections/layout/class-astra-lifter-general-configs.php
> -					'name'              => ASTRA_THEME_SETTINGS . '[llms-course-grid]',
It was mistakenly removed @vrundakansara! I have just reverted this change!

2021-03-24 08:47 UTC, vrundakansara approved these changes

2021-03-24 08:50 UTC, RajkiranBagal approved these changes

2021-03-24 10:39 UTC, merged