refactor: Block Editor & GB layout improvements
brainstormforce/astra pull request #2530
Opened 2021-03-23 10:47 UTC by imnavanath

### Description
- Spacing & alignment related issues in GB blocks & editor. 
- Issue with the left-right spacing in Gutenberg editor for pattern & normal blocks

### Screenshots
- Inner spacing issue - Astra - [SS](https://share.getcloudapp.com/jkuepBvD) | TwentryTwentyOne - [SS](https://share.getcloudapp.com/mXu1W42g) -> [FIXED](https://a.cl.ly/6qu8K79K)
- Cover / Group block - https://share.getcloudapp.com/4gu1vd5j
- Group block - https://share.getcloudapp.com/qGuX8kvq 
- Group block - https://share.getcloudapp.com/NQuJm8Q7
- Group block - https://share.getcloudapp.com/nOulrqlkl

### Types of changes
- Non-breaking CSS change
- As managed with backward conditions & with filter

### How has this been tested?
- With creating new GB pages & test in block editor as well
- Check with alignleft / alignright block layout

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-23 10:48 UTC, Nikschavan commented
Task linked: [CU-jwk5e6 Block Editor compatibility CSS](https://app.clickup.com/t/jwk5e6)

2021-03-24 05:15 UTC, rohitp-bsf requested changes

2021-03-24 05:15 UTC, rohitp-bsf commented on inc/core/class-gutenberg-editor-css.php
> +				$gb_patterns_min_mobile_css = array(
Can we get this in `if..else`?

2021-03-24 05:15 UTC, rohitp-bsf commented on inc/class-astra-dynamic-css.php
> +				$gb_patterns_min_mobile_css = array(
Can we get this in `if..else`?

2021-03-24 05:33 UTC, imnavanath commented on inc/core/class-gutenberg-editor-css.php
> +				$gb_patterns_min_mobile_css = array(
Done 👍

2021-03-24 05:33 UTC, imnavanath commented on inc/class-astra-dynamic-css.php
> +				$gb_patterns_min_mobile_css = array(
Done 👍

2021-03-24 06:20 UTC, rohitp-bsf submitted a review, later dismissed

2021-03-25 13:06 UTC, vrundakansara approved these changes

2021-03-31 11:37 UTC, rohitp-bsf approved these changes

2021-03-31 14:22 UTC, premanshup approved these changes

2021-04-01 08:51 UTC, merged