feat: Related Posts on Single Post.
brainstormforce/astra pull request #2559
Opened 2021-03-31 00:21 UTC by premanshup

### Description

https://wp-astra.atlassian.net/jira/software/projects/AST/boards/21?selectedIssue=AST-30

### Screenshots

### Types of changes

New feature (non-breaking change which adds functionality) 

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-03-31 11:48 UTC, rohitp-bsf approved these changes

2021-03-31 11:48 UTC, rohitp-bsf commented on inc/customizer/configurations/typography/class-astra-single-typo-configs.php
> -						'divider'   => array( 'ast_class' => 'ast-bottom-divider' ),
Removed? Is it an extra divider?

2021-03-31 13:02 UTC, vrundakansara submitted a review, later dismissed

2021-04-01 07:41 UTC, imnavanath commented on inc/customizer/configurations/typography/class-astra-single-typo-configs.php
> -						'divider'   => array( 'ast_class' => 'ast-bottom-divider' ),
Yes because here we are adding new options and divider is managed from there. 👍

2021-04-02 13:02 UTC, vrundakansara approved these changes

2021-04-06 12:00 UTC, Nikschavan commented
@imnavanath - FYI - the asset sizes have increased substantially in this PR - https://github.com/brainstormforce/astra/pull/2559#issuecomment-810662914

Can you check this once if this is expected?

2021-04-18 14:37 UTC, Nikschavan commented on inc/blog/related-posts.php
> +
```suggestion
```

2021-04-18 14:38 UTC, Nikschavan commented on inc/blog/related-posts.php
> +
```suggestion
```

2021-04-18 14:39 UTC, Nikschavan commented on inc/blog/related-posts.php
> +
```suggestion
```

2021-04-18 15:14 UTC, Nikschavan requested changes

2021-04-19 03:57 UTC, imnavanath commented on inc/blog/related-posts.php
> +function render_related_posts_by_query( $post_id ) {
As this function name already their, so renamed this like - `astra_get_related_posts_by_query`

2021-04-19 04:13 UTC, imnavanath commented on inc/blog/related-posts.php
> +
Done 👍

2021-04-19 04:13 UTC, imnavanath commented on inc/blog/related-posts.php
> +
Done 👍

2021-04-19 04:13 UTC, imnavanath commented on inc/blog/related-posts.php
> +
Done 👍

2021-04-19 04:13 UTC, imnavanath commented on inc/blog/related-posts.php
> + * @return string|void
Done 👍

2021-04-19 04:13 UTC, imnavanath commented on inc/blog/related-posts.php
> +
Done 👍

2021-04-19 04:13 UTC, imnavanath commented on inc/blog/related-posts.php
> +
Done 👍

2021-04-19 04:14 UTC, imnavanath commented on inc/blog/related-posts.php
> +
Done 👍

2021-04-19 04:14 UTC, imnavanath commented on inc/blog/related-posts.php
> +function get_related_post_featured_image( $current_post_id, $before = '', $after = '', $echo = true ) {
Done 👍

2021-04-19 04:14 UTC, imnavanath commented on inc/blog/related-posts.php
> +
Done 👍

2021-04-19 04:15 UTC, imnavanath commented on inc/blog/related-posts.php
> +
Done 👍

2021-04-19 04:15 UTC, imnavanath commented on inc/blog/related-posts.php
> +
Done 👍

2021-04-19 07:00 UTC, premanshup commented on inc/dynamic-css/related-posts.php
> +			'.ast-single-post .ast-related-post-content .ast-related-post-excerpt' => array(
```suggestion
			'.ast-related-post-excerpt' => array(
```
Please check for all the CSS if we can remove the extra CSS classes if not required?

2021-04-19 07:00 UTC, premanshup commented on inc/extras.php
> +function ast_target_rules_for_related_posts() {
```suggestion
function astra_target_rules_for_related_posts() {
```

2021-04-19 08:32 UTC, imnavanath commented on inc/extras.php
> +function ast_target_rules_for_related_posts() {
Done

2021-04-19 08:32 UTC, imnavanath commented on inc/dynamic-css/related-posts.php
> + * @package astra-builder
Done

2021-04-19 08:33 UTC, imnavanath commented on inc/customizer/configurations/layout/class-astra-related-posts-configs.php
> + * @copyright   Copyright (c) 2020, Astra
Done

2021-04-19 08:34 UTC, imnavanath commented on inc/core/builder/class-astra-builder-options.php
> +	$defaults['mobile-header-type']                 = 'off-canvas';
Done, correct 👍

2021-04-19 09:03 UTC, imnavanath commented on inc/dynamic-css/related-posts.php
> +			'.ast-single-post .ast-related-post-content .ast-related-post-excerpt' => array(
Managed lower weightage CSS selectors [here](https://github.com/brainstormforce/astra/pull/2559/commits/5f9d157e536656b10c2327d1ece91b7b97dc6830)

2021-04-19 09:03 UTC, imnavanath commented on inc/dynamic-css/related-posts.php
> +			'.ast-single-post .ast-related-post-content .entry-meta, .ast-single-post .ast-related-post-content .entry-meta *' => array(
Managed lower weightage CSS selectors [here](https://github.com/brainstormforce/astra/pull/2559/commits/5f9d157e536656b10c2327d1ece91b7b97dc6830)

2021-04-19 09:03 UTC, imnavanath commented on assets/js/unminified/customizer-preview.js
> +	astra_css( 'astra-settings[related-posts-text-color]', 'color', '.ast-single-post .ast-related-post-content .ast-related-post-title *, .ast-single-post .ast-related-post-content .ast-related-post-ex
Managed lower weightage CSS selectors [here](https://github.com/brainstormforce/astra/pull/2559/commits/5f9d157e536656b10c2327d1ece91b7b97dc6830)

2021-04-19 10:17 UTC, imnavanath commented on inc/blog/related-posts.php
> +		return $before . $featured_img_markup . $after;
Corrected now 👍

2021-04-19 10:17 UTC, imnavanath commented on inc/blog/related-posts.php
> +			'<a ' . astra_attr(
Used `astra_markup_open|close()` functions instead direct HTML anchor.

2021-04-21 08:49 UTC, merged