AST-77 - fix: Off-Canvas & Dropdown does not close when you click a one page navigation link inside them.
brainstormforce/astra pull request #2560
Opened 2021-03-31 11:05 UTC by RajkiranBagal

### Description
 - Task - https://wp-astra.atlassian.net/browse/AST-77

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
 - Mentioned in the task.

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-03-31 11:35 UTC, rohitp-bsf requested changes

2021-03-31 11:35 UTC, rohitp-bsf commented on assets/js/unminified/frontend.js
> +		if ( 'dropdown' === headerType ) {
As if-else is being used without else, can we use the switch here?

2021-03-31 11:35 UTC, rohitp-bsf commented on assets/js/unminified/frontend.js
> +			for ( i = 0, len = popupLinks.length; i < len; i++ ) {
Can we use the `index` or any meaningful variable instead of `i`? Let's make the changes at other locations as well, please.

2021-03-31 12:43 UTC, vrundakansara requested changes

2021-03-31 12:43 UTC, vrundakansara commented on assets/js/unminified/frontend.js
> +	function newToggleClose( event ) {
Let's use a better nomenclature here `newToggleClose`.

2021-03-31 12:52 UTC, RajkiranBagal commented on assets/js/unminified/frontend.js
> +	function newToggleClose( event ) {
Done

2021-03-31 12:52 UTC, RajkiranBagal commented on assets/js/unminified/frontend.js
> +			for ( i = 0, len = popupLinks.length; i < len; i++ ) {
Done

2021-03-31 13:27 UTC, vrundakansara approved these changes

2021-03-31 14:43 UTC, premanshup requested changes

2021-04-01 03:54 UTC, RajkiranBagal commented on assets/js/unminified/frontend.js
> +				submenuButtons = document.querySelectorAll( '#ast-mobile-popup .ast-menu-toggle' ),
That variable was not added in this PR. Also, I see that variable is not used anywhere so removing it.

2021-04-01 03:57 UTC, RajkiranBagal commented on assets/js/unminified/frontend.js
> +			}
Currently, all the Popup related JS is in `frontend.js` file. Separating popup related JS from this file will be a separate task as it has a larger scope.

2021-04-01 05:19 UTC, sagarb90 commented on assets/js/unminified/frontend.js
> +			}
@premanshup We can move popup related JS to other file  but as  discus with @RajkiranBagal  the total size is less that 1kb for  popup related JS. So this will increase an extra resources by loading it separately. Your thought on this please.

2021-04-01 11:39 UTC, premanshup commented on assets/js/unminified/frontend.js
> +				submenuButtons = document.querySelectorAll( '#ast-mobile-popup .ast-menu-toggle' ),
Okay 👍🏼

2021-04-01 11:41 UTC, premanshup commented on assets/js/unminified/frontend.js
> +			}
@sagarb90 @RajkiranBagal Right! If this is the case, then I agree in keeping this in this file only 👍🏼

2021-04-01 11:42 UTC, premanshup submitted a review, later dismissed

2021-04-01 16:04 UTC, vrundakansara submitted a review, later dismissed

2021-04-02 13:19 UTC, vrundakansara approved these changes

2021-04-02 13:24 UTC, merged