AST-26 - refactor: remove Popup from Mobile menu by default and make it Dropdown
brainstormforce/astra pull request #2561
Opened 2021-03-31 11:57 UTC by sagarb90

### Description
- For frontend optimization we have removed Default flyout option from mobile menu popup and make it as Dropdown.
- Move Static CSS related dropdown and flyout to Dynamic CSS and load it conditionally.
- After this optimization we have reduce the total **HTML  no. of lines by 14** and **Static CSS file by 8KB**.

### Types of changes
- Improvements.

### How has this been tested?
Verify off-canvas header type dropdown and flyout both on Desktop and on mobile view

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-03-31 14:33 UTC, premanshup requested changes

2021-04-01 05:00 UTC, Nikschavan approved these changes

2021-04-01 05:02 UTC, sagarb90 commented on inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
> +
@premanshup Because on customizer we need both type CSS as we changes the option (flyout/dropdown) from customizer and it has partial refresh action.

2021-04-01 09:48 UTC, vrundakansara requested changes

2021-04-01 09:48 UTC, vrundakansara commented on inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
> +function off_canvas_static_css() {
Can we prefix this function?

2021-04-01 09:48 UTC, vrundakansara commented on inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
> +function dropdown_type_static_css() {
Can we prefix this function?

2021-04-01 10:20 UTC, sagarb90 commented on inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
> +function off_canvas_static_css() {
@vrundakansara Yes added astra_ prefix to this function.

2021-04-01 10:20 UTC, sagarb90 commented on inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
> +function dropdown_type_static_css() {
@vrundakansara Yes added astra_ prefix to this function.

2021-04-01 10:29 UTC, Nikschavan approved these changes

2021-04-01 11:29 UTC, vrundakansara approved these changes

2021-04-02 16:50 UTC, merged