Display Global color palette in all color option controls
brainstormforce/astra pull request #2568
Opened 2021-04-01 12:02 UTC by patilvikasj

### Description
Display Global Color Palette inside all color options 

### Screenshots
![1b53e2f5-11db-4ac3-9ac0-84aa88cc4c4a](https://user-images.githubusercontent.com/10000232/113290903-e1fa4580-930f-11eb-8e32-0f4da0537ce3.png)

### Types of changes
New feature (non-breaking change which adds functionality)

### How has this been tested?

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-04-08 12:21 UTC, rohitp-bsf approved these changes

2021-04-08 12:21 UTC, rohitp-bsf commented on inc/addons/heading-colors/customizer/class-astra-heading-colors-configs.php
> +					'default'           => astra_get_option( 'heading-base-color', 'var(--ast-global-heading-color)' ),
it would be good if we can set defaults in `class-astra-builder-options.php` file. Helpful in future reset functionality.

2021-04-08 12:21 UTC, rohitp-bsf commented on inc/core/builder/class-astra-builder-options.php
> +		'extra-2'          => '#F3F4F7',
Let's follow the lowercase color code pattern everywhere.

2021-04-08 12:21 UTC, rohitp-bsf commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		props.customizer.control( 'astra-settings[selected-color-palette]' ).setting.set( modifiedPalette );
Can we cache this `props.customizer.control( 'astra-settings[selected-color-palette]' )` and use subsequentry for get & set?

2021-04-08 12:21 UTC, rohitp-bsf commented on inc/customizer/extend-custom-controls/src/color-palette/control.js
> +		const palette = wp.customize.control( 'astra-settings[selected-color-palette]' ).setting.get();
Can we use here `props.customizer` instead direct access to `wp.customize` ?

2021-04-08 12:21 UTC, rohitp-bsf commented on inc/customizer/extend-custom-controls/src/common/astra-color-picker-control.js
> +		let globalColorPalette = wp.customize.control( 'astra-settings[selected-color-palette]' ).setting.get();
Can we use here `props.customizer` instead direct access to `wp.customize` ?

2021-04-08 12:21 UTC, rohitp-bsf commented on inc/customizer/extend-custom-controls/src/common/astra-color-picker-control.js
> +			Object.assign( paletteColors, { color: 'var(--ast-global-'+ key +')' } );
Can we combine this? like

`Object.assign( paletteColors, { name: key, color: 'var(--ast-global-'+ key +')' } );`

2021-04-08 12:21 UTC, rohitp-bsf commented on inc/customizer/extend-custom-controls/src/control-customizer.js
> +					'AstPaletteUpdated', {
Can event name be more meaningful?

2021-04-08 12:22 UTC, rohitp-bsf requested changes
Requesting changes.

2021-04-08 13:19 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/color-palette/control.js
> +		const palette = wp.customize.control( 'astra-settings[selected-color-palette]' ).setting.get();
props.customizer is not accessible inside control.js

2021-04-08 13:22 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/common/astra-color-picker-control.js
> +		let globalColorPalette = wp.customize.control( 'astra-settings[selected-color-palette]' ).setting.get();
No. we can't. props do not have customizer variable.

2021-04-08 13:35 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/control-customizer.js
> +					'AstPaletteUpdated', {
Renamed event name.

2021-04-08 13:36 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		props.customizer.control( 'astra-settings[selected-color-palette]' ).setting.set( modifiedPalette );
Done.

2021-04-08 13:37 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/common/astra-color-picker-control.js
> +			Object.assign( paletteColors, { color: 'var(--ast-global-'+ key +')' } );
Done

2021-04-09 10:56 UTC, patilvikasj commented on inc/addons/heading-colors/customizer/class-astra-heading-colors-configs.php
> +					'default'           => astra_get_option( 'heading-base-color', 'var(--ast-global-heading-color)' ),
Done.

2021-04-09 10:59 UTC, patilvikasj commented on inc/core/builder/class-astra-builder-options.php
> +		'extra-2'          => '#F3F4F7',
Done.

2021-04-09 11:05 UTC, patilvikasj commented on inc/customizer/configurations/colors-background/class-astra-body-colors-configs.php
> +								'palette_1' => array(
This key will be removed as it is only a single palette array. It will modify in the next PR for the color palette.

2021-04-09 11:51 UTC, vrundakansara approved these changes

2021-04-09 12:36 UTC, rohitp-bsf approved these changes

2021-04-09 12:38 UTC, merged