GCP-2 Global palette frontend implementation
brainstormforce/astra pull request #2580
Opened 2021-04-02 13:36 UTC by patilvikasj

### Description
Global Palette front end implementation

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-04-14 04:32 UTC, rohitp-bsf requested changes

2021-04-14 04:32 UTC, rohitp-bsf commented on inc/class-astra-dynamic-css.php
> +			foreach ( $palette['palette'] as $key => $color ) {
Can you pull out `$palette['palette']` like `$palette =  isset( $palette['palette'] ) ? $palette['palette'] : array() ` for safe side?

2021-04-14 04:32 UTC, rohitp-bsf commented on inc/class-astra-dynamic-css.php
> +				$palette_key                   = '--ast-global-' . $key;
It would be good if we can use const for '--ast-global-'.

2021-04-14 05:46 UTC, patilvikasj commented on inc/class-astra-dynamic-css.php
> +			foreach ( $palette['palette'] as $key => $color ) {
Done.

2021-04-14 05:46 UTC, patilvikasj commented on inc/class-astra-dynamic-css.php
> +				$palette_key                   = '--ast-global-' . $key;
We have now added a helper function to get the palette variable prefix.

2021-04-14 05:47 UTC, rohitp-bsf approved these changes

2021-04-15 05:56 UTC, premanshup requested changes

2021-04-15 05:56 UTC, premanshup commented on inc/class-astra-global-palette.php
> +		$palette = isset( $palette_data['palette'] ) ? $palette_data['palette'] : '';
```suggestion

```
`empty( $palette )` internally checks `isset( $palette )`

2021-04-15 05:56 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
>  	document.addEventListener(
@patilvikasj I think custom event can be removed along with https://github.com/brainstormforce/astra/pull/2580/files#diff-2c13e8e5e8d439689c38a56849e0a95a9f5d3de49ef8548e1760719c637ca31fR105. Please check.

2021-04-22 14:16 UTC, closed without merging