imprv: Removed default sidebar and move blog page grid related options from addon to theme.
brainstormforce/astra pull request #2608
Opened 2021-04-08 09:42 UTC by sagarb90

### Description
- Removed default sidebar and move grid-related options from addon to theme.
- Also manage theme and add-on version dependency.
- Changes default options value for grid layout (default -3), inside-post spacing(30px), Post Title Font Size(24) and post meta sequence( category/user/date) 
- https://wp-astra.atlassian.net/browse/AST-97

### Screenshots

### Types of changes
- Improvements 

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-05 10:02 UTC, imnavanath commented on functions.php
> +add_filter( 'astra_apply_flex_based_css', '__return_true' );
@sagarb90 can you please remove this.

2021-05-05 10:02 UTC, imnavanath commented on functions.php
> +>>>>>>> 87711d73ed01ada056d0964d62eb32fe44b36d47
Please remove the conflicts.

2021-05-05 10:05 UTC, imnavanath commented on functions.php
> +if ( defined( 'ASTRA_EXT_VER' ) && version_compare( ASTRA_EXT_VER, '3.4.0', '>' ) || ! defined( 'ASTRA_EXT_VER' ) ) {
Looks like condition needs to be modified. Adding again `! defined( 'ASTRA_EXT_VER' )` not understood.
If by anyways we need to require this file then we can avoid condition here.

2021-05-05 10:08 UTC, imnavanath commented on inc/addons/blog/class-astra-blog.php
> +	Astra_Blog::get_instance();
Instead of singleton class can we create instance by `new`.  Let's avoid `Astra_Blog::get_instance();`

2021-05-05 10:10 UTC, sagarb90 commented on functions.php
> +>>>>>>> 87711d73ed01ada056d0964d62eb32fe44b36d47
Resolved.

2021-05-05 10:10 UTC, sagarb90 commented on functions.php
> +if ( defined( 'ASTRA_EXT_VER' ) && version_compare( ASTRA_EXT_VER, '3.4.0', '>' ) || ! defined( 'ASTRA_EXT_VER' ) ) {
Modified condition now

2021-05-05 10:11 UTC, imnavanath commented on inc/addons/blog/class-astra-blog.php
> +if ( ! class_exists( 'Astra_Blog' ) ) {
Can you please remove `class_exists` check from here.
And add at top of file -

`// No direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}`

2021-05-05 10:11 UTC, sagarb90 commented on inc/addons/blog/class-astra-blog.php
> +	Astra_Blog::get_instance();
@imnavanath Any specific reason not to use singleton here.

2021-05-05 10:16 UTC, sagarb90 commented on inc/addons/blog/class-astra-blog.php
> +if ( ! class_exists( 'Astra_Blog' ) ) {
Done

2021-05-05 10:17 UTC, imnavanath commented on inc/addons/blog/class-astra-blog.php
> +	Astra_Blog::get_instance();
Because if any requirement comes in future to create new instance of the class we can't achieve. So that's why we decided to  not to use singleton class anymore and will go with `new`.

2021-05-05 15:07 UTC, premanshup commented
@sagarb90 `inc/addons/blog/classes/dynamic.php` -> inc/addons/blog/classes/dynamic-css.php

2021-06-25 16:02 UTC, premanshup requested changes

2021-06-25 16:02 UTC, premanshup commented on inc/addons/blog/classes/dynamic-css.php
> +		),
@sagarb90 Can we load each grid CSS option based? Like if grid 4 is enabled then only grid 4 related CSS will load. Similarly for other grid. I think this will help in reducing the inline CSS size.

2021-06-25 16:02 UTC, premanshup commented on inc/addons/blog/classes/dynamic-css.php
> +	);
Similarly option based CSS here.

2021-06-25 16:51 UTC, premanshup requested changes

2021-06-25 16:51 UTC, premanshup commented on inc/addons/blog/classes/class-astra-blog-loader.php
> +			$defaults['blog-grid-layout']         = 1;
@sagarb90 This default is not used anywhere in the theme, can you please check if this is required in the theme?

2021-06-25 16:51 UTC, premanshup commented on inc/addons/blog/classes/class-astra-blog-loader.php
> +			$defaults['blog-layout']              = 'blog-layout-1';
@sagarb90 This option is loaded from Addon and I believe we are still loading this from addon. Any reason we have added default value from theme? https://share.bsf.io/geugmpGp

2021-06-25 16:58 UTC, premanshup requested changes

2021-06-25 16:58 UTC, premanshup commented on inc/addons/blog/classes/class-astra-blog-loader.php
> +			if ( true === Astra_Builder_Helper::$is_header_footer_builder_active ) {
@sagarb90 I see the JS is related to Customizer preview for blog related options. Can you please explain why we are adding header builder condition here.

2021-06-25 16:59 UTC, premanshup requested changes

2021-06-25 16:59 UTC, premanshup commented on inc/addons/blog/classes/class-astra-blog-loader.php
> +		public function new_customize_register( $wp_customize ) {
```suggestion
		public function blog_addon_customizer_configs( $wp_customize ) {
```

2021-06-25 17:01 UTC, premanshup requested changes

2021-06-25 17:01 UTC, premanshup commented on inc/addons/blog/classes/index.php
> +/* Silence is golden, and we agree. */
@sagarb90 I think we can remove this file, please verify.

2021-06-25 17:01 UTC, premanshup commented on inc/addons/blog/classes/sections/index.php
> +/* Silence is golden, and we agree. */
@sagarb90 I think we can remove this file as well, please verify

2021-06-25 17:10 UTC, premanshup requested changes

2021-06-25 17:10 UTC, premanshup commented on inc/addons/blog/classes/sections/class-astra-customizer-blog-configs.php
> +if ( ! class_exists( 'Astra_Customizer_Blog_Configs' ) ) {
```suggestion

```

2021-06-28 05:33 UTC, sagarb90 commented on inc/addons/blog/classes/dynamic-css.php
> +		),
@premanshup Yes I have already did the same on this grid based css related changes PR - https://github.com/brainstormforce/astra/pull/2634/files#diff-673a8d6cfdb6cb9a51da80b4bf91e3fcb70d7f2fe35ea9cd5c9652d81499053eR190

2021-06-28 05:34 UTC, sagarb90 commented on inc/addons/blog/classes/dynamic-css.php
> +	);
@premanshup Yes I have already did the same on this grid based css related changes PR - 
https://github.com/brainstormforce/astra/pull/2634/files#diff-673a8d6cfdb6cb9a51da80b4bf91e3fcb70d7f2fe35ea9cd5c9652d81499053eR187

2021-06-28 06:03 UTC, sagarb90 commented on inc/addons/blog/classes/class-astra-blog-loader.php
> +			$defaults['blog-grid-layout']         = 1;
Yes this is required as we have moved some blog grid related options to the theme and used it here- https://github.com/brainstormforce/astra/pull/2608/files#diff-673a8d6cfdb6cb9a51da80b4bf91e3fcb70d7f2fe35ea9cd5c9652d81499053eR21-R23

2021-06-28 06:27 UTC, sagarb90 commented on inc/addons/blog/classes/class-astra-blog-loader.php
> +			$defaults['blog-layout']              = 'blog-layout-1';
Yes, As we have dependent code for grid base css classes on blog-layouts so we need this blog-layout default option to check. But I as have checked the code if we have activated only theme then we can load by default as 'blog-layout-1' and will do the change.

2021-06-28 06:49 UTC, sagarb90 commented on inc/addons/blog/classes/class-astra-blog-loader.php
> +			if ( true === Astra_Builder_Helper::$is_header_footer_builder_active ) {
Yes this is already added in add-on as I have just moved this to the theme - master branch ref-  https://github.com/brainstormforce/astra-addon/blob/master/addons/blog-pro/classes/class-astra-ext-blog-pro-loader.php#L42
Also I have checked this why we added this condition for JS this is added for removing customizer refresh for space betwn  post in New HFB case as per git commit.

2021-06-28 07:29 UTC, sagarb90 commented on inc/addons/blog/classes/index.php
> +/* Silence is golden, and we agree. */
Removed.

2021-06-28 07:29 UTC, sagarb90 commented on inc/addons/blog/classes/sections/class-astra-customizer-blog-configs.php
> +if ( ! class_exists( 'Astra_Customizer_Blog_Configs' ) ) {
Removed this check

2021-06-28 07:30 UTC, sagarb90 commented on inc/addons/blog/classes/sections/index.php
> +/* Silence is golden, and we agree. */
Removed.

2021-09-08 01:47 UTC, closed without merging