AST-349 - fix: Console error in case of Dropdown Toggle for Sticky Header on Mobile.
brainstormforce/astra pull request #2611
Opened 2021-04-08 13:16 UTC by RajkiranBagal

### Description
 - Task - https://wp-astra.atlassian.net/browse/AST-349

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
 - Steps in Task.
 
### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-04-09 04:13 UTC, vrundakansara submitted a review, later dismissed

2021-04-09 04:46 UTC, Nikschavan requested changes

2021-04-09 04:46 UTC, Nikschavan commented on changelog.txt
> +- Fix: Console error in case of Dropdown Toggle for Sticky Header on Mobile.
```suggestion
- Fix: JavaScript error when clicking on the Dropdown Toggle for Sticky Header on Mobile.
```

2021-04-09 04:47 UTC, Nikschavan commented on changelog.txt
> +- Fix: Console error in case of Dropdown Toggle for Sticky Header on Mobile.
- It's a `Javascript` error which is shown in the console'
- Avoid using words like `case`, `issue` etc and instead describe what the actual case or the issue is.

2021-04-09 05:09 UTC, RajkiranBagal commented on changelog.txt
> +- Fix: Console error in case of Dropdown Toggle for Sticky Header on Mobile.
Okay! Updated & Noted.

2021-04-10 11:58 UTC, premanshup submitted a review, later dismissed

2021-04-12 08:25 UTC, rohitp-bsf approved these changes

2021-04-19 04:51 UTC, premanshup approved these changes

2021-04-19 04:52 UTC, merged