AST-71 - fix: Mega menu heading hover color issue
brainstormforce/astra pull request #2620
Opened 2021-04-09 12:47 UTC by abhishek-bsf

### Description

Task- https://wp-astra.atlassian.net/browse/AST-71

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests

2021-04-14 04:55 UTC, premanshup requested changes

2021-04-14 04:55 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +				$css_output['.main-header-menu .menu-item .menu-link:hover, .main-header-menu .menu-item:hover > .ast-menu-toggle, .main-header-menu .ast-masthead-custom-menu-items a:hover, .main-header-menu .me
@abhishek-bsf If the issue is in Mega Menu, why are we changing the CSS of main menu?

2021-04-14 14:33 UTC, abhishek-bsf commented on inc/class-astra-dynamic-css.php
> +				$css_output['.main-header-menu .menu-item .menu-link:hover, .main-header-menu .menu-item:hover > .ast-menu-toggle, .main-header-menu .ast-masthead-custom-menu-items a:hover, .main-header-menu .me
This CSS selector is causing issue while applying CSS to Mega menu. It overrides Mega menu styles and dynamic Mega menu style is not applied. I have tested this change and it does not affect any Main menu style.

2021-05-28 06:52 UTC, imnavanath approved these changes

2021-05-28 06:54 UTC, imnavanath commented on inc/class-astra-dynamic-css.php
> +				$css_output['.main-header-menu .menu-item .menu-link:hover, .main-header-menu .menu-item:hover > .ast-menu-toggle, .main-header-menu .ast-masthead-custom-menu-items a:hover, .main-header-menu .me
It will be better if we test this case.

2021-05-28 07:00 UTC, abhishek-bsf commented on inc/class-astra-dynamic-css.php
> +				$css_output['.main-header-menu .menu-item .menu-link:hover, .main-header-menu .menu-item:hover > .ast-menu-toggle, .main-header-menu .ast-masthead-custom-menu-items a:hover, .main-header-menu .me
@imnavanath I tested this case. Basically in this ``.menu-item:hover > .menu-link`` we were adding hover action for ``<li>`` tag which was causing some issue to apply style. Instead now, we have directly targeted ``<a>`` tag class for hover style ``.menu-link:hover``.

2021-08-18 01:47 UTC, closed without merging