AST-70 new: Added a filter to retrive 404 classes
brainstormforce/astra pull request #2635
Opened 2021-04-16 15:14 UTC by rohitp-bsf

### Description
- Added a new filter `astra_get_404_page_classes`

### Screenshots
- NA

### Types of changes
- Added a new filter only.

### How has this been tested?
- NA

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-04-16 15:36 UTC, premanshup requested changes

2021-04-16 15:36 UTC, premanshup commented on template-parts/404/404-layout.php
> +}
@rohitp-bsf We already have `astra_attr()` using which we can generate attributes and inside it dynamic filter is also there which we can use. I don't think there is need to add separate filter. We can just convert the below markup to `astra_attr()`. Please check.

2021-04-17 15:36 UTC, rohitp-bsf commented on template-parts/404/404-layout.php
> +}
Updated!

2021-04-19 06:03 UTC, premanshup approved these changes

2021-04-19 06:15 UTC, merged