AST-371 - fix: Eneven spacing in between single post section has been corrected as per design perspective
brainstormforce/astra pull request #2651
Opened 2021-04-21 10:30 UTC by imnavanath

### Description
- Extra margin space removed from single post sections for stretched layout 

### Screenshots
- https://share.getcloudapp.com/KoudJmNA
- https://share.getcloudapp.com/X6uelJ8E
- https://share.getcloudapp.com/z8u6rvmk

### Types of changes
- Non breaking change

### How has this been tested?
- Set layout to Stretched
- Visit single post layout

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-04-21 10:40 UTC, sagarb90 commented
@imnavanath Can we move `related_posts_static_css()`  code to seperate file in `inc\dynamic-css\` folder.
cc -  @premanshup

2021-04-21 10:42 UTC, premanshup commented
> @imnavanath Can we move `related_posts_static_css()` code to seperate file in `inc\dynamic-css\` folder.
> cc - @premanshup

Yes I agree @sagarb90

2021-04-21 11:15 UTC, imnavanath commented
> @imnavanath Can we move `related_posts_static_css()` code to seperate file in `inc\dynamic-css\` folder?
> cc - @premanshup

@premanshup @sagarb90 Please review this commit where we divided static CSS in new file. - https://github.com/brainstormforce/astra/pull/2651/commits/c12abef3c3b4701d846f60c6ab70a3d8a1a319b3

2021-04-28 15:59 UTC, premanshup requested changes

2021-04-28 15:59 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +				$parse_css .= Astra_Enqueue_Scripts::trim_css( related_posts_static_css() );
@imnavanath Instead of adding function in `inc/modules/related-posts/css/static-css.php`, I think we should add filter astra_dynamic_css there directly.

2021-04-28 15:59 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +				$parse_css .= Astra_Enqueue_Scripts::trim_css( related_posts_static_css() );
Also instead of including the file here, we should include this somewhere in the `astra\inc\modules\related-posts\` folder . Same goes for dynamic CSS.

2021-04-29 06:12 UTC, imnavanath commented on inc/class-astra-dynamic-css.php
> +				$parse_css .= Astra_Enqueue_Scripts::trim_css( related_posts_static_css() );
Refactored code flow now - [comit](https://github.com/brainstormforce/astra/pull/2651/commits/ab49d1beb5252e5094a7cd049c0fae861e250370)

2021-04-30 07:31 UTC, premanshup requested changes

2021-04-30 07:31 UTC, premanshup commented on inc/modules/related-posts/class-astra-related-posts.php
> +define( 'ASTRA_RELATED_POSTS_URI', ASTRA_THEME_URI . 'inc/modules/related-posts/' );
@imnavanath This is not used anywhere, please remove this.

2021-04-30 07:35 UTC, imnavanath commented on inc/modules/related-posts/class-astra-related-posts.php
> +define( 'ASTRA_RELATED_POSTS_URI', ASTRA_THEME_URI . 'inc/modules/related-posts/' );
Correct, thank you 👍

2021-04-30 07:37 UTC, premanshup approved these changes

2021-05-03 12:07 UTC, sagarb90 approved these changes

2021-05-03 12:37 UTC, merged