AST-74 - refactor: Updated priorities of control in order to maintain correct sequence in customizer
brainstormforce/astra pull request #2663
Opened 2021-04-26 12:31 UTC by imnavanath

### Description
- Updated correct sequence in Single post section

### Screenshots
- https://share.bsf.io/wbuwQ0ev

### Types of changes
- Non-breaking change

### How has this been tested?
- With Single Post section
- With General | Design tab
- W/o General | Design tab
- With Free theme
- With Theme + Addon

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-04-27 17:12 UTC, premanshup requested changes

2021-04-27 17:12 UTC, premanshup commented on inc/customizer/configurations/layout/class-astra-related-posts-configs.php
> +					'title'    => ( true === Astra_Builder_Helper::$is_header_footer_builder_active ) ? __( 'Related Posts', 'astra' ) : __( 'Related Posts Design', 'astra' ),
@imnavanath Why do we have 2 different string?

2021-04-28 03:19 UTC, imnavanath commented on inc/customizer/configurations/layout/class-astra-related-posts-configs.php
> +					'title'    => ( true === Astra_Builder_Helper::$is_header_footer_builder_active ) ? __( 'Related Posts', 'astra' ) : __( 'Related Posts Design', 'astra' ),
Because when old header-footer is active (where General | Design tab is not there) then "Related Posts" heading is appearing twice (1. - Before query settings, 2. before these style options) 
When General | Design tab is there then these diversified in different tabs. Which looks correct.
So as per QA suggestion added different strings for this heading.

2021-04-28 05:00 UTC, premanshup approved these changes

2021-04-28 05:00 UTC, merged