AST-74 - fix: Page Builder's menu elements shows double arrow icons when Astra's SVG icons are enabled.
brainstormforce/astra pull request #2664
Opened 2021-04-27 06:09 UTC by imnavanath

### Description
- SVG double arrow icon issue with page builder's menu element

### Screenshots
- https://share.bsf.io/nOuoXdjW

### Types of changes
- Bug fix

### How has this been tested?
- With page builder's menu element

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-04-27 17:07 UTC, premanshup requested changes

2021-04-27 17:07 UTC, premanshup commented on changelog.txt
> +- Fix: Page Builder's menu elements shows double arrow icons when Astra's SVG icons are enabled.
```suggestion
- Fix: Page Builder's menu elements show double arrow icons when theme's SVG icons are enabled.
```

2021-04-27 17:07 UTC, premanshup commented on inc/extras.php
> +	if ( in_array( $args->menu_id, $astra_menu_locations ) ) {
@imnavanath It looks like this will only work for these three menus:

`'mobile-menu'`
`'ast-hf-menu-1'`
`'ast-hf-menu-2'`

Can you please check this with cloned menus or off canvas or account menus. Also please make sure to check the menus after disabling just `nav-menu` addon.

2021-04-28 04:33 UTC, imnavanath commented on changelog.txt
> +- Fix: Page Builder's menu elements shows double arrow icons when Astra's SVG icons are enabled.
Corrected.

2021-04-28 04:52 UTC, imnavanath commented on inc/extras.php
> +	if ( in_array( $args->menu_id, $astra_menu_locations ) ) {
Yesterday we checked the clone feature as well & coming to the part of Account menu then it's corrected now.
Removed `'ast-hf-account-menu'` from exclude array and added inside include array.

2021-04-30 09:26 UTC, imnavanath commented on inc/extras.php
> +	if ( in_array( $args->menu_id, $astra_menu_locations ) ) {
@premanshup reverted this above change just added small tweak for those menus where we don't get menu IDs.

Can you please review once,

2021-05-03 12:49 UTC, premanshup requested changes

2021-05-03 12:49 UTC, premanshup commented on inc/extras.php
> +	if ( ! ( defined( 'ASTRA_EXT_VER' ) && Astra_Ext_Extension::is_active( 'nav-menu' ) && ( isset( $args->container_class ) && ! in_array( $args->menu_id, $skip_menu_locations ) ) ) && ! in_array( $arg
@imnavanath I was thinking that we should add SVG only when our locations are loaded else we will not add SVG. This will resolve the issue with Elementor for now but in long run this may cause issue again with other page builders or third party plugins.

2021-05-05 12:36 UTC, imnavanath commented on inc/extras.php
> +	if ( ! ( defined( 'ASTRA_EXT_VER' ) && Astra_Ext_Extension::is_active( 'nav-menu' ) && ( isset( $args->container_class ) && ! in_array( $args->menu_id, $skip_menu_locations ) ) ) && ! in_array( $arg
@premanshup please review now. Checked with the cases as well as mentioned in card - https://wp-astra.atlassian.net/browse/AST-402

2021-05-06 12:10 UTC, premanshup requested changes

2021-05-06 13:47 UTC, imnavanath commented on inc/extras.php
> +		'below_header-menu',     // Old header - Below Menu.
For footer menu we don't load submenu. So getting arrow icon is incorrect there. I checked with Footer Menu but not getting single arrow in my case - https://share.bsf.io/xQubkZxd Is there any specific case? 

Also added cloned menu dependency in array. BTW condition logic is also revamped please have a look. - https://github.com/brainstormforce/astra/pull/2664/commits/131474d5dcf22cd0728c58cb8262d5242b9f5e7e

2021-05-06 13:49 UTC, premanshup commented on inc/extras.php
> +		'below_header-menu',     // Old header - Below Menu.
@imnavanath For footer menu, try disabling the Addon, just activate the theme and add footer menu.

2021-05-06 13:52 UTC, imnavanath commented on inc/extras.php
> +		'below_header-menu',     // Old header - Below Menu.
Tried with this case as well - https://share.bsf.io/v1ubGlkk

BTW I checked in this current PR's branch only.

2021-05-06 13:55 UTC, imnavanath commented on inc/extras.php
> +		'below_header-menu',     // Old header - Below Menu.
Ohh I checked in other branch & got the issue - https://share.bsf.io/v1ubGlZB
But in this PR's branch this is fixed as per my above comment & screencast.

2021-05-06 14:59 UTC, premanshup submitted a review, later dismissed

2021-05-07 09:23 UTC, sagarb90 approved these changes

2021-05-07 09:24 UTC, sagarb90 commented
@imnavanath Please resolve conflicts.

2021-05-07 09:29 UTC, abhishek-bsf approved these changes

2021-05-13 06:04 UTC, merged