Palette migration
brainstormforce/astra pull request #2670
Opened 2021-04-28 07:55 UTC by patilvikasj

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-04 05:04 UTC, vrundakansara requested changes

2021-05-04 05:04 UTC, vrundakansara commented on inc/core/common-functions.php
> +		$hex = apply_filters( 'astra_before_fg_color_generate', $hex );
Let's keep it to `astra_before_foreground_color_generation`.

2021-05-04 05:04 UTC, vrundakansara commented on inc/customizer/extend-custom-controls/src/common/astra-color-picker-control.js
> +	return (
@premanshup - Do confirm if the SVG can be kept here or shall we move it to common SVG file.

2021-05-07 06:58 UTC, patilvikasj commented on inc/core/common-functions.php
> +		$hex = apply_filters( 'astra_before_fg_color_generate', $hex );
Done.

2021-05-07 09:34 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/common/astra-color-picker-control.js
> +	return (
@vrundakansara I think we can keep it here only since it is not going to be used in the frontend. This will be only used in the customizer.

2021-05-07 10:40 UTC, vrundakansara approved these changes

2021-05-10 04:56 UTC, rohitp-bsf approved these changes

2021-05-10 04:58 UTC, merged