Gcp elementor
brainstormforce/astra pull request #2672
Opened 2021-04-28 13:38 UTC by patilvikasj

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-26 12:37 UTC, Nikschavan commented on inc/compatibility/class-astra-elementor.php
> +		public function display_global_colors_front_end( $response, $handler, \WP_REST_Request $request ) {
We are not checking the route like it is checked in `elementor_add_theme_colors()`, does this mean this method will run on all the rest api calls?

2021-05-26 12:38 UTC, Nikschavan commented on inc/compatibility/class-astra-elementor.php
> +			$response = new \WP_REST_Response(
You can `use WP_REST_Response` at the start of the file.

2021-05-26 12:38 UTC, Nikschavan commented on inc/compatibility/class-astra-elementor.php
> +			$response = new \WP_REST_Response(
Same for `WP_REST_Request`

2021-05-26 12:39 UTC, Nikschavan reviewed
Added a few questions

2021-05-27 06:21 UTC, patilvikasj commented on inc/compatibility/class-astra-elementor.php
> +		public function display_global_colors_front_end( $response, $handler, \WP_REST_Request $request ) {
I have added a check at the beginning of the method now.

2021-05-27 06:22 UTC, patilvikasj commented on inc/compatibility/class-astra-elementor.php
> +			$response = new \WP_REST_Response(
Using `rest_ensure_response` function instead now.

2021-05-27 06:26 UTC, Nikschavan approved these changes

2021-05-27 14:30 UTC, premanshup commented
@patilvikasj For Dark theme, the background color is not appearing properly for Theme related Global Color - [https://share.bsf.io/OAuQmAmo](https://share.bsf.io/OAuQmAmo), please check.

2021-05-27 14:50 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +		let resetValue =
```suggestion
		const resetValue =
```

2021-05-27 14:52 UTC, premanshup requested changes

2021-05-27 14:52 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +					let paletteLables = astra.customizer.globalPaletteLabels;
```suggestion
					const paletteLables = astra.customizer.globalPaletteLabels;
```

2021-05-27 14:52 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/common/astra-color-picker-control.js
> +			let paletteLables = astra.customizer.globalPaletteLabels;
```suggestion
			const paletteLables = astra.customizer.globalPaletteLabels;
```

2021-05-28 04:23 UTC, vrundakansara approved these changes

2021-06-01 11:08 UTC, patilvikasj commented
> @patilvikasj For Dark theme, the background color is not appearing properly for Theme related Global Color - https://share.bsf.io/OAuQmAmo, please check.

@premanshup  We are now losing style for dark mode also.

2021-06-01 11:16 UTC, premanshup approved these changes

2021-06-01 11:17 UTC, merged