AST-83 - improvement: Added responsive control for 'Display Site Title' and 'Display Site Tagline' settings
brainstormforce/astra pull request #2675
Opened 2021-04-29 09:55 UTC by abhishek-bsf

### Description
Task- https://wp-astra.atlassian.net/browse/AST-83

### Types of changes
New feature (non-breaking change which adds functionality)

### How has this been tested?
Tested whether new controls works properly and displays Site Title and Tagline based on settings selected.

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests

2021-05-06 10:03 UTC, premanshup requested changes

2021-05-06 10:03 UTC, premanshup commented on assets/js/unminified/customizer-preview.js
> +			var dynamicStyle = '.ast-site-title-wrap .site-description { display: ' + desktop_tagline_visibility + ';} @media( max-width: 921px ) { .ast-site-title-wrap .site-description { display: ' + tablet
@abhishek-bsf Please make the breakpoints dynamic. Check the same for dynamic CSS as well. It should work with our breakpoint filter.

2021-05-07 10:13 UTC, abhishek-bsf commented on inc/theme-update/astra-update-functions.php
> +			error_log( sprintf( 'Astra: Migrating Background Response Option - %s', $option_name ) ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
Done, removed.

2021-05-07 10:14 UTC, abhishek-bsf commented on inc/customizer/extend-custom-controls/src/index.js
>  import { BoxShadowControl }  from './box-shadow/control.js';
We have not made any changes to this line in this PR.

2021-05-07 10:19 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/index.js
>  import { BoxShadowControl }  from './box-shadow/control.js';
@abhishek-bsf I agree, this code is there since previous versions but can you please add correct naming convention?

2021-05-07 10:35 UTC, abhishek-bsf commented on inc/customizer/extend-custom-controls/src/responsive-toggle-control/responsive-toggle-control-component.js
> +            </Fragment>;
Verified! divider classes works with this control.

2021-05-07 10:36 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/responsive-toggle-control/responsive-toggle-control-component.js
> +            </Fragment>;
@abhishek-bsf Thank you!

2021-05-07 10:37 UTC, abhishek-bsf commented on inc/customizer/extend-custom-controls/src/customizer.js
> +						}
The current ``context`` parameter of control used to conditionally display settings only support ``non-array``. Here we adding support of array value for context.

2021-05-07 10:41 UTC, abhishek-bsf commented on inc/customizer/custom-controls/assets/css/unminified/responsive-toggle-control.css
> +.customize-control-ast-responsive-toggle-control .ast-responsive-toggle-control-wrapper .ast-responsive-slider-btns {
Done, updated class name.

2021-05-07 10:53 UTC, abhishek-bsf commented on inc/customizer/extend-custom-controls/src/common/responsive-helper.js
> +    jQuery( '.customize-control-ast-responsive-toggle-control .ast-responsive-slider-btns li' ).removeClass( 'active' );
Done, updated class name.

2021-05-07 10:53 UTC, abhishek-bsf commented on inc/customizer/extend-custom-controls/src/responsive-toggle-control/responsive-toggle-control-component.js
> +      responsiveHtml = <ul key={'ast-resp-ul'} className="ast-responsive-slider-btns">
Done, updated class name.

2021-05-07 10:54 UTC, abhishek-bsf commented on inc/customizer/extend-custom-controls/src/responsive-toggle-control/responsive-toggle-control-component.js
> +    const [props_value, setPropsValue] = useState(props.control.setting.get());
Done, changed props_value to propsValue.

2021-05-07 11:13 UTC, abhishek-bsf commented on inc/customizer/extend-custom-controls/src/responsive-toggle-control/responsive-toggle-control-component.js
> +	let inputHtml = null;
Updated and used const for ``inputHtml``.
For ``responsiveHtml`` - we are assigning value to ``responsiveHtml`` inside ``if`` condition ( [reference](https://github.com/brainstormforce/astra/pull/2675/files#diff-ddfd5f2daceaeaa39efee9fcd172187e3d3d98a400eae520a3bd2df1d7ca4c2eR15) ). If we declare it as a const, it will return undefined console error.

2021-05-07 11:38 UTC, abhishek-bsf commented on inc/customizer/extend-custom-controls/src/index.js
>  import { BoxShadowControl }  from './box-shadow/control.js';
Done, changed ``BoxShadowControl`` to ``boxShadowControl`` here as well as other required places.

2021-05-07 13:48 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/index.js
>  import { BoxShadowControl }  from './box-shadow/control.js';
@abhishek-bsf Thank you!

2021-05-07 13:50 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/responsive-toggle-control/responsive-toggle-control-component.js
> +	let inputHtml = null;
@abhishek-bsf Right!

2021-05-07 14:20 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/customizer.js
> +						}
@abhishek-bsf Okay, as discussed, please mention test cases for this as well in the task.

2021-05-07 14:21 UTC, abhishek-bsf commented on inc/customizer/extend-custom-controls/src/customizer.js
> +						}
Sure!

2021-05-07 15:04 UTC, abhishek-bsf commented on inc/theme-update/astra-update-functions.php
> + * Migrate Site Title Responsive options to new array.
Updated comment.

2021-05-07 15:05 UTC, abhishek-bsf commented on inc/theme-update/astra-update-functions.php
> +		'display-site-tagline',
Done, created new setting key or responsive options.

2021-05-11 14:08 UTC, premanshup approved these changes

2021-05-11 14:43 UTC, sagarb90 approved these changes

2021-05-12 04:08 UTC, imnavanath commented
@abhishek-bsf I checked with free theme only (addon is deactivate) Tagline not hiding not working. - https://share.bsf.io/nOuoyjEr (for all devices)
Also branch is not upto-date please pull latest next-release in it.

2021-05-12 04:15 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/common/responsive-helper.js
> +function astra_add_dynamic_css( control, style ) {
@abhishek-bsf we already have same named function `astra_add_dynamic_css` in assests/js/unminified/customizer.js so is it necessary here to introduce this again? Can that function reuse her? If No & it's needed can we rename this specifically. As already same function exists.

2021-05-12 13:13 UTC, abhishek-bsf commented on inc/customizer/extend-custom-controls/src/common/responsive-helper.js
> +function astra_add_dynamic_css( control, style ) {
``astra_add_dynamic_css()`` declared in ``customizer.js`` cannot be called here. I have renamed this function instead.

2021-05-26 06:23 UTC, imnavanath commented on inc/customizer/configurations/layout/class-astra-site-identity-configs.php
> +					'control'  => 'ast-divider',
instead of this control @abhishek-bsf can we use `'divider'    => array( 'ast_class' => 'ast-bottom-divider' ),` thing here.

2021-05-26 06:29 UTC, imnavanath commented on inc/class-astra-dynamic-css.php
> +			$desktop_title_visibility   = ( ( astra_get_option( 'display-site-title-responsive' ) )['desktop'] ) ? 'block' : 'none';
can you update like this - 
`( $site_tagline_setting['desktop'] || $site_tagline_setting['tablet'] || $site_tagline_setting['mobile'] ) ? true : false;`

2021-05-26 06:38 UTC, abhishek-bsf commented on inc/customizer/configurations/layout/class-astra-site-identity-configs.php
> +					'control'  => 'ast-divider',
We are using this divider below Tagline control. As this tagline control is of WordPress and not our own control, we cannot use our divider property with it.

2021-05-26 06:40 UTC, abhishek-bsf commented on inc/class-astra-dynamic-css.php
> +			$desktop_title_visibility   = ( ( astra_get_option( 'display-site-title-responsive' ) )['desktop'] ) ? 'block' : 'none';
We cannot use ``true`` or ``false`` here because it cant be used as value of ``display`` style which we are using hide/show Title and Tagline.

2021-05-26 06:53 UTC, imnavanath commented on inc/class-astra-dynamic-css.php
> +			$desktop_title_visibility   = ( ( astra_get_option( 'display-site-title-responsive' ) )['desktop'] ) ? 'block' : 'none';
Yes right, I wanted to give just an example with formatting and avoiding `astra_get_option( 'display-site-title-responsive' )` thrice. Which we can call once `$site_tagline_setting` and use further for desktop|tablet|mobile.

2021-05-26 07:43 UTC, abhishek-bsf commented on inc/class-astra-dynamic-css.php
> +			$desktop_title_visibility   = ( ( astra_get_option( 'display-site-title-responsive' ) )['desktop'] ) ? 'block' : 'none';
Done! Made changes.

2021-05-28 06:39 UTC, merged