AST-413 - refactor: Removed extra CSS from dynamic CSS which loads already from static CSS
brainstormforce/astra pull request #2682
Opened 2021-04-30 13:26 UTC by imnavanath

### Description
- Removed extra CSS from dynamic CSS which loads already from static CSS

### Screenshots
- https://share.bsf.io/mXupv76Q

### Types of changes
- Non-breaking change 

### How has this been tested?
- With cart element 

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-04-30 13:48 UTC, abhishek-bsf submitted a review, later dismissed

2021-05-03 11:53 UTC, premanshup requested changes

2021-05-03 11:53 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> -			}
@imnavanath Keep this CSS  in SVG disable condition instead removing this to maintain backward comp.

2021-05-05 10:41 UTC, imnavanath commented on inc/class-astra-dynamic-css.php
> -			}
Done 👍

2021-05-05 11:24 UTC, abhishek-bsf submitted a review, later dismissed

2021-05-05 11:28 UTC, sagarb90 approved these changes

2021-05-06 10:28 UTC, premanshup submitted a review, later dismissed

2021-05-13 09:12 UTC, premanshup approved these changes

2021-05-13 09:14 UTC, sagarb90 approved these changes

2021-05-13 09:15 UTC, merged