AST-271 - improvement: Improved accessibility for Search button
brainstormforce/astra pull request #2686
Opened 2021-05-03 06:08 UTC by abhishek-bsf

### Description
Task- https://wp-astra.atlassian.net/browse/AST-271

### Screenshots
Before- https://share.getcloudapp.com/Jru45N8E
After- https://share.getcloudapp.com/Z4uo2Pmq

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
Tested using Lighthouse if the search button accessibility issue is fixed.

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-03 09:01 UTC, imnavanath submitted a review, later dismissed

2021-05-03 09:53 UTC, premanshup approved these changes

2021-05-03 09:55 UTC, premanshup commented on changelog.txt
> +- Improvement: Improved accessibility for Search button.
```suggestion
- Fix: Added accessibility for search button of search form.
```

2021-05-03 09:56 UTC, premanshup submitted a review, later dismissed

2021-05-03 09:59 UTC, abhishek-bsf commented on changelog.txt
> +- Improvement: Improved accessibility for Search button.
Done! Updated changelog text.

2021-05-03 10:20 UTC, premanshup submitted a review, later dismissed

2021-05-03 10:21 UTC, imnavanath approved these changes

2021-05-03 17:23 UTC, Nikschavan requested changes

2021-05-03 17:23 UTC, Nikschavan commented on searchform.php
> +			<button class="search-submit" aria-label="search-submit">
```suggestion
			<button class="search-submit" aria-label="<?php esc_html_e( 'Search Submit', 'astra' ); ?>">
```

This text will be read aloud by the accessibility assisting devices and should be a text that defines this button rather than `search-submit`

2021-05-05 07:27 UTC, abhishek-bsf commented on searchform.php
> +			<button class="search-submit" aria-label="search-submit">
Resolved! Changed the value of ``aria-label`` attribute.

2021-05-05 09:40 UTC, premanshup approved these changes

2021-05-05 09:43 UTC, merged

2021-05-05 09:44 UTC, imnavanath approved these changes

2021-05-05 09:44 UTC, imnavanath approved these changes