feat: Added new options in Related Posts
brainstormforce/astra pull request #2687
Opened 2021-05-03 06:47 UTC by imnavanath

### Description
- Added new option in Related Posts
- 1. Related Posts title text
- 2. Title text alignment

### Screenshots
- https://share.bsf.io/nOuoJp6p

### Types of changes
- New improvement

### How has this been tested?
- With Related Posts in Astra
- Check by navigating this branch with designing Related Posts in `master` version

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-05-04 05:05 UTC, vrundakansara approved these changes

2021-05-04 09:21 UTC, sagarb90 approved these changes

2021-05-04 13:58 UTC, premanshup commented on changelog.txt
>  - Fix: PHP error with Uncaught Error: Class 'Astra_Icons' not found in searchform.php when using plugin 'LearnDash Ratings Review Feedbacks'.
@imnavanath Please move this changelog to v3.5.0 and remove v3.4.0.

2021-05-04 14:26 UTC, premanshup requested changes

2021-05-04 14:26 UTC, premanshup commented on inc/modules/related-posts/class-astra-related-posts-markup.php
> +						echo '<div class="ast-related-posts-wrapper ast-posts-grid">'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
@imnavanath I think we can combine these two CSS classes and have only single CSS class here?

2021-05-04 14:26 UTC, premanshup commented on inc/modules/related-posts/customizer/class-astra-related-posts-configs.php
> +				'title'    => __( 'Related Posts Title', 'astra' ),
@imnavanath No need to add duplicate `Related Posts` string - Just keep `Title`  - https://share.bsf.io/Jru4EWnR

2021-05-04 14:26 UTC, premanshup commented on inc/modules/related-posts/customizer/class-astra-related-posts-configs.php
> +				'title'      => __( 'Alignment', 'astra' ),
@imnavanath Please change this to `Title Alignment` to avoid confusion - https://share.bsf.io/8LubNJ1B

2021-05-04 14:26 UTC, premanshup commented on inc/theme-update/astra-update-functions.php
> +
```suggestion

```

2021-05-04 14:26 UTC, premanshup commented on inc/theme-update/astra-update-functions.php
> +	update_option( 'astra-settings', $theme_options );
@imnavanath Should this update_option come inside `if` condition?

2021-05-05 06:14 UTC, imnavanath commented on inc/theme-update/astra-update-functions.php
> +	update_option( 'astra-settings', $theme_options );
Done 👍

2021-05-05 06:14 UTC, imnavanath commented on inc/theme-update/astra-update-functions.php
> +
Done 👍

2021-05-05 06:15 UTC, imnavanath commented on inc/modules/related-posts/customizer/class-astra-related-posts-configs.php
> +				'title'      => __( 'Alignment', 'astra' ),
Done 👍

2021-05-05 06:15 UTC, imnavanath commented on inc/modules/related-posts/customizer/class-astra-related-posts-configs.php
> +				'title'    => __( 'Related Posts Title', 'astra' ),
Done 👍

2021-05-05 06:15 UTC, imnavanath commented on inc/modules/related-posts/class-astra-related-posts-markup.php
> +						echo '<div class="ast-related-posts-wrapper ast-posts-grid">'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
Done 👍

2021-05-05 06:15 UTC, imnavanath commented on changelog.txt
>  - Fix: PHP error with Uncaught Error: Class 'Astra_Icons' not found in searchform.php when using plugin 'LearnDash Ratings Review Feedbacks'.
Done 👍

2021-05-06 10:11 UTC, premanshup approved these changes

2021-05-07 07:54 UTC, merged