fix: menu close issue when resize event trigger on keyboard display
brainstormforce/astra pull request #2694
Opened 2021-05-04 05:43 UTC by shubhw12

### Description
I have added a condition check before we trigger the menu toggle logic in the window.resize event callback.

### Types of changes
Bugfix (non-breaking change which fixes an issue)

### How has this been tested?
Checked if the closes after resize?
Checked if the menu closes if the active element is input field.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-04 05:53 UTC, premanshup commented
@shubhw12 Please update changelog in this as well for v3.5.0.

2021-05-11 12:41 UTC, premanshup requested changes

2021-05-11 12:41 UTC, premanshup commented on assets/js/unminified/frontend.js
> +		var menu_close_flag = 'INPUT' !== document.activeElement.tagName;
```suggestion
		var menuCloseFlag = 'INPUT' !== document.activeElement.tagName;
```

2021-05-12 09:02 UTC, premanshup approved these changes

2021-05-12 09:56 UTC, sagarb90 commented
@shubhw12 Got this console error - https://share.getcloudapp.com/7KuPGB4q please check.
I have also confirmed this error is not in `next-release`  branch.

2021-05-12 12:21 UTC, imnavanath approved these changes

2021-05-12 12:44 UTC, abhishek-bsf approved these changes

2021-05-12 13:47 UTC, shubhw12 commented
> @shubhw12 Got this console error - https://share.getcloudapp.com/7KuPGB4q please check.
> I have also confirmed this error is not in `next-release` branch. May be pull `next-release` branch will resolved this issue

I have pulled the latest code here and that resolves this console error

2021-05-12 13:48 UTC, merged