AST-435 - imprv : remove HTML widget related static CSS and move it to dynamic with conditions
brainstormforce/astra pull request #2701
Opened 2021-05-04 13:15 UTC by sagarb90

### Description
- Remove HTML widget related static CSS and move it to dynamic with conditions
- https://wp-astra.atlassian.net/browse/AST-435

### Screenshots

### Types of changes
- Improvements

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-06 15:10 UTC, premanshup requested changes

2021-05-06 15:10 UTC, premanshup commented on inc/builder/type/footer/html/dynamic-css/dynamic.css.php
> +			),
@sagarb90 Adding CSS here will add it in loop and multiple CSS will be added. Can you please check if we should keep this outside of loop?

2021-05-06 15:10 UTC, premanshup commented on sass/site/builder/_header.scss
> + .ast-builder-social-element {
```suggestion
.ast-builder-social-element {
```

2021-05-06 15:10 UTC, premanshup commented on sass/site/builder/_header.scss
> +
```suggestion

```

2021-05-06 15:10 UTC, premanshup commented on sass/site/builder/_header.scss
> +
```suggestion

```

2021-05-11 07:23 UTC, sagarb90 commented on inc/builder/type/footer/html/dynamic-css/dynamic.css.php
> +			),
Yes added to outside of loop

2021-05-11 14:31 UTC, premanshup commented on inc/builder/type/footer/html/dynamic-css/dynamic.css.php
> +			),
Thank you!

2021-05-11 14:32 UTC, premanshup approved these changes

2021-05-26 07:37 UTC, merged