AST-436 - imprv: Remove icon related static CSS and load only when svg icon display off
brainstormforce/astra pull request #2702
Opened 2021-05-05 06:59 UTC by sagarb90

### Description
- Remove icon related static CSS and load only when SVG icon displays off.
- https://wp-astra.atlassian.net/browse/AST-436

### Screenshots

### Types of changes
- Improvements

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-06 15:15 UTC, premanshup requested changes

2021-05-06 15:15 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +			}
@sagarb90 Let's remove this from here and add `astra_dynamic_css` filter with appropriate priority and add CSS on that filter in `inc/dynamic-css/astra-icons.php` file only. Make sure that we avoid adding new code to this file as much as possible.

2021-05-11 07:36 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> +			}
Yes right, I removed the condition from `astra_dynamic_css` and handle in `inc/dynamic-css/astra-icons.php` file itself using the filter.

2021-05-11 14:34 UTC, premanshup approved these changes

2021-05-26 10:14 UTC, merged