imprv: remove static CSS related to hf button omponent and move to it dynamic CSS conditionally.
brainstormforce/astra pull request #2707
Opened 2021-05-05 09:09 UTC by sagarb90

### Description
- Remove static CSS related to HF button component and move to it dynamic CSS conditionally.
- https://wp-astra.atlassian.net/browse/AST-440

## Screenshots

### Types of changes
- Improvements

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-06 16:52 UTC, premanshup requested changes

2021-05-06 16:52 UTC, premanshup commented on sass/site/builder/_header.scss
>  }
@sagarb90 This CSS can also be moved conditionally, can you please check this and confirm?

2021-05-11 14:44 UTC, premanshup commented on sass/site/builder/_header.scss
>  }
Can we move this directly to the header button dynamic CSS file - `\wp-content\themes\astra\inc\builder\type\header\button\dynamic-css\dynamic.css.php`? You still have to add one more condition I think. Let me know if this will work?

2021-05-11 14:44 UTC, premanshup commented on sass/site/builder/_header.scss
>  }
@sagarb90 Can we move this directly to the header button dynamic CSS file - `\wp-content\themes\astra\inc\builder\type\header\button\dynamic-css\dynamic.css.php`? You still have to add one more condition I think. Let me know if this will work?

2021-05-13 09:42 UTC, sagarb90 commented on sass/site/builder/_header.scss
>  }
@premanshup Yes we can add using condition but again it's not a single component we need to add [this ](https://share.getcloudapp.com/8LubARNP)code to check is button is loaded or not just for single CSS in the file that you have mentioned.

2021-05-27 05:14 UTC, sagarb90 commented on sass/site/builder/_header.scss
>  }
@premanshup Yes added condition [here](https://github.com/brainstormforce/astra/pull/2707/files#diff-7565620b2515827fea1cbb69672e3b4fe3db13241bf8d302a7f7c6ad2bc14c45R37)

2021-05-27 05:19 UTC, premanshup approved these changes

2021-05-27 05:19 UTC, merged