AST-445 - imprv: remove static CSS related to site logo and move it to dynamic conditionally
brainstormforce/astra pull request #2708
Opened 2021-05-05 11:15 UTC by sagarb90

### Description
 - Remove static CSS related to site logo and move it to dynamic conditionally.
 - https://wp-astra.atlassian.net/browse/AST-445
 
### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-06 16:56 UTC, premanshup requested changes

2021-05-06 16:56 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +			if ( get_theme_mod( 'custom_logo' ) || is_customize_preview() ) {
@sagarb90 Please verify the condition when normal logo is not added but logo is added from Transparent header or Sticky header or Page Header. 
1. Is this CSS needed for above types of logos?
2. If yes, then does this condition work properly with the these conditions?

2021-05-11 14:47 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +			if ( get_theme_mod( 'custom_logo' ) || is_customize_preview() ) {
@sagarb90 Can you check the blackfire report and page load report how much difference does it make? Further, In theme, we can keep just transparent header condition. Sticky and Page Header conditions can go in addon, let me know if this will help us reduce the conditions?

2021-05-13 09:34 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> +			if ( get_theme_mod( 'custom_logo' ) || is_customize_preview() ) {
@premanshup Yes I will check the report, but if we add conditions in add-on then we need again add same CSS then if     add-on is activated then this leads to duplicate CSS from theme and add-on

2021-05-22 03:34 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +			if ( get_theme_mod( 'custom_logo' ) || is_customize_preview() ) {
@sagarb90 Yes, that will lead to duplicate CSS. Can we check the stats by adding all the condition? Are we getting any optimization or not? If not, we can leave this as it is.

2021-05-26 07:42 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> +			if ( get_theme_mod( 'custom_logo' ) || is_customize_preview() ) {
Yes as there is only 2 CSS for logo which we have removed and adding these condition in PHP is no any impact on stats means this will not be showing any optimization.

2021-05-26 09:04 UTC, premanshup approved these changes

2021-05-26 09:10 UTC, merged