AST-438 - imprv: removed static CSS related to comments and load from dynamic
brainstormforce/astra pull request #2710
Opened 2021-05-06 06:13 UTC by sagarb90

### Description
- Removed static CSS related to comments and load from dynamic.
- Also removed duplicate CSS from dynamic CSS.
- https://wp-astra.atlassian.net/browse/AST-438

### Screenshots

### Types of changes
- Improvements

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-06 16:42 UTC, premanshup requested changes

2021-05-06 16:42 UTC, premanshup commented on inc/dynamic-css/comments-flex.php
> +		}
@sagarb90 Why are we adding this additional CSS for comment?

2021-05-06 16:42 UTC, premanshup commented on inc/dynamic-css/comments-flex.php
> +		}
@sagarb90 Here as well.

2021-05-06 16:42 UTC, premanshup commented on inc/dynamic-css/comments.php
> +        }
```suggestion
      .ast-separate-container .comment-respond {
        padding: 3em 2.34em;
      }
```

2021-05-11 07:41 UTC, sagarb90 commented on inc/dynamic-css/comments-flex.php
> +		}
This is not additional CSS this was in the main `astra_dynamic_css` file and have moved it to the comment CSS file.

2021-05-11 07:42 UTC, sagarb90 commented on inc/dynamic-css/comments-flex.php
> +		}
This is not additional CSS this was in the main `astra_dynamic_css` file and have moved it to the comment CSS file.

2021-05-11 14:37 UTC, premanshup commented on inc/dynamic-css/comments-flex.php
> +		}
Okay 👍🏼

2021-05-26 09:16 UTC, merged