AST-441 - imprv:  Remove static CSS related to Inline on mobile and move to dynamic conditionally
brainstormforce/astra pull request #2711
Opened 2021-05-06 07:53 UTC by sagarb90

### Description
- Remove static CSS related to Inline on mobile and move to dynamic conditionally.
- https://wp-astra.atlassian.net/browse/AST-441

### Screenshots

### Types of changes
- Improvements

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-07 14:48 UTC, premanshup requested changes

2021-05-07 14:48 UTC, premanshup commented on inc/dynamic-css/inline-on-mobile.php
> +		if ( ! astra_get_option( 'header-menu' . $index . '-menu-stack-on-mobile' ) ) {
```suggestion
		if ( false !== astra_get_option( 'header-menu' . $index . '-menu-stack-on-mobile' ) ) {
```

2021-05-11 10:16 UTC, sagarb90 commented on inc/class-astra-dynamic-css.php
> +			$parse_css .= astra_inline_on_mobile_css();
Yes done.

2021-05-11 14:49 UTC, premanshup approved these changes

2021-05-11 14:50 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +			$parse_css .= astra_inline_on_mobile_css();
Thank you!

2021-05-26 09:34 UTC, merged