AST-451 - feat: Added new border width option for WooCommerce & EDD cart elements for style Outline
brainstormforce/astra pull request #2712
Opened 2021-05-06 10:21 UTC by imnavanath

### Description
- Added new border width option for outline 
- To fix this issue we can have option to control border width

### Screenshots
- Main issue after update v3.4.0 - https://d.pr/i/JvniZO (border directly visible on frontend)
- https://share.bsf.io/xQubkKw5

### Types of changes
- Bug fix
- New feature 

### How has this been tested?
- Check with the backwards
- With outline cart style

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-05-06 11:55 UTC, shubhw12 approved these changes

2021-05-06 12:47 UTC, sagarb90 approved these changes

2021-05-06 12:53 UTC, abhishek-bsf requested changes
@imnavanath Could you please update the changelog as well.

2021-05-07 06:42 UTC, imnavanath commented
> @imnavanath Could you please update the changelog as well.

Done @abhishek-bsf thank you 👍

2021-05-07 13:39 UTC, premanshup submitted a review, later dismissed

2021-05-10 03:27 UTC, imnavanath commented on changelog.txt
> +- Improvement: Builder - WooCommerce & EDD Cart - Compatibility with Border width option for cart outline style.
Done 👍

2021-05-12 15:10 UTC, premanshup approved these changes

2021-05-13 07:15 UTC, abhishek-bsf approved these changes

2021-05-13 08:02 UTC, abhishek-bsf approved these changes

2021-05-13 08:46 UTC, merged