AST-452 - imprv: removed default loading of search component related CSS and load conditionally from dynamic CSS
brainstormforce/astra pull request #2722
Opened 2021-05-07 13:07 UTC by sagarb90

### Description
- Removed default loading of search component related CSS and load conditionally from dynamic CSS.
- We have removed only for New HFB and for Old HFB we kept as its as there is no way add conditional or need to to add in a separate place.
- https://wp-astra.atlassian.net/browse/AST-452

### Screenshots

### Types of changes
- Improvements

### How has this been tested?
- Test search component related CSS in all devices.

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-11 16:40 UTC, premanshup requested changes

2021-05-11 16:40 UTC, premanshup commented on sass/site/_main.scss
> +@import "site-normalize/site-normalize-builder";
@sagarb90 Can you please explain why we are loading new file called `site-normalize-builder`?

2021-05-11 16:40 UTC, premanshup commented on inc/builder/type/header/search/dynamic-css/dynamic.css.php
> +	}
@sagarb90 This CSS is not removed from this code and still we are loading this in here. Any reason?

2021-05-11 16:40 UTC, premanshup commented on inc/builder/type/header/search/dynamic-css/dynamic.css.php
> +		}
@sagarb90 Is this CSS duplicated with dynamic CSS - https://github.com/brainstormforce/astra/pull/2722/files#diff-1fa603c7b6bf95f4695a33ac8649f3b4445613784707b6b07e36b74bb1819e6aR68. Please check!

2021-05-12 03:48 UTC, imnavanath commented
@sagarb90 facing this case where left-right spacing is missing https://share.bsf.io/X6ueywy6 (same thing I noticed in next-release as well) so probably not issue in this PR. But if we can fix this one in current PR would be much better.

2021-05-26 06:21 UTC, sagarb90 commented on sass/site/_main.scss
> +@import "site-normalize/site-normalize-builder";
Reverted this as this is related to OLD HFB and which is already handle in this [PR  ](https://github.com/brainstormforce/astra/pull/2737)

2021-05-26 12:47 UTC, sagarb90 commented on inc/builder/type/header/search/dynamic-css/dynamic.css.php
> +	}
This CSS should be removed from here I hade added here but this is common CSS in OLD and New HFB so I have by mistake added but not removed. and our search dynamic CSS is in builder folder so we can't add here

2021-05-26 12:47 UTC, sagarb90 commented on inc/builder/type/header/search/dynamic-css/dynamic.css.php
> +		}
Yes this was duplicate in dynamic and removed

2021-05-26 12:58 UTC, sagarb90 commented
> @sagarb90 facing this case where left-right spacing is missing https://share.bsf.io/X6ueywy6 (same thing I noticed in next-release as well) so probably not issue in this PR. But if we can fix this one in current PR would be much better.

I have check this in current and master branch as well this look correct at my end - https://share.getcloudapp.com/9ZudenWB

2021-05-26 13:48 UTC, premanshup approved these changes

2021-05-26 13:48 UTC, merged