AST-465 - feat: Moved Site Tagline section's color controls from addon to theme
brainstormforce/astra pull request #2734
Opened 2021-05-10 07:29 UTC by imnavanath

### Description
- Moved Addon's tagline section's color controls into theme
- Following color controls are being moved
- 1. Site Title color
- 2. Site Title Hover color
- 3. Site Tagline color

### Screenshots
- https://share.bsf.io/12uA8xo8

### Types of changes
- New options (just moved from addon to theme)

### How has this been tested?
- Following test cases needs to be consider while testing this task
- 1. Check with update only theme
- 2. Check with update only addon
- 3. Check with deactivating all addon's from Pro
- 4. With old header's Site Tagline section
- 5. With new header builder's Logo element
- 6. Check by using controls (in preview as well as on frontend)

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards
- [x] My code has proper inline documentation
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-05-11 13:30 UTC, premanshup requested changes

2021-05-11 13:30 UTC, premanshup commented on inc/builder/type/header/site-identity/assets/js/unminified/customizer-preview.js
> +
```suggestion

```

2021-05-11 13:30 UTC, premanshup commented on inc/customizer/configurations/layout/class-astra-site-identity-configs.php
> +			$load_site_tagline_color_controls = true;
@imnavanath Instead of introducing new variable can we directly use the condition?

2021-05-11 13:30 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +				'.site-title'                            => array(
@imnavanath Let's load this CSS conditionally. It should only load when Logo element is added to the header builder.

2021-05-11 13:30 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +			$tagline_color      = astra_get_option( 'header-color-site-tagline' );
@imnavanath Same as below comment.

2021-05-11 13:30 UTC, premanshup commented on inc/builder/type/header/site-identity/dynamic-css/dynamic.css.php
> +
```suggestion

```

2021-05-11 13:30 UTC, premanshup commented on inc/builder/type/header/site-identity/dynamic-css/dynamic.css.php
> -		$selector                          => array(
@imnavanath Was this CSS already available in the theme?

2021-05-12 05:01 UTC, imnavanath commented on inc/builder/type/header/site-identity/assets/js/unminified/customizer-preview.js
> -    );
We moved this in theme's overall customizer.js file because if you notice currently this file only scoped with HFB logo element (where we already have color options). But as introducing these in free theme (for old header case as well) so that needs to be work there as well.

That's why instead of rewriting this preview code again. I reused these in overall Astra (for both old+new header)

2021-05-12 05:07 UTC, imnavanath commented on inc/builder/type/header/site-identity/dynamic-css/dynamic.css.php
> -		$selector                          => array(
Yes its already there, current one is for new HFB-Logo element. 
So what I've done here is I removed this from logo element and made it work with both old & new header's logo element.

2021-05-14 09:09 UTC, imnavanath commented on inc/builder/type/header/site-identity/dynamic-css/dynamic.css.php
> +
Done 👍

2021-05-14 09:09 UTC, imnavanath commented on inc/builder/type/header/site-identity/assets/js/unminified/customizer-preview.js
> +
Done 👍

2021-05-14 09:45 UTC, imnavanath commented on inc/customizer/configurations/layout/class-astra-site-identity-configs.php
> +			$load_site_tagline_color_controls = true;
We need this config in following cases - 
1. in free theme 
2. in addon's case as well (but only addon's version is lesser than 3.5.0)
So previously I tried to combine this case in single condition, but it satisfies all the time (whether theme/addon activated). Because only version compare not sufficient then this will only load iff addon is activate.

2021-05-14 09:55 UTC, imnavanath commented on inc/class-astra-dynamic-css.php
> +				'.site-title'                            => array(
But I think no need of add this conditionally, because anyways we are moving color options for both old & new header's logo section. So as I removed duplicate CSS from logo element & using this CSS globally for both old-new header's logo.

If I'm missing anything or any other point you are talking about we can discuss the case on call.

2021-05-14 09:57 UTC, imnavanath commented on inc/class-astra-dynamic-css.php
> +			$tagline_color      = astra_get_option( 'header-color-site-tagline' );
You mean above comment ? Like it should load conditionally?

2021-05-21 02:38 UTC, premanshup commented on inc/builder/type/header/site-identity/assets/js/unminified/customizer-preview.js
> -    );
@imnavanath Thank you for the explanation.

2021-05-21 02:40 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +			$tagline_color      = astra_get_option( 'header-color-site-tagline' );
Yep! Resolving this.

2021-05-21 02:42 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +				'.site-title'                            => array(
@imnavanath Okay got it! I think we can keep it common for both globally.

2021-05-21 02:45 UTC, premanshup approved these changes

2021-05-21 05:09 UTC, abhishek-bsf approved these changes

2021-05-21 07:00 UTC, sagarb90 approved these changes

2021-05-24 12:10 UTC, merged