AST-395 - fix: Dropdown menu disappears while scrolling on mobile device
brainstormforce/astra pull request #2752
Opened 2021-05-12 10:30 UTC by abhishek-bsf

### Description
Task- https://wp-astra.atlassian.net/browse/AST-395

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
Tested the fix on Browser Stack mobile device simulator

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-12 10:36 UTC, sagarb90 commented on assets/js/unminified/frontend.js
> +	var mobile_width = window.innerWidth;
@abhishek-bsf Please check this @shubhw12 's [PR](https://github.com/brainstormforce/astra/pull/2694/files#diff-028c69d8b9d2a3a3d3fec58fb1c21286b6c64b80fe2377d34c8ef0583d5cb1aeR424) He has also changed code on the same line/function you may face conflict while merging make sure to confirm a single change for these 2 issues.

2021-05-12 10:40 UTC, abhishek-bsf commented on assets/js/unminified/frontend.js
> +	var mobile_width = window.innerWidth;
Sure! Will resolve conflicts once the mentioned PR is merged.

2021-05-13 04:49 UTC, premanshup commented on assets/js/unminified/frontend.js
> +	var mobile_width = window.innerWidth;
@abhishek-bsf This PR is merged https://github.com/brainstormforce/astra/pull/2694/

2021-05-13 06:58 UTC, abhishek-bsf commented on assets/js/unminified/frontend.js
> +	var mobile_width = window.innerWidth;
@premanshup I took latest pull and tested my fixes. Could you please review the PR now?

2021-05-14 06:04 UTC, imnavanath approved these changes

2021-05-14 08:39 UTC, sagarb90 submitted a review, later dismissed

2021-05-14 12:16 UTC, premanshup requested changes

2021-05-14 12:16 UTC, premanshup commented on assets/js/unminified/frontend.js
> +		if ( window.innerWidth !== mobile_width ) {
@abhishek-bsf Can you please explain why we are checking `if ( window.innerWidth !== window.innerWidth ) {`
Since `mobile_width` is equal to `window.innerWidth`

2021-05-14 12:25 UTC, abhishek-bsf commented on assets/js/unminified/frontend.js
> +		if ( window.innerWidth !== mobile_width ) {
This block is executed inside ``resize`` event. The resize event is called when the screen size is changed(i.e. height or width of screen). In mobile phone when we scroll, the resize event occurs because height of screen changes, but width remains. So we are checking condition if width changes, then code inside if statement will be executed.

2021-05-14 12:53 UTC, premanshup commented on assets/js/unminified/frontend.js
> +		if ( window.innerWidth !== mobile_width ) {
@abhishek-bsf Thank you for the explanation.

2021-05-14 12:54 UTC, premanshup submitted a review, later dismissed

2021-05-18 05:31 UTC, merged