AST-419 - feat: added SVG logo height option to resolve the CLS issue
brainstormforce/astra pull request #2780
Opened 2021-05-20 13:42 UTC by sagarb90

### Description
- Added SVG logo height option to resolve the CLS issue
- We have introduced a new option in the customizer for SCG logo height as it is not getting applied by default like normal png logo.

### Screenshots
- https://share.getcloudapp.com/OAuPkpdb

### Types of changes
- New feature (non-breaking change which adds functionality) 

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-29 05:17 UTC, premanshup requested changes

2021-05-29 05:17 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/control-customizer.js
> +				let customizer_preview_container =  document.getElementById('customize-preview')
```suggestion
				const customizerPreviewContainer =  document.getElementById('customize-preview');
```

2021-05-29 05:17 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/control-customizer.js
> +				let iframe 						 = customizer_preview_container.getElementsByTagName('iframe')[0]
@sagarb90 Can we change the selector from TagName to maybe ID? There can be multiple iframes and in this case, it can target some other iframe.

2021-05-29 05:17 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/control-customizer.js
> +						var existingValues 	    = api('astra-settings[ast-header-responsive-logo-width]').get();
```suggestion
						let existingValues 	    = api('astra-settings[ast-header-responsive-logo-width]').get();
```

2021-05-29 05:17 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/control-customizer.js
> +						api('astra-settings[ast-header-responsive-logo-width]').set( existingValues );
@sagarb90 Instead of updating the existing array option for the same logo width, can we add hidden setting for SVG height separately?

2021-05-31 05:40 UTC, sagarb90 commented on inc/customizer/extend-custom-controls/src/control-customizer.js
> +						api('astra-settings[ast-header-responsive-logo-width]').set( existingValues );
@premanshup Yes I was implement first solution by adding hidden inputs but it has two drawbacks
1 . We Need to add responsive hidden control and as their is currently ast-hidden is non-responsive, I had added responsive hidden but facing some problem with updating responsive values as it get saved in JS settings but it does not get saved in DB `astra-settings` I tried all the possible ways also discuss with rohit as well but cant resolved it.
2. We need to register 2 more controls one for normal logo and other for transparent logo width  this will increase the total controls size and again some PHP code as well.

So I think this is best and optimize solution for this.

2021-05-31 05:51 UTC, sagarb90 commented on inc/customizer/extend-custom-controls/src/control-customizer.js
> +				let iframe 						 = customizer_preview_container.getElementsByTagName('iframe')[0]
@premanshup Yes but as I don't see any unique ID or class in the iframe tag so I used this 
ref- https://share.getcloudapp.com/5zuYprpZ

2021-05-31 05:52 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/control-customizer.js
> +				let iframe 						 = customizer_preview_container.getElementsByTagName('iframe')[0]
@sagarb90 Can we target it using tagName? I see there is name attr in the iFrame.

2021-05-31 05:55 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/control-customizer.js
> +						api('astra-settings[ast-header-responsive-logo-width]').set( existingValues );
@sagarb90 Okay, right considering the array size, I agree, we should go with this. Please make sure to check any backward compatibility cases. Resolving this thread.

2021-05-31 08:51 UTC, sagarb90 commented on inc/customizer/extend-custom-controls/src/control-customizer.js
> +				let iframe 						 = customizer_preview_container.getElementsByTagName('iframe')[0]
@premanshup No we can't use that name attr as it's value is dynamic and change sometime `customize-preview-0` and `customize-preview-2`.
https://share.getcloudapp.com/Kou4Gn2r

2021-05-31 08:55 UTC, sagarb90 commented on inc/customizer/extend-custom-controls/src/control-customizer.js
> +						var existingValues 	    = api('astra-settings[ast-header-responsive-logo-width]').get();
Done

2021-05-31 09:00 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/control-customizer.js
> +				let iframe 						 = customizer_preview_container.getElementsByTagName('iframe')[0]
@sagarb90 Okay!

2021-05-31 09:12 UTC, sagarb90 commented on inc/customizer/extend-custom-controls/src/control-customizer.js
> +				let customizer_preview_container =  document.getElementById('customize-preview')
Done

2021-05-31 10:04 UTC, premanshup submitted a review, later dismissed

2021-06-09 07:21 UTC, abhishek-bsf approved these changes

2021-06-09 08:02 UTC, premanshup approved these changes

2021-06-11 05:16 UTC, merged