Fix: page header layout 2 alignment issues for new users.
brainstormforce/astra pull request #2811
Opened 2021-05-31 08:02 UTC by shubhw12

### Description
I have added a flex-direction CSS specific to the page header layout 2 as this is related to layout 2 only.

### Screenshots

https://d.pr/i/iq7Sg1

### Types of changes
 Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
- Checked the same case or new users and old users.
- Checked the responsive devices.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-06-07 08:56 UTC, sagarb90 commented
@premanshup This PR was closed by @shubhw12 because these changes are related to add-on so he closed this and Open same from add-on.

2021-06-09 05:32 UTC, premanshup requested changes

2021-06-09 05:32 UTC, premanshup commented on sass/site/layout/_layout-flex.scss
> +}
@shubhw12 I think this CSS can be moved to addon inside Page Header related CSS, can you please check?

2021-06-09 05:32 UTC, premanshup commented on sass/site/layout/_layout-flex.scss
> +}
@shubhw12  Closing this - https://github.com/brainstormforce/astra/pull/2811#issuecomment-855744709

2021-06-09 05:33 UTC, closed without merging