AST-176 - WIP: feat: Introducing new self hosted Google fonts feature in Astra
brainstormforce/astra pull request #2814
Opened 2021-05-31 12:15 UTC by imnavanath

### Description
- Adding self hosted google fonts option to improvise Astra's performance

### Screenshots
- Astra's Performance section - https://share.bsf.io/JruDz5D5

### Types of changes
- New feature

### How has this been tested?
- With Astra google fonts
- With direct updation 

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-06-03 11:59 UTC, premanshup requested changes

2021-06-03 11:59 UTC, premanshup commented on inc/lib/webfont/class-astra-webfont-loader.php
> + * @license https://opensource.org/licenses/MIT
@imnavanath Let's mention this https://github.com/WPTT/webfont-loader in style.css and readme.txt

2021-06-03 11:59 UTC, premanshup commented on inc/lib/webfont/class-astra-webfont-loader.php
> +if ( ! class_exists( 'Astra_WebFont_Loader' ) ) {
```suggestion

```

2021-06-03 11:59 UTC, premanshup commented on inc/lib/webfont/class-astra-webfont-loader.php
> +}
@imnavanath I think this function is not called anywhere. If this is not required can remove this?

2021-06-03 11:59 UTC, premanshup commented on inc/lib/webfont/class-astra-webfont-loader.php
> +}
@imnavanath Can we move these two functions to `wp-content\themes\astra\inc\extras.php` since they are not part of the class.

2021-06-03 11:59 UTC, premanshup commented on changelog.txt
> +- New: Performance - Load Google Font locally option.
```suggestion
- New: Performance - Load Google Font locally.
- New: Performance - Preload locally hosted Google Font.
```

2021-06-03 11:59 UTC, premanshup commented on inc/customizer/class-astra-fonts.php
> +		if ( astra_get_option( 'load-google-fonts-locally', false ) && ! is_customize_preview() ) {
```suggestion
		if ( astra_get_option( 'load-google-fonts-locally' ) && ! is_customize_preview() ) {
```
Default is already defined.

2021-06-03 11:59 UTC, premanshup commented on inc/customizer/class-astra-customizer.php
> +
```suggestion

```

2021-06-03 11:59 UTC, premanshup commented on inc/customizer/class-astra-fonts.php
> +		$base_url  = 'https://fonts.googleapis.com/css';
@imnavanath Any reason why we are updating this?

2021-06-03 11:59 UTC, premanshup commented on inc/lib/webfont/class-astra-webfont-loader.php
> +				update_site_option( 'ast_downloaded_font_files', $stored );
@imnavanath Is this added for multisite? Or can we move this to `astra-settings` in options table?

2021-06-03 12:54 UTC, imnavanath commented on inc/lib/webfont/class-astra-webfont-loader.php
> +}
Yes removed, I noticed this later.
Removed 👍

2021-06-04 05:35 UTC, imnavanath commented on inc/lib/webfont/class-astra-webfont-loader.php
> + * @license https://opensource.org/licenses/MIT
Done 👍

2021-06-04 05:35 UTC, imnavanath commented on inc/lib/webfont/class-astra-webfont-loader.php
> +if ( ! class_exists( 'Astra_WebFont_Loader' ) ) {
Done 👍

2021-06-04 05:36 UTC, imnavanath commented on changelog.txt
> +- New: Performance - Load Google Font locally option.
Done 👍

2021-06-04 05:36 UTC, imnavanath commented on inc/customizer/class-astra-fonts.php
> +		if ( astra_get_option( 'load-google-fonts-locally', false ) && ! is_customize_preview() ) {
Correct, Done 👍

2021-06-04 05:36 UTC, imnavanath commented on inc/customizer/class-astra-customizer.php
> +
Done 👍

2021-06-04 05:36 UTC, imnavanath commented on inc/customizer/configurations/performance/class-astra-performance-configs.php
> +if ( ! class_exists( 'Astra_Performance_Configs' ) ) {
Done 👍

2021-06-04 05:37 UTC, imnavanath commented on inc/lib/webfont/class-astra-webfont-loader.php
> +	/**
Done 👍

2021-06-04 05:37 UTC, imnavanath commented on inc/lib/webfont/class-astra-webfont-loader.php
> +if ( ! class_exists( 'Astra_WebFont_Loader' ) ) {
Done 👍

2021-06-04 05:43 UTC, imnavanath commented on inc/lib/webfont/class-astra-webfont-loader.php
> +}
Done 👍

2021-06-04 06:30 UTC, imnavanath commented on inc/lib/webfont/class-astra-webfont-loader.php
> +				update_site_option( 'ast_downloaded_font_files', $stored );
Yes this is specifically for multisite. For saving concern in astra-settings - there can be huge dataset if number of fonts being used on site (for ex - https://share.bsf.io/z8uOq21R) So IMO it would be better if we go with separate option.

2021-06-04 06:32 UTC, imnavanath commented on inc/customizer/class-astra-fonts.php
> +		$base_url  = 'https://fonts.googleapis.com/css';
We updated this because wp_remote_get needs valid URL to fetch remote content - https://github.com/brainstormforce/astra/blob/self-hosted-google-fonts/inc/lib/webfont/class-astra-webfont-loader.php#L263

Default `//fonts.googleapis.com/css` gives `Not valid URL` return value.

2021-06-04 06:49 UTC, imnavanath commented on inc/lib/webfont/class-astra-webfont-loader.php
> +				update_site_option( 'ast_downloaded_font_files', $stored );
For network setup its working you can check here - 
Setup 1 - http://ast-dev.xka9ibwowp-jqp3vd915350.p.runcloud.link/local-google-fonts/testing-fonts/
Setup 2 - http://ast-dev.xka9ibwowp-jqp3vd915350.p.runcloud.link/local-google-fonts-2/testing-fonts/

2021-06-04 06:54 UTC, abhishek-bsf submitted a review, later dismissed

2021-06-04 09:52 UTC, premanshup commented on inc/lib/webfont/class-astra-webfont-loader.php
> +				update_site_option( 'ast_downloaded_font_files', $stored );
@imnavanath Great! Thank you for sharing the details.

2021-06-04 09:54 UTC, premanshup submitted a review, later dismissed

2021-06-08 05:34 UTC, premanshup requested changes

2021-06-08 05:34 UTC, premanshup commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls-plain.js
> +      $selection.append('&nbsp;<span class="select2-selection__choice__remove" role="presentation" aria-hidden="true">&times; </span>');
@imnavanath Can you please check why we are adding this change here?

2021-06-08 06:32 UTC, imnavanath commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls-plain.js
> +      $selection.append('&nbsp;<span class="select2-selection__choice__remove" role="presentation" aria-hidden="true">&times; </span>');
This change seems to be with the cross button we added in the select2 library.

2021-06-08 07:33 UTC, sagarb90 commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls-plain.js
> +      $selection.append('&nbsp;<span class="select2-selection__choice__remove" role="presentation" aria-hidden="true">&times; </span>');
Yes right. Please pull latest code.

2021-06-08 09:09 UTC, imnavanath commented on inc/customizer/class-astra-customizer.php
> +			if ( astra_get_option( 'load-google-fonts-locally' ) ) {
@premanshup I tried by storing this in a class variable but at the time of saving customizer or flushing Astra font files this fails. Don't get that value - https://share.bsf.io/Z4uKwgrN while saving - https://share.bsf.io/xQu70rzD

2021-06-08 09:27 UTC, imnavanath commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls-plain.js
> +      $selection.append('&nbsp;<span class="select2-selection__choice__remove" role="presentation" aria-hidden="true">&times; </span>');
Done 👍

2021-06-08 12:04 UTC, abhishek-bsf submitted a review, later dismissed

2021-06-09 06:22 UTC, premanshup commented on inc/customizer/class-astra-customizer.php
> +			if ( astra_get_option( 'load-google-fonts-locally' ) ) {
@imnavanath Have you tried static variable?

2021-06-09 06:27 UTC, imnavanath commented on inc/customizer/class-astra-customizer.php
> +			if ( astra_get_option( 'load-google-fonts-locally' ) ) {
Yes, @premanshup I tried that as well. 👍 Still faced the same result.

2021-06-09 06:43 UTC, premanshup approved these changes

2021-06-11 07:19 UTC, merged