AST-448 - fix: Multiselect close icon not showing on selected items.
brainstormforce/astra pull request #2828
Opened 2021-06-02 11:27 UTC by sagarb90

### Description
- Multiselect close icon not showing on selected items in customizer multiselect.
- https://wp-astra.atlassian.net/browse/AST-448

### Screenshots
- https://share.getcloudapp.com/Kou4ym85

### Types of changes
Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-06-03 06:00 UTC, premanshup approved these changes

2021-06-03 06:03 UTC, imnavanath commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
> +      $selection.prepend('<span class="select2-selection__choice__remove" role="presentation" aria-hidden="true">&times; </span>');
IMO, ideally x sign needs to be appear after text - https://share.getcloudapp.com/Kou4ym85 (not prepend)

2021-06-03 06:04 UTC, imnavanath commented
@sagarb90 changelog is missing here, can you please add too.

2021-06-03 06:07 UTC, sagarb90 commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
> +      $selection.prepend('<span class="select2-selection__choice__remove" role="presentation" aria-hidden="true">&times; </span>');
@imnavanath the default position for x icon in select2 library is before the text please refer this.
 https://share.getcloudapp.com/8LuoyLl2
 But if we want to do that we can do this here but in add-on we need to add custom CSS for that.

2021-06-03 06:14 UTC, imnavanath commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
> +      $selection.prepend('<span class="select2-selection__choice__remove" role="presentation" aria-hidden="true">&times; </span>');
Okay, but UI wise it looks little bit odd. Select2 UI is different which suits to their icon position. This improvement may come from designer, better to confirm this once with Satish/Monika.

2021-06-03 06:30 UTC, abhishek-bsf approved these changes

2021-06-07 06:30 UTC, imnavanath commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
> +      $selection.prepend('<span class="select2-selection__choice__remove" role="presentation" aria-hidden="true">&times; </span>');
@sagarb90 any update on this?

2021-06-07 06:39 UTC, sagarb90 commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
> +      $selection.prepend('<span class="select2-selection__choice__remove" role="presentation" aria-hidden="true">&times; </span>');
@imnavanath Yes, we had asked Monika and move the cross button after the text, also added comments in the task by Monika.

2021-06-07 06:40 UTC, imnavanath commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls.js
> +      $selection.prepend('<span class="select2-selection__choice__remove" role="presentation" aria-hidden="true">&times; </span>');
Great 👍 Thanks.

2021-06-07 06:51 UTC, premanshup requested changes

2021-06-07 06:51 UTC, premanshup commented on changelog.txt
> +- Improvement: Added close button for multiselect selected items in google font variants.
```suggestion
- Improvement: Added close button for multiselect selected items in Google font variants.
```

2021-06-07 06:54 UTC, sagarb90 commented on changelog.txt
> +- Improvement: Added close button for multiselect selected items in google font variants.
Done

2021-06-07 06:58 UTC, merged

2021-06-07 06:58 UTC, premanshup approved these changes