AST-281 - fix: Secondary menu not expendable on mobile when outside of Off Canvas
brainstormforce/astra pull request #2830
Opened 2021-06-03 06:23 UTC by sagarb90

### Description
- https://wp-astra.atlassian.net/browse/AST-281
- Secondary menu not expendable on mobile when outside of Off Canvas.

### Screenshots
 https://share.getcloudapp.com/8LuoyZkY

### Types of changes
Bug fix (non-breaking change which fixes an issue).

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-06-03 09:23 UTC, premanshup commented on assets/js/unminified/frontend.js
> +					for( var k=0; k < __main_header_all.length; k++ ){
@sagarb90 please rename `k` to mainHeaderCount or something descriptive.

2021-06-03 09:25 UTC, premanshup requested changes

2021-06-03 09:25 UTC, premanshup commented on assets/js/unminified/frontend.js
> +			// comma seprated selector added, if menu is outside of off-canvas then submenu will not clickable, it work only for off-cnavas area submenu.
```suggestion
			// comma separated selector added, if menu is outside of Off-Canvas then submenu is not clickable, it work only for Off-Canvas area with dropdown style.
```

Please add changelog as well.

2021-06-03 13:15 UTC, sagarb90 commented on assets/js/unminified/frontend.js
> +					for( var k=0; k < __main_header_all.length; k++ ){
Yes done.

2021-06-03 13:16 UTC, sagarb90 commented on assets/js/unminified/frontend.js
> +			// comma seprated selector added, if menu is outside of off-canvas then submenu will not clickable, it work only for off-cnavas area submenu.
Comment updated also added changelog for the same just confirm the version that I have added.

2021-06-04 04:48 UTC, premanshup requested changes

2021-06-04 04:48 UTC, premanshup commented on assets/js/unminified/frontend.js
> +							var astra_menu_toggle = __main_header_all[k].querySelectorAll('ul.main-header-menu .menu-item-has-children > .menu-link, ul.main-header-menu .ast-menu-toggle');
@sagarb90 Have we not updated the `k` from everywhere? Please make sure to test this once after updating.

2021-06-04 05:57 UTC, sagarb90 commented on assets/js/unminified/frontend.js
> +							var astra_menu_toggle = __main_header_all[k].querySelectorAll('ul.main-header-menu .menu-item-has-children > .menu-link, ul.main-header-menu .ast-menu-toggle');
@premanshup Opps my bad I missed it, now I have modified and tested the changes as well. thank you.

2021-06-04 06:34 UTC, premanshup commented on assets/js/unminified/frontend.js
> +							var astra_menu_toggle = __main_header_all[k].querySelectorAll('ul.main-header-menu .menu-item-has-children > .menu-link, ul.main-header-menu .ast-menu-toggle');
@sagarb90 No worries 🙂

2021-06-04 06:35 UTC, premanshup submitted a review, later dismissed

2021-06-04 07:00 UTC, abhishek-bsf approved these changes

2021-06-07 05:54 UTC, merged