AST-495 - imprv: Changed submenu container animation option name from Default to None
brainstormforce/astra pull request #2847
Opened 2021-06-08 10:32 UTC by sagarb90

### Description
- Changed submenu container animation option name from Default to None.
- https://wp-astra.atlassian.net/browse/AST-495

### Screenshots

https://share.bsf.io/jkuL9NOL

### Types of changes
- Improvements

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-06-08 11:29 UTC, imnavanath submitted a review, later dismissed

2021-06-08 12:17 UTC, abhishek-bsf submitted a review, later dismissed

2021-06-09 06:07 UTC, premanshup requested changes

2021-06-09 06:07 UTC, premanshup commented on changelog.txt
> +- Improvement: Changed sub-menu container animation option name from "Default" to "None".
```suggestion
- Improvement: Changed sub-menu container animation option name from 'Default' to 'None'. 
```

2021-06-09 06:11 UTC, sagarb90 commented on changelog.txt
> +- Improvement: Changed sub-menu container animation option name from "Default" to "None".
Done

2021-06-09 06:11 UTC, premanshup submitted a review, later dismissed

2021-06-09 13:02 UTC, abhishek-bsf approved these changes

2021-06-11 06:29 UTC, merged