AST-492 - imrpv: Changed customizer submenu control title from "Container Animations" to "Submenu Animation"
brainstormforce/astra pull request #2848
Opened 2021-06-08 11:09 UTC by sagarb90

### Description
- https://wp-astra.atlassian.net/browse/AST-492
- Changed customizer submenu control title from "Container Animations" to "Submenu Animation".
- Changed for both Old and New Header footer builder.

### Screenshots
https://share.getcloudapp.com/JruD7dN4

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-06-08 11:30 UTC, imnavanath submitted a review, later dismissed

2021-06-08 12:20 UTC, abhishek-bsf commented on changelog.txt
> +- Improvement: Changed customizer submenu control title from "Container Animations" to "Submenu Animation".
@sagarb90 Please update ``"Container Animations"`` to ``"Container Animation"``

2021-06-08 12:30 UTC, sagarb90 commented on changelog.txt
> +- Improvement: Changed customizer submenu control title from "Container Animations" to "Submenu Animation".
@abhishek-bsf Yes updated.

2021-06-08 12:34 UTC, abhishek-bsf submitted a review, later dismissed

2021-06-08 12:38 UTC, imnavanath submitted a review, later dismissed

2021-06-09 06:08 UTC, premanshup requested changes

2021-06-09 06:08 UTC, premanshup commented on changelog.txt
> +- Improvement: Changed customizer submenu control title from "Container Animation" to "Submenu Animation".
```suggestion
- Improvement: Changed customizer submenu control title from 'Container Animation' to 'Submenu Animation'.
```

2021-06-09 11:16 UTC, sagarb90 commented on changelog.txt
> +- Improvement: Changed customizer submenu control title from "Container Animation" to "Submenu Animation".
Yes this is Done

2021-06-09 11:31 UTC, premanshup approved these changes

2021-06-09 11:32 UTC, merged