AST-490 - fix:  Removed default border bottom for transparent header and make it as 0 value.
brainstormforce/astra pull request #2850
Opened 2021-06-09 08:55 UTC by sagarb90

### Description
- https://wp-astra.atlassian.net/browse/AST-490
- Removed default border bottom for transparent header and make it as 0 value as previous was blank so it get applied the normal header border.

### Screenshots
https://share.getcloudapp.com/rRuj6Z1Y

### Types of changes
Bug fix (non-breaking change which fixes an issue) .

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-06-09 10:18 UTC, premanshup approved these changes

2021-06-09 10:21 UTC, abhishek-bsf approved these changes
@sagarb90  Please add changelog if required.

2021-06-11 09:19 UTC, premanshup requested changes

2021-06-11 09:19 UTC, premanshup commented on inc/extras.php
> +function apply_updated_default_tranparent_header_value() {
```suggestion
function astra_transparent_header_default_value() {
```

2021-06-11 09:33 UTC, sagarb90 commented on inc/extras.php
> +function apply_updated_default_tranparent_header_value() {
This is done rename funciton name

2021-06-14 12:16 UTC, premanshup commented on changelog.txt
> +- Improvements: Changed Transparent Header Border Bottom default value from '' to 0;
```suggestion
- Improvement: Changed Transparent Header Border Bottom default value from '' to 0;
```

2021-06-14 12:24 UTC, sagarb90 commented on changelog.txt
> +- Improvements: Changed Transparent Header Border Bottom default value from '' to 0;
Done

2021-06-14 12:27 UTC, premanshup submitted a review, later dismissed

2021-06-14 12:32 UTC, imnavanath commented on changelog.txt
> +- Improvement: Changed sub-menu container animation option name from 'Default' to 'None'.
@sagarb90 all these 3 points are already covered in the above changelog. L2-5

2021-06-14 12:36 UTC, sagarb90 commented on changelog.txt
> +- Improvement: Changed sub-menu container animation option name from 'Default' to 'None'.
@imnavanath Yes Done, thanks.

2021-06-14 12:38 UTC, imnavanath approved these changes

2021-06-14 12:39 UTC, merged