Feat: Theme Check - Automated GitHub action
brainstormforce/astra pull request #2856
Opened 2021-06-12 12:11 UTC by premanshup

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-06-14 03:26 UTC, imnavanath approved these changes

2021-06-14 04:39 UTC, sagarb90 approved these changes

2021-06-14 12:46 UTC, imnavanath approved these changes

2021-06-14 14:55 UTC, Nikschavan requested changes
I think instead of introducing a new environment we should integrate this with the existing `local-env`

One thing we will have to change in `local-env` is instead of mounting the whole workspace, we should "build" the package and then only mount the built directory.

We will also need a way to install extra plugins, maybe we can do this by passing name of the shell script which will be run from the [install-wordpress.sh](https://github.com/brainstormforce/astra/blob/master/bin/local-env/install-wordpress.sh)

Let me know and we can get on a call to discuss this more.

2021-06-17 03:32 UTC, premanshup commented
> I think instead of introducing a new environment we should integrate this with the existing `local-env`
> 
> One thing we will have to change in `local-env` is instead of mounting the whole workspace, we should "build" the package and then only mount the built directory.
> 
> We will also need a way to install extra plugins, maybe we can do this by passing name of the shell script which will be run from the [install-wordpress.sh](https://github.com/brainstormforce/astra/blob/master/bin/local-env/install-wordpress.sh)
> 
> Let me know and we can get on a call to discuss this more.

@Nikschavan I have scheduled a call for today. Let's discuss this.

2021-06-23 03:38 UTC, imnavanath commented on bin/local-env/theme-check.sh
> +wp plugin install theme-check --version=20200922.1 --activate
Just curious @premanshup is there any way, we target their stable released version from WP here instead of hardcoded `20200922.1` or might be targeting their [gitthub repo](https://github.com/WordPress/theme-check) > master version?

2021-06-23 10:25 UTC, Nikschavan commented on bin/local-env/theme-check.sh
> +wp plugin install theme-check --version=20200922.1 --activate
This was added I think because there was a fatal error introduced with the latest version of theme check plugin and  `anhskohbo/wp-cli-themecheck` action. @premanshup do check if this is fixed and if not report the error.

It's better to revert this to master so that this gets always updated.

2021-06-23 10:29 UTC, premanshup commented on bin/local-env/theme-check.sh
> +wp plugin install theme-check --version=20200922.1 --activate
@Nikschavan Yes, It is reported here - https://github.com/anhskohbo/wp-cli-themecheck/issues/6. Will keep watching this.

2021-06-24 04:14 UTC, closed without merging

2021-06-24 04:14 UTC, Nikschavan commented
Closing in favour of #2911