Bug in searchform.php translation
brainstormforce/astra pull request #2863
Opened 2021-06-15 08:03 UTC by murshed

Bug in searchform.php translation

2021-06-15 08:47 UTC, Nikschavan submitted a review, later dismissed

2021-06-16 09:49 UTC, premanshup submitted a review, later dismissed

2021-06-16 09:50 UTC, imnavanath submitted a review, later dismissed

2021-06-16 09:51 UTC, sagarb90 submitted a review, later dismissed

2021-06-16 10:02 UTC, premanshup commented
@murshed Thank you for the PR, this will be released in the version v3.7.0.

2021-06-19 06:45 UTC, murshed commented
I have modified the code.
If we added 'astra" on the line the translation does not work! Video- https://streamable.com/sj2utg

2021-06-20 15:32 UTC, premanshup requested changes

2021-06-20 15:32 UTC, premanshup commented on searchform.php
> +	<input type="submit" class="search-submit" value="<?php echo esc_attr_x( 'Search', 'submit button' ); ?>" />
```suggestion
	<input type="submit" class="search-submit" value="<?php echo esc_attr_x( 'Search', 'submit button', 'astra' ); ?>" />
```

2021-06-23 11:29 UTC, premanshup commented
> I have modified the code.
> If we added 'astra" on the line the translation does not work! Video- https://streamable.com/sj2utg

@murshed For some reason the link you shared is not working and I think it can still be translated using Loco Translate plugin. Since it will not appear the translatable strings.

2021-06-23 13:01 UTC, merged