AST-251 - improvement: Moved customizer related code from frontend JS file to customizer JS file
brainstormforce/astra pull request #2872
Opened 2021-06-17 13:56 UTC by abhishek-bsf

### Description
Task- https://wp-astra.atlassian.net/browse/AST-251

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
Checked if Mobile Dropdown and Full Screen toggle closes on partial refresh in customizer.

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-06-17 14:11 UTC, Nikschavan commented on assets/js/unminified/customizer-preview.js
> +	menu_toggle_all = document.querySelectorAll( '.main-header-menu-toggle' );
This seems to be not used anywhere

2021-06-17 14:14 UTC, Nikschavan commented on assets/js/unminified/customizer-preview.js
> +} );
```suggestion
} );

```

2021-06-18 05:02 UTC, abhishek-bsf commented on assets/js/unminified/customizer-preview.js
> +	menu_toggle_all = document.querySelectorAll( '.main-header-menu-toggle' );
Resolved! Removed ``menu_toggle_all``.

2021-06-18 05:03 UTC, abhishek-bsf commented on assets/js/unminified/customizer-preview.js
> +} );
Made changes, added new line at the end.

2021-06-24 11:43 UTC, premanshup requested changes

2021-06-24 11:43 UTC, premanshup commented on assets/js/unminified/frontend.js
> +		if ( desktop_toggle.classList.contains( 'toggled' ) ) {
@abhishek-bsf Getting console JS error on this line when Toggle for Desktop is enabled from addon - [Screenshot](https://share.bsf.io/2Nuqv08k)

2021-06-25 07:38 UTC, abhishek-bsf commented on assets/js/unminified/frontend.js
> +		if ( desktop_toggle.classList.contains( 'toggled' ) ) {
@premanshup The console error was only in the development branch due to code conflict. I have resolved it now!

2021-06-25 09:32 UTC, premanshup approved these changes

2021-06-25 09:39 UTC, imnavanath approved these changes

2021-06-25 09:43 UTC, sagarb90 approved these changes

2021-06-30 04:39 UTC, Nikschavan requested changes

2021-06-30 04:39 UTC, Nikschavan commented on assets/js/unminified/frontend.js
> +var menu_toggle_all 	 = document.querySelectorAll( '#masthead .main-header-menu-toggle' ),
Does all the new change need to execute on dom events such as ready etc?
Can we wrap this in a function instead of keeping this in a global scope like this?

2021-07-05 14:12 UTC, abhishek-bsf commented on assets/js/unminified/frontend.js
> +var menu_toggle_all 	 = document.querySelectorAll( '#masthead .main-header-menu-toggle' ),
In function scope there are some functions that needs be accessed in ``customizer-preview.js`` file. If we declare those inside in function scope then they are not accessible in any other file. For this purpose we have removed function scope here.

2021-09-10 01:48 UTC, closed without merging