AST-580 - fix: Fixed warnings in theme-check for search-role and compatibility with get_search_form function
brainstormforce/astra pull request #2875
Opened 2021-06-18 09:04 UTC by imnavanath

### Description
- Core trac ticket - https://themes.trac.wordpress.org/ticket/101061
- Avoided extra search-fom markup and managed using get_search_form function
- Core trac ticket - https://themes.trac.wordpress.org/ticket/101061

### Screenshots
- With master (latest theme check) - https://share.bsf.io/eDuyjX4d
- With this branch - https://share.bsf.io/bLukAOJZ

### Types of changes
- Bugfix

### How has this been tested?
- With all Astra search types
- Header searches
- With search widget in the sidebar
- On the results page search bar

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-06-18 09:29 UTC, sagarb90 approved these changes

2021-06-18 09:36 UTC, abhishek-bsf approved these changes

2021-06-18 09:39 UTC, shubhw12 approved these changes

2021-06-20 14:48 UTC, premanshup requested changes

2021-06-20 14:48 UTC, premanshup commented on inc/core/common-functions.php
> +		);
@imnavanath Could please explain why we are replacing existing form with `get_search_form()`?

2021-06-21 03:54 UTC, imnavanath commented on inc/core/common-functions.php
> +		);
Because we are getting warnings in the latest Theme Check, please take a look - https://themes.trac.wordpress.org/ticket/101061

2021-06-21 04:13 UTC, premanshup commented on inc/core/common-functions.php
> +		);
@imnavanath Thank you for the explaination.

2021-06-21 04:45 UTC, premanshup requested changes

2021-06-21 04:45 UTC, premanshup commented on changelog.txt
> +- Fix: Avoided extra search-form markup and added compatibility with get_search_form().
```suggestion
- Fix: Theme check warning - Replaced search-form markup with get_search_form().
```

2021-06-21 09:56 UTC, merged