AST-253 - Improvement: Rendered Addon dependent toggle code conditionally and removed unwanted code.
brainstormforce/astra pull request #2909
Opened 2021-06-23 13:13 UTC by abhishek-bsf

### Description
Task- https://wp-astra.atlassian.net/browse/AST-253

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
- Tested if toggle on desktop and mobile works properly or not.
- Tested if submenu toggle works properly on desktop and mobile or not.

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-06-24 11:10 UTC, premanshup requested changes

2021-06-24 11:10 UTC, premanshup commented on assets/js/unminified/frontend.js
> +		if( typeof astraAddon != 'undefined' ) {
@abhishek-bsf I see that we have not defined `astraAddon` anywhere. Does this come from Addon? If yes, then can you please make sure that our addon JS load only after JS from theme is loaded, otherwise this may not work at all.

2021-06-25 07:54 UTC, abhishek-bsf commented on assets/js/unminified/frontend.js
> +		if( typeof astraAddon != 'undefined' ) {
@premanshup `astraAddon` comes from the Addon. I have also confirmed that Addon JS is loaded after Theme JS only- https://share.getcloudapp.com/eDuy5vKW

2021-06-25 08:33 UTC, premanshup approved these changes

2021-06-25 08:38 UTC, sagarb90 approved these changes

2021-06-25 08:56 UTC, imnavanath approved these changes

2021-06-28 11:51 UTC, merged

2021-06-29 02:21 UTC, Nikschavan commented on assets/js/unminified/frontend-pro.js
> +astraToggleSetupPro = function( mobileHeaderType, body, menu_click_listeners ) {
@premanshup / @abhishek-bsf  Can this be moved to Astra Pro plugin? since this is required if Astra Pro is required?

2021-07-09 14:07 UTC, premanshup commented on assets/js/unminified/frontend-pro.js
> +astraToggleSetupPro = function( mobileHeaderType, body, menu_click_listeners ) {
@Nikschavan I think we can do this. @abhishek-bsf do check this.

2021-08-11 07:43 UTC, Nikschavan commented on assets/js/unminified/frontend-pro.js
> +astraToggleSetupPro = function( mobileHeaderType, body, menu_click_listeners ) {
IS this done? or do we have a task for this?