fix: Null border size showing solid border for headers on frontend
brainstormforce/astra pull request #2915
Opened 2021-06-24 12:11 UTC by imnavanath

### Description
- Customizer data - https://share.bsf.io/WnuxqlGD
- If empty (null) value is set from customizer still headers applying border style CSS
- Slack conversation - https://brainstormforce.slack.com/archives/C5QL6NXEK/p1624455426078500

### Screenshots
- https://share.getcloudapp.com/7KuoAQDw

### Types of changes
- Bug fix 

### How has this been tested?
- Import the above customizer data
- In this, the above header border is empty but it still shows the border for above header in frontend
- Ideal case should be - If & only if we apply border size then only it show border styles 

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-07-06 07:11 UTC, abhishek-bsf submitted a review, later dismissed

2021-07-09 11:39 UTC, premanshup requested changes

2021-07-09 11:39 UTC, premanshup commented on inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
> +	if ( $hba_header_divider ) {
@imnavanath This condition will work even if the value is string like `inherit`, can you please add some check here that the value is greater than or equal to 0 only then we add this CSS?

2021-07-09 11:39 UTC, premanshup requested changes

2021-07-09 11:39 UTC, premanshup commented on inc/builder/type/header/primary-header/dynamic-css/dynamic.css.php
> +	if ( $header_separator ) {
@imnavanath Same here

2021-07-13 05:29 UTC, imnavanath commented on inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
> +	if ( $hba_header_divider ) {
Added `absint` here and in following comment's code @premanshup, so it is working correctly now, Please review [this commit](https://github.com/brainstormforce/astra/pull/2915/commits/9eabecdc55288c02cd3c17c7e965e16006a43bbf)

2021-07-13 05:29 UTC, imnavanath commented on inc/builder/type/header/primary-header/dynamic-css/dynamic.css.php
> +	if ( $header_separator ) {
Added `absint` here [review this commit](https://github.com/brainstormforce/astra/pull/2915/commits/9eabecdc55288c02cd3c17c7e965e16006a43bbf)

2021-07-14 09:49 UTC, premanshup approved these changes

2021-07-14 10:20 UTC, shubhw12 submitted a review, later dismissed

2021-07-16 05:53 UTC, merged