fix: customizer not working the wordpress v5.8 latest
brainstormforce/astra pull request #2922
Opened 2021-06-28 08:17 UTC by shubhw12

### Description
Removed the widget block editor support from the theme so that the customizer works in WP 5.8

### Screenshots

### Types of changes

Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?
Checked the working of customizer with latest WP version

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-06-29 03:25 UTC, Nikschavan requested changes

2021-06-29 03:25 UTC, Nikschavan commented on inc/customizer/class-astra-customizer.php
> +					function() {
This should be done on `after_setup_theme` - https://github.com/brainstormforce/astra/blob/ef341e2532ab3a4819bf939fbff5709f2597f333/inc/class-astra-after-setup-theme.php#L74

2021-06-29 03:25 UTC, Nikschavan commented on inc/customizer/class-astra-customizer.php
> +			if ( astra_wp_version_compare( '5.7.2', '>' ) ) {
Do we need to check for WordPress version here? since the `widgets-block-editor` is coming from this version of WordPress and does not exist in older versions.

2021-07-07 00:16 UTC, premanshup commented
This was a temporary fix until we fixed the block editor JS issue which is now fixed here https://github.com/brainstormforce/astra/pull/2931. Hence, closing this PR.

2021-07-07 00:16 UTC, closed without merging