AST-597 - E2E initial setup for Related Posts correct author name.
brainstormforce/astra pull request #2930
Opened 2021-07-02 06:18 UTC by premanshup

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-07-02 12:46 UTC, Nikschavan requested changes

2021-07-02 12:46 UTC, Nikschavan commented on tests/e2e/specs/customizer/related-posts/author.name.test.js
> +			throw 'Author name for Current Post is not correct in the frontend!';
Jest has several assertions which you can call using [`except()`](https://jestjs.io/docs/expect) you can use one of those.

Probably here you can use [`toBe`](https://jestjs.io/docs/expect#tobevalue)

2021-07-02 12:46 UTC, Nikschavan commented on tests/e2e/specs/customizer/related-posts/author.name.test.js
> +			throw 'Author name for Related Post is not correct in the frontend!';
Same as above

2021-07-02 12:46 UTC, Nikschavan commented on tests/e2e/specs/customizer/related-posts/author.name.test.js
> +		await trashAllPosts();
Post are trashed automatically before each test - https://github.com/brainstormforce/astra/blob/e584ce1921f11070adf74b43248fb4f65a84d524/tests/e2e/config/bootstrap.js#L207

2021-07-02 12:46 UTC, Nikschavan commented on tests/e2e/specs/customizer/related-posts/author.name.test.js
> +		await deleteUser( 'teamAstra01' );
Maybe we can include this in [siteReset](https://github.com/brainstormforce/astra/blob/e584ce1921f11070adf74b43248fb4f65a84d524/tests/e2e/config/bootstrap.js#L208) function.

This makes a rest request and and that cleares the theme, maybe we can include this resets in this to reduce time in the actual tests - https://github.com/brainstormforce/astra/blob/e584ce1921f11070adf74b43248fb4f65a84d524/tests/e2e/e2e-plugin/rest-api/namespace.php#L37-L49

2021-07-02 12:46 UTC, Nikschavan commented on tests/e2e/specs/customizer/related-posts/author.name.test.js
> +		let relatedPostAuthorValue = await page.evaluate(el => el.textContent, relatedPostAuthor);
```suggestion
		let relatedPostAuthor = await page.$( '.ast-related-post-content .author-name' );
		let relatedPostAuthorValue = await page.evaluate( el => el.textContent, relatedPostAuthor );
```

I wonder why this was not picked by the linter.

2021-07-02 12:46 UTC, Nikschavan commented on tests/e2e/specs/customizer/related-posts/author.name.test.js
> +		await page.keyboard.press( 'Tab' );
Instead of this we can directly select the value of a dropdown, [for eg here](https://github.com/brainstormforce/astra/blob/e584ce1921f11070adf74b43248fb4f65a84d524/tests/e2e/utils/create-new-user.js#L30) the role is set directly without tabbing through all the settings.

Also another disadvantage of tabbing is that this is very static. if in future any new option is added/removed the number of tabs required here will change and the test will fail.

2021-07-02 13:00 UTC, premanshup commented on tests/e2e/specs/customizer/related-posts/author.name.test.js
> +			throw 'Author name for Current Post is not correct in the frontend!';
@Nikschavan Updated!

2021-07-02 13:00 UTC, premanshup commented on tests/e2e/specs/customizer/related-posts/author.name.test.js
> +			throw 'Author name for Related Post is not correct in the frontend!';
@Nikschavan Updated!

2021-07-02 13:04 UTC, Nikschavan commented on tests/e2e/utils/create-new-user.js
> +
```suggestion
```

2021-07-02 13:06 UTC, Nikschavan commented on tests/e2e/utils/create-new-user.js
> + export async function createUser( username, firstName, lastName, role ) {
This function in the parent package is updated, do check this so that we don't have to refactor when this is released - https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-test-utils/src/create-user.js#L24

Verify if deleteuser is same in trynk branch of gutenberg

2021-07-02 13:09 UTC, Nikschavan commented on tests/e2e/specs/customizer/related-posts/author.name.test.js
> +		await page.keyboard.press( 'Tab' );
Another solution is @premanshup you can login as the user which was just created and then create the post - https://github.com/WordPress/gutenberg/blob/829f88e7f2434c5be2283c655dd53ba1fa5de48b/packages/e2e-test-utils/src/login-user.js#L15

Check which execution is quicker and choose that since this does not affect our test much only contributes to the test.

2021-07-02 13:18 UTC, Nikschavan commented on tests/e2e/specs/customizer/related-posts/author.name.test.js
> +		await createUser( 'teamAstra01', '', '', 'administrator' );
Preferably name the user's based on the role they are assigned

2021-07-02 13:25 UTC, premanshup commented on tests/e2e/specs/customizer/related-posts/author.name.test.js
> +		await trashAllPosts();
@Nikschavan Removed!

2021-07-02 13:26 UTC, premanshup commented on tests/e2e/specs/customizer/related-posts/author.name.test.js
> +		await deleteUser( 'teamAstra01' );
@Nikschavan Updated! Removed deleteUser and added delete user here in this rest request. Please verify once.

2021-07-02 13:28 UTC, premanshup commented on tests/e2e/specs/customizer/related-posts/author.name.test.js
> +		let relatedPostAuthorValue = await page.evaluate(el => el.textContent, relatedPostAuthor);
@Nikschavan  Not sure, I have updated this though.

2021-07-02 13:30 UTC, premanshup commented on tests/e2e/utils/create-new-user.js
> +
Updated!

2021-07-02 13:33 UTC, Nikschavan commented on tests/e2e/e2e-plugin/rest-api/namespace.php
> +					require_once(ABSPATH.'wp-admin/includes/user.php');
In a separate PR maybe, enable phpcs in this directory - 
```suggestion
					require_once( ABSPATH . 'wp-admin/includes/user.php' );
```

2021-07-02 13:34 UTC, Nikschavan commented on tests/e2e/e2e-plugin/rest-api/namespace.php
> +						}
Instead of this you can do a positive check and `continue`

2021-07-02 13:34 UTC, premanshup commented on tests/e2e/utils/create-new-user.js
> + export async function createUser( username, firstName, lastName, role ) {
@Nikschavan For `createUser`:
In trunk: They have implemented `role` as well - https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-test-utils/src/create-user.js#L26

Once released, we can remove our function and function call.

For `deleteUser`:
Our implementation is same, so we can directly just remove the function we have defined once this is released - https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-test-utils/src/delete-user.js#L13

2021-07-02 13:36 UTC, Nikschavan commented on tests/e2e/utils/create-new-user.js
> + export async function createUser( username, firstName, lastName, role ) {
for `createUser` - I mean keep the parameters etc same, i.e. second parameter is object instead of all parameters being separate - basically once this is released we should just need to change the import statement and no refactoring.

2021-07-02 13:36 UTC, premanshup commented on tests/e2e/specs/customizer/related-posts/author.name.test.js
> +		await createUser( 'teamAstra01', '', '', 'administrator' );
Updated to `adminRelatedPost`

2021-07-02 13:40 UTC, premanshup commented on tests/e2e/e2e-plugin/rest-api/namespace.php
> +					require_once(ABSPATH.'wp-admin/includes/user.php');
@Nikschavan Updated!

2021-07-02 13:40 UTC, premanshup commented on tests/e2e/e2e-plugin/rest-api/namespace.php
> +						}
Added positive check using continue.

2021-07-02 13:53 UTC, premanshup commented on tests/e2e/utils/create-new-user.js
> + export async function createUser( username, firstName, lastName, role ) {
@Nikschavan Updated the arguments to object except for `username`.

2021-07-02 14:41 UTC, premanshup commented on tests/e2e/specs/customizer/related-posts/author.name.test.js
> +		await page.keyboard.press( 'Tab' );
@Nikschavan I have updated the logic and now we are setting the author before publishing the post - [https://share.bsf.io/GGuW7YG7](https://share.bsf.io/GGuW7YG7). Please check.

2021-07-02 15:02 UTC, Nikschavan commented
@premanshup can you check the linter errors?

2021-07-05 08:39 UTC, Nikschavan commented
@premanshup - do look into this approach as well for deleting the user, `beforeAll` the user is added and in `afterAll` the user is cleared again - https://github.com/WordPress/gutenberg/pull/32868/files#diff-84f6af106afdeb159152237f035ef1232c6d320a79197abb18115faf52495212R65-R73

2021-07-06 11:15 UTC, premanshup commented
> @premanshup can you check the linter errors?

@Nikschavan linter errors fixed!

2021-07-06 11:19 UTC, premanshup commented
> @premanshup - do look into this approach as well for deleting the user, `beforeAll` the user is added and in `afterAll` the user is cleared again - https://github.com/WordPress/gutenberg/pull/32868/files#diff-84f6af106afdeb159152237f035ef1232c6d320a79197abb18115faf52495212R65-R73

@Nikschavan  IMO our current approach is better since we will always have to delete users. Instead of writing it inside all the test cases, we can keep it global, please let me know your thoughts.

2021-07-06 11:24 UTC, imnavanath approved these changes

2021-07-07 03:45 UTC, Nikschavan approved these changes

2021-07-07 03:45 UTC, merged