AST-628 - fix: WP 5.8 JS console error in customizer due to widget settings.
brainstormforce/astra pull request #2931
Opened 2021-07-02 06:50 UTC by sagarb90

### Description
- https://wp-astra.atlassian.net/browse/AST-628
- Customizer not working due to JS error in the wp 5.8 version.
- To fix this issue we have added a separate section for widget alignment and color options and a widget block editor.
- Added separate button in widget component to navigate to these sections - https://share.getcloudapp.com/eDuyreR1
### Screenshots

### Types of changes
 Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-07-05 07:01 UTC, premanshup requested changes

2021-07-05 07:13 UTC, imnavanath commented on inc/extras.php
> +	|| version_compare( substr( get_bloginfo( 'version' ), 0, 3 ), '5.8', '>=' ) ) {
We can use here preg_replace for now, after WP-5.8's some releases we can remove this. Ref @sagarb90 - https://github.com/brainstormforce/astra-addon/blob/master/addons/nav-menu/classes/class-astra-walker-nav-menu-edit-custom.php#L55

2021-07-05 07:19 UTC, Nikschavan commented on inc/extras.php
> +function astra_is_wp5_8_version() {
instead of `is` maybe `has` is more correct?I might be wrong

2021-07-05 07:24 UTC, premanshup commented on inc/extras.php
> +function astra_is_wp5_8_version() {
@Nikschavan I agree! `has` is more accurate.

2021-07-05 07:29 UTC, Nikschavan commented on inc/extras.php
> +	|| version_compare( substr( get_bloginfo( 'version' ), 0, 3 ), '5.8', '>=' ) ) {
AFAIK `version_compare` also takes care of rc / beta versions into account - eg - https://3v4l.org/n7J5G

Do cross check and test how the version strings of different WP releases is and if that does work with `version_compare`

2021-07-05 07:36 UTC, sagarb90 commented on inc/extras.php
> +	|| version_compare( substr( get_bloginfo( 'version' ), 0, 3 ), '5.8', '>=' ) ) {
Yes will check the same if version_compare take care for beta and RC versions as well. 
FYI- kadense also used the same method( i.e `preg_replace` ) to compare the beta version. We will change the condition once WP 5.8 released.

2021-07-05 08:56 UTC, sagarb90 commented on inc/extras.php
> +	|| version_compare( substr( get_bloginfo( 'version' ), 0, 3 ), '5.8', '>=' ) ) {
I have verified the the version comparision [function ](https://3v4l.org/n7J5G)i.e `version_compare( get_bloginfo( 'version' ), '5.8-alpha', '>=' )` and it works for beta, RC  and stable version numbers. Also updated the same.

2021-07-05 08:56 UTC, sagarb90 commented on inc/extras.php
> +function astra_is_wp5_8_version() {
Yes updated to `astra_has_widgets_block_editor`.

2021-07-05 09:28 UTC, abhishek-bsf approved these changes

2021-07-06 08:16 UTC, imnavanath approved these changes

2021-07-07 08:58 UTC, merged