AST-663 fix: UI changes in the customizer for WP 5.8
brainstormforce/astra pull request #2947
Opened 2021-07-08 14:24 UTC by shubhw12

### Description

WP5.8 compatibility - added the editor-specific class selector so that the font-weight CSS is applied in the editor view only. 
Added CSS specific to block editor in the customizer as well.

### Screenshots
https://share.getcloudapp.com/bLukb6AJ

### Types of changes
 Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

Checked the h1-h6 changes in the editor comparing master and this branch.
Checked the same for the h1-h6 in the block editor present in the customizer as well.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-07-09 05:27 UTC, imnavanath approved these changes

2021-07-12 10:32 UTC, premanshup requested changes

2021-07-12 10:32 UTC, premanshup commented on inc/assets/css/block-editor-styles-rtl.css
> +
@shubhw12 Instead of updating the existing heading CSS for h1, h2, and so on, I think we should override this CSS with Customizer specific classes since this CSS also loads in the post editor for blocks and modifying existing CSS will result in change in the heading CSS.

2021-07-13 04:39 UTC, premanshup requested changes

2021-07-13 04:57 UTC, sagarb90 approved these changes

2021-07-13 11:53 UTC, premanshup approved these changes

2021-07-14 08:29 UTC, merged