Default color link site title
brainstormforce/astra pull request #2950
Opened 2021-07-09 10:32 UTC by abhishek-bsf

### Description
Task- https://wp-astra.atlassian.net/browse/GCP-20

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
Checked if the new default color is applied only for new users and not the existing one.

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-07-23 12:12 UTC, premanshup requested changes

2021-07-23 12:12 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +		public function is_support_link_default_color() {
@abhishek-bsf Getting this error in the branch:
```
Deprecated: Non-static method Astra_Dynamic_CSS::is_support_link_default_color() should not be called statically in C:\xampp\htdocs\rc-wp\wp-content\themes\astra\inc\class-astra-dynamic-css.php on line 549

2021-07-29 13:31 UTC, abhishek-bsf commented on inc/class-astra-dynamic-css.php
> +		public function is_support_link_default_color() {
Resolved, fixed issues!

2021-07-30 12:46 UTC, patilvikasj approved these changes

2021-07-30 12:46 UTC, merged