E2e site tagline
brainstormforce/astra pull request #2961
Opened 2021-07-12 17:20 UTC by Swapnildhanrale

### Description
Added test case for site tagline

### Screenshots
Options to be tested - https://share.bsf.io/p9uA4EYp

### Types of changes
Only added new test case file

### How has this been tested?
Run the command by pulling branch - npm run test:e2e:interactive -- tests/e2e/specs/customizer/header-builder/site-identity/site-tagline.test.js

### Checklist:
Test in autoload browser, tagline color, and font size is working or not.

2021-07-20 05:09 UTC, Nikschavan requested changes

2021-07-20 05:09 UTC, Nikschavan commented on tests/e2e/specs/customizer/header-builder/Site-identity/site-tagline.test.js
> +				'mobile': true,
```suggestion
			'display-site-tagline-responsive': {
				'desktop': true,
				'tablet': true,
				'mobile': true,
```
Let's not disable the rules, I think this is not required anyway and this is already fixed. Can you try and remove this?

2021-07-20 05:09 UTC, Nikschavan commented on tests/e2e/specs/customizer/header-builder/Site-identity/site-tagline.test.js
> +				'mobile': 18,
```suggestion
				'desktop': 22,
				'tablet': 20,
				'mobile': 18,
```

2021-07-20 05:14 UTC, Nikschavan requested changes

2021-07-20 05:14 UTC, Nikschavan commented on tests/e2e/specs/customizer/header-builder/Site-identity/site-tagline.test.js
> +				'mobile': true,
```suggestion
				desktop: true,
				tablet: true,
				mobile: true,
```

2021-07-20 05:14 UTC, Nikschavan commented on tests/e2e/specs/customizer/header-builder/Site-identity/site-tagline.test.js
> +				'mobile': 18,
```suggestion
				desktop: 22,
				tablet: 20,
				mobile: 18,
```

2021-08-03 04:33 UTC, shubhw12 approved these changes

2021-08-03 17:23 UTC, premanshup requested changes

2021-08-05 05:33 UTC, premanshup approved these changes

2021-08-05 05:37 UTC, merged

2021-08-05 05:37 UTC, Nikschavan commented on tests/e2e/utils/post.js
> +<!-- wp:list-item {"level":7} -->
I am getting this error @swapnilde 

![Image 2021-08-05 at 11 06 48 AM](https://user-images.githubusercontent.com/2931091/128296812-a554fcf3-94ed-43d5-9479-a6198f2bbae2.jpg)


Can you confirm if this block exists on your site?

2021-08-05 05:37 UTC, Nikschavan commented on tests/e2e/utils/post.js
> +<!-- wp:list-item {"level":7} -->
@premanshup is this working for you?

2021-08-05 05:39 UTC, premanshup commented on tests/e2e/utils/post.js
> +<!-- wp:list-item {"level":7} -->
@Nikschavan _checking_

2021-08-06 07:08 UTC, premanshup commented on tests/e2e/utils/post.js
> +<!-- wp:list-item {"level":7} -->
@Nikschavan This is fixed here - https://github.com/brainstormforce/astra/pull/3080. Please review.