GCP-34 Feature/font presets
brainstormforce/astra pull request #3011
Opened 2021-07-19 11:28 UTC by patilvikasj

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-08-03 09:40 UTC, premanshup requested changes

2021-08-03 09:40 UTC, premanshup commented on style.css
> +>>>>>>> dff2684196c9058c9d829cf67f330d1082ca30cf
@patilvikasj Please check these merge conflicts.

2021-08-03 09:42 UTC, patilvikasj commented on style.css
> +>>>>>>> dff2684196c9058c9d829cf67f330d1082ca30cf
@premanshup Merge conflicts resolved now

2021-08-03 09:50 UTC, imnavanath commented on inc/customizer/configurations/typography/class-astra-global-typo-configs.php
> + * @since       Astra 1.0.15
Please update @since version & @copyright year.

2021-08-03 09:51 UTC, imnavanath commented on inc/customizer/configurations/typography/class-astra-heading-typo-configs.php
> + * @since       Astra 1.0.15
Please updare since version & copyright year here too.

2021-08-03 09:53 UTC, imnavanath commented on inc/customizer/configurations/typography/class-astra-heading-typo-configs.php
> +				'title'             => __( 'Line Height', 'astra-addon' ),
'astra-addon' textdomain needs to be replaced with 'astra' from this entire file.

2021-08-03 09:54 UTC, imnavanath commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls-plain.js
> +			console.log( this.id );
Please remove log from here.

2021-08-03 11:06 UTC, patilvikasj commented on inc/customizer/configurations/typography/class-astra-global-typo-configs.php
> + * @since       Astra 1.0.15
Done.

2021-08-03 11:06 UTC, patilvikasj commented on inc/customizer/configurations/typography/class-astra-heading-typo-configs.php
> +				'title'             => __( 'Line Height', 'astra-addon' ),
Done.

2021-08-03 11:06 UTC, patilvikasj commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls-plain.js
> +			console.log( this.id );
Done.

2021-08-03 11:07 UTC, patilvikasj commented on inc/customizer/configurations/typography/class-astra-heading-typo-configs.php
> + * @since       Astra 1.0.15
Done.

2021-08-03 11:08 UTC, imnavanath commented on inc/customizer/custom-controls/typography/typography.js
> +			console.log( this.id );
Log needs to be removed.

2021-08-03 11:09 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/ast-font-family/control.js
> +		// setTimeout( function )
If we don't need this, we can remove it.

2021-08-03 11:10 UTC, imnavanath commented on inc/customizer/extend-custom-controls/src/customizer.js
> +						console.log( "is lazy" );
log needs to be removed.

2021-08-03 12:33 UTC, patilvikasj commented on inc/customizer/custom-controls/typography/typography.js
> +			console.log( this.id );
Done

2021-08-03 12:33 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/customizer.js
> +						console.log( "is lazy" );
Done

2021-08-03 12:33 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/ast-font-family/control.js
> +		// setTimeout( function )
Removed now.

2021-08-04 08:29 UTC, imnavanath approved these changes

2021-08-09 10:25 UTC, imnavanath approved these changes

2021-08-09 11:46 UTC, sagarb90 approved these changes

2021-08-09 13:20 UTC, premanshup requested changes

2021-08-09 13:20 UTC, premanshup commented on psalm.xml
> -    </plugins>
@patilvikasj Why are we removing this?

2021-08-09 13:20 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +			$h6_text_transform = astra_get_option( 'text-transform-h6' );
@patilvikasj Just like options, we can load dynamic CSS conditionally too.

2021-08-09 13:34 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +					'text-transform' => esc_attr( $h4_text_transform ),
@patilvikasj this CSS can be added conditionally.

2021-08-09 14:07 UTC, premanshup requested changes

2021-08-09 14:07 UTC, premanshup commented on inc/customizer/configurations/typography/class-astra-content-typo-configs.php
> +							'operator' => '==',
@patilvikasj I think we can check strict type checking and in all other options too?

2021-08-09 14:11 UTC, premanshup requested changes

2021-08-09 14:11 UTC, premanshup commented on inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
> +    border: 1px solid #3582c4!important;
@patilvikasj Can we avoid using !important here?

2021-08-09 14:11 UTC, premanshup commented on inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
> +}
```suggestion
.ast-typography-reset-btn {
    margin-top: 15px;
    padding: 0 20px;
    cursor: pointer;
    background: #2271b1;
    border-color: #2271b1;
    color: #fff;
    font-size: 13px;
    line-height: 2.15384615;
    min-height: 30px;
}
```

2021-08-09 14:35 UTC, premanshup requested changes

2021-08-09 14:35 UTC, premanshup commented on inc/customizer/custom-controls/assets/js/unminified/custom-controls-plain.js
> +			} else {
```suggestion
			if( isSelect2 ) {
    			       $( "[data-name='"+ optionName + "']" ).select2().trigger('change');
			} else {
```

2021-08-09 14:35 UTC, premanshup commented on inc/customizer/custom-controls/typography/typography.js
> +			} else {
```suggestion
			if( isSelect2 ) {
    			       $( "[data-name='"+ optionName + "']" ).select2().trigger('change');
			} else { 
```

2021-08-09 14:35 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/ast-font-family/ast-font-family.js
> +import {useEffect,useState} from 'react';
```suggestion
import {useState} from 'react';
```

2021-08-09 14:35 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/ast-font-family/ast-font-family.js
> +	});
```suggestion

	const [state, setState] = useState({
		value: props.control.setting.get(),
	});
```

2021-08-09 14:35 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/ast-font-family/ast-font-family.js
> +				setState({ value : value });
```suggestion
				setState({ value : props.control.setting.get() });
```

2021-08-09 14:35 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/ast-font-family/ast-font-family.js
> +export default FontFamilyComponent;
@patilvikasj Any reason we are updating this?

2021-08-09 14:35 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/typography-presets/control.js
> +	},
@patilvikasj I think this can be removed?

2021-08-09 14:35 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/typography-presets/typo-presets-component.js
> +import {useState, useEffect} from 'react';
```suggestion
import {useState} from 'react';
```

2021-08-09 14:35 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/typography-presets/typo-presets-component.js
> +	const [props_value, setPropsValue] = useState(props.control.setting.get());
```suggestion
	const [propsValue, setPropsValue] = useState(props.control.setting.get());
```

2021-08-09 14:35 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/typography-presets/typo-presets-component.js
> +		let headingFontWeight  = options[presetKey]['headings-font-weight'];
```suggestion
		const bodyFontFamily     = options[presetKey]['body-font-family'];
		const headingsFontFamily = options[presetKey]['headings-font-family'];
		const bodyFontVariant    = options[presetKey]['body-font-variant'];
		const headingFontVariant = options[presetKey]['headings-font-variant'];
		const bodyFontWeight     = options[presetKey]['body-font-weight'];
		const headingFontWeight  = options[presetKey]['headings-font-weight'];
```

2021-08-09 14:35 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/typography-presets/typo-presets-component.js
> +		let typoOptions = [
```suggestion
		const typoOptions = [
```

2021-08-09 14:35 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/typography-presets/typo-presets-component.js
> +		var event = new CustomEvent('AstRemoteUpdateState', {
```suggestion
		const updateTypoEvent = new CustomEvent('AstRemoteUpdateState', {
```

2021-08-09 14:35 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/typography-presets/typo-presets-component.js
> +		AstTypography.setOption( 'astra-settings[body-font-family]', defaulBodyFontFamily, true );
```suggestion
		const defaulHeadingFontFamily = props.customizer.control( "astra-settings[headings-font-family]" ).params.default;
		AstTypography.setOption( 'astra-settings[headings-font-family]', defaulHeadingFontFamily, true );

		const defaulBodyFontFamily = props.customizer.control( "astra-settings[body-font-family]" ).params.default;
		AstTypography.setOption( 'astra-settings[body-font-family]', defaulBodyFontFamily, true );
```

2021-08-09 14:35 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/typography-presets/typo-presets-component.js
> +		let options = [
```suggestion
		const options = [
```

2021-08-09 14:35 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/typography-presets/typo-presets-component.js
> +			props.customizer.control( "astra-settings[" + option + "]" ).setting.set( defaultVal );
```suggestion
			const defaultVal = props.customizer.control( "astra-settings[" + option + "]" ).params.default;
			props.customizer.control( "astra-settings[" + option + "]" ).setting.set( defaultVal );
```

2021-08-10 06:21 UTC, patilvikasj commented on inc/class-astra-dynamic-css.php
> +			$h6_text_transform = astra_get_option( 'text-transform-h6' );
Done.

2021-08-10 06:21 UTC, patilvikasj commented on inc/class-astra-dynamic-css.php
> +					'text-transform' => esc_attr( $h4_text_transform ),
Done.

2021-08-10 06:23 UTC, patilvikasj commented on inc/customizer/configurations/typography/class-astra-content-typo-configs.php
> +							'operator' => '==',
Done

2021-08-10 10:08 UTC, patilvikasj commented on inc/extras.php
> +function astra_is_h4_to_h6_typo_option_to_load() {
Done.

2021-08-10 10:14 UTC, patilvikasj commented on inc/customizer/custom-controls/assets/css/unminified/custom-controls.css
> +    border: 1px solid #3582c4!important;
Done.

2021-08-12 14:32 UTC, premanshup commented on psalm.xml
> -    </plugins>
This is fixed!

2021-08-12 14:32 UTC, premanshup approved these changes

2021-08-13 06:54 UTC, merged