AST-694 - WIP: Removing widget design options in WP-5.8 setup
brainstormforce/astra pull request #3049
Opened 2021-07-28 04:04 UTC by imnavanath

### Description
- We are going to remove color, typography options from the widget block editor from the customizer.
- Task - https://wp-astra.atlassian.net/browse/AST-694

### Types of changes
- Kind of improvement

### How has this been tested?
- Details added in the above card

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-08-04 04:50 UTC, premanshup requested changes

2021-08-04 04:50 UTC, premanshup commented on changelog.txt
> +- Improvement: Builder - Removed design specific options from widgets in WordPress 5.8.
```suggestion
- Deprecated: Header footer widgets - Deprecated design specific sticky header options for better compatibility with WordPress 5.8.
```

2021-08-05 06:33 UTC, imnavanath commented on changelog.txt
> +- Improvement: Builder - Removed design specific options from widgets in WordPress 5.8.
Done 👍

2021-08-05 13:54 UTC, premanshup commented on inc/theme-update/class-astra-theme-background-updater.php
> +			'3.7.1' => array(
```suggestion
			'3.6.8' => array(
```

2021-08-05 14:09 UTC, premanshup requested changes

2021-08-05 14:09 UTC, premanshup commented on inc/extras.php
> +		if ( astra_get_option( 'remove-widget-design-options' ) ) {
@imnavanath Check if we can optimize this by reducing the DB call and using the above DB call.

2021-08-05 14:09 UTC, premanshup commented on functions.php
> +define( 'ASTRA_THEME_VERSION', '3.7.1' );
```suggestion
define( 'ASTRA_THEME_VERSION', '3.6.8' );
```

2021-08-05 14:09 UTC, imnavanath commented on inc/theme-update/class-astra-theme-background-updater.php
> +			'3.7.1' => array(
Done

2021-08-05 14:09 UTC, imnavanath commented on functions.php
> +define( 'ASTRA_THEME_VERSION', '3.7.1' );
Done

2021-08-05 14:16 UTC, imnavanath commented on inc/extras.php
> +		if ( astra_get_option( 'remove-widget-design-options' ) ) {
Please review once now, used isset() & new var for avoided astra_get_option() in condition.

2021-08-05 14:29 UTC, premanshup approved these changes

2021-08-06 05:47 UTC, sagarb90 commented on inc/extras.php
> +	$is_widget_design_sections_hidden = true;
Instead of introducing a new variable, we can also use `$remove_widget_design_options` and update the flag(true/false) Also below if condition is also not required in that case.

2021-08-06 06:12 UTC, imnavanath commented on inc/extras.php
> +	$is_widget_design_sections_hidden = true;
we can eliminate first if condition and only 3 `if-elseif-else` conditions will remain. But then for every old user second elseif condition satisfy and it will hide those options. Whereas it needed to be visible anyhow for old users.

2021-08-06 06:35 UTC, sagarb90 commented on inc/extras.php
> +	$is_widget_design_sections_hidden = true;
Okay Can do like this then,
return early and avoid nesting of code.
```suggestion
	if ( ! $remove_widget_design_options ) {
		// For old users we will show widget design options by anyways.
		return apply_filters( 'astra_remove_widget_design_options', $is_widget_design_sections_hidden );
	}
	// Considering the user is new now.
	if ( isset( $astra_settings['remove-widget-design-options'] ) && $astra_settings['remove-widget-design-options'] ) {
		// User was on WP-5.8 lesser version previously and he may update their WordPress to 5.8 in future. So we display the options in this case.
		$is_widget_design_sections_hidden = false;
	} elseif ( astra_has_widgets_block_editor() ) {
		// User is new & having block widgets active. So we will hide those options.
		$is_widget_design_sections_hidden = true;
	} else {
			// Setting up flag because user is on lesser WP versions and may update WP to 5.8.
			astra_update_option( 'remove-widget-design-options', true );
	}
	

	return apply_filters( 'astra_remove_widget_design_options', $is_widget_design_sections_hidden );
```

2021-08-06 10:10 UTC, imnavanath commented on inc/extras.php
> +	$is_widget_design_sections_hidden = true;
Done 👍

2021-08-06 12:00 UTC, merged