AST-634 - Elementor Pro's Header-Footer theme builder layouts does not override theme's Header-Footer builder layouts
brainstormforce/astra pull request #3073
Opened 2021-08-05 12:29 UTC by imnavanath

### Description
- Elementor Pro's built header/footer layouts not override Astra's new Header-Footer builder layouts where as it works with oild header-footer layout

### Screenshots
- Issue- - https://share.bsf.io/E0uAZ5YQ
- Working with old header-footer layout - https://share.bsf.io/qGu5xj8z

### Types of changes
- Bug fix 

### How has this been tested?
- Design header-footer layouts from Elementor+Elementor pro
- Check if its override Astra's header-footer in both old & new HFB cases

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-08-05 14:37 UTC, premanshup commented on changelog.txt
> +- Fix: Elementor Pro's Header-Footer theme builder layouts does not override theme's Header-Footer builder layouts.
@imnavanath This can be moved to v3.6.8 changelog below.

2021-08-05 14:51 UTC, premanshup requested changes

2021-08-05 14:51 UTC, premanshup commented on inc/core/builder/class-astra-builder-helper.php
> +}
@imnavanath I think this global function can be removed and outer classes with method can be called something like this - 
```
\Astra_Loop::get_instance()
\Astra_Builder_Footer::get_instance()
\Astra_Builder_Helper::$is_header_footer_builder_active
```

2021-08-06 04:49 UTC, imnavanath commented on changelog.txt
> +- Fix: Elementor Pro's Header-Footer theme builder layouts does not override theme's Header-Footer builder layouts.
Done

2021-08-06 04:56 UTC, imnavanath commented on inc/core/builder/class-astra-builder-helper.php
> +}
Yes it worked thanks 🎉

2021-08-06 05:05 UTC, abhishek-bsf approved these changes

2021-08-06 05:05 UTC, sagarb90 approved these changes

2021-08-06 05:06 UTC, shubhw12 approved these changes

2021-08-06 05:15 UTC, premanshup approved these changes

2021-08-06 14:45 UTC, merged