AST-582- imprv: Clear asset cache of the theme and addon on every new update of the theme
brainstormforce/astra pull request #3085
Opened 2021-08-09 06:10 UTC by sagarb90

### Description
- Clear asset cache of the theme and addon on every new update of the theme
- https://wp-astra.atlassian.net/browse/AST-582
- Test with enable file generation and update the theme, It should clear theme and add-on asset cache( from Upload directory ) 

### Screenshots

### Types of changes
- Improvements

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-08-09 12:35 UTC, premanshup requested changes

2021-08-09 12:35 UTC, premanshup commented on inc/theme-update/class-astra-theme-background-updater.php
> +			self::astra_clear_all_assets_cache();
```suggestion
			astra_clear_all_assets_cache();
```
@sagarb90 Instead of creating a new function, can we call this existing function directly?

2021-08-10 05:08 UTC, sagarb90 commented on inc/theme-update/class-astra-theme-background-updater.php
> +			self::astra_clear_all_assets_cache();
@premanshup Yes we can use the existing function I thought we have functions in `astra-update-functions.php` file which are called in db update process.

2021-08-10 11:54 UTC, premanshup commented on changelog.txt
> +- Improvement: Clear asset cache of theme and addon on every new update of theme.
@sagarb90 This can go under `v3.6.9`

2021-08-10 11:55 UTC, premanshup approved these changes

2021-08-10 11:58 UTC, imnavanath commented on inc/theme-update/class-astra-theme-background-updater.php
> -				do_action( 'astra_theme_update_after' );
We removed this because already in this function same action exists and also this is not right position of this action, right? or any other reason is there?

2021-08-10 12:00 UTC, sagarb90 commented on inc/theme-update/class-astra-theme-background-updater.php
> -				do_action( 'astra_theme_update_after' );
@imnavanath Yes This is not the right position to add action because this is will run on every page refresh. No other reason

2021-08-10 12:19 UTC, imnavanath approved these changes

2021-08-10 12:21 UTC, imnavanath commented on inc/theme-update/astra-update-functions.php
>  function astra_clear_all_assets_cache() {
a thought - can we move this function from this batch functions specific file, we can move this in common-functions / helper functions itself. Same for addon as well.

2021-08-10 12:25 UTC, sagarb90 commented on inc/theme-update/astra-update-functions.php
>  function astra_clear_all_assets_cache() {
Yes I was also thinking the same but we have reused this function. otherwise, we have to remove it from here and update the existing function calls as well, Also this is also same job as batch function i.e run after each update. So we can keep here

2021-08-10 12:29 UTC, sagarb90 commented on changelog.txt
> +- Improvement: Clear asset cache of theme and addon on every new update of theme.
Yes this is done

2021-08-10 12:30 UTC, imnavanath commented on inc/theme-update/astra-update-functions.php
>  function astra_clear_all_assets_cache() {
IMO, as soon as we deploy this code, cache clears from every site so no longer needed those old batch function calls (from previous versions) we can remove those and keep this one only. 

Your thought also @premanshup ??

2021-08-11 06:37 UTC, premanshup commented on inc/theme-update/astra-update-functions.php
>  function astra_clear_all_assets_cache() {
@imnavanath Yes, It will work with each update, @sagarb90 can we remove the function calls since this new logic will work after each update regardless of the version number?

2021-08-11 06:40 UTC, sagarb90 commented on inc/theme-update/astra-update-functions.php
>  function astra_clear_all_assets_cache() {
@premanshup Yes I will remove those.

2021-08-11 06:47 UTC, sagarb90 commented on inc/theme-update/astra-update-functions.php
>  function astra_clear_all_assets_cache() {
I have removed please review it once.

2021-08-11 07:06 UTC, premanshup approved these changes

2021-08-11 07:10 UTC, merged