Added Content background option
brainstormforce/astra pull request #3103
Opened 2021-08-13 07:13 UTC by patilvikasj

### Description
Added Content Background Option 

### Screenshots
![Image 2021-08-13 at 12 42 28 PM](https://user-images.githubusercontent.com/10000232/129318952-be44a5fe-1951-4f16-8911-07bedaeb9a99.jpeg)

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-08-16 06:46 UTC, imnavanath approved these changes

2021-08-17 14:55 UTC, premanshup commented
@patilvikasj Please check the GitHub check.

2021-08-20 04:14 UTC, premanshup commented on inc/addons/heading-colors/dynamic-css/dynamic.css.php
> +	error_log( print_r( astra_has_global_color_format_support(), true  ) );
```suggestion
```

2021-08-20 04:15 UTC, premanshup requested changes

2021-08-20 04:15 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +		console.log( "in handlechange" );
```suggestion
```

2021-08-20 04:18 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-group/color-group-component.js
> +export default ColorGroupComponent;
```suggestion
export default React.memo(  ColorGroupComponent );;
```

2021-08-20 04:33 UTC, premanshup commented on inc/modules/related-posts/css/dynamic-css.php
> +			'.ast-single-related-posts-container' => astra_get_responsive_background_obj( $related_posts_bg_color, 'desktop' ),
@patilvikasj I think we will have to add backward compatibility here. Please check.

2021-08-20 04:33 UTC, premanshup commented on inc/modules/related-posts/css/dynamic-css.php
> +		$related_posts_bg_color              = astra_get_option( 'related-posts-background-color', $content_bg_obj );
@patilvikasj I think we will have to add backward compatibility here. Please check.

2021-08-20 04:42 UTC, premanshup commented on inc/dynamic-css/global-color-palette.php
> +add_filter( 'astra_dynamic_theme_css', 'astra_generate_palette_editor_style', 11 );
@patilvikasj Any reason why we are keeping the priority low here?

2021-08-20 04:46 UTC, premanshup commented on assets/js/unminified/wordpress.code-workspace
> +}
@patilvikasj This file can be removed I think.

2021-08-20 04:50 UTC, premanshup commented on functions.php
> +require_once ASTRA_THEME_DIR . 'inc/dynamic-css/content-background.php';
@patilvikasj This complete file can be loaded conditionally.

2021-08-20 04:55 UTC, premanshup commented on inc/class-astra-dynamic-css.php
> +			}
@patilvikasj These can be merged inside single condition.

2021-08-20 05:37 UTC, premanshup commented on inc/dynamic-css/global-color-palette.php
> +function astra_generate_palette_editor_style( $dynamic_css ) {
@patilvikasj It looks like this function is loading in the frontend and not in the editor. Can we rename this if that is so?

2021-08-20 05:38 UTC, patilvikasj commented on inc/class-astra-dynamic-css.php
> +			}
Done.

2021-08-20 05:38 UTC, premanshup commented on inc/dynamic-css/global-color-palette.php
> + * Generate editor style on front end compatible for global palette.
@patilvikasj It looks like this function is loading in the frontend and not in the editor. Can we update the doc comment if that is so?

2021-08-20 05:45 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/slider/slider-component.js
> +export default SliderComponent;
```suggestion
export default React.memo( SliderComponent );
```

2021-08-20 05:54 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/index.js
> +wp.customize.controlConstructor['ast-button-presets'] = ButtonPresetControl;
```suggestion
wp.customize.controlConstructor['ast-button-presets'] = buttonPresetControl;
```

2021-08-20 05:54 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/index.js
>  import { TypographyPresetControl } from './typography-presets/control.js';
```suggestion
import { buttonPresetControl } from './button-presets/control.js';
import { typographyPresetControl } from './typography-presets/control.js';
```

2021-08-20 05:57 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/customizer.js
> +		let customizer_preview_container =  document.getElementById('customize-preview')
```suggestion
		const customizerPreviewContainer =  document.getElementById('customize-preview')
```

2021-08-20 05:57 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/customizer.js
> +		let iframe = customizer_preview_container.getElementsByTagName('iframe')[0]
```suggestion
		const iframe = customizer_preview_container.getElementsByTagName('iframe')[0]
```

2021-08-20 06:05 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/customizer.js
> +		let innerDoc = iframe.contentDocument || iframe.contentWindow.document;
```suggestion
		const innerDoc = iframe.contentDocument || iframe.contentWindow.document;
```

2021-08-20 06:38 UTC, patilvikasj commented on inc/modules/related-posts/css/dynamic-css.php
> +			'.ast-single-related-posts-container' => astra_get_responsive_background_obj( $related_posts_bg_color, 'desktop' ),
Done.

2021-08-20 06:38 UTC, patilvikasj commented on inc/modules/related-posts/css/dynamic-css.php
> +		$related_posts_bg_color              = astra_get_option( 'related-posts-background-color', $content_bg_obj );
Done.

2021-08-20 06:41 UTC, patilvikasj commented on functions.php
> +require_once ASTRA_THEME_DIR . 'inc/dynamic-css/content-background.php';
Helper functions load later so calling conditions early will cause an error.

2021-08-20 06:44 UTC, premanshup commented on inc/modules/related-posts/css/dynamic-css.php
> +		$related_posts_bg_color              = astra_get_option( 'related-posts-background-color', $container_bg_color, $container_bg_color );
```suggestion
		$related_posts_bg_color              = astra_get_option( 'related-posts-background-color', $container_bg_color );
```

2021-08-20 07:02 UTC, patilvikasj commented on inc/dynamic-css/global-color-palette.php
> +add_filter( 'astra_dynamic_theme_css', 'astra_generate_palette_editor_style', 11 );
Nothing specific. Will it make any difference here?

2021-08-20 07:03 UTC, patilvikasj commented on assets/js/unminified/wordpress.code-workspace
> +}
Done

2021-08-20 07:04 UTC, premanshup commented on inc/dynamic-css/global-color-palette.php
> +add_filter( 'astra_dynamic_theme_css', 'astra_generate_palette_editor_style', 11 );
Okay I was curious because here we adding the CSS in root, so it will be recommended if we load this with the highest priority though I think this will work too.

2021-08-20 07:05 UTC, patilvikasj commented on inc/dynamic-css/global-color-palette.php
> +function astra_generate_palette_editor_style( $dynamic_css ) {
Done.

2021-08-20 07:08 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/border/border-component.js
> +export default BorderComponent;
```suggestion
export default React.memo( BorderComponent );
```

2021-08-20 07:09 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +import {Tooltip} from '@wordpress/components';
```suggestion
import { Tooltip } from '@wordpress/components';
```

2021-08-20 07:10 UTC, patilvikasj commented on inc/dynamic-css/global-color-palette.php
> +add_filter( 'astra_dynamic_theme_css', 'astra_generate_palette_editor_style', 11 );
Okay! modified the priority to default.

2021-08-20 07:11 UTC, patilvikasj commented on inc/dynamic-css/global-color-palette.php
> + * Generate editor style on front end compatible for global palette.
Updated.

2021-08-20 07:11 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/color/color-component.js
> +	// }, [props]);
@patilvikasj If this code is not useful, we can remove this.

2021-08-20 07:14 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/button-presets/control.js
> +	},
@patilvikasj I think this can be removed too.

2021-08-20 07:33 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/slider/slider-component.js
> +export default SliderComponent;
Done

2021-08-20 07:34 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/index.js
>  import { TypographyPresetControl } from './typography-presets/control.js';
Done.

2021-08-20 07:34 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/customizer.js
> +		let iframe = customizer_preview_container.getElementsByTagName('iframe')[0]
Done.

2021-08-20 07:34 UTC, patilvikasj commented on inc/modules/related-posts/css/dynamic-css.php
> +		$related_posts_bg_color              = astra_get_option( 'related-posts-background-color', $container_bg_color, $container_bg_color );
Done

2021-08-20 07:34 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/color-palette/color-palette.js
> +import {Tooltip} from '@wordpress/components';
Done.

2021-08-20 07:34 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/button-presets/control.js
> +	},
Removed.

2021-08-20 07:34 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/color/color-component.js
> +	// }, [props]);
Removed.

2021-08-20 07:35 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/border/border-component.js
> +export default BorderComponent;
Done

2021-08-20 07:35 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/customizer.js
> +		let innerDoc = iframe.contentDocument || iframe.contentWindow.document;
Done.

2021-08-20 07:35 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/customizer.js
> +		let customizer_preview_container =  document.getElementById('customize-preview')
Done

2021-08-20 07:35 UTC, patilvikasj commented on inc/customizer/extend-custom-controls/src/index.js
> +wp.customize.controlConstructor['ast-button-presets'] = ButtonPresetControl;
Done

2021-08-20 08:58 UTC, premanshup approved these changes

2021-08-20 09:26 UTC, merged