refactor: Button border radius preview updated for instant reflections
brainstormforce/astra pull request #3114
Opened 2021-08-16 12:13 UTC by imnavanath

### Description
- For instant border-radius preview reflection JS & config updated

### Screenshots
- https://share.bsf.io/rRubLRpk

### Types of changes
- Non-breaking change 

### How has this been tested?
- Button border radius test in preview

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-08-16 12:56 UTC, patilvikasj commented on assets/js/unminified/customizer-preview.js
> +			var dynamicStyle = '.menu-toggle, button, .ast-button, .ast-custom-button, .button, input#submit, input[type="button"], input[type="submit"], input[type="reset"]' + lmsButtonSelectors + search_but
@imnavanath Is it possible to check if Learndash is active and then only load/add CSS selectors?

2021-08-16 12:56 UTC, patilvikasj requested changes
Please check comment @imnavanath

2021-08-17 03:34 UTC, imnavanath commented on assets/js/unminified/customizer-preview.js
> +			var dynamicStyle = '.menu-toggle, button, .ast-button, .ast-custom-button, .button, input#submit, input[type="button"], input[type="submit"], input[type="reset"]' + lmsButtonSelectors + search_but
I tried but only EDD applies body class on frontend, learndash & lifter applies body classes with respect to their taxonomy & special pages. So I though any of the case will miss that's why I added lms selectors in direct way.

2021-08-17 03:41 UTC, patilvikasj approved these changes

2021-08-20 11:09 UTC, premanshup approved these changes

2021-08-20 11:25 UTC, merged