AST-774 - Override default large space margin by 20px for UL & OL in editor
brainstormforce/astra pull request #3123
Opened 2021-08-17 06:47 UTC by imnavanath

### Description
- Default `margin: 0 0 1.5em 3em;` overriding by 20px to OL & UL lists in GB editor

### Screenshots
- Till now - https://share.bsf.io/04uxK50G
- In PR - https://share.bsf.io/JruxWnv4

### Types of changes
- Non-breaking change 

### How has this been tested?
- With lists having blocks like comment block, lists etc

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-08-17 06:50 UTC, sagarb90 approved these changes

2021-08-24 07:28 UTC, premanshup requested changes

2021-08-24 07:28 UTC, premanshup commented on sass/admin/block-editor-styles.scss
> +.wp-block ol, .wp-block ul {
@imnavanath I think this should be checked with all the blocks since this will change for all blocks containing OL and UL. Can you please verify?

2021-08-24 10:03 UTC, imnavanath commented on sass/admin/block-editor-styles.scss
> +.wp-block ol, .wp-block ul {
Yes correct. added testing case in comment likewise  - https://wp-astra.atlassian.net/browse/AST-774?focusedCommentId=16267

2021-09-08 06:33 UTC, merged