AST-494 wip: Move sticky option to sticky header
brainstormforce/astra pull request #3130
Opened 2021-08-17 14:24 UTC by sagarb90

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-09-13 17:28 UTC, premanshup commented
@sagarb90 Please add description to the PR.

2021-09-13 17:31 UTC, premanshup requested changes

2021-09-13 17:31 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/index.js
> +import { controlTitleControl } from './controls-title/control';
@sagarb90 We already have 
`import { headingControl } from './heading/control';`
Can you please check if this can be used and if we can avoid adding new control?

2021-09-14 04:55 UTC, sagarb90 commented on inc/customizer/extend-custom-controls/src/index.js
> +import { controlTitleControl } from './controls-title/control';
@premanshup No, we can't use this as this is different control - https://share.getcloudapp.com/jku46JpA
And we need this new control because we have a divider context where we can add titles but some controls are shown on a conditional basis so we can't add title in tit so we introduce this new control for heading.

2021-09-15 04:01 UTC, premanshup commented on inc/customizer/extend-custom-controls/src/index.js
> +import { controlTitleControl } from './controls-title/control';
@sagarb90 I see! Can we use divider? Just like we have used it here - https://share.bsf.io/mXuKzZq4. Please check.

2021-10-06 12:01 UTC, sagarb90 commented on inc/core/builder/class-astra-builder-options.php
> -	$defaults[ 'sticky-header-button' . $index . '-padding' ] = Astra_Builder_Helper::$default_responsive_spacing;
This is removed and move it to addon as this is related to sticky and need to load from the addon

2021-12-29 01:50 UTC, closed without merging