Feat: Replace Global Color Palette 'editor-color-palette' to theme.json
brainstormforce/astra pull request #3194
Opened 2021-09-01 12:41 UTC by premanshup

### Description

This PR introduced theme.json in the theme. Global Color Palette for GB editor works on the basis of theme.json

### Screenshots

![Image 2021-09-01 at 6 03 12 PM](https://user-images.githubusercontent.com/36841355/131671744-0e4881c9-9feb-49d9-9bf7-aac2bfe76f93.jpeg)

### Types of changes

New feature (non-breaking change which adds functionality)

### How has this been tested?

Tested by changing the global color from customizer and applying the colors to the text/background.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-09-01 13:26 UTC, premanshup commented
Checking the failed GitHub checks

2021-09-01 15:13 UTC, premanshup commented
> Checking the failed GitHub checks

Static analysis is passed, Size check will get passed once we will pull the `release-candidate` in this as it is fix there. @patilvikasj Can you please pull the latest `release-candidate` in `release/v3.7.0-beta.2`

2021-09-06 10:14 UTC, patilvikasj approved these changes

2021-09-06 10:29 UTC, Nikschavan requested changes

2021-09-06 10:29 UTC, Nikschavan commented on inc/customizer/configurations/layout/class-astra-site-container-layout-configs.php
> +			$section_content_bg_obj = ( defined( 'ASTRA_EXT_VER' ) && Astra_Ext_Extension::is_active( 'colors-and-background' ) ) ? 'section-colors-body' : 'section-colors-background';
Does adding `Class_Exists` fix the psalm complaint?
Also we should add class_exists instead of checking the constant anyway AST-737

2021-09-06 10:29 UTC, Nikschavan commented on inc/core/class-gutenberg-editor-css.php
> +				/** @psalm-suppress InvalidArgument */ // phpcs:ignore Generic.Commenting.DocComment.MissingShort
Does `@psalm-suppress` take inline comments format `//`>

2021-09-06 10:29 UTC, Nikschavan commented on inc/class-astra-global-palette.php
> +		add_theme_support( 'editor-color-palette', $editor_palette );
Comment seems superfluous, maybe drop the comment or if there is any better description that can be added here.

2021-09-06 10:29 UTC, Nikschavan commented on inc/class-astra-global-palette.php
> +	 *
Not a requirement: Do try to describe the functions a bit more, in this case - what is the actual difference in how we store it and how Gutenberg uses it.

Also, just wondering - this data formatting will be done on each page loads, is there any way to avoid this?
maybe storing the data as gutenberg requires? (not saying we should do it FYI but worth discussing)

2021-09-06 10:29 UTC, Nikschavan commented on inc/class-astra-global-palette.php
> +		 * This will be fixed in the future updates of WordPress/Gutenberg.
```suggestion
		 * If theme.json is not present in the child theme load Global Color Palette in the editor using add_theme_support( 'editor-color-palette', $editor_palette );.
		 * This is a known issue in Gutenberg - If theme.json is not present in the child theme, it does fallback to the parent theme's theme.json file.
		 * This will be fixed in the future updates of WordPress/Gutenberg.
```

Removing extra lines in the comment description.

2021-09-06 10:29 UTC, Nikschavan commented on inc/class-astra-global-palette.php
> +		 * Adding backward for theme.json file.
Maybe word it - `Support for overriding theme.json from the child theme` instead?

2021-09-06 15:43 UTC, premanshup commented on inc/customizer/configurations/layout/class-astra-site-container-layout-configs.php
> +			$section_content_bg_obj = ( defined( 'ASTRA_EXT_VER' ) && Astra_Ext_Extension::is_active( 'colors-and-background' ) ) ? 'section-colors-body' : 'section-colors-background';
@Nikschavan It works with `class_exists` check. I tried it with `method_exists` function but psalm was throwing error for this. I will update it to class_exists.

2021-09-06 16:07 UTC, premanshup commented on inc/core/class-gutenberg-editor-css.php
> +				/** @psalm-suppress InvalidArgument */ // phpcs:ignore Generic.Commenting.DocComment.MissingShort
@Nikschavan If we add it as multi doc comment then it shows error in PHPCS about missing short. If we add short description then psalm shows error. This is the only way I could find to make them both work.

2021-09-06 16:11 UTC, premanshup commented on inc/customizer/configurations/layout/class-astra-site-container-layout-configs.php
> +			$section_content_bg_obj = ( defined( 'ASTRA_EXT_VER' ) && Astra_Ext_Extension::is_active( 'colors-and-background' ) ) ? 'section-colors-body' : 'section-colors-background';
Updated!

2021-09-06 16:11 UTC, premanshup commented on inc/class-astra-global-palette.php
> +		add_theme_support( 'editor-color-palette', $editor_palette );
Right! Removed!

2021-09-06 16:12 UTC, premanshup commented on inc/class-astra-global-palette.php
> +		 * This will be fixed in the future updates of WordPress/Gutenberg.
Done!

2021-09-06 16:12 UTC, premanshup commented on inc/class-astra-global-palette.php
> +		 * Adding backward for theme.json file.
Updated!

2021-09-06 16:14 UTC, premanshup commented on inc/class-astra-global-palette.php
> +	 *
@patilvikasj Please check this, I think we can read this from theme.json as well.

2021-09-07 04:07 UTC, patilvikasj commented on inc/class-astra-global-palette.php
> +	 *
@premanshup We are reading this from theme.json itself. This is just a fallback function which will be called in the case where the user is using a child theme and WP does not use the parent theme theme.json as a fallback.

2021-09-07 04:09 UTC, patilvikasj commented on inc/class-astra-global-palette.php
> +	 *
Once WP uses parent theme.json as a fallback. We will deprecate/remove this code.

2021-09-07 05:14 UTC, premanshup commented on inc/class-astra-global-palette.php
> +	 *
@patilvikasj I have added a task for this as per the discussion, please check - https://wp-astra.atlassian.net/browse/GCP-155

2021-09-07 09:26 UTC, merged