AST-908 - Added PHPCS ruleset for adding astra prefix in code
brainstormforce/astra pull request #3247
Opened 2021-09-14 06:45 UTC by imnavanath

### Description
- Ruleset added for checking prefix `astra` in dir code
- `<rule ref="WordPress.NamingConventions.PrefixAllGlobals">
		<properties>
			<property name="prefixes" type="array" value="astra_"/>
		</properties>
	</rule>`

### Screenshots
- With error - https://share.bsf.io/Z4ujpz8W
- W/o error - https://share.bsf.io/rRubmnYo

### Types of changes
- Non-breaking change 
- PHPCS Ruleset 

### How has this been tested?
- By checking phpcs & phpcbf

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-09-23 10:19 UTC, premanshup commented
@imnavanath The PR is looking good. Once all the other errors are resolved, we will get this merged.

2021-09-23 10:19 UTC, premanshup approved these changes

2021-09-27 08:07 UTC, abhishek-bsf approved these changes

2021-09-27 10:00 UTC, premanshup requested changes

2021-09-27 10:00 UTC, premanshup commented on template-parts/header/builder/mobile-header-row.php
> +					<div class="ast-builder-grid-row <?php echo Astra_Builder_Helper::has_mobile_side_columns( $astra_row ) ? 'ast-builder-grid-row-has-sides' : 'ast-grid-center-col-layout-only ast-flex'; ?> <?php
```suggestion
					<div class="ast-builder-grid-row <?php echo Astra_Builder_Helper::has_mobile_side_columns( $astra_row, 'header', 'mobile' ) ? 'ast-builder-grid-row-has-sides' : 'ast-grid-center-col-layout-only ast-flex'; ?> <?php echo Astra_Builder_Helper::has_mobile_center_column( $astra_row, 'header', 'mobile' ) ? 'ast-grid-center-col-layout' : 'ast-builder-grid-row-no-center'; ?>">
```
@imnavanath  I think this should be updated, please check all other same functions.

2021-09-27 10:03 UTC, imnavanath commented on template-parts/header/builder/mobile-header-row.php
> +					<div class="ast-builder-grid-row <?php echo Astra_Builder_Helper::has_mobile_side_columns( $astra_row ) ? 'ast-builder-grid-row-has-sides' : 'ast-grid-center-col-layout-only ast-flex'; ?> <?php
I think no need of this - https://github.com/brainstormforce/astra/blob/next-release/inc/core/builder/class-astra-builder-helper.php#L870-L880
Only 1 parameter provided & processed here.

2021-09-27 10:11 UTC, premanshup approved these changes

2021-09-27 10:11 UTC, merged