AST-899 - feat: added astra meta settings icon in post editor
brainstormforce/astra pull request #3256
Opened 2021-09-14 14:01 UTC by sagarb90

### Description
- Added astra meta settings icon in post editor
- https://wp-astra.atlassian.net/browse/AST-899
### Screenshots
 https://share.getcloudapp.com/v1u0nYd9 

### Types of changes
- Improvements

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-09-20 12:41 UTC, premanshup commented on inc/metabox/class-astra-meta-boxes.php
> +			$asset_path = get_template_directory() . $filepath . 'index.asset.php';
@sagarb90 I don't think there is need for `index.asset.php`, can you please verify?

2021-09-20 12:53 UTC, premanshup requested changes

2021-09-20 12:53 UTC, premanshup commented on inc/metabox/class-astra-meta-boxes.php
> +			}
@sagarb90 Instead of this, can we add a condition in which this function will load only if it is GB Editor? Maybe some similar condition can be added for this as well:
`add_action( 'init', array( $this, 'register_script' ) );`

2021-09-20 12:53 UTC, premanshup commented on inc/metabox/class-astra-meta-boxes.php
> +				'astraMetaParams',
```suggestion
				'astMetaParams',
```

2021-09-20 12:53 UTC, premanshup commented on inc/metabox/extend-metabox/src/settings.js
> + class AstraMetaSettings extends Component {
```suggestion
 class MetaSettings extends Component {
```
@sagarb90 Let's convert this to functional components.

2021-09-20 12:53 UTC, premanshup commented on inc/metabox/extend-metabox/src/settings.js
> + const { withSelect, withDispatch } = wp.data;
```suggestion
 const { __ } = wp.i18n;
 const { Component, Fragment} = wp.element;
 const { compose } = wp.compose;
 const { withSelect, withDispatch } = wp.data;
```
Let's use `@wordpress/` instead of `wp.`

2021-09-20 12:53 UTC, premanshup commented on inc/metabox/extend-metabox/src/settings.js
> +			 <Fragment>
```suggestion
			 <>
```

2021-09-23 05:06 UTC, sagarb90 commented on inc/metabox/class-astra-meta-boxes.php
> +			$asset_path = get_template_directory() . $filepath . 'index.asset.php';
We need this for dependency Also Gutenberg doc they have mention to use these dependency while enqueue scripts

2021-09-23 05:32 UTC, sagarb90 commented on inc/metabox/class-astra-meta-boxes.php
> +			}
Yes added condition directly for `add_action( 'init', array( $this, 'register_script' ) );` Also there is no condition to verify that is is GB editor.

2021-09-23 05:33 UTC, sagarb90 commented on inc/metabox/extend-metabox/src/settings.js
> + const { withSelect, withDispatch } = wp.data;
W need `wp` to access the `data` variable `@wodpress` only user for importing wp related components

2021-09-27 11:07 UTC, merged