Single Test Case for default layout options of Sidebar
brainstormforce/astra pull request #3276
Opened 2021-09-16 07:06 UTC by bsfsnehal

### Description

Test case for Default layout of sidebar
### Screenshots

### Types of changes

### How has this been tested?

Branch-Name :- sidebar
Test case Execution :- npm run test:e2e:interactive — tests/e2e/specs/customizer/sidebar/def-layout-sidebar.test.js

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-09-16 07:11 UTC, sushmak02 commented on tests/e2e/specs/customizer/sidebar/def-layout-sidebar.test.js
> +        it( 'Default layout for sidebar from customizer should apply corectly', async () => {
spelling mistake

2021-09-16 07:12 UTC, sushmak02 commented on tests/e2e/specs/customizer/sidebar/def-layout-sidebar.test.js
> +        it( 'Default layout for sidebar  as No Sidebar should apply corectly', async () => {
more than 1 spaces bet 2 words

2021-09-16 07:12 UTC, sushmak02 commented on tests/e2e/specs/customizer/sidebar/def-layout-sidebar.test.js
> +            await page.waitForSelector( '.secondary' );
can we wait for some sidebar specific class?

2021-09-16 07:14 UTC, bsfsnehal commented on tests/e2e/specs/customizer/sidebar/def-layout-sidebar.test.js
> +            await page.waitForSelector( '.secondary' );
Means?

2021-09-16 07:14 UTC, sushmak02 requested changes
Review the changes suggested and get them done at all the places

2021-09-16 07:15 UTC, sushmak02 commented on tests/e2e/specs/customizer/sidebar/def-layout-sidebar.test.js
> +            await page.waitForSelector( '.secondary' );
This class is not specifically related to left-sidebar. "secondary"

2021-09-16 07:15 UTC, sushmak02 commented on tests/e2e/specs/customizer/sidebar/def-layout-sidebar.test.js
> +            await page.waitForSelector( '.secondary' );
await page.waitForSelector( '.ast-right-sidebar #secondary' );
expecting something like this

2021-09-16 09:10 UTC, sushmak02 approved these changes

2021-09-23 14:07 UTC, sushmak02 approved these changes

2021-11-29 01:47 UTC, closed without merging