Introducing onboarding document for new developers for onboarding on Astra.
brainstormforce/astra pull request #3300
Opened 2021-09-20 13:44 UTC by premanshup

### Description

Introducing onboarding document for new developers for onboarding on Astra.

### Types of changes

Non-breaking change, documentation related change.

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-09-21 04:54 UTC, imnavanath approved these changes

2021-09-21 05:32 UTC, sagarb90 commented on docs/onboarding/index.md
> +
I think we should also add grunt setup and grunt commands (`grunt minify` and `grunt release`) steps in this process.

2021-09-21 05:59 UTC, Nikschavan requested changes

2021-09-21 05:59 UTC, Nikschavan commented on docs/onboarding/index.md
> +    2. [https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker)
I am not sure if this is required for everyone to install?

2021-09-21 05:59 UTC, Nikschavan commented on docs/onboarding/index.md
> +    1. [https://marketplace.visualstudio.com/items?itemName=aeschli.vscode-css-formatter](https://marketplace.visualstudio.com/items?itemName=aeschli.vscode-css-formatter)
```suggestion
    1. [CSS Formatter](https://marketplace.visualstudio.com/items?itemName=aeschli.vscode-css-formatter)
```

Le's add text + link instead of only links, this is much more readable.

2021-09-21 05:59 UTC, Nikschavan commented on docs/onboarding/index.md
> +    3. [https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)
This extension is not maintained at the moment - https://github.com/editorconfig/editorconfig-vscode/issues/263

I have had some bugs with this and had to keep it deactivated, I think let's not recommend to new joiners.

2021-09-21 06:01 UTC, Nikschavan commented on docs/onboarding/index.md
> +      * [The team](#-the-team)
I don't think we need these two sections

2021-09-21 06:03 UTC, Nikschavan commented on docs/onboarding/index.md
> +6. **`#ast-website`** - Discussions related to wpastra.com website happen here.
I don't think we need to mention slack channels here

2021-09-21 09:41 UTC, premanshup commented on docs/onboarding/index.md
> +    2. [https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker)
Right! Removed.

2021-09-21 09:42 UTC, premanshup commented on docs/onboarding/index.md
> +    1. [https://marketplace.visualstudio.com/items?itemName=aeschli.vscode-css-formatter](https://marketplace.visualstudio.com/items?itemName=aeschli.vscode-css-formatter)
Updated!

2021-09-21 09:42 UTC, premanshup commented on docs/onboarding/index.md
> +    3. [https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)
I see, removed it from the extension list.

2021-09-21 09:42 UTC, premanshup commented on docs/onboarding/index.md
> +      * [The team](#-the-team)
Removed!

2021-09-21 09:42 UTC, premanshup commented on docs/onboarding/index.md
> +6. **`#ast-website`** - Discussions related to wpastra.com website happen here.
Removed slack channels.

2021-09-28 05:55 UTC, premanshup commented on docs/onboarding/index.md
> +
@sagarb90 I will open a separate PR for this.

2022-01-10 01:51 UTC, closed without merging