AST-1025 - Cart Total/Label position
brainstormforce/astra pull request #3529
Opened 2021-10-20 06:41 UTC by GauravKhupse

### Description
Need option to add Cart Total/Label Position.

### Screenshots

### Types of changes

New feature (non-breaking change which adds functionality) 

### How has this been tested?
Added tests cases in the card.
### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-10-20 07:22 UTC, premanshup commented
@GauravKhupse Do get this sycned.

2021-11-02 09:42 UTC, imnavanath commented on inc/builder/type/header/woo-cart/assets/js/unminified/customizer-preview.js
> +
```suggestion
```

2021-11-02 09:42 UTC, imnavanath commented on inc/builder/type/header/woo-cart/assets/js/unminified/customizer-preview.js
> +			defaultCart.addClass('ast-cart-position-' + position);
@GauravKhupse can you please adjust indentation here.

2021-11-02 09:43 UTC, imnavanath commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +			'margin-top'  => 0.5 . 'em',
```suggestion
			'margin-top'  => '0.5em',
```

2021-11-02 09:43 UTC, imnavanath commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +			'margin-right' => 0.5 . 'em',
```suggestion
			'margin-right' => '0.5em',
```

2021-11-02 09:44 UTC, imnavanath commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +			'margin-left' => 0.7 . 'em',
```suggestion
			'margin-left' => '0.7em',
```

2021-11-02 09:44 UTC, imnavanath commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +			'margin-left' => 0.5 . 'em',
```suggestion
			'margin-left' => '0.5em',
```

2021-11-02 09:44 UTC, imnavanath commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +
```suggestion
```

2021-11-02 10:15 UTC, imnavanath commented
Also @GauravKhupse please resolve conflicts and make branch upto-date.

2021-11-03 07:51 UTC, imnavanath commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +		),
Can this CSS combine? There is no such major diff in 0.7 & 0.5, in contrast 0.7 looks better - https://share.bsf.io/v1ujbDwP

2021-11-03 07:53 UTC, imnavanath commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +			'line-height' => 0.1,
Witll this CSS affect other icons??

2021-11-03 12:17 UTC, imnavanath approved these changes

2021-11-03 12:17 UTC, sagarb90 commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +			self::$cart_total_label_postion = astra_get_option( 'woo-header-cart-icon-total-label-position' );
You have defined and initialized this variable  `self::$cart_total_label_postion` as an array and we use it as a string below,
Why we need to initialize this variable on top can we directly get the value from the option and use it

2021-11-03 12:20 UTC, sagarb90 commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +	$css_total_position_output_bottom   = array(
this code also goes in conditions no need to initialize all the array.

2021-11-03 12:21 UTC, GauravKhupse commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +			self::$cart_total_label_postion = astra_get_option( 'woo-header-cart-icon-total-label-position' );
it increases to 2 calls as per premanshu so I created a variable to use this option to 2 locations. link:- https://github.com/brainstormforce/astra/pull/3529#discussion_r732861005

2021-11-03 12:22 UTC, premanshup commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +		'.cart-container.ast-cart-position-bottom, .ast-addon-cart-wrap.ast-cart-position-bottom' => array(
```suggestion
		'.ast-cart-position-bottom, .ast-cart-position-bottom' => array(
```
@GauravKhupse @sagarb90 Can we reduce the CSS selectors weightage from dynamic CSS and preview JS as well?

2021-11-03 12:23 UTC, premanshup commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +	}
Instead of multiple if conditions, can we add switch cases for better performance?
@GauravKhupse @sagarb90

2021-11-03 12:24 UTC, sagarb90 commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +	}
Right, that is also a good approach!

2021-11-03 12:29 UTC, sagarb90 commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +		'.cart-container.ast-cart-position-bottom, .ast-addon-cart-wrap.ast-cart-position-bottom' => array(
Right but then this will the single class here `.ast-cart-position-bottom,` @GauravKhupse any reason why we use two different parent class for same `ast-cart-position-bottom` class

2021-11-03 12:33 UTC, sagarb90 commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +			self::$cart_total_label_postion = astra_get_option( 'woo-header-cart-icon-total-label-position' );
Okay right, but you have initialized/assing it in function, You should initialize/assign the value in constructor at once, every time I call this function will call the `get_option()` then no use of a static variable.

2021-11-09 12:33 UTC, GauravKhupse commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +	}
Changes done!

2021-11-09 12:33 UTC, GauravKhupse commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +		'.cart-container.ast-cart-position-bottom, .ast-addon-cart-wrap.ast-cart-position-bottom' => array(
Changes done!

2021-11-09 12:33 UTC, GauravKhupse commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +	$css_total_position_output_bottom   = array(
Changes done!

2021-11-09 12:36 UTC, GauravKhupse commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +			self::$cart_total_label_postion = astra_get_option( 'woo-header-cart-icon-total-label-position' );
@premanshup I had to discuss with @sagar 
- If we use variables to get value, it will affect the action hooks sequence in the future so I have to get the astra_get _option to take value in both markups and there is no issue with calls, we have managed cache for this.

2021-11-09 12:37 UTC, GauravKhupse commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +			self::$cart_total_label_postion = astra_get_option( 'woo-header-cart-icon-total-label-position' );
changes done!

2021-11-09 13:31 UTC, sagarb90 approved these changes

2021-11-26 16:43 UTC, premanshup requested changes

2021-11-26 16:43 UTC, premanshup commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +			'line-height' => 0.1,
@GauravKhupse But when this will load on the page, this CSS will be applied to all the astra-icon classes, right?
cc: @imnavanath

2021-11-29 06:20 UTC, GauravKhupse commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +			'line-height' => 0.1,
I checked this Astra-icon class markup only used for the WooCommerce Astra icon.

2021-11-29 06:24 UTC, GauravKhupse commented on inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
> +			'line-height' => 0.1,
I checked this Astra-icon class markup only used for the WooCommerce Astra icon.

2021-12-23 11:23 UTC, premanshup approved these changes

2021-12-23 11:24 UTC, merged