AST-1195 - Mobile menu does not close when you click a one page navigation link inside them
brainstormforce/astra pull request #3684
Opened 2021-11-03 11:29 UTC by imnavanath

### Description
- If any menu-item has # link, then that was not closing after clicking it, 
- due to that the dropdown & offcanvas open

### Screenshots
- https://bit.ly/2XNh0l2

### Types of changes
- Bug fix 

### How has this been tested?
- Check as per steps mentioned in tasks
- Apart from that check dropdown target option setting - https://share.bsf.io/E0uKY9WO
- Check all offcanvas styles

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-11-08 07:14 UTC, abhishek-bsf approved these changes

2021-11-08 09:38 UTC, premanshup commented on assets/js/unminified/frontend.js
> +				if( null !== popupLinks[link].getAttribute("href") && ( '#' == popupLinks[link].getAttribute("href") || popupLinks[link].getAttribute("href").startsWith('#') ) && ! popupLinks[link].parentElement
```suggestion
				if( null !== popupLinks[link].getAttribute('href') && ( '#' == popupLinks[link].getAttribute('href') || popupLinks[link].getAttribute('href').startsWith('#') ) && ! popupLinks[link].parentElement.classList.contains('menu-item-has-children') ){
```

2021-11-08 09:39 UTC, premanshup requested changes

2021-11-08 09:39 UTC, premanshup commented on assets/js/unminified/frontend.js
> +				if( null !== popupLinks[link].getAttribute("href") && ( '#' == popupLinks[link].getAttribute("href") || popupLinks[link].getAttribute("href").startsWith('#') ) && ! popupLinks[link].parentElement
@imnavanath I think we can remove 
`'#' == popupLinks[link].getAttribute("href")` this condition now? Please check.

2021-11-08 10:05 UTC, imnavanath commented on assets/js/unminified/frontend.js
> +				if( null !== popupLinks[link].getAttribute("href") && ( '#' == popupLinks[link].getAttribute("href") || popupLinks[link].getAttribute("href").startsWith('#') ) && ! popupLinks[link].parentElement
Valid one, updated likewise 👍

2021-11-09 05:30 UTC, sagarb90 approved these changes

2021-11-23 14:08 UTC, premanshup approved these changes

2021-11-23 14:14 UTC, merged