AST-1315 - Added new design options for dark mode switcher
brainstormforce/astra pull request #3706
Opened 2021-11-09 12:11 UTC by imnavanath

### Description
 Design options for dark mode switcher element

### Screenshots
- https://share.bsf.io/rRuWNvzZ

### Types of changes
- New feature - non-breaking change 

### How has this been tested?
- Check every option 
- With light mode
- with dark mode
- Check on frontend
- Check with customizer preview

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-11-11 03:40 UTC, premanshup commented
@imnavanath Please get this synced.

2021-11-11 03:56 UTC, premanshup commented
@imnavanath Please check the code analysis too.

2021-11-12 16:55 UTC, premanshup requested changes

2021-11-12 16:55 UTC, premanshup commented on inc/builder/controllers/class-astra-builder-ui-controller.php
> +				<button class="ast-mode-switcher-trigger ast-switcher-<?php echo esc_attr( $switcher_type ); ?>-type ast-switcher-<?php echo esc_attr( $switcher_style ); ?>-style" aria-label="Switch to dark mode
@imnavanath Can we reduce the extra CSS classes from here?

2021-11-12 16:55 UTC, premanshup commented on inc/builder/controllers/class-astra-builder-ui-controller.php
> +							echo '<span class="ast-dark-mode-wrap ast-mode-label" data-tooltip="' . esc_html( 'Dark' ) . '">' . self::fetch_svg_icon( $switcher_dark_icon ) . '</span>'; // phpcs:ignore WordPress.Security.
@imnavanath Can we remove extra CSS classes from here?

2021-11-12 16:55 UTC, premanshup commented on inc/customizer/configurations/builder/header/class-astra-header-mode-switcher-component-configs.php
> +					'default'   => astra_get_option( 'dark-mode-switch-type' ),
@imnavanath Any reason we are changing the name of this option? 
`dark-mode-switch-style` this option is still used in other places as well. Please verify once.

2021-11-16 10:03 UTC, imnavanath commented on inc/builder/controllers/class-astra-builder-ui-controller.php
> +							echo '<span class="ast-dark-mode-wrap ast-mode-label" data-tooltip="' . esc_html( 'Dark' ) . '">' . self::fetch_svg_icon( $switcher_dark_icon ) . '</span>'; // phpcs:ignore WordPress.Security.
Yes we can remove that, actually I made a common `ast-mode-label` class for both light & dark span, to apply common stylings.

2021-11-16 13:09 UTC, imnavanath commented on inc/customizer/configurations/builder/header/class-astra-header-mode-switcher-component-configs.php
> +					'default'   => astra_get_option( 'dark-mode-switch-type' ),
Yes intentionally it was changed. 
TYPE means switcher type should br of icon/label/icon-width-label.
STYLE means how it should display toggle/button format. 
Previously I worked with type then I realized we are going to add new control for style as well that's why I renamed this accordingly.

2021-11-16 13:13 UTC, imnavanath commented on inc/builder/controllers/class-astra-builder-ui-controller.php
> +				<button class="ast-mode-switcher-trigger ast-switcher-<?php echo esc_attr( $switcher_type ); ?>-type ast-switcher-<?php echo esc_attr( $switcher_style ); ?>-style" aria-label="Switch to dark mode
Compatibility CSS I written on basis of these class like ast-switcher-icon/ast-switcher-label/ast-switcher-icon-with-label.
BTW, I removed the class `ast-switcher-toggle/button` and loaded only when pro & fixed-switch addon is active. https://share.bsf.io/5zu92kXd

2021-11-17 16:27 UTC, premanshup commented on inc/core/builder/class-astra-builder-options.php
> +	$defaults['dark-mode-switcher-dark-color']  = '#eeeeee';
@imnavanath Please check if can integrate this with Global Colors Pallete?

2021-11-17 16:33 UTC, premanshup commented on inc/markup-extras.php
> +		do_action( 'astra_before_logo_image', $device );
```suggestion
		do_action( 'astra_before_logo_image', $device );
```
@imnavanath Any reason we are introducing this action?

2021-11-19 04:07 UTC, imnavanath commented on inc/markup-extras.php
> +		do_action( 'astra_before_logo_image', $device );
We added this new action to insert dark mode logo which will come from addon, you can ref that here - https://github.com/brainstormforce/astra-addon/blob/pro-dark-mode-features/addons/dark-mode-switch/classes/class-astra-addon-dark-mode-markup.php#L68

2021-11-22 10:33 UTC, imnavanath commented on assets/js/unminified/mode-switcher.js
> +updateSwitcherFlashMessages = function ( switchedTo ) {
As flash message removed this code is no longer exists.

2021-11-22 10:59 UTC, imnavanath commented on inc/core/builder/class-astra-builder-options.php
> +	$defaults['dark-mode-switcher-dark-color']  = '#eeeeee';
Done = https://github.com/brainstormforce/astra/pull/3706/commits/746b7bd8023c742808b00a07741feb1a7fc8c830

2021-11-22 11:36 UTC, merged