AST-1043 Add To Cart - Button Size option
brainstormforce/astra pull request #3718
Opened 2021-11-11 06:31 UTC by GauravKhupse

### Description
- Responsive Button Width option for Single Product.

### Screenshots
- https://share.bsf.io/7KuAQKBq

### Types of changes

New feature (non-breaking change which adds functionality

### How has this been tested?
Added in the card.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-11-11 12:01 UTC, premanshup commented
@GauravKhupse Code analysis is failing, please check.

2021-11-12 16:55 UTC, premanshup commented on inc/lib/astra-notices/class-astra-notices.php
> +				wp_send_json_error( esc_html_e( 'WordPress Nonce not validated.' ) );
```suggestion
				wp_send_json_error( esc_html_e( 'WordPress Nonce not validated.', 'astra' ) );
```

2021-11-12 17:01 UTC, premanshup requested changes

2021-11-12 17:01 UTC, premanshup commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +			$yith_wcwl_main_style .= astra_parse_css( $yith_wcwl_main_style_small, astra_get_tablet_breakpoint() );
```suggestion
			$yith_wcwl_main_style .= astra_parse_css( $yith_wcwl_main_style_small, '', astra_get_tablet_breakpoint() );
```
@GauravKhupse Any reason for this change?

2021-11-15 13:23 UTC, GauravKhupse commented on inc/lib/astra-notices/class-astra-notices.php
> +				wp_send_json_error( esc_html_e( 'WordPress Nonce not validated.' ) );
Changes done!

2021-11-15 13:23 UTC, GauravKhupse commented on assets/js/unminified/customizer-preview.js
> +				console.log(size);
Changes done!

2021-11-15 13:23 UTC, GauravKhupse commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +
Changes done!

2021-11-15 13:24 UTC, GauravKhupse commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +			$yith_wcwl_main_style .= astra_parse_css( $yith_wcwl_main_style_small, astra_get_tablet_breakpoint() );
This is showing code analysis changes but now I have fixed using ignore the rule.

2021-11-26 16:40 UTC, premanshup approved these changes

2021-12-06 09:40 UTC, imnavanath approved these changes

2021-12-16 11:06 UTC, merged