AST-1473 - Applying content-background option to backgrounds of full with (contained+stertched) layouts
brainstormforce/astra pull request #3883
Opened 2021-12-07 07:43 UTC by imnavanath

### Description
- Need to work Content Background color as background-color for full-width content layout (contained + stretched) cases.
- Right now, Site background color is appearing as background-color for Full width content layouts - https://share.bsf.io/DOu60DE9
- But Content Background color should apply here - https://share.bsf.io/nOu5ZoLP

### Screenshots
- Customizer where content-bg applying to full-width contained layout - https://share.bsf.io/kpu6joNx
- Frontend view - https://share.bsf.io/12uP26o9
- Editor view - https://share.bsf.io/2NuPNREl

### Types of changes
- New improvement

### How has this been tested?
- Check with every site-layout
- Check special WP pages like 404, search, author, archives etc with assigned layouts 
- Check customizer preview, frontend view, editor view

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-12-07 13:40 UTC, premanshup requested changes

2021-12-07 13:40 UTC, premanshup commented on inc/dynamic-css/content-background.php
> +		);
@imnavanath Instead of overriding the colors can we replace the CSS color - [https://share.bsf.io/6quvq2RD](https://share.bsf.io/6quvq2RD)

2021-12-08 06:33 UTC, imnavanath commented on inc/dynamic-css/content-background.php
> +		);
This happens due to `body` tag added there. Instead of overriding there I updated `body, .ast-separate-container` selector conditionally. So only single CSS will come on frontend (after static) - https://share.bsf.io/jkuE5d9j 
Review commit here - https://github.com/brainstormforce/astra/pull/3883/commits/67f39ffa3b8245da543302c4cbfe9821884e8ac3

2021-12-17 12:40 UTC, premanshup commented on inc/extras.php
> + * Is Content BG settings need to apply on Fullwidth Contained/Stretched layout or not?
```suggestion
 * Should Content BG settings apply to Fullwidth Contained/Stretched layout or not?
```

2021-12-17 12:45 UTC, premanshup commented on changelog.txt
> +- Improvement: Site Background is applying as background-CSS for Full-Width Contained/Stretched layouts instead of Content Background.
```suggestion
- Improvement: Site Background will be applied as background CSS for Full-Width Contained/Stretched layouts instead of Content Background.
```

2021-12-18 03:42 UTC, premanshup approved these changes

2021-12-18 03:42 UTC, merged