QAE-260 - test case for Transparent header disable on pages
brainstormforce/astra pull request #3895
Opened 2021-12-10 12:03 UTC by SimranChougule1

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-01-03 06:59 UTC, premanshup requested changes

2022-01-03 06:59 UTC, premanshup commented on tests/e2e/specs/customizer/header-builder/transparent-header/enable-on-complete-website.test.js
> +
@SimranChougule1 This is not an array, this should be either 1 or 0, can you please confirm the same?

2022-01-03 07:00 UTC, premanshup commented on tests/e2e/specs/customizer/header-builder/transparent-header/enable-on-complete-website.test.js
> +				right: 0,
@SimranChougule1 This as well.

2022-01-03 07:00 UTC, premanshup commented on tests/e2e/specs/customizer/header-builder/transparent-header/enable-on-complete-website.test.js
> +
```suggestion
				position: 'absolute',
				left: 0,
				right: 0,

```
This too

2022-01-03 07:00 UTC, premanshup commented on tests/e2e/specs/customizer/header-builder/transparent-header/enable-on-complete-website.test.js
> +			},
```suggestion
			'transparent-header-disable-posts': {
				position: 'absolute',
				left: 0,
				right: 0,

			},
```

2022-01-03 07:06 UTC, SimranChougule1 commented on tests/e2e/specs/customizer/header-builder/transparent-header/enable-on-complete-website.test.js
> +
Okay I'll check

2022-01-03 07:06 UTC, SimranChougule1 commented on tests/e2e/specs/customizer/header-builder/transparent-header/enable-on-complete-website.test.js
> +
@imnavanath suggested me to add this array

2022-03-28 04:12 UTC, bsfsnehal commented on tests/e2e/specs/customizer/header-builder/transparent-header/enable-on-complete-website.test.js
> +import { createURL,	createNewPost, publishPost } from '@wordpress/e2e-test-utils';
required change in "publish-post" util path

2022-03-28 04:12 UTC, bsfsnehal commented on tests/e2e/specs/customizer/header-builder/transparent-header/enable-on-complete-website.test.js
> +describe( 'transparent header in the customizer', () => {
1st letter should be capital

2022-03-28 04:13 UTC, bsfsnehal commented on tests/e2e/specs/customizer/header-builder/transparent-header/enable-on-complete-website.test.js
> +		const Disableonarchive = {
constant name should be in camelCase

2022-03-28 04:22 UTC, SimranChougule1 commented on tests/e2e/specs/customizer/header-builder/transparent-header/enable-on-complete-website.test.js
> +import { createURL,	createNewPost, publishPost } from '@wordpress/e2e-test-utils';
Done

2022-03-28 04:22 UTC, SimranChougule1 commented on tests/e2e/specs/customizer/header-builder/transparent-header/enable-on-complete-website.test.js
> +describe( 'transparent header in the customizer', () => {
Done

2022-03-28 04:22 UTC, SimranChougule1 commented on tests/e2e/specs/customizer/header-builder/transparent-header/enable-on-complete-website.test.js
> +		const Disableonarchive = {
Done

2022-03-28 04:23 UTC, SimranChougule1 commented on tests/e2e/specs/customizer/header-builder/transparent-header/enable-on-complete-website.test.js
> +
Done

2022-03-28 05:15 UTC, bsfsnehal approved these changes

2022-03-28 10:13 UTC, GauravKhupse approved these changes

2022-04-03 10:20 UTC, GauravKhupse commented on tests/e2e/specs/customizer/header-builder/transparent-header/enable-on-complete-website.test.js
> +		await page.waitForSelector( '.ast-theme-transparent-header' );
404 page is not showing in the preview.

2022-04-07 08:35 UTC, bsfsnehal commented on tests/e2e/specs/customizer/header-builder/transparent-header/enable-on-complete-website.test.js
> +		await page.waitForSelector( '.ast-theme-transparent-header' );
@SimranChougule1 can you please verify this?

2022-04-07 09:18 UTC, SimranChougule1 commented on tests/e2e/specs/customizer/header-builder/transparent-header/enable-on-complete-website.test.js
> +		await page.waitForSelector( '.ast-theme-transparent-header' );
Resolved

2022-04-28 04:11 UTC, premanshup approved these changes

2022-04-28 10:56 UTC, merged