AST-1466 - Nav menu is not working properly on the sticky header
brainstormforce/astra pull request #3947
Opened 2021-12-27 04:27 UTC by shubshinde

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-12-27 07:32 UTC, nileshc-bsf commented on assets/css/unminified/frontend.css
> +
@shubshinde - Is this specific for Mobile/tablet?
Cross-check for desktop, it should not affect the menu height.

2021-12-27 12:21 UTC, shubshinde commented on assets/css/unminified/frontend.css
> +
Added Media Query for tablet, mobile devices.

2021-12-28 07:35 UTC, premanshup requested changes

2021-12-28 07:35 UTC, premanshup commented on sass/site/header/_header-builder-main.scss
> +}
@shubshinde Can you please move this CSS to Astra Pro - Sticky Header - CSS.

2021-12-28 07:40 UTC, shubshinde commented on sass/site/header/_header-builder-main.scss
> +}
Ok

2021-12-28 08:37 UTC, shubshinde commented
Closing this PR, as this code is moved to Addons.

https://github.com/brainstormforce/astra-addon/pull/567

2021-12-28 08:37 UTC, closed without merging