AST-1499 - Elementor Pro Products element issue, where customizing the product column is not working with our theme.
brainstormforce/astra pull request #3949
Opened 2021-12-27 21:15 UTC by shubshinde

### Description
Fixed it by removing old CSS which was added by Astra for setting default 4 columns, Our CSS was restricting Elementor Pro to override their CSS.
We don't need to handle it now, It's handled by Elementor Pro In a recent update.

### Screenshots
After Fix - 

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
1. Created Products Archive in Elementor Theme builder (Elementor Pro latest plugin needed)
2. Added the 'Products' element  - https://share.getcloudapp.com/04uL1obQ
3. Tried to change the product column (as pointed in the screenshot) - https://share.bsf.io/6quERvdL
4. It will now change the product column number as specified.

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-12-28 08:08 UTC, premanshup requested changes

2021-12-28 08:08 UTC, premanshup commented on sass/site/compatibility/woocommerce/woocommerce-layout-grid.scss
> -		grid-template-columns:  repeat(4, 1fr);
@shubshinde We need to add backward compatibility here for older version of Elementor.

2022-01-03 08:22 UTC, shubshinde commented on sass/site/compatibility/woocommerce/woocommerce-layout-grid.scss
> -		grid-template-columns:  repeat(4, 1fr);
The custom grids should be managed only when Elementor is not active. Elementor handles it by default.
Our Astra's custom grid CSS was restricting Elementor to apply proper grid settings from Elementor editor. 

So I have applied our previous custom grid CSS just when the product grid is not created using Elementor.

2022-01-03 10:03 UTC, imnavanath approved these changes

2022-01-03 10:34 UTC, nileshc-bsf approved these changes

2022-01-03 14:29 UTC, premanshup approved these changes

2022-01-04 11:19 UTC, merged