QAE-328 - E2E test case for footer builder background image
brainstormforce/astra pull request #3969
Opened 2022-01-03 10:51 UTC by SimranChougule1

### Description

Added test case for footer builder background image

### Screenshots

https://share.getcloudapp.com/DOumgbwo

### Types of changes

### How has this been tested?

Run single test: npm run test:e2e:interactive tests/e2e/specs/customizer/footer-builder/background-image.test.js

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-02-27 15:47 UTC, GauravKhupse commented on tests/e2e/specs/customizer/footer-builder/background-image.test.js
> +					'background-image': 'https://images.ctfassets.net/hrltx12pl8hq/4CH9hYoMSORDuL8BXgX0Br/c2520603e3d2616468161c38519c9446/shutterstock_631575830.jpg?fit=fill&w=2560&h=400&fm=webp',
Check to add different images for responsive images.

2022-02-28 06:17 UTC, SimranChougule1 commented on tests/e2e/specs/customizer/footer-builder/background-image.test.js
> +					'background-image': 'https://images.ctfassets.net/hrltx12pl8hq/4CH9hYoMSORDuL8BXgX0Br/c2520603e3d2616468161c38519c9446/shutterstock_631575830.jpg?fit=fill&w=2560&h=400&fm=webp',
Added different images

2022-03-01 02:55 UTC, premanshup requested changes

2022-03-01 02:55 UTC, premanshup commented on tests/e2e/specs/customizer/footer-builder/background-image.test.js
> +					'background-image': 'https://images.ctfassets.net/hrltx12pl8hq/4CH9hYoMSORDuL8BXgX0Br/c2520603e3d2616468161c38519c9446/shutterstock_631575830.jpg?fit=fill&w=2560&h=400&fm=webp',
@SimranChougule1 Please use all the images from recommended sources - https://make.wordpress.org/themes/handbook/review/resources/#recommended-websites-for-images. @SimranChougule1 Can you replace all the images added with the websites mentioned here?

2022-03-01 05:27 UTC, SimranChougule1 commented on tests/e2e/specs/customizer/footer-builder/background-image.test.js
> +					'background-image': 'https://images.ctfassets.net/hrltx12pl8hq/4CH9hYoMSORDuL8BXgX0Br/c2520603e3d2616468161c38519c9446/shutterstock_631575830.jpg?fit=fill&w=2560&h=400&fm=webp',
added resources suggested by you but image is not visible on front end, @GauravKhupse is checking this problem

2022-03-01 11:42 UTC, GauravKhupse commented on tests/e2e/specs/customizer/footer-builder/background-image.test.js
> +					'background-image': 'https://images.ctfassets.net/hrltx12pl8hq/4CH9hYoMSORDuL8BXgX0Br/c2520603e3d2616468161c38519c9446/shutterstock_631575830.jpg?fit=fill&w=2560&h=400&fm=webp',
This issue in our Astra setting, I have fixed branch:- **footer-global-color-issue**, I am adding task in Astra.

2022-03-24 05:59 UTC, bsfsnehal approved these changes

2022-04-08 10:21 UTC, GauravKhupse commented on tests/e2e/specs/customizer/footer-builder/background-image.test.js
> +		const FooterBuilderBgImage = {
```suggestion
		const footerBuilderBgImage = {
```

2022-04-08 10:25 UTC, SimranChougule1 commented on tests/e2e/specs/customizer/footer-builder/background-image.test.js
> +		const FooterBuilderBgImage = {
Done chnages

2022-04-18 09:12 UTC, GauravKhupse approved these changes

2022-05-02 10:37 UTC, premanshup commented on tests/e2e/specs/customizer/footer-builder/background-image.test.js
> +describe( 'Footer builder backgeround image setting in customizer', () => {
```suggestion
describe( 'Footer builder background image setting in customizer', () => {
```

2022-05-02 10:50 UTC, premanshup approved these changes

2022-05-02 10:54 UTC, SimranChougule1 commented on tests/e2e/specs/customizer/footer-builder/background-image.test.js
> +describe( 'Footer builder backgeround image setting in customizer', () => {
Resolved

2022-05-02 14:42 UTC, GauravKhupse commented on tests/e2e/specs/customizer/footer-builder/background-image.test.js
> +					'background-image': 'https://pickupimage.com/free-photos/Combine-harvester/2358359',
desktop URL is not the proper URL, please update.

2022-05-02 14:54 UTC, bsfsnehal commented on tests/e2e/specs/customizer/footer-builder/background-image.test.js
> +					'background-image': 'https://pickupimage.com/free-photos/Combine-harvester/2358359',
resolved

2022-05-05 03:38 UTC, merged