added e2e test case for above header BG-gradient
brainstormforce/astra pull request #3971
Opened 2022-01-03 13:19 UTC by bsfsnehal

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-02-24 14:12 UTC, premanshup requested changes

2022-02-24 14:12 UTC, premanshup commented on tests/e2e/specs/customizer/header-builder/above-header/bg-gradient.test.js
> +					'background-color': 'linear-gradient(135deg, rgb(6, 147, 227) 31%, rgb(155, 81, 224) 64%)',
@SimranChougule1 / @GauravKhupse Please make sure the colors are different for all the three devices.

2022-02-24 14:46 UTC, SimranChougule1 commented on tests/e2e/specs/customizer/header-builder/above-header/bg-gradient.test.js
> +					'background-color': 'linear-gradient(135deg, rgb(6, 147, 227) 31%, rgb(155, 81, 224) 64%)',
okay I'll make changes in color PR's

2022-02-26 03:48 UTC, premanshup approved these changes

2022-02-26 03:49 UTC, merged