QAE-335 - E2E test case for below footer background gradient
brainstormforce/astra pull request #3976
Opened 2022-01-04 08:26 UTC by SimranChougule1

### Description

Added test case for below footer background gradient

### Screenshots

https://share.getcloudapp.com/Z4u1ZjyZ

### Types of changes

### How has this been tested?

Run single test: npm run test:e2e:interactive tests/e2e/specs/customizer/footer-builder/below-footer/background-gradient.test.js

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-03-08 16:07 UTC, premanshup requested changes

2022-03-08 16:07 UTC, premanshup commented on tests/e2e/specs/customizer/footer-builder/below-footer/background-gradient.test.js
> +					'background-color': 'linear-gradient(135deg, rgb(6, 147, 227) 0%, rgb(255, 255, 255) 37%, rgb(155, 81, 224) 53%)',
@GauravKhupse / @SimranChougule1 Please verify if the gradient is correct or not?
[https://share.bsf.io/QwuL6e11](https://share.bsf.io/QwuL6e11) seems to be not working at my end for all three devices.

2022-03-21 12:35 UTC, SimranChougule1 commented on tests/e2e/specs/customizer/footer-builder/below-footer/background-gradient.test.js
> +					'background-color': 'linear-gradient(135deg, rgb(6, 147, 227) 0%, rgb(255, 255, 255) 37%, rgb(155, 81, 224) 53%)',
this is working properly at my end

2022-04-13 12:43 UTC, bsfsnehal approved these changes

2022-04-13 14:20 UTC, GauravKhupse approved these changes

2022-04-22 09:45 UTC, premanshup approved these changes

2022-04-22 09:47 UTC, merged