QAE-313 - E2E test case for Gutenberg Shortcode block default width
brainstormforce/astra pull request #3989
Opened 2022-01-06 06:26 UTC by SimranChougule1

### Description

Added test case for Gutenberg Shortcode block default width

### Screenshots

https://share.getcloudapp.com/7KuqxDO8

### Types of changes

### How has this been tested?

Run single test: npm run test:e2e:interactive tests/e2e/specs/block-editor/shortcode-block/width.test.js

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-01-10 15:33 UTC, premanshup requested changes

2022-01-10 15:33 UTC, premanshup commented on tests/e2e/specs/block-editor/shortcode-block/width.test.js
> +		// await page.keyboard.type( 'two' );
@SimranChougule1 Can we remove this commented code?

2022-01-11 04:05 UTC, SimranChougule1 commented on tests/e2e/specs/block-editor/shortcode-block/width.test.js
> +		// await page.keyboard.type( 'two' );
yes

2022-01-20 16:05 UTC, premanshup approved these changes

2022-02-26 03:21 UTC, premanshup approved these changes

2022-02-26 03:21 UTC, merged