QAE-312 - E2E test case for GB embed block wide width padding and margin
brainstormforce/astra pull request #3990
Opened 2022-01-06 07:06 UTC by bsfsnehal

### Description

E2E test case for GB embed block wide width padding and margin
### Screenshots

### Types of changes

### How has this been tested?

 npm run test:e2e:interactive — tests/e2e/specs/block-editor/embed/width.test.js

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-02-26 03:52 UTC, premanshup requested changes

2022-02-26 03:52 UTC, premanshup commented on tests/e2e/config/bootstrap.js
> +	//deactivatePlugin,
```suggestion
	deactivatePlugin,
```

2022-02-26 03:52 UTC, premanshup commented on tests/e2e/config/bootstrap.js
> +	//await deactivatePlugin( 'gutenberg' ); // by default keep the Gutenberg plugin deactive, Activate when needed.
```suggestion
	await deactivatePlugin( 'gutenberg' ); // by default keep the Gutenberg plugin deactive, Activate when needed.
```

2022-07-21 10:20 UTC, bsfsnehal commented
Closing this PR due to expected & receive value difference error for width option on local as well as github.

2022-07-21 10:20 UTC, closed without merging