Site title markup load issue
brainstormforce/astra pull request #4138
Opened 2022-02-17 03:44 UTC by GauravKhupse

### Description
In site title & logo options if we have the display site title option disabled then still we see the H1 tags.

### Screenshots
https://drive.google.com/file/d/1jkE5SqvihwynQ7bNgj4I3eU3f0xZV9Rf/view?usp=drivesdk

### Types of changes

Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?
- Go to site title & logo settings
- Disable the “Display site title” option
- Check for the error in the console (ref: see the above screenshots)
- The tags should be hidden if the option is disabled.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-02-21 04:13 UTC, imnavanath commented on inc/lib/astra-notices/.phpunit.result.cache
> +{"version":1,"defects":{"TestDismissNotice::test_user_can_dismiss_notice":4,"TestNoticeVisibleForCorrectRole::test_user_can_see_notice":3,"TestNoticeVisibleForCorrectRole::test_user_can_see_notice_wi
@GauravKhupse why this file change appear here?

2022-02-21 04:14 UTC, imnavanath commented on inc/lib/astra-notices/notices.css
> +}
Same here?

2022-02-21 04:35 UTC, GauravKhupse commented on inc/lib/astra-notices/.phpunit.result.cache
> +{"version":1,"defects":{"TestDismissNotice::test_user_can_dismiss_notice":4,"TestNoticeVisibleForCorrectRole::test_user_can_see_notice":3,"TestNoticeVisibleForCorrectRole::test_user_can_see_notice_wi
I have installed composer dependency again, it will fetch bsf core and astra notice changes in my branch.

2022-02-21 04:36 UTC, GauravKhupse commented on inc/lib/astra-notices/notices.css
> +}
I have installed composer dependency again, it will fetch bsf core, and Astra notice changes in my branch, need to discuss on this point.

2022-02-24 13:58 UTC, premanshup approved these changes

2022-02-25 04:04 UTC, imnavanath approved these changes

2022-02-25 04:05 UTC, imnavanath commented
@GauravKhupse please add changelog for this.

2022-03-10 11:44 UTC, premanshup commented on inc/markup-extras.php
> +
```suggestion
```

2022-03-10 11:47 UTC, premanshup requested changes

2022-03-10 11:47 UTC, premanshup commented on inc/markup-extras.php
> +		$old_header_active  = add_filter( 'astra_is_header_footer_builder_active', '__return_false' );
@GauravKhupse Why are we adding filter to update old header to new header?
We should be directly checking if the old header is active or not directly.

2022-03-10 12:30 UTC, GauravKhupse commented on inc/markup-extras.php
> +
Changes done!

2022-03-10 12:31 UTC, GauravKhupse commented on inc/markup-extras.php
> +		$old_header_active  = add_filter( 'astra_is_header_footer_builder_active', '__return_false' );
this is my mistake, I have removed, Added is_header_footer_builder_active condition

2022-03-29 11:47 UTC, premanshup commented
@GauravKhupse Code analysis is failed here, please check.

2022-06-05 02:13 UTC, closed without merging