AST-1630 - WooCommerce Product layout column breaks
brainstormforce/astra pull request #4171
Opened 2022-03-07 06:52 UTC by GauravKhupse

### Description
With the latest Theme update v3.7.9, the WooCommerce shortcode for [product] layout breaks down.

Discussion forum: [WooCommerce shortcode issue with Astra last version (3.7.9)] https://wordpress.org/support/topic/woocommerce-shortcode-issue-with-astra-last-version-3-7-9/

### Screenshots

### Types of changes

Breaking change 

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-03-07 08:58 UTC, premanshup requested changes

2022-03-07 08:58 UTC, premanshup commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +				$css_global_button_tablet['.woocommerce ul.products:not(.elementor-grid), .woocommerce-page ul.products'] = array(
@GauravKhupse Any reason we are making changes to existing CSS. Please confirm this with @nileshc-bsf and @imnavanath .

2022-03-08 03:32 UTC, GauravKhupse commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +				$css_global_button_tablet['.woocommerce ul.products:not(.elementor-grid), .woocommerce-page ul.products'] = array(
shubham has added CSS only for desktop but he has not made changes for the responsive devices so the column setting is not working for responsive devices found as per @Swapnildhanrale We have fixed the issue for responsive devices.

2022-03-08 09:13 UTC, imnavanath commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +					'.woocommerce.tablet-columns-' . $archive_tablet_grid . ' ul.products li.product:not(.elementor-grid), .woocommerce-page.tablet-columns-' . $archive_tablet_grid . ' ul.products:not(.elementor-gr
li.product don't have .elementor-grid class its only applying for ul.products. Please do the needful.

2022-03-08 09:20 UTC, nileshc-bsf commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +					'.woocommerce.tablet-columns-' . $archive_tablet_grid . ' ul.products li.product:not(.elementor-grid), .woocommerce-page.tablet-columns-' . $archive_tablet_grid . ' ul.products:not(.elementor-gr
@imnavanath - Correct, it should for `ul.products` not for the `li.product`

2022-03-08 09:27 UTC, GauravKhupse commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +					'.woocommerce.tablet-columns-' . $archive_tablet_grid . ' ul.products li.product:not(.elementor-grid), .woocommerce-page.tablet-columns-' . $archive_tablet_grid . ' ul.products:not(.elementor-gr
Changes done!

2022-03-08 09:30 UTC, imnavanath commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +				$css_global_button_mobile[ '.ast-container .woocommerce.mobile-rel-up-columns-' . $single_mobile_grid . ' ul.products::not(.elementor-grid)' ] = array(
mobile-rel-up-columns- class comes for body, then how `.ast-container` comes before that in CSS?

2022-03-08 09:45 UTC, GauravKhupse commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +				$css_global_button_mobile[ '.ast-container .woocommerce.mobile-rel-up-columns-' . $single_mobile_grid . ' ul.products::not(.elementor-grid)' ] = array(
Removed, selector changes done.

2022-03-08 09:49 UTC, GauravKhupse commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +				$css_global_button_mobile[ '.ast-container .woocommerce.mobile-rel-up-columns-' . $single_mobile_grid . ' ul.products::not(.elementor-grid)' ] = array(
updated selector, changes done!

2022-03-08 09:50 UTC, imnavanath commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +				$css_global_button_mobile[ '.woocommerce.mobile-rel-up-columns-' . $single_mobile_grid . ' ul.products::not(.elementor-grid)' ] = array(
This will work right as we removed one selector from here?

2022-03-08 09:52 UTC, GauravKhupse commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +				$css_global_button_mobile[ '.woocommerce.mobile-rel-up-columns-' . $single_mobile_grid . ' ul.products::not(.elementor-grid)' ] = array(
yes!

2022-03-08 09:53 UTC, imnavanath commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +					'.woocommerce.tablet-columns-' . $archive_tablet_grid . ' ul.products li.product, .woocommerce-page.tablet-columns-' . $archive_tablet_grid . ' ul.products:not(.elementor-grid)' => array(
here one ul.products is without elementor-grid, that should also updated, correct me if I'm wrong.

2022-03-08 10:08 UTC, imnavanath approved these changes

2022-03-08 10:09 UTC, GauravKhupse commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +					'.woocommerce.tablet-columns-' . $archive_tablet_grid . ' ul.products li.product, .woocommerce-page.tablet-columns-' . $archive_tablet_grid . ' ul.products:not(.elementor-grid)' => array(
Currently, we have provided CSS for ul, so it might be not needed for this

2022-03-08 11:22 UTC, nileshc-bsf approved these changes

2022-03-22 06:40 UTC, premanshup approved these changes

2022-03-22 09:01 UTC, merged