AST-1620 - WP blocks styles changes on preview of Tablet and mobile on Firefox when Astra theme is active.
brainstormforce/astra pull request #4262
Opened 2022-04-11 15:51 UTC by GauravKhupse

### Description
On the Firefox browser, the UAG blocks styles, fonts and width are getting changed when previewing the blocks on Tablet and Mobile view on the backend on It seems like the problem is with the Astra theme only. When I am switching it to some other themes, it is working fine.

Chrome preview is not working

Video - https://share.bsf.io/eDulKxR6

Discussion link: https://brainstormforce.slack.com/archives/CDS7TQ75Z/p1644399792268069

### Screenshots

### Types of changes

 Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?

Added in the Card.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-04-13 04:28 UTC, imnavanath commented on changelog.txt
> +- Fix: Fixed block editor style issue with the responsive preview option on the post or page.
```suggestion
- Fix: Theme's responsive styles not loading with the responsive preview option in the block editor.
```

2022-04-13 13:47 UTC, imnavanath approved these changes

2022-05-19 08:10 UTC, imnavanath commented
Alongwith this PR please check typo font issue which is not loading in preview iframes - https://share.bsf.io/E0uy54O9

2022-05-23 14:19 UTC, RajkiranBagal requested changes

2022-05-23 15:14 UTC, GauravKhupse commented on changelog.txt
> +- Fix: Fixed block editor style issue with the responsive preview option on the post or page.
Resolved!

2022-05-24 04:21 UTC, GauravKhupse commented on inc/assets/js/block-editor-script.js
> +				if ( (null === element || undefined === element)&& (null === elementBlock || undefined === elementBlock )) {
Changes done!

2022-05-24 04:54 UTC, RajkiranBagal approved these changes

2022-05-31 05:19 UTC, nileshc-bsf approved these changes

2022-05-31 06:20 UTC, merged