AST-2275 - Featured product when cart is empty
brainstormforce/astra pull request #4860
Opened 2022-12-29 03:42 UTC by nathanrodrigues2111

### Description
Jira : https://brainstormforce.atlassian.net/browse/AST-2275

### Screenshots
https://d.pr/i/w1ApNd

### Types of changes
New feature (non-breaking change which adds functionality)

### How has this been tested?
- Checked responsive,
- Checked in customizer 
- Checked when slide in cart is active 

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-01-02 10:39 UTC, er-roshan reviewed
Need to update with base branch

2023-01-04 01:06 UTC, er-roshan requested changes
@nathanrodrigues2111 Need please update with base branch

2023-01-04 02:20 UTC, yssambare12 approved these changes

2023-01-04 03:40 UTC, er-roshan approved these changes

2023-01-04 04:33 UTC, neerajmasai approved these changes

2023-01-04 05:50 UTC, imnavanath approved these changes

2023-01-04 07:02 UTC, imnavanath commented on inc/compatibility/woocommerce/class-astra-woocommerce.php
> +							<p class="woocommerce-mini-cart__empty-message"><?php echo apply_filters( 'astra_mini_cart_empty_msg', __( 'No products in the cart.', 'astra' ) ); // phpcs:ignore WordPress.Security.EscapeOut
```suggestion
							<p class="woocommerce-mini-cart__empty-message"><?php esc_html_e( apply_filters( 'astra_mini_cart_empty_msg', __( 'No products in the cart.', 'astra' ) ) ); ?></p>
```

2023-01-04 07:24 UTC, imnavanath approved these changes

2023-02-07 07:02 UTC, merged